// packages/angular/adapter-taiga-ui/src/components/filterPopover.ts
import { type FilterOverlaySlotProps } from "@adapttable/angular";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  type ElementRef,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";

import { TAIGA_CONTROLS } from "../taigaControls";

/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 */

/** An overlay's props in Angular: its content is a template. */

/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 *
 * @internal
 */
@Component({
  selector: "adapt-filter-popover",
  imports: [...TAIGA_CONTROLS, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <span
      #anchor
      [tuiDropdown]="content"
      [tuiDropdownOpen]="p.open"
      (tuiDropdownOpenChange)="onOpenChange($event)"
      data-taiga-part="filters-anchor"
      style="position: relative; display: inline-flex"
    >
      @if (p.children; as trigger) {
        <ng-container [ngTemplateOutlet]="trigger" />
      }
    </span>
    <ng-template #content>
      @if (p.open) {
        <div
          #card
          data-taiga-part="filters-popover"
          [attr.dir]="p.dir ?? 'ltr'"
          [attr.data-dir]="p.dir ?? 'ltr'"
          [style.width.px]="380"
          [style.max-width]="'calc(100vw - 16px)'"
          [style.overflow-y]="'auto'"
        >
          <header data-taiga-part="filters-header">
            <h3 data-taiga-part="filters-title">
              {{ p.labels.filters
              }}{{
                p.activeFilterCount > 0 ? " (" + p.activeFilterCount + ")" : ""
              }}
            </h3>
            <button
              tuiButton
              size="s"
              appearance="secondary"
              type="button"
              data-taiga-part="filters-clear"
              [disabled]="p.activeFilterCount === 0"
              (click)="p.onClearFilters()"
            >
              {{ p.labels.clearAll }}
            </button>
          </header>
          <div data-taiga-part="filters-body">
            <ng-container [ngTemplateOutlet]="p.filters" />
          </div>
        </div>
      }
    </ng-template>
  `,
})
export class AdaptFilterPopover {
  /** The slot's props. */
  readonly props =
    input.required<FilterOverlaySlotProps<TemplateRef<unknown>>>();

  private readonly anchor =
    viewChild.required<ElementRef<HTMLElement>>("anchor");
  protected onOpenChange(open: boolean): void {
    if (open || !this.props().open) return;
    this.props().onClose();
    this.anchor().nativeElement.querySelector<HTMLElement>("button")?.focus();
  }
}

// packages/adapter-base-ui/src/components/FilterPopover.tsx
import type { Direction, TableLabels } from "@adapttable/core";
import { Popover } from "@base-ui/react/popover";
import { isValidElement, type ReactElement, type ReactNode } from "react";

import type { BaseUiAccentColor } from "../types";
import { Button, Flex, Text } from "../ui";

/** Props for {@link FilterPopover}. */
export interface FilterPopoverProps {
  open: boolean;
  onClose: () => void;
  filters: ReactNode;
  activeFilterCount: number;
  onClearFilters: () => void;
  labels: Required<TableLabels>;
  accentColor?: BaseUiAccentColor;
  dir?: Direction;
  /** The Filters trigger button — becomes the popover anchor. */
  children: ReactNode;
}

/**
 * Anchored filter card (the default filter container). Opens under the Filters
 * button with no backdrop — the background stays visible and interactive;
 * clicking outside or pressing Escape closes it. Pair with
 * `filtersMode="drawer"` for the modal panel instead.
 */
export function FilterPopover({
  open,
  onClose,
  filters,
  activeFilterCount,
  onClearFilters,
  labels,
  accentColor,
  dir = "ltr",
  children,
}: Readonly<FilterPopoverProps>) {
  const trigger = isValidElement(children) ? (
    <Popover.Trigger render={children as ReactElement} />
  ) : (
    <Popover.Trigger>{children}</Popover.Trigger>
  );
  return (
    <Popover.Root
      open={open}
      onOpenChange={(next) => {
        if (!next) onClose();
      }}
    >
      {trigger}
      <Popover.Portal>
        <Popover.Positioner
          className="adapttable-popup-positioner"
          side="bottom"
          align={dir === "rtl" ? "start" : "end"}
          sideOffset={8}
        >
          <Popover.Popup
            data-testid="adapttable-filter-popover"
            aria-label={labels.filters}
            dir={dir}
            className="adapttable-popup"
            style={{ width: 340, maxWidth: "90vw" }}
          >
            <Flex direction="column" gap="3">
              <Flex justify="between" align="center">
                <Text weight="bold" size="2">
                  {labels.filters}
                </Text>
                <Button
                  size="1"
                  variant="ghost"
                  color={accentColor}
                  onClick={onClearFilters}
                  disabled={activeFilterCount === 0}
                >
                  {labels.clearAll}
                </Button>
              </Flex>
              <Flex direction="column" gap="4">
                {filters}
              </Flex>
            </Flex>
          </Popover.Popup>
        </Popover.Positioner>
      </Popover.Portal>
    </Popover.Root>
  );
}
