// packages/adapter-unstyled/src/components/AutoFilterForm.tsx
import {
  defaultFilterRegistry,
  type FilterDef,
  filterLabel,
  type FilterTypeRegistry,
  type FilterValue,
  filterWidgetKind,
  joinRelativeToken,
  RELATIVE_PRESET_LABEL_KEYS,
  RELATIVE_PRESETS,
  renderRegisteredFilter,
  resolveLabels,
  splitRelativeToken,
  type TableLabels,
  type TableSource,
} from "@adapttable/core";
import {
  CHECKLIST_LIST_HEIGHT,
  filterOpLabel,
  useBooleanFilterWidget,
  useFilterOptions,
  useRangeFilterWidget,
  useTextFilterWidget,
} from "@adapttable/react";
import {
  type CSSProperties,
  type ReactElement,
  type ReactNode,
  useId,
} from "react";

import type { DataTableClassNames } from "../types";
import { ChecklistFilter } from "./ChecklistFilter";

/* Part names shared by more than one field shape. */
const FIELD_PART = "filter-field";
const LABEL_PART = "filter-label";

/** Column stack so the caption is a flex item (legend ignored gap). */
const FIELD_STACK: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 16,
  minWidth: 0,
  margin: 0,
  padding: 0,
  border: 0,
};

/** A filter-bag value as input text (`undefined` renders empty). */
function asText(value: FilterValue): string {
  return String(value ?? "");
}

/** A `multiSelect` bag value as an array, tolerating a scalar from the URL. */
function selectedValues(value: FilterValue): string[] {
  if (Array.isArray(value)) return value;
  if (value == null || value === "") return [];
  return [String(value)];
}

/** Props shared by every per-definition field component. */
interface DefFieldProps<TRow> {
  def: FilterDef<TRow>;
  source: TableSource<TRow>;
  classNames: DataTableClassNames;
}

interface GroupFieldProps {
  caption: string;
  classNames: DataTableClassNames;
  children: ReactNode;
}

/** Native labelled group for multi-control fields — no visible fieldset box. */
function GroupField({
  caption,
  classNames,
  children,
}: Readonly<GroupFieldProps>) {
  const id = useId();
  return (
    <fieldset
      aria-labelledby={id}
      data-adapttable-part={FIELD_PART}
      className={classNames.filterField}
      style={FIELD_STACK}
    >
      <div
        id={id}
        data-adapttable-part={LABEL_PART}
        className={classNames.filterLabel}
      >
        {caption}
      </div>
      {children}
    </fieldset>
  );
}

function TextField<TRow>({
  def,
  source,
  classNames,
  labels,
}: Readonly<DefFieldProps<TRow> & { labels: Required<TableLabels> }>) {
  const { label, ops, opLabelKeys, op, value, needsValue, write } =
    useTextFilterWidget(def, source);
  return (
    <GroupField caption={label} classNames={classNames}>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
        <select
          style={{ flex: "0 0 8.5rem", width: "8.5rem" }}
          aria-label={labels.operator}
          data-adapttable-part="filter-operator"
          className={classNames.filterOperator}
          value={op}
          onChange={(e) => {
            const next = ops.find((choice) => choice === e.currentTarget.value);
            if (next) write(next, value);
          }}
        >
          {ops.map((choice) => (
            <option key={choice} value={choice}>
              {filterOpLabel(labels, opLabelKeys[choice])}
            </option>
          ))}
        </select>
        {needsValue && (
          <input
            type="text"
            aria-label={label}
            placeholder={def.placeholder}
            data-adapttable-part="filter-input"
            className={classNames.filterInput}
            value={value}
            onChange={(e) => write(op, e.currentTarget.value)}
          />
        )}
      </div>
    </GroupField>
  );
}

function BooleanField<TRow>({
  def,
  source,
  classNames,
  labels,
}: Readonly<DefFieldProps<TRow> & { labels: Required<TableLabels> }>) {
  const { label, choice, write } = useBooleanFilterWidget(def, source);
  return (
    <label
      data-adapttable-part={FIELD_PART}
      className={classNames.filterField}
      style={FIELD_STACK}
    >
      <span
        data-adapttable-part={LABEL_PART}
        className={classNames.filterLabel}
      >
        {label}
      </span>
      <select
        aria-label={label}
        data-adapttable-part="filter-select"
        className={classNames.filterSelect}
        value={choice}
        onChange={(e) => {
          const next = e.currentTarget.value;
          if (next === "" || next === "true" || next === "false") write(next);
        }}
      >
        <option value="">{labels.boolAny}</option>
        <option value="true">{labels.boolTrue}</option>
        <option value="false">{labels.boolFalse}</option>
      </select>
    </label>
  );
}

function SelectField<TRow>({
  def,
  source,
  classNames,
}: Readonly<DefFieldProps<TRow>>) {
  // `def.options` may be a static array, an async loader, or a leftover
  // "auto" — never map it directly; the hook resolves all three shapes.
  const { options, loading } = useFilterOptions(def);
  return (
    <label
      data-adapttable-part={FIELD_PART}
      className={classNames.filterField}
      style={FIELD_STACK}
    >
      <span
        data-adapttable-part={LABEL_PART}
        className={classNames.filterLabel}
      >
        {filterLabel(def)}
      </span>
      <select
        data-adapttable-part="filter-select"
        className={classNames.filterSelect}
        value={asText(source.extra[def.key])}
        onChange={(e) => source.setExtra(def.key, e.currentTarget.value)}
      >
        {loading ? (
          <option value="" disabled>
            …
          </option>
        ) : (
          <>
            <option value="">All</option>
            {options.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </>
        )}
      </select>
    </label>
  );
}

function MultiSelectField<TRow>({
  def,
  source,
  classNames,
}: Readonly<DefFieldProps<TRow>>) {
  const selected = selectedValues(source.extra[def.key]);
  // Same contract as SelectField: the hook resolves arrays / loaders / "auto".
  const { options, loading } = useFilterOptions(def);
  return (
    <GroupField caption={filterLabel(def)} classNames={classNames}>
      <div
        data-adapttable-part="filter-checkbox-group"
        className={classNames.filterCheckboxGroup}
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: 10,
          maxHeight: CHECKLIST_LIST_HEIGHT,
          overflow: "auto",
        }}
      >
        {loading ? (
          <span
            data-adapttable-part="filter-options-loading"
            className={classNames.filterOptionsLoading}
          >
            …
          </span>
        ) : (
          options.map((option) => (
            <label
              key={option.value}
              data-adapttable-part="filter-checkbox"
              className={classNames.filterCheckbox}
            >
              <input
                type="checkbox"
                checked={selected.includes(option.value)}
                onChange={(e) =>
                  source.setExtra(
                    def.key,
                    e.currentTarget.checked
                      ? [...selected, option.value]
                      : selected.filter((v) => v !== option.value)
                  )
                }
              />{" "}
              {option.label}
            </label>
          ))
        )}
      </div>
    </GroupField>
  );
}

interface RangeValueInputProps {
  type: "date" | "number" | "text";
  /** Placeholder AND accessible name (`Value`, `From`, or `To`). */
  label: string;
  value: string;
  onValue: (next: string) => void;
  classNames: DataTableClassNames;
}

/** One bound of a range widget; the parent owns the write-through. */
function RangeValueInput({
  type,
  label,
  value,
  onValue,
  classNames,
}: Readonly<RangeValueInputProps>) {
  return (
    <input
      type={type}
      style={{ flex: "1 1 7rem", minWidth: "7rem" }}
      placeholder={label}
      aria-label={label}
      data-adapttable-part="filter-input"
      className={classNames.filterInput}
      value={value}
      onChange={(e) => onValue(e.currentTarget.value)}
    />
  );
}

interface RelativeTokenFieldProps {
  labels: Required<TableLabels>;
  value: string;
  onValue: (next: string) => void;
  classNames: DataTableClassNames;
}

/** Preset select + optional N for `last:N` / `next:N`. Stores the token. */
function RelativeTokenField({
  labels,
  value,
  onValue,
  classNames,
}: Readonly<RelativeTokenFieldProps>) {
  const { preset, n } = splitRelativeToken(value);
  const counted = preset === "last" || preset === "next";
  return (
    <>
      <select
        style={{ flex: "1 1 8.5rem", minWidth: "8.5rem" }}
        aria-label={labels.opRelative}
        data-adapttable-part="filter-input"
        className={classNames.filterInput}
        value={preset}
        onChange={(e) => {
          const next = RELATIVE_PRESETS.find(
            (p) => p === e.currentTarget.value
          );
          if (next) onValue(joinRelativeToken(next, n));
        }}
      >
        {RELATIVE_PRESETS.map((p) => (
          <option key={p} value={p}>
            {labels[RELATIVE_PRESET_LABEL_KEYS[p]]}
          </option>
        ))}
      </select>
      {counted && (
        <input
          type="number"
          min={1}
          style={{ flex: "0 0 4.5rem", width: "4.5rem" }}
          aria-label={labels.value}
          data-adapttable-part="filter-input"
          className={classNames.filterInput}
          value={n}
          onChange={(e) =>
            onValue(joinRelativeToken(preset, Number(e.currentTarget.value)))
          }
        />
      )}
    </>
  );
}

interface RangeFieldProps<TRow> extends DefFieldProps<TRow> {
  labels: Required<TableLabels>;
}

/**
 * Operator-first range field: a comparison `<select>` (its placeholder
 * option clears the pair), then ONE value input — or a labeled From/To
 * pair for `between`. The operator is persisted as `f_<key>Op`.
 */
function RangeField<TRow>({
  def,
  source,
  classNames,
  labels,
}: Readonly<RangeFieldProps<TRow>>) {
  const { label, ops, opLabelKeys, inputType, arity, op, setOp, a, b, write } =
    useRangeFilterWidget(def, source);
  const boundType = inputType === "text" ? "text" : inputType;
  return (
    <GroupField caption={label} classNames={classNames}>
      {/* Structural layout only (like the toolbar): the operator keeps a
          constant width; values fill the rest and wrap when they don't fit
          (date inputs have a wide native minimum). */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>
        <select
          style={{ flex: "0 0 8.5rem", width: "8.5rem" }}
          aria-label={labels.operator}
          data-adapttable-part="filter-operator"
          className={classNames.filterOperator}
          value={op ?? ""}
          onChange={(e) => {
            // Find (not cast) the next operator; "" → undefined → clear.
            const next = ops.find((o) => o === e.currentTarget.value);
            setOp(next);
            write(next, a, b);
          }}
        >
          <option value="">{labels.operator}</option>
          {ops.map((o) => (
            <option key={o} value={o}>
              {filterOpLabel(
                labels,
                opLabelKeys[o as keyof typeof opLabelKeys]
              )}
            </option>
          ))}
        </select>
        {arity === "two" && (
          <>
            <RangeValueInput
              type={boundType}
              label={labels.from}
              value={a}
              onValue={(next) => write(op, next, b)}
              classNames={classNames}
            />
            <RangeValueInput
              type={boundType}
              label={labels.to}
              value={b}
              onValue={(next) => write(op, a, next)}
              classNames={classNames}
            />
          </>
        )}
        {op === "relative" && (
          <RelativeTokenField
            labels={labels}
            value={a}
            onValue={(next) => write(op, next, "")}
            classNames={classNames}
          />
        )}
        {op !== undefined &&
          op !== "relative" &&
          arity !== "none" &&
          arity !== "two" && (
            <RangeValueInput
              type={boundType}
              label={labels.value}
              value={a}
              onValue={(next) => write(op, next, "")}
              classNames={classNames}
            />
          )}
      </div>
    </GroupField>
  );
}

interface FilterFieldProps<TRow> extends DefFieldProps<TRow> {
  labels: Required<TableLabels>;
  registry: FilterTypeRegistry;
}

function FilterField<TRow>({
  def,
  source,
  classNames,
  labels,
  registry,
}: Readonly<FilterFieldProps<TRow>>): ReactElement | null {
  const spec = registry.get(def.type);
  const custom = renderRegisteredFilter(def, source, labels, registry);
  if (custom) return custom as ReactElement;
  switch (spec?.widget ?? filterWidgetKind(def, registry)) {
    case "text":
      return (
        <TextField
          def={def}
          source={source}
          classNames={classNames}
          labels={labels}
        />
      );
    case "boolean":
      return (
        <BooleanField
          def={def}
          source={source}
          classNames={classNames}
          labels={labels}
        />
      );
    case "select":
      return <SelectField def={def} source={source} classNames={classNames} />;
    case "multiSelect":
      return (
        <MultiSelectField def={def} source={source} classNames={classNames} />
      );
    case "checklist":
      return (
        <ChecklistFilter
          def={def}
          source={source}
          classNames={classNames}
          labels={labels}
        />
      );
    case "dateRange":
    case "numberRange":
      return (
        <RangeField
          def={def}
          source={source}
          classNames={classNames}
          labels={labels}
        />
      );
    default:
      return null;
  }
}

/**
 * Props for `AutoFilterForm`.
 *
 * @public
 */
export interface AutoFilterFormProps<TRow> {
  /** The resolved filter definitions, in render order. */
  defs: readonly FilterDef<TRow>[];
  /** The table source whose filter bag the controls read and write. */
  source: TableSource<TRow>;
  /** Per-part class name overrides (the `filter*` keys). */
  classNames?: DataTableClassNames;
  /**
   * Label overrides for the range widgets (`operator`, `value`, `from`,
   * `to`, and the `op*` operator names); English defaults merge in.
   */
  labels?: TableLabels;
  /** Type registry; defaults to the built-ins. */
  registry?: FilterTypeRegistry;
}

/**
 * The auto-built filter form for the declarative `filters` array: one
 * semantic field per definition (`text` input, `select` with an "All"
 * option, wrapping `multiSelect` chips, operator-first `dateRange` /
 * `numberRange` widgets), each carrying `data-adapttable-part` hooks and
 * `classNames` overrides. Controls read `source.extra` and write through
 * `source.setExtra` / `source.setExtras` — an empty value clears its key.
 *
 * @typeParam TRow - The row type.
 *
 * @public
 */
export function AutoFilterForm<TRow>({
  defs,
  source,
  classNames = {},
  labels,
  registry = defaultFilterRegistry,
}: Readonly<AutoFilterFormProps<TRow>>) {
  const resolvedLabels = resolveLabels(labels);
  return (
    <>
      {defs.map((def) => (
        <FilterField
          key={def.key}
          def={def}
          source={source}
          classNames={classNames}
          labels={resolvedLabels}
          registry={registry}
        />
      ))}
    </>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/autoFilterForm.ts
/**
 * The auto-built filter form: one native field per definition — a text
 * field with its operator, a yes/no select, a select, a group of checkboxes,
 * a checklist, or an operator-first number or date range.
 */
import {
  AdaptChecklistChrome,
  booleanFilterFor,
  defaultFilterRegistry,
  type FilterDef,
  filterLabel,
  filterOpLabel,
  filterOptionsFor,
  type FilterOptionsState,
  type FilterTypeRegistry,
  filterWidgetKind,
  type FilterWidgetRenderProps,
  joinRelativeToken,
  listFilterValues,
  rangeFilterFor,
  type RangeOp,
  RELATIVE_PRESET_LABEL_KEYS,
  RELATIVE_PRESETS,
  type RelativePreset,
  renderRegisteredFilter,
  resolveRenderer,
  splitRelativeToken,
  type TableLabels,
  type TableSource,
  textFilterFor,
  type TextOp,
} from "@adapttable/angular";
import { NgComponentOutlet, NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  Directive,
  inject,
  Injector,
  input,
  type OnInit,
  type Signal,
  signal,
  TemplateRef,
  type Type,
} from "@angular/core";

import { CHECKLIST_SLOTS } from "./checklistFilter";

/** A field's column stack: the caption is a flex item, so `gap` applies. */
const FIELD_STACK =
  "display: flex; flex-direction: column; gap: 16px; min-width: 0; margin: 0; padding: 0; border: 0";

let nextFieldId = 0;

/** A fresh id for a field's caption, which its group is labelled by. */
function fieldId(): string {
  nextFieldId += 1;
  return `adapttable-filter-${String(nextFieldId)}`;
}

/** A text filter: its operator and its value. @internal */
@Component({
  selector: "adapt-text-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ w.label }}</div>
      <div style="display: flex; flex-wrap: wrap; gap: 12px">
        <select
          data-adapttable-part="filter-operator"
          style="flex: 0 0 8.5rem; width: 8.5rem"
          [attr.aria-label]="labels().operator"
          [value]="w.op"
          (change)="pickOp($any($event.target).value)"
        >
          @for (op of w.ops; track op) {
            <option [value]="op" [selected]="op === w.op">
              {{ opLabel(w.opLabelKeys[op]) }}
            </option>
          }
        </select>
        @if (w.needsValue) {
          <input
            type="text"
            data-adapttable-part="filter-input"
            [attr.aria-label]="w.label"
            [attr.placeholder]="def().placeholder ?? null"
            [value]="w.value"
            (input)="w.write(w.op, $any($event.target).value)"
          />
        }
      </div>
    </fieldset>
  `,
})
export class AdaptTextFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly widget = textFilterFor(this.def, this.source);

  protected opLabel(key: keyof TableLabels): string {
    return filterOpLabel(this.labels(), key);
  }

  /** The select offers only the widget's operators. */
  protected pickOp(value: string): void {
    const w = this.widget();
    w.write(value as TextOp, w.value);
  }
}

/** A yes/no filter. @internal */
@Component({
  selector: "adapt-boolean-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    <label data-adapttable-part="filter-field" [style]="stack">
      <span data-adapttable-part="filter-label">{{ w.label }}</span>
      <select
        data-adapttable-part="filter-select"
        [attr.aria-label]="w.label"
        [value]="w.choice"
        (change)="pick($any($event.target).value)"
      >
        <option value="" [selected]="w.choice === ''">
          {{ labels().boolAny }}
        </option>
        <option value="true" [selected]="w.choice === 'true'">
          {{ labels().boolTrue }}
        </option>
        <option value="false" [selected]="w.choice === 'false'">
          {{ labels().boolFalse }}
        </option>
      </select>
    </label>
  `,
})
export class AdaptBooleanFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly stack = FIELD_STACK;
  protected readonly widget = booleanFilterFor(this.def, this.source);

  /** The select offers only the three choices. */
  protected pick(value: string): void {
    this.widget().write(value as "" | "true" | "false");
  }
}

/** The choices of a select or checkbox field, following its definition. */
@Directive()
abstract class OptionsField<TRow> implements OnInit {
  abstract readonly def: Signal<FilterDef<TRow>>;
  private readonly injector = inject(Injector);
  protected readonly choices = signal<Signal<FilterOptionsState> | undefined>(
    undefined
  );
  protected readonly options = computed(
    () => this.choices()?.() ?? { options: [], loading: false }
  );

  ngOnInit(): void {
    this.choices.set(filterOptionsFor(this.def, this.injector));
  }
}

/** A single-choice filter. @internal */
@Component({
  selector: "adapt-select-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let value = current();
    <label data-adapttable-part="filter-field" [style]="stack">
      <span data-adapttable-part="filter-label">{{ caption() }}</span>
      <select
        data-adapttable-part="filter-select"
        [value]="value"
        (change)="source().setExtra(def().key, $any($event.target).value)"
      >
        @if (options().loading) {
          <option value="" disabled>…</option>
        } @else {
          <option value="" [selected]="value === ''">
            {{ labels().filterAll }}
          </option>
          @for (option of options().options; track option.value) {
            <option [value]="option.value" [selected]="option.value === value">
              {{ option.label }}
            </option>
          }
        }
      </select>
    </label>
  `,
})
export class AdaptSelectFilterField<TRow> extends OptionsField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels: the option for every value. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly stack = FIELD_STACK;
  protected readonly caption = computed(() => filterLabel(this.def()));
  protected readonly current = computed(() =>
    String(this.source().extra[this.def().key] ?? "")
  );
}

/** A multi-choice filter drawn as checkboxes. @internal */
@Component({
  selector: "adapt-multi-select-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ caption() }}</div>
      <div
        data-adapttable-part="filter-checkbox-group"
        style="display: flex; flex-wrap: wrap; gap: 10px; overflow: auto"
        [style.max-height.px]="listHeight"
      >
        @if (options().loading) {
          <span data-adapttable-part="filter-options-loading">…</span>
        } @else {
          @for (option of options().options; track option.value) {
            <label data-adapttable-part="filter-checkbox">
              <input
                type="checkbox"
                [checked]="selected().includes(option.value)"
                (change)="toggle(option.value, $any($event.target).checked)"
              />
              {{ option.label }}
            </label>
          }
        }
      </div>
    </fieldset>
  `,
})
export class AdaptMultiSelectFilterField<TRow> extends OptionsField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly listHeight = 220;
  protected readonly caption = computed(() => filterLabel(this.def()));
  protected readonly selected = computed(() =>
    listFilterValues(this.source().extra[this.def().key])
  );

  protected toggle(value: string, on: boolean): void {
    const current = this.selected();
    this.source().setExtra(
      this.def().key,
      on ? [...current, value] : current.filter((item) => item !== value)
    );
  }
}

/** An operator-first number or date range. @internal */
@Component({
  selector: "adapt-range-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    @let l = labels();
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ w.label }}</div>
      <div style="display: flex; flex-wrap: wrap; gap: 12px">
        <select
          data-adapttable-part="filter-operator"
          style="flex: 0 0 8.5rem; width: 8.5rem"
          [attr.aria-label]="l.operator"
          [value]="w.op ?? ''"
          (change)="pickOp($any($event.target).value)"
        >
          <option value="" [selected]="w.op === undefined">
            {{ l.operator }}
          </option>
          @for (op of w.ops; track op) {
            <option [value]="op" [selected]="op === w.op">
              {{ opLabel(op) }}
            </option>
          }
        </select>
        @if (w.arity === "two") {
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.from"
            [attr.aria-label]="l.from"
            [value]="w.a"
            (input)="w.write(w.op, $any($event.target).value, w.b)"
          />
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.to"
            [attr.aria-label]="l.to"
            [value]="w.b"
            (input)="w.write(w.op, w.a, $any($event.target).value)"
          />
        }
        @if (w.op === "relative") {
          @let token = relative();
          <select
            data-adapttable-part="filter-input"
            style="flex: 1 1 8.5rem; min-width: 8.5rem"
            [attr.aria-label]="l.opRelative"
            [value]="token.preset"
            (change)="pickPreset($any($event.target).value)"
          >
            @for (preset of presets; track preset) {
              <option [value]="preset" [selected]="preset === token.preset">
                {{ presetLabel(preset) }}
              </option>
            }
          </select>
          @if (token.preset === "last" || token.preset === "next") {
            <input
              type="number"
              min="1"
              data-adapttable-part="filter-input"
              style="flex: 0 0 4.5rem; width: 4.5rem"
              [attr.aria-label]="l.value"
              [value]="token.n"
              (input)="pickCount($any($event.target).value)"
            />
          }
        }
        @if (
          w.op !== undefined &&
          w.op !== "relative" &&
          w.arity !== "none" &&
          w.arity !== "two"
        ) {
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.value"
            [attr.aria-label]="l.value"
            [value]="w.a"
            (input)="w.write(w.op, $any($event.target).value, '')"
          />
        }
      </div>
    </fieldset>
  `,
})
export class AdaptRangeFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly presets = RELATIVE_PRESETS;
  protected readonly widget = rangeFilterFor(this.def, this.source);
  protected readonly relative = computed(() =>
    splitRelativeToken(this.widget().a)
  );

  protected opLabel(op: RangeOp): string {
    const keys = this.widget().opLabelKeys as Partial<
      Record<RangeOp, keyof TableLabels>
    >;
    const key = keys[op];
    return key ? filterOpLabel(this.labels(), key) : op;
  }

  protected presetLabel(preset: RelativePreset): string {
    return this.labels()[RELATIVE_PRESET_LABEL_KEYS[preset]];
  }

  protected pickOp(value: string): void {
    const w = this.widget();
    const next = w.ops.find((op) => op === value);
    w.setOp(next);
    w.write(next, w.a, w.b);
  }

  /** The select offers only the presets. */
  protected pickPreset(value: string): void {
    const w = this.widget();
    w.write(
      w.op,
      joinRelativeToken(value as RelativePreset, this.relative().n),
      ""
    );
  }

  protected pickCount(value: string): void {
    const w = this.widget();
    w.write(w.op, joinRelativeToken(this.relative().preset, Number(value)), "");
  }
}

/**
 * The auto-built filter form: one native field per definition.
 *
 * @public
 */
@Component({
  selector: "adapt-auto-filter-form",
  imports: [
    AdaptBooleanFilterField,
    AdaptChecklistChrome,
    AdaptMultiSelectFilterField,
    AdaptRangeFilterField,
    AdaptSelectFilterField,
    AdaptTextFilterField,
    NgComponentOutlet,
    NgTemplateOutlet,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @for (field of fields(); track field.def.key) {
      @let def = field.def;
      @if (field.renderer?.template; as template) {
        <ng-container
          [ngTemplateOutlet]="template"
          [ngTemplateOutletContext]="field.context"
        />
      } @else if (field.renderer?.component; as component) {
        <ng-container
          [ngComponentOutlet]="component"
          [ngComponentOutletInputs]="field.renderer.inputs"
        />
      } @else if (field.text; as text) {
        {{ text }}
      } @else {
        @switch (kindOf(def)) {
          @case ("text") {
            <adapt-text-filter-field
              [def]="def"
              [source]="source()"
              [labels]="labels()"
            />
          }
          @case ("boolean") {
            <adapt-boolean-filter-field
              [def]="def"
              [source]="source()"
              [labels]="labels()"
            />
          }
          @case ("select") {
            <adapt-select-filter-field
              [def]="def"
              [source]="source()"
              [labels]="labels()"
            />
          }
          @case ("multiSelect") {
            <adapt-multi-select-filter-field [def]="def" [source]="source()" />
          }
          @case ("checklist") {
            <adapt-checklist-chrome
              [def]="def"
              [source]="source()"
              [labels]="labels()"
              [slots]="checklistSlots"
            />
          }
          @case ("range") {
            <adapt-range-filter-field
              [def]="def"
              [source]="source()"
              [labels]="labels()"
            />
          }
        }
      }
    }
  `,
})
export class AdaptAutoFilterForm<TRow> {
  /** The resolved definitions, in order. */
  readonly defs = input.required<readonly FilterDef<TRow>[]>();
  /** The source whose filter bag the fields read and write. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();
  /** The filter type registry. */
  readonly registry = input<FilterTypeRegistry>(defaultFilterRegistry);

  protected readonly checklistSlots = CHECKLIST_SLOTS;

  /** Resolve each host renderer with the same live props its callback receives. */
  protected readonly fields = computed(() => {
    const source = this.source();
    const labels = this.labels();
    const registry = this.registry();
    return this.defs().map((def) => {
      const props: FilterWidgetRenderProps<TRow> = {
        def,
        source,
        labels,
        className: undefined,
      };
      const value = renderRegisteredFilter(def, source, labels, registry);
      const context = { ...props, $implicit: props };
      let renderer: TemplateRef<typeof context> | Type<unknown> | undefined;
      if (value instanceof TemplateRef) {
        renderer = value;
      } else if (typeof value === "function" && "ɵcmp" in value) {
        renderer = value as unknown as Type<unknown>;
      }
      return {
        def,
        context,
        renderer: resolveRenderer(renderer, context),
        text:
          value && (typeof value === "string" || typeof value === "number")
            ? String(value)
            : null,
      };
    });
  });

  /** Which field draws a definition. */
  protected kindOf(def: FilterDef<TRow>): string {
    const registry = this.registry();
    const kind: string =
      registry.get(def.type)?.widget ?? filterWidgetKind(def, registry) ?? "";
    return kind === "dateRange" || kind === "numberRange" ? "range" : kind;
  }
}
