// packages/adapter-mui/src/components/GroupHeader.tsx
import {
  groupAggregateEntries,
  type GroupedFlatEntry,
  groupLeafCount,
  groupRowLayout,
  groupSelectionState,
  type TableLabels,
} from "@adapttable/core";
import { type ColumnDef, type SelectionState } from "@adapttable/react";
import {
  groupIndentStyle,
  groupRowParts,
  GroupToggleSpacer,
  resolveMobileLabel,
} from "@adapttable/react/adapter";
import {
  Box,
  Card,
  CardContent,
  Checkbox,
  IconButton,
  TableCell,
  TableRow,
  Typography,
} from "@mui/material";
import type { ReactElement, ReactNode } from "react";

import { GroupMoreButton } from "./kitControls";

function GroupChevron({ expanded }: Readonly<{ expanded: boolean }>) {
  return (
    <Box
      component="span"
      aria-hidden
      sx={{
        display: "inline-flex",
        transition: "transform 150ms",
        transform: expanded ? "rotate(90deg)" : undefined,
      }}
    >
      <svg
        width="1em"
        height="1em"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9 6l6 6-6 6" />
      </svg>
    </Box>
  );
}

function GroupToggle({
  expanded,
  expandLabel,
  collapseLabel,
  onToggle,
}: Readonly<{
  expanded: boolean;
  expandLabel: string;
  collapseLabel: string;
  onToggle: () => void;
}>) {
  return (
    <IconButton
      size="small"
      data-adapttable-part="group-toggle"
      aria-expanded={expanded}
      aria-label={expanded ? collapseLabel : expandLabel}
      onClick={onToggle}
    >
      <GroupChevron expanded={expanded} />
    </IconButton>
  );
}

/** MUI group header row for the desktop table. */
export function GroupHeaderRow<TRow>({
  entry,
  columns,
  leadingCells,
  showActions,
  getCellProps,
  selection,
  labels,
  onToggleCollapse,
  onShowMore,
}: Readonly<{
  entry: Extract<
    GroupedFlatEntry<TRow>,
    { kind: "group" | "groupFooter" | "groupMore" }
  >;
  /** The data columns as rendered, so a subtotal lands under its own. */
  columns: readonly ColumnDef<TRow>[];
  /** Edge cells before the first data column (chevron, checkbox). */
  leadingCells: number;
  /** Whether a trailing actions column needs an empty cell. */
  showActions: boolean;
  /** The table's per-column cell props, so a number inherits its alignment. */
  getCellProps: (column: ColumnDef<TRow>) => Record<string, unknown>;
  selection: SelectionState | null;
  labels: Required<TableLabels>;
  onToggleCollapse: (groupKey: string) => void;
  /** Reveal the next page of groups, or of one group's rows. */
  onShowMore: (entry: { scope: "groups" | "rows"; groupKey?: string }) => void;
}>): ReactElement {
  // A footer is the same row with the controls taken away: no chevron
  // (nothing to collapse from the bottom), no checkbox (the header's own
  // selects the group), and a caption saying what the numbers are.
  const footer = entry.kind === "groupFooter";
  // A "show more" row is the same row again with a button where the label
  // goes: one component, so the three never drift apart in a kit.
  const more = entry.kind === "groupMore";
  const parts = groupRowParts(entry.kind);
  /** What the label cell shows: a button on a "more" row, else the name. */
  let labelContent: ReactNode = entry.label;
  if (entry.kind === "groupMore") {
    labelContent = (
      <GroupMoreButton
        scope={entry.scope}
        remaining={entry.remaining}
        groupKey={entry.groupKey}
        labels={labels}
        onShowMore={onShowMore}
      />
    );
  } else if (footer) {
    labelContent = labels.groupTotal(entry.label);
  }
  const expanded = entry.kind !== "group" || !entry.collapsed;
  const groupState =
    selection && !footer && !more
      ? groupSelectionState(entry.leafIds, selection.selectedIds)
      : "none";
  // One cell per column from the first aggregate onward: a subtotal only reads
  // as one when it sits under the column it totals.
  const layout = groupRowLayout<TRow, ColumnDef<TRow>>(
    columns,
    entry.kind === "groupMore" ? undefined : entry.aggregateCells,
    entry.kind === "groupMore" ? undefined : entry.aggregateOps
  );

  return (
    <TableRow
      data-adapttable-part={parts.row}
      data-collapsed={
        entry.kind === "group" && entry.collapsed ? "true" : undefined
      }
    >
      <TableCell
        colSpan={leadingCells + layout.labelColumns.length}
        data-adapttable-part={parts.cell}
        sx={{ fontWeight: 600 }}
        style={groupIndentStyle(entry.level)}
      >
        <Box
          sx={{
            display: "inline-flex",
            alignItems: "center",
            gap: 1,
            width: "100%",
          }}
        >
          {footer || more ? (
            <GroupToggleSpacer />
          ) : (
            <GroupToggle
              expanded={expanded}
              expandLabel={labels.expandGroup}
              collapseLabel={labels.collapseGroup}
              onToggle={() => onToggleCollapse(entry.key)}
            />
          )}
          {selection && !footer && !more && (
            <Checkbox
              data-adapttable-part="group-select"
              slotProps={{ input: { "aria-label": labels.selectAll } }}
              checked={groupState === "all"}
              indeterminate={groupState === "some"}
              onChange={() => selection.toggleGroupLeaves(entry.leafIds)}
            />
          )}
          <Typography
            component="span"
            data-adapttable-part={parts.label}
            variant="body2"
            sx={{ fontWeight: 600 }}
          >
            {labelContent}
          </Typography>
          <Typography
            component="span"
            data-adapttable-part="group-count"
            variant="body2"
            color="text.secondary"
          >
            {footer || more ? null : labels.groupCount(groupLeafCount(entry))}
          </Typography>
          {layout.labelAggregates.map(({ column, node }) => (
            <Box
              key={column.key}
              component="span"
              data-adapttable-part="group-aggregate"
              data-column={column.key}
              sx={{ marginInlineStart: "auto" }}
            >
              {node as ReactNode}
            </Box>
          ))}
        </Box>
      </TableCell>
      {layout.cells.map(({ column, node }) => (
        <TableCell
          key={column.key}
          {...getCellProps(column)}
          data-adapttable-part={
            node === undefined ? undefined : "group-aggregate"
          }
          data-column={node === undefined ? undefined : column.key}
        >
          {node as ReactNode}
        </TableCell>
      ))}
      {showActions && <TableCell />}
    </TableRow>
  );
}

/** Group header block for the mobile card list. */
export function GroupHeaderCard<TRow>({
  entry,
  columns,
  selection,
  labels,
  onToggleCollapse,
  onShowMore,
  compact = false,
}: Readonly<{
  entry: Extract<
    GroupedFlatEntry<TRow>,
    { kind: "group" | "groupFooter" | "groupMore" }
  >;
  /** The card's columns, for captioning each subtotal. */
  columns: readonly ColumnDef<TRow>[];
  selection: SelectionState | null;
  labels: Required<TableLabels>;
  onToggleCollapse: (groupKey: string) => void;
  /** Reveal the next page of groups, or of one group's rows. */
  onShowMore: (entry: { scope: "groups" | "rows"; groupKey?: string }) => void;
  compact?: boolean;
}>): ReactElement {
  // A footer is the same row with the controls taken away: no chevron
  // (nothing to collapse from the bottom), no checkbox (the header's own
  // selects the group), and a caption saying what the numbers are.
  const footer = entry.kind === "groupFooter";
  // A "show more" row is the same row again with a button where the label
  // goes: one component, so the three never drift apart in a kit.
  const more = entry.kind === "groupMore";
  const parts = groupRowParts(entry.kind);
  /** What the label cell shows: a button on a "more" row, else the name. */
  let labelContent: ReactNode = entry.label;
  if (entry.kind === "groupMore") {
    labelContent = (
      <GroupMoreButton
        scope={entry.scope}
        remaining={entry.remaining}
        groupKey={entry.groupKey}
        labels={labels}
        onShowMore={onShowMore}
      />
    );
  } else if (footer) {
    labelContent = labels.groupTotal(entry.label);
  }
  const expanded = entry.kind !== "group" || !entry.collapsed;
  const groupState =
    selection && !footer && !more
      ? groupSelectionState(entry.leafIds, selection.selectedIds)
      : "none";

  return (
    <Card
      data-adapttable-part={parts.card}
      data-collapsed={
        entry.kind === "group" && entry.collapsed ? "true" : undefined
      }
      variant="outlined"
    >
      <CardContent
        sx={compact ? { p: 1.25, "&:last-child": { pb: 1.25 } } : undefined}
      >
        <Box
          sx={{
            display: "inline-flex",
            alignItems: "center",
            gap: 1,
            fontWeight: 600,
          }}
        >
          {footer || more ? (
            <GroupToggleSpacer />
          ) : (
            <GroupToggle
              expanded={expanded}
              expandLabel={labels.expandGroup}
              collapseLabel={labels.collapseGroup}
              onToggle={() => onToggleCollapse(entry.key)}
            />
          )}
          {selection && !footer && !more && (
            <Checkbox
              data-adapttable-part="group-select"
              slotProps={{ input: { "aria-label": labels.selectAll } }}
              checked={groupState === "all"}
              indeterminate={groupState === "some"}
              onChange={() => selection.toggleGroupLeaves(entry.leafIds)}
            />
          )}
          <Typography
            component="span"
            data-adapttable-part={parts.label}
            variant="body2"
            sx={{ fontWeight: 600 }}
          >
            {labelContent}
          </Typography>
          <Typography
            component="span"
            data-adapttable-part="group-count"
            variant="body2"
            color="text.secondary"
          >
            {footer || more ? null : labels.groupCount(groupLeafCount(entry))}
          </Typography>
        </Box>
        {groupAggregateEntries<TRow, ColumnDef<TRow>>(
          columns,
          entry.kind === "groupMore" ? undefined : entry.aggregateCells,
          entry.kind === "groupMore" ? undefined : entry.aggregateOps
        ).map(({ column, node }) => (
          <Box key={column.key} sx={{ display: "flex", gap: 1, mt: 0.5 }}>
            <Typography component="span" variant="body2" color="text.secondary">
              {resolveMobileLabel(column)}
            </Typography>
            <Typography
              component="span"
              data-adapttable-part="group-aggregate"
              data-column={column.key}
              variant="body2"
              sx={{ marginInlineStart: "auto" }}
            >
              {node as ReactNode}
            </Typography>
          </Box>
        ))}
      </CardContent>
    </Card>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/groupHeader.ts
/**
 * Native group header, footer and "show more" rows for the desktop table,
 * and the same three as cards on phones — the kit fills for
 * {@link GROUP_HEADER_ROW} and {@link GROUP_HEADER_CARD}.
 */
import {
  AdaptAttrs,
  AdaptGroupMoreButtonChrome,
  AdaptGroupToggleSpacer,
  AdaptIcon,
  type ColumnDef,
  groupAggregateEntries,
  type GroupHeaderCardSlotProps,
  type GroupHeaderRowSlotProps,
  groupIndentStyle,
  groupLeafCount,
  type GroupMoreButtonSlotProps,
  groupRowLayout,
  groupRowParts,
  groupSelectionState,
  type IconDescriptor,
  resolveMobileLabel,
  type SelectionState,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Signal,
} from "@angular/core";

/** The entry either slot draws. */
type Entry = GroupHeaderRowSlotProps<
  never,
  SelectionState,
  ColumnDef<never>
>["entry"];

/** A chevron pointing into the row; the toggle turns it down when open. */
const CHEVRON: IconDescriptor = {
  viewBox: "0 0 24 24",
  width: 14,
  height: 14,
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 2,
  strokeLinecap: "round",
  strokeLinejoin: "round",
  focusable: "false",
  shapes: [{ tag: "path", d: "m9 6 6 6-6 6" }],
};

/**
 * The "show more" button inside a more row or card.
 *
 * @public
 */
@Component({
  selector: "adapt-group-more",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <button
      type="button"
      data-adapttable-part="group-more"
      style="font: inherit; background: transparent; border: none; padding: 0; cursor: pointer; text-decoration: underline; color: inherit"
      (click)="props().onClick()"
    >
      {{ props().label }}
    </button>
  `,
})
export class AdaptGroupMore {
  readonly props = input.required<GroupMoreButtonSlotProps>();
}

/** What both the row and the card derive from one entry. */
function groupEntryView(
  entry: () => Entry,
  selection: () => SelectionState | null
) {
  const group = computed(() => {
    const current = entry();
    return current.kind === "group" ? current : undefined;
  });
  return {
    parts: computed(() => groupRowParts(entry().kind)),
    /** Neither a footer nor a "show more" row has a toggle or a count. */
    plain: computed(() => entry().kind !== "group"),
    expanded: computed(() => {
      const current = entry();
      return current.kind !== "group" || !current.collapsed;
    }),
    collapsed: computed(() => {
      const current = entry();
      return current.kind === "group" && current.collapsed ? "true" : null;
    }),
    group,
    footer: computed(() => {
      const current = entry();
      return current.kind === "groupFooter" ? current : undefined;
    }),
    more: computed(() => {
      const current = entry();
      return current.kind === "groupMore" ? current : undefined;
    }),
    selectState: computed(() => {
      const open = group();
      const current = selection();
      return open && current
        ? groupSelectionState(open.leafIds, current.selectedIds)
        : undefined;
    }),
    count: computed(() => {
      const open = group();
      return open ? groupLeafCount(open) : 0;
    }),
    aggregateCells: computed(() => {
      const current = entry();
      return current.kind === "groupMore" ? undefined : current.aggregateCells;
    }),
  };
}

/**
 * A group's header, footer or "show more" row in the desktop table. One
 * cell per column from the first aggregate onward, so a subtotal sits under
 * the column it totals.
 *
 * @public
 */
@Component({
  selector: "tr[adaptGroupHeaderRow]",
  imports: [
    AdaptAttrs,
    AdaptGroupMoreButtonChrome,
    AdaptGroupToggleSpacer,
    AdaptIcon,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[attr.data-adapttable-part]": "view.parts().row",
    "[attr.data-collapsed]": "view.collapsed()",
  },
  template: `
    @let p = props();
    @let l = layout();
    <td
      [attr.colspan]="p.leadingCells + l.labelColumns.length"
      [attr.data-adapttable-part]="view.parts().cell"
      [style]="labelCellStyle()"
    >
      <span
        style="display: inline-flex; align-items: center; gap: 8px; width: 100%"
      >
        @if (view.group(); as group) {
          <button
            type="button"
            data-adapttable-part="group-toggle"
            [attr.aria-expanded]="view.expanded()"
            [attr.aria-label]="
              view.expanded() ? p.labels.collapseGroup : p.labels.expandGroup
            "
            (click)="p.onToggleCollapse(group.key)"
          >
            <span
              style="display: inline-flex; transition: transform 150ms ease"
              [style.transform]="
                view.expanded() ? 'rotate(90deg)' : 'rotate(0deg)'
              "
            >
              <svg [adaptIcon]="chevron"></svg>
            </span>
          </button>
          @if (p.selection; as selection) {
            <input
              type="checkbox"
              data-adapttable-part="group-select"
              [attr.aria-label]="p.labels.selectAll"
              [checked]="view.selectState() === 'all'"
              [indeterminate]="view.selectState() === 'some'"
              (change)="selection.toggleGroupLeaves(group.leafIds)"
            />
          }
        } @else {
          <adapt-group-toggle-spacer />
        }
        <span [attr.data-adapttable-part]="view.parts().label">
          @if (view.more(); as more) {
            <adapt-group-more-button-chrome
              [scope]="more.scope"
              [remaining]="more.remaining"
              [groupKey]="more.groupKey"
              [labels]="p.labels"
              [onShowMore]="p.onShowMore"
              [slots]="moreSlots"
            />
          } @else if (view.footer(); as footer) {
            {{ p.labels.groupTotal(footer.label) }}
          } @else {
            {{ view.group()?.label }}
          }
        </span>
        @if (view.plain()) {
          <adapt-group-toggle-spacer />
        } @else {
          <span data-adapttable-part="group-count" style="opacity: 0.65">{{
            p.labels.groupCount(view.count())
          }}</span>
        }
        @for (aggregate of l.labelAggregates; track aggregate.column.key) {
          <span
            data-adapttable-part="group-aggregate"
            [attr.data-column]="aggregate.column.key"
            style="margin-inline-start: auto"
            >{{ aggregate.node }}</span
          >
        }
      </span>
    </td>
    @for (cell of l.cells; track cell.column.key) {
      <td
        [adaptAttrs]="p.getCellProps(cell.column)"
        [attr.data-adapttable-part]="
          cell.node === undefined ? null : 'group-aggregate'
        "
        [attr.data-column]="cell.node === undefined ? null : cell.column.key"
      >
        {{ cell.node }}
      </td>
    }
    @if (p.showActions) {
      <td></td>
    }
  `,
})
export class AdaptGroupHeaderRow {
  /** Slot props from the table's group-header-row fill. */
  readonly props =
    input.required<
      GroupHeaderRowSlotProps<never, SelectionState, ColumnDef<never>>
    >();

  protected readonly chevron = CHEVRON;
  protected readonly moreSlots = { Button: AdaptGroupMore };
  /** Operations for the current group or footer, retaining the model type. */
  protected readonly aggregateOps: Signal<
    Parameters<typeof groupRowLayout>[2]
  > = computed(() => {
    const current = this.props().entry;
    return current.kind === "groupMore" ? undefined : current.aggregateOps;
  });
  protected readonly view = groupEntryView(
    () => this.props().entry,
    () => this.props().selection
  );

  protected readonly layout = computed(() =>
    groupRowLayout<never, ColumnDef<never>>(
      this.props().columns,
      this.view.aggregateCells(),
      this.aggregateOps()
    )
  );

  protected readonly labelCellStyle = computed(() => ({
    fontWeight: 600,
    ...groupIndentStyle(this.props().entry.level),
  }));
}

/**
 * A group's header, footer or "show more" block in the phone card list. A
 * card shows only the subtotals that exist, each captioned by its column.
 *
 * @public
 */
@Component({
  selector: "adapt-group-header-card",
  imports: [AdaptGroupMoreButtonChrome, AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <div
      [attr.data-adapttable-part]="view.parts().card"
      [attr.data-collapsed]="view.collapsed()"
      style="font-weight: 600"
    >
      <span style="display: inline-flex; align-items: center; gap: 8px">
        @if (view.group(); as group) {
          <button
            type="button"
            data-adapttable-part="group-toggle"
            [attr.aria-expanded]="view.expanded()"
            [attr.aria-label]="
              view.expanded() ? p.labels.collapseGroup : p.labels.expandGroup
            "
            (click)="p.onToggleCollapse(group.key)"
          >
            <span
              style="display: inline-flex; transition: transform 150ms ease"
              [style.transform]="
                view.expanded() ? 'rotate(90deg)' : 'rotate(0deg)'
              "
            >
              <svg [adaptIcon]="chevron"></svg>
            </span>
          </button>
          @if (p.selection; as selection) {
            <input
              type="checkbox"
              data-adapttable-part="group-select"
              [attr.aria-label]="p.labels.selectAll"
              [checked]="view.selectState() === 'all'"
              [indeterminate]="view.selectState() === 'some'"
              (change)="selection.toggleGroupLeaves(group.leafIds)"
            />
          }
        }
        <span [attr.data-adapttable-part]="view.parts().label">
          @if (view.more(); as more) {
            <adapt-group-more-button-chrome
              [scope]="more.scope"
              [remaining]="more.remaining"
              [groupKey]="more.groupKey"
              [labels]="p.labels"
              [onShowMore]="p.onShowMore"
              [slots]="moreSlots"
            />
          } @else if (view.footer(); as footer) {
            {{ p.labels.groupTotal(footer.label) }}
          } @else {
            {{ view.group()?.label }}
          }
        </span>
        @if (!view.plain()) {
          <span data-adapttable-part="group-count" style="opacity: 0.65">{{
            p.labels.groupCount(view.count())
          }}</span>
        }
      </span>
      @for (aggregate of aggregates(); track aggregate.column.key) {
        <span style="display: flex; gap: 8px; margin-top: 4px">
          <span style="opacity: 0.65">{{ caption(aggregate.column) }}</span>
          <span
            data-adapttable-part="group-aggregate"
            [attr.data-column]="aggregate.column.key"
            style="margin-inline-start: auto"
            >{{ aggregate.node }}</span
          >
        </span>
      }
    </div>
  `,
})
export class AdaptGroupHeaderCard {
  /** Slot props from the table's group-header-card fill. */
  readonly props =
    input.required<
      GroupHeaderCardSlotProps<never, SelectionState, ColumnDef<never>>
    >();

  protected readonly chevron = CHEVRON;
  protected readonly moreSlots = { Button: AdaptGroupMore };
  /** Operations for the current group or footer, retaining the model type. */
  protected readonly aggregateOps: Signal<
    Parameters<typeof groupRowLayout>[2]
  > = computed(() => {
    const current = this.props().entry;
    return current.kind === "groupMore" ? undefined : current.aggregateOps;
  });
  protected readonly view = groupEntryView(
    () => this.props().entry,
    () => this.props().selection
  );

  protected readonly aggregates = computed(() =>
    groupAggregateEntries<never, ColumnDef<never>>(
      this.props().columns,
      this.view.aggregateCells(),
      this.aggregateOps()
    )
  );

  /** A subtotal's caption: the column's mobile label. */
  protected caption(column: ColumnDef<never>): string | undefined {
    return resolveMobileLabel(column);
  }
}
