// packages/adapter-unstyled/src/components/PaginationFooter.tsx
/** Row count and the windowed pager. */
import {
  pageSizeOptions,
  type PaginationInfo,
  type TableLabels,
  type TableSource,
} from "@adapttable/core";
import { paginationSlots } from "@adapttable/react/adapter";

import type { DataTableClassNames } from "../types";

/** The rows-per-page selector shared by the toolbar (infinite) and footer. */
export function RowsPerPageSelect({
  source,
  labels,
  classNames,
}: Readonly<{
  source: Pick<TableSource<unknown>, "limit" | "defaultLimit" | "setLimit">;
  labels: Required<TableLabels>;
  classNames: DataTableClassNames;
}>) {
  return (
    <label>
      {labels.rowsPerPage}{" "}
      <select
        aria-label={labels.rowsPerPage}
        data-adapttable-part="rows-per-page"
        className={classNames.rowsPerPage}
        value={source.limit}
        onChange={(e) => source.setLimit(Number(e.currentTarget.value))}
      >
        {pageSizeOptions([source.limit, source.defaultLimit]).map((n) => (
          <option key={n} value={n}>
            {n}
          </option>
        ))}
      </select>
    </label>
  );
}

/** Prev/next pager with a rows-per-page select. */
export function Footer({
  pagination,
  source,
  labels,
  classNames,
  showRowsPerPage = true,
}: Readonly<{
  pagination: PaginationInfo;
  source: {
    limit: number;
    defaultLimit: number;
    total: number;
    setPage: (n: number) => void;
    setLimit: (n: number) => void;
  };
  labels: Required<TableLabels>;
  classNames: DataTableClassNames;
  /** Hidden in the grouped full-set view, where page size has no effect. */
  showRowsPerPage?: boolean;
}>) {
  const { safePage, totalPages, fromIndex, toIndex } = pagination;
  return (
    <div data-adapttable-part="footer" className={classNames.footer}>
      {showRowsPerPage && (
        <RowsPerPageSelect
          source={source}
          labels={labels}
          classNames={classNames}
        />
      )}
      {source.total > 0 && (
        <span>
          {labels.showing({
            from: fromIndex,
            to: toIndex,
            total: source.total,
          })}
        </span>
      )}
      <div data-adapttable-part="pager" className={classNames.pager}>
        <span>{labels.pageOf({ page: safePage, total: totalPages })}</span>
        <button
          type="button"
          aria-label={labels.previousPage}
          data-adapttable-part="page-prev"
          className={classNames.pagePrev}
          disabled={safePage <= 1}
          onClick={() => source.setPage(safePage - 1)}
        >
          ‹
        </button>
        {paginationSlots(safePage, totalPages).map(({ item, key }) =>
          item === "ellipsis" ? (
            <span
              key={key}
              data-adapttable-part="page-ellipsis"
              aria-hidden="true"
              className={classNames.pageEllipsis}
            >
              …
            </span>
          ) : (
            <button
              key={key}
              type="button"
              data-adapttable-part="page-number"
              aria-current={item === safePage ? "page" : undefined}
              className={classNames.pageNumber}
              onClick={() => source.setPage(item)}
            >
              {item}
            </button>
          )
        )}
        <button
          type="button"
          aria-label={labels.nextPage}
          data-adapttable-part="page-next"
          className={classNames.pageNext}
          disabled={safePage >= totalPages}
          onClick={() => source.setPage(safePage + 1)}
        >
          ›
        </button>
      </div>
    </div>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/paginationFooter.ts
/**
 * Row count and the windowed pager.
 */
import {
  AdaptAttrs,
  AdaptIcon,
  expandChevronIcon,
} from "@adapttable/angular/adapter";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";

import type { TableView } from "../dataTable";

/**
 * Prev/next pager with a rows-per-page select.
 *
 * @internal
 */
@Component({
  selector: "adapt-pagination-footer",
  imports: [AdaptAttrs, AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let v = view();
    <div data-adapttable-part="footer">
      <label>
        {{ v.table.labels().rowsPerPage }}
        <select
          data-adapttable-part="rows-per-page"
          [attr.aria-label]="v.table.labels().rowsPerPage"
          [adaptAttrs]="{ value: v.table.source().limit }"
          (change)="v.table.setLimit(+$any($event.target).value)"
        >
          @for (size of v.table.pageSizeOptions(); track size) {
            <option
              [value]="size"
              [attr.selected]="size === v.table.source().limit ? '' : null"
            >
              {{ size }}
            </option>
          }
        </select>
      </label>
      @if (v.table.source().total > 0) {
        <span>{{
          v.table.labels().showing({
            from: v.table.pagination().fromIndex,
            to: v.table.pagination().toIndex,
            total: v.table.source().total,
          })
        }}</span>
      }
      <div data-adapttable-part="pager">
        <span>{{
          v.table.labels().pageOf({
            page: v.table.pagination().safePage,
            total: v.table.pagination().totalPages,
          })
        }}</span>
        <button
          type="button"
          data-adapttable-part="page-prev"
          [attr.aria-label]="v.table.labels().previousPage"
          [disabled]="v.table.pagination().safePage <= 1"
          (click)="v.table.setPage(v.table.pagination().safePage - 1)"
        >
          <svg [adaptIcon]="previousIcon()"></svg>
        </button>
        @for (slot of v.table.pagerSlots(); track slot.key) {
          @if (slot.item === "ellipsis") {
            <span data-adapttable-part="page-ellipsis" aria-hidden="true"
              >…</span
            >
          } @else {
            <button
              type="button"
              data-adapttable-part="page-number"
              [attr.aria-label]="v.table.labels().goToPage(+slot.item)"
              [attr.aria-current]="
                slot.item === v.table.pagination().safePage ? 'page' : null
              "
              (click)="v.table.setPage(+slot.item)"
            >
              {{ slot.item }}
            </button>
          }
        }
        <button
          type="button"
          data-adapttable-part="page-next"
          [attr.aria-label]="v.table.labels().nextPage"
          [disabled]="
            v.table.pagination().safePage >= v.table.pagination().totalPages
          "
          (click)="v.table.setPage(v.table.pagination().safePage + 1)"
        >
          <svg [adaptIcon]="nextIcon()"></svg>
        </button>
      </div>
    </div>
  `,
})
export class AdaptPaginationFooter<TRow> {
  /** What the table renders from. */
  readonly view = input.required<TableView<TRow>>();

  /** Pagination follows reading order, including live direction changes. */
  protected readonly previousIcon = computed(() =>
    expandChevronIcon({
      open: false,
      dir: this.view().table.dir() === "rtl" ? "ltr" : "rtl",
    })
  );
  protected readonly nextIcon = computed(() =>
    expandChevronIcon({ open: false, dir: this.view().table.dir() })
  );
}
