// packages/adapter-chakra/src/components/PaginationFooter.tsx
/** Row count and the windowed pager. */
import type { PaginationInfo, TableLabels } from "@adapttable/core";
import { pageSizeOptions } from "@adapttable/core";
import { paginationSlots } from "@adapttable/react/adapter";
import { Button, HStack, Text } from "@chakra-ui/react";

import { subtleText } from "../styles";
import { NativeSelect } from "./primitives";

/** Paged footer with prev/next. */
export function Footer({
  pagination,
  total,
  limit,
  defaultLimit = limit,
  setPage,
  setLimit,
  labels,
  className,
  showRowsPerPage = true,
}: Readonly<{
  pagination: PaginationInfo;
  total: number;
  limit: number;
  defaultLimit?: number;
  setPage: (n: number) => void;
  setLimit: (n: number) => void;
  labels: Required<TableLabels>;
  /** Class hook for the footer row. */
  className?: string;
  /** Hidden in the grouped full-set view, where page size has no effect. */
  showRowsPerPage?: boolean;
}>) {
  const { safePage, totalPages, fromIndex, toIndex } = pagination;
  return (
    <HStack
      gap={3}
      justify="space-between"
      flexWrap="wrap"
      className={className}
    >
      <HStack gap={2}>
        {showRowsPerPage && (
          <>
            <Text fontSize="xs" {...subtleText}>
              {labels.rowsPerPage}
            </Text>
            <NativeSelect
              size="xs"
              w="72px"
              aria-label={labels.rowsPerPage}
              value={String(limit)}
              onChange={(e) => setLimit(Number(e.target.value))}
            >
              {pageSizeOptions([limit, defaultLimit]).map((n) => (
                <option key={n} value={String(n)}>
                  {n}
                </option>
              ))}
            </NativeSelect>
          </>
        )}
        {total > 0 && (
          <Text fontSize="xs" {...subtleText}>
            {labels.showing({ from: fromIndex, to: toIndex, total })}
          </Text>
        )}
      </HStack>
      <HStack gap={1}>
        <Text fontSize="xs" {...subtleText}>
          {labels.pageOf({ page: safePage, total: totalPages })}
        </Text>
        <Button
          size="xs"
          variant="outline"
          aria-label={labels.previousPage}
          disabled={safePage <= 1}
          onClick={() => setPage(safePage - 1)}
        >
          ‹
        </Button>
        {paginationSlots(safePage, totalPages).map(({ item, key }) =>
          item === "ellipsis" ? (
            <Text key={key} fontSize="xs" px={1} {...subtleText}>
              …
            </Text>
          ) : (
            <Button
              key={key}
              size="xs"
              variant={item === safePage ? "solid" : "outline"}
              aria-current={item === safePage ? "page" : undefined}
              onClick={() => setPage(item)}
            >
              {item}
            </Button>
          )
        )}
        <Button
          size="xs"
          variant="outline"
          aria-label={labels.nextPage}
          disabled={safePage >= totalPages}
          onClick={() => setPage(safePage + 1)}
        >
          ›
        </Button>
      </HStack>
    </HStack>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/paginationFooter.ts
/**
 * Row count and the windowed pager.
 */
import {
  AdaptAttrs,
  AdaptIcon,
  expandChevronIcon,
} from "@adapttable/angular/adapter";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";

import type { TableView } from "../dataTable";

/**
 * Prev/next pager with a rows-per-page select.
 *
 * @internal
 */
@Component({
  selector: "adapt-pagination-footer",
  imports: [AdaptAttrs, AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let v = view();
    <div data-adapttable-part="footer">
      <label>
        {{ v.table.labels().rowsPerPage }}
        <select
          data-adapttable-part="rows-per-page"
          [attr.aria-label]="v.table.labels().rowsPerPage"
          [adaptAttrs]="{ value: v.table.source().limit }"
          (change)="v.table.setLimit(+$any($event.target).value)"
        >
          @for (size of v.table.pageSizeOptions(); track size) {
            <option
              [value]="size"
              [attr.selected]="size === v.table.source().limit ? '' : null"
            >
              {{ size }}
            </option>
          }
        </select>
      </label>
      @if (v.table.source().total > 0) {
        <span>{{
          v.table.labels().showing({
            from: v.table.pagination().fromIndex,
            to: v.table.pagination().toIndex,
            total: v.table.source().total,
          })
        }}</span>
      }
      <div data-adapttable-part="pager">
        <span>{{
          v.table.labels().pageOf({
            page: v.table.pagination().safePage,
            total: v.table.pagination().totalPages,
          })
        }}</span>
        <button
          type="button"
          data-adapttable-part="page-prev"
          [attr.aria-label]="v.table.labels().previousPage"
          [disabled]="v.table.pagination().safePage <= 1"
          (click)="v.table.setPage(v.table.pagination().safePage - 1)"
        >
          <svg [adaptIcon]="previousIcon()"></svg>
        </button>
        @for (slot of v.table.pagerSlots(); track slot.key) {
          @if (slot.item === "ellipsis") {
            <span data-adapttable-part="page-ellipsis" aria-hidden="true"
              >…</span
            >
          } @else {
            <button
              type="button"
              data-adapttable-part="page-number"
              [attr.aria-label]="v.table.labels().goToPage(+slot.item)"
              [attr.aria-current]="
                slot.item === v.table.pagination().safePage ? 'page' : null
              "
              (click)="v.table.setPage(+slot.item)"
            >
              {{ slot.item }}
            </button>
          }
        }
        <button
          type="button"
          data-adapttable-part="page-next"
          [attr.aria-label]="v.table.labels().nextPage"
          [disabled]="
            v.table.pagination().safePage >= v.table.pagination().totalPages
          "
          (click)="v.table.setPage(v.table.pagination().safePage + 1)"
        >
          <svg [adaptIcon]="nextIcon()"></svg>
        </button>
      </div>
    </div>
  `,
})
export class AdaptPaginationFooter<TRow> {
  /** What the table renders from. */
  readonly view = input.required<TableView<TRow>>();

  /** Pagination follows reading order, including live direction changes. */
  protected readonly previousIcon = computed(() =>
    expandChevronIcon({
      open: false,
      dir: this.view().table.dir() === "rtl" ? "ltr" : "rtl",
    })
  );
  protected readonly nextIcon = computed(() =>
    expandChevronIcon({ open: false, dir: this.view().table.dir() })
  );
}
