// packages/adapter-unstyled/src/components/FilterPopover.tsx
import type { Direction, TableLabels } from "@adapttable/core";
import { type ReactNode, useEffect, useRef } from "react";
import { createPortal } from "react-dom";

import { cx } from "../cx";
import type { DataTableClassNames } from "../types";
import {
  OVERLAY_Z,
  placeOverlayBelowTrigger,
  VIEWPORT_GUTTER,
} from "./overlayPlacement";

/**
 * Props for {@link FilterPopover}.
 *
 * @public
 */
export interface FilterPopoverProps {
  open: boolean;
  onClose: () => void;
  filters: ReactNode;
  activeFilterCount: number;
  onClearFilters?: () => void;
  labels: Required<TableLabels>;
  dir?: Direction;
  classNames: DataTableClassNames;
  /** The Filters trigger button — the popover anchors beneath it. */
  children: ReactNode;
}

/**
 * Anchored filter card (the default filter container). Opens beneath the
 * Filters button with NO backdrop — the background stays visible and
 * interactive; clicking outside the popover/anchor or pressing Escape closes
 * it. Portalled to `document.body` so sticky headers cannot paint over it.
 * Pair with `filtersMode="drawer"` for the slide-in panel (`FilterPanel`).
 *
 * @public
 */
export function FilterPopover({
  open,
  onClose,
  filters,
  activeFilterCount,
  onClearFilters,
  labels,
  dir = "ltr",
  classNames,
  children,
}: Readonly<FilterPopoverProps>) {
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;
  const rootRef = useRef<HTMLSpanElement>(null);
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onClick = (event: MouseEvent) => {
      const root = rootRef.current!;
      const target = event.target as Node;
      if (!document.contains(target)) return;
      if (root.contains(target)) return;
      if (cardRef.current?.contains(target)) return;
      if (cardRef.current?.contains(document.activeElement)) return;
      onCloseRef.current();
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      onCloseRef.current();
      rootRef.current?.querySelector("button")?.focus();
    };
    document.addEventListener("click", onClick);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("click", onClick);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  useEffect(() => {
    if (!open) return;
    const card = cardRef.current;
    const root = rootRef.current;
    if (!card || !root) return;
    const place = () => placeOverlayBelowTrigger(card, root, dir);
    place();
    window.addEventListener("resize", place);
    window.addEventListener("scroll", place, true);
    return () => {
      window.removeEventListener("resize", place);
      window.removeEventListener("scroll", place, true);
    };
  }, [open, dir]);

  const card = open ? (
    <div
      ref={cardRef}
      data-adapttable-part="filters-popover"
      dir={dir}
      data-dir={dir}
      className={cx("adapttable-filters-popover", classNames.filtersPopover)}
      style={{
        position: "fixed",
        zIndex: OVERLAY_Z,
        width: 380,
        maxWidth: `calc(100vw - ${VIEWPORT_GUTTER * 2}px)`,
        overflowY: "auto",
      }}
    >
      <header
        data-adapttable-part="filters-header"
        className={classNames.filtersHeader}
      >
        <h3
          data-adapttable-part="filters-title"
          className={classNames.filtersTitle}
        >
          {labels.filters}
          {activeFilterCount > 0 ? ` (${activeFilterCount})` : ""}
        </h3>
        <button
          type="button"
          onClick={() => onClearFilters?.()}
          disabled={activeFilterCount === 0}
          data-adapttable-part="filters-clear"
          className={classNames.filtersClear}
        >
          {labels.clearAll}
        </button>
      </header>
      <div
        data-adapttable-part="filters-body"
        className={classNames.filtersBody}
      >
        {filters}
      </div>
    </div>
  ) : null;

  return (
    <span
      ref={rootRef}
      data-adapttable-part="filters-anchor"
      className={cx("adapttable-filters-anchor", classNames.filtersAnchor)}
      style={{ position: "relative", display: "inline-flex" }}
    >
      {children}
      {card && createPortal(card, document.body)}
    </span>
  );
}

// packages/angular/adapter-angular-aria/src/components/filterPopover.ts
/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 */
import { type FilterOverlaySlotProps } from "@adapttable/angular";
import { Dir } from "@angular/cdk/bidi";
import { CdkConnectedOverlay, CdkOverlayOrigin } from "@angular/cdk/overlay";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  type ElementRef,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";

/** An overlay's props in Angular: its content is a template. */

/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 *
 * @internal
 */
@Component({
  host: { class: "adapt-aria" },
  selector: "adapt-filter-popover",
  imports: [NgTemplateOutlet, CdkConnectedOverlay, CdkOverlayOrigin, Dir],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <span
      #anchor
      [dir]="p.dir ?? 'ltr'"
      cdkOverlayOrigin
      #origin="cdkOverlayOrigin"
      data-adapttable-part="filters-anchor"
      style="position: relative; display: inline-flex"
    >
      @if (p.children; as trigger) {
        <ng-container [ngTemplateOutlet]="trigger" />
      }
      <ng-template
        cdkConnectedOverlay
        [cdkConnectedOverlayOrigin]="origin"
        [cdkConnectedOverlayOpen]="p.open"
        [cdkConnectedOverlayHasBackdrop]="false"
        [cdkConnectedOverlayViewportMargin]="8"
        [cdkConnectedOverlayPush]="true"
        (overlayOutsideClick)="outside($event)"
        (overlayKeydown)="key($event)"
      >
        <div
          class="adapt-aria adapt-aria-popup"
          data-adapttable-part="filters-popover"
          [attr.dir]="p.dir ?? 'ltr'"
          [attr.data-dir]="p.dir ?? 'ltr'"
          [style.width.px]="380"
          [style.max-width]="'calc(100vw - 16px)'"
          [style.overflow-y]="'auto'"
        >
          <header data-adapttable-part="filters-header">
            <h3 data-adapttable-part="filters-title">
              {{ p.labels.filters
              }}{{
                p.activeFilterCount > 0 ? " (" + p.activeFilterCount + ")" : ""
              }}
            </h3>
            <button
              type="button"
              data-adapttable-part="filters-clear"
              [disabled]="p.activeFilterCount === 0"
              (click)="p.onClearFilters()"
            >
              {{ p.labels.clearAll }}
            </button>
          </header>
          <div data-adapttable-part="filters-body">
            <ng-container [ngTemplateOutlet]="p.filters" />
          </div>
        </div>
      </ng-template>
    </span>
  `,
})
export class AdaptFilterPopover {
  /** The slot's props. */
  readonly props =
    input.required<FilterOverlaySlotProps<TemplateRef<unknown>>>();

  private readonly anchor =
    viewChild.required<ElementRef<HTMLElement>>("anchor");

  protected outside(event: MouseEvent): void {
    if (!this.anchor().nativeElement.contains(event.target as Node))
      this.props().onClose();
  }

  protected key(event: KeyboardEvent): void {
    if (event.key !== "Escape") return;
    event.preventDefault();
    this.props().onClose();
    this.anchor().nativeElement.querySelector("button")?.focus();
  }
}
