// packages/angular/adapter-angular-unstyled/src/components/filterPopover.ts
/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 */
import { type FilterOverlaySlotProps } from "@adapttable/angular";
import { NgTemplateOutlet } from "@angular/common";
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  effect,
  type ElementRef,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";

import { OVERLAY_Z, placeOverlayBelowTrigger } from "./overlayPlacement";

/** An overlay's props in Angular: its content is a template. */

/**
 * The anchored filter card: opens under the Filters button with no
 * backdrop, closes on an outside click or Escape, and hands focus back to
 * the button on Escape.
 *
 * @internal
 */
@Component({
  selector: "adapt-filter-popover",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <span
      #anchor
      data-adapttable-part="filters-anchor"
      style="position: relative; display: inline-flex"
    >
      @if (p.children; as trigger) {
        <ng-container [ngTemplateOutlet]="trigger" />
      }
      @if (p.open) {
        <div
          #card
          data-adapttable-part="filters-popover"
          [attr.dir]="p.dir ?? 'ltr'"
          [attr.data-dir]="p.dir ?? 'ltr'"
          [style.position]="'fixed'"
          [style.z-index]="zIndex"
          [style.width.px]="380"
          [style.max-width]="'calc(100vw - 16px)'"
          [style.overflow-y]="'auto'"
        >
          <header data-adapttable-part="filters-header">
            <h3 data-adapttable-part="filters-title">
              {{ p.labels.filters
              }}{{
                p.activeFilterCount > 0 ? " (" + p.activeFilterCount + ")" : ""
              }}
            </h3>
            <button
              type="button"
              data-adapttable-part="filters-clear"
              [disabled]="p.activeFilterCount === 0"
              (click)="p.onClearFilters()"
            >
              {{ p.labels.clearAll }}
            </button>
          </header>
          <div data-adapttable-part="filters-body">
            <ng-container [ngTemplateOutlet]="p.filters" />
          </div>
        </div>
      }
    </span>
  `,
})
export class AdaptFilterPopover {
  /** The slot's props. */
  readonly props =
    input.required<FilterOverlaySlotProps<TemplateRef<unknown>>>();

  protected readonly zIndex = OVERLAY_Z;
  private readonly anchor =
    viewChild.required<ElementRef<HTMLElement>>("anchor");
  private readonly card = viewChild<ElementRef<HTMLElement>>("card");

  constructor() {
    effect((onCleanup) => {
      const { open, onClose } = this.props();
      if (!open) return;
      const onClick = (event: MouseEvent): void => {
        const target = event.target as Node;
        if (!document.contains(target)) return;
        if (this.anchor().nativeElement.contains(target)) return;
        const card = this.card()?.nativeElement;
        if (card?.contains(target) || card?.contains(document.activeElement)) {
          return;
        }
        onClose();
      };
      const onKey = (event: KeyboardEvent): void => {
        if (event.key !== "Escape") return;
        onClose();
        this.anchor().nativeElement.querySelector("button")?.focus();
      };
      document.addEventListener("click", onClick);
      document.addEventListener("keydown", onKey);
      onCleanup(() => {
        document.removeEventListener("click", onClick);
        document.removeEventListener("keydown", onKey);
      });
    });

    afterRenderEffect((onCleanup) => {
      const card = this.card()?.nativeElement;
      const { open, dir } = this.props();
      if (!open || !card) return;
      const place = (): void => {
        placeOverlayBelowTrigger(
          card,
          this.anchor().nativeElement,
          dir ?? "ltr"
        );
      };
      place();
      window.addEventListener("resize", place);
      window.addEventListener("scroll", place, true);
      onCleanup(() => {
        window.removeEventListener("resize", place);
        window.removeEventListener("scroll", place, true);
      });
    });
  }
}

// packages/adapter-chakra/src/components/FilterPopover.tsx
import type { Direction, TableLabels } from "@adapttable/core";
import { Button, HStack, Popover, Portal, Stack, Text } from "@chakra-ui/react";
import { type ReactNode, useEffect, useRef } from "react";

/** Props for {@link FilterPopover}. */
export interface FilterPopoverProps {
  open: boolean;
  onClose: () => void;
  filters: ReactNode;
  activeFilterCount: number;
  onClearFilters: () => void;
  labels: Required<TableLabels>;
  accentColor?: string;
  dir?: Direction;
  /** The Filters trigger button — becomes the popover anchor. */
  children: ReactNode;
}

/**
 * Anchored filter card (the default filter container). Opens under the Filters
 * button with no backdrop — the background stays visible and interactive;
 * clicking outside or pressing Escape closes it. Pair with
 * `filtersMode="drawer"` for the slide-in panel instead.
 */
export function FilterPopover({
  open,
  onClose,
  filters,
  activeFilterCount,
  onClearFilters,
  labels,
  accentColor,
  dir = "ltr",
  children,
}: Readonly<FilterPopoverProps>) {
  const anchorRef = useRef<HTMLSpanElement>(null);

  // Ark's `closeOnEscape` restores focus only through `Popover.Trigger`, which
  // this layout doesn't use (the Filters button is an external anchor). Handle
  // Escape ourselves instead: close, then hand focus back to the trigger
  // inside the anchor — the same document-level pattern as the other adapters
  // (and, unlike Ark's browser-only restore, exercisable in jsdom).
  useEffect(() => {
    if (!open) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      onClose();
      anchorRef.current?.querySelector("button")?.focus();
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [open, onClose]);

  return (
    <Popover.Root
      open={open}
      onOpenChange={(e) => {
        if (!e.open) onClose();
      }}
      positioning={{
        placement: dir === "rtl" ? "bottom-start" : "bottom-end",
      }}
      closeOnInteractOutside
      closeOnEscape={false}
      lazyMount
      unmountOnExit
    >
      <Popover.Anchor asChild>
        <span ref={anchorRef} style={{ display: "inline-flex" }}>
          {children}
        </span>
      </Popover.Anchor>
      <Portal>
        <Popover.Positioner>
          <Popover.Content
            data-testid="adapttable-filter-popover"
            aria-label={labels.filters}
            w="340px"
            maxW="90vw"
            dir={dir}
            zIndex="popover"
          >
            <Popover.Header border="0" pb={1}>
              <HStack justify="space-between" align="center">
                <Text fontWeight="semibold" fontSize="sm">
                  {labels.filters}
                </Text>
                <Button
                  size="xs"
                  variant="ghost"
                  colorPalette={accentColor}
                  onClick={onClearFilters}
                  disabled={activeFilterCount === 0}
                >
                  {labels.clearAll}
                </Button>
              </HStack>
            </Popover.Header>
            <Popover.Body>
              <Stack gap={4}>{filters}</Stack>
            </Popover.Body>
          </Popover.Content>
        </Popover.Positioner>
      </Portal>
    </Popover.Root>
  );
}
