// packages/angular/angular/src/rows/rowPinning.ts
/**
 * Row pinning — the asking, never the data. A pinned row leaves the scrolling
 * rows and renders above or below them; the lists are the host's or the
 * table's own, and the table never mutates the rows. Grouping and trees
 * refuse it: a nested list is not a flat pin stack.
 */
import {
  commitRowPin,
  createControllableStore,
  EMPTY_ROW_PIN_STATE,
  ROW_PIN_STORE_OPTIONS,
  rowPinActions,
  type RowPinLabels,
  type RowPinSide,
  rowPinSideOf,
  type RowPinState,
} from "@adapttable/core";
import type { RowPinningState } from "@adapttable/core/binding";
import {
  assertInInjectionContext,
  computed,
  inject,
  Injector,
  type Signal,
  untracked,
} from "@angular/core";

import {
  fromStore,
  type MaybeSignal,
  type MaybeSignalOptional,
  readMaybe,
} from "../store";

export type { RowPinLabels, RowPinSide } from "@adapttable/core";
export type { RowPinningState } from "@adapttable/core/binding";

/**
 * Options for {@link injectRowPinning}.
 *
 * @public
 */
export interface RowPinningOptions<TRow> {
  /** Whether pinning runs; every action does nothing while it does not. */
  readonly enabled: MaybeSignal<boolean>;
  /** The pinned rows, when the host holds them. Omit to let the table. */
  readonly pinnedRowIds?: MaybeSignalOptional<RowPinState>;
  /** Told the next lists whenever a row is pinned or unpinned. */
  readonly onPinnedRowIdsChange?: (next: RowPinState) => void;
  /** Row identity. */
  readonly getRowId: (row: TRow) => string;
  /** The pin actions' names. */
  readonly labels: MaybeSignal<RowPinLabels>;
  /** The injector whose lifetime the state follows. */
  readonly injector?: Injector;
}

/**
 * Row pinning as a signal: the lists, which side a row is on, pin and unpin,
 * and the pin entries for the row actions menu.
 *
 * @param options - See {@link RowPinningOptions}.
 * @returns The state, as a signal.
 *
 * @public
 */
export function injectRowPinning<TRow>(
  options: RowPinningOptions<TRow>
): Signal<RowPinningState<TRow>> {
  if (!options.injector) assertInInjectionContext(injectRowPinning);
  const injector = options.injector ?? inject(Injector);
  const store = createControllableStore<RowPinState>(
    EMPTY_ROW_PIN_STATE,
    ROW_PIN_STORE_OPTIONS
  );
  const own = fromStore(store, { injector });
  const controlled = computed(() =>
    options.pinnedRowIds === undefined
      ? undefined
      : readMaybe(options.pinnedRowIds)
  );
  const enabled = computed(() => readMaybe(options.enabled));
  // Every action hands the store the host's current value first, so a
  // controlled pin computes from what the host holds now.
  const commit = (rowId: string, side: RowPinSide | undefined): void => {
    store.control({
      value: untracked(controlled),
      onChange: options.onPinnedRowIdsChange,
    });
    commitRowPin(store, untracked(enabled), rowId, side);
  };
  const pin = (rowId: string, side: RowPinSide): void => {
    commit(rowId, side);
  };
  const unpin = (rowId: string): void => {
    commit(rowId, undefined);
  };
  const state = computed(() => controlled() ?? own());
  const sideOf = computed(
    () =>
      (rowId: string): RowPinSide | undefined =>
        rowPinSideOf(state(), rowId)
  );
  const actions = computed(() => {
    if (!enabled()) return [];
    const labels = readMaybe(options.labels);
    const side = sideOf();
    return rowPinActions<TRow>({
      labels,
      getRowId: options.getRowId,
      sideOf: side,
      pin,
      unpin,
    });
  });
  return computed((): RowPinningState<TRow> => ({
    state: state(),
    sideOf: sideOf(),
    pin,
    unpin,
    actions: actions(),
  }));
}

// packages/react/src/rows/rowPinning.ts
/**
 * Row pinning — the asking, never the data.
 *
 * A pinned row stays put through scroll: it leaves the virtual window and
 * renders in a sticky section above or below it. The host owns the id lists
 * (`pinnedRowIds` / `onPinnedRowIdsChange`); the table never mutates them.
 * Grouping and trees refuse it the same way they refuse reorder — a nested
 * list is not a flat pin stack.
 *
 * Mobile cards are a list, not a grid: the pin actions write the same state,
 * but there is no sticky chrome. The order of the list still puts top pins
 * first and bottom pins last.
 */
import type { RowAction } from "@adapttable/core";
import { useCallback, useMemo, useRef, useState } from "react";

import { useEventCallback } from "../hooks/useEventCallback";

export { partitionPinnedRows, rowPinSignature } from "@adapttable/core";

/**
 * Which edge a pinned row sticks to.
 *
 * @public
 */
export type RowPinSide = "top" | "bottom";

/**
 * Controlled pin lists — ids in dataset order within each edge.
 *
 * @public
 */
export interface RowPinState {
  /** Row ids pinned to the top. */
  readonly top: readonly string[];
  /** Row ids pinned to the bottom. */
  readonly bottom: readonly string[];
}

/**
 * Empty pin lists — omit `pinnedRowIds` and this is what the table holds.
 *
 * @public
 */
export const EMPTY_ROW_PIN_STATE: RowPinState = { top: [], bottom: [] };

/**
 * Synthesized "Pin to top" action.
 *
 * @public
 */
export const PIN_TOP_ACTION_KEY = "adapttable:pin-row-top";
/**
 * Synthesized "Pin to bottom" action.
 *
 * @public
 */
export const PIN_BOTTOM_ACTION_KEY = "adapttable:pin-row-bottom";
/**
 * Synthesized "Unpin" action.
 *
 * @public
 */
export const UNPIN_ROW_ACTION_KEY = "adapttable:unpin-row";

/**
 * Labels the pin actions and the live region need.
 *
 * @public
 */
export interface RowPinLabels {
  /** Pin the row to the top. */
  pinToTop: string;
  /** Pin the row to the bottom. */
  pinToBottom: string;
  /** Return the row to the scroll area. */
  unpinRow: string;
}

/**
 * Headless pin state adapters read.
 *
 * @public
 */
export interface RowPinningState<TRow> {
  /** Current lists. */
  state: RowPinState;
  /** Which edge a row is pinned to, if any. */
  sideOf: (rowId: string) => RowPinSide | undefined;
  /** Pin a row to an edge (moves it if it was on the other). */
  pin: (rowId: string, side: RowPinSide) => void;
  /** Remove a row from both edges. */
  unpin: (rowId: string) => void;
  /** Pin actions, hidden per row so a top-pinned row does not offer Pin to top. */
  actions: readonly RowAction<TRow>[];
}

function withoutId(ids: readonly string[], rowId: string): string[] {
  return ids.filter((id) => id !== rowId);
}

function withId(ids: readonly string[], rowId: string): string[] {
  return ids.includes(rowId) ? [...ids] : [...ids, rowId];
}

/**
 * Apply a pin or unpin to a copy of the state.
 *
 * @public
 */
export function applyRowPin(
  state: RowPinState,
  rowId: string,
  side: RowPinSide | undefined
): RowPinState {
  const top = withoutId(state.top, rowId);
  const bottom = withoutId(state.bottom, rowId);
  if (side === "top") return { top: withId(top, rowId), bottom };
  if (side === "bottom") return { top, bottom: withId(bottom, rowId) };
  return { top, bottom };
}

function sameLists(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  return a.every((id, index) => id === b[index]);
}

function sameState(a: RowPinState, b: RowPinState): boolean {
  return sameLists(a.top, b.top) && sameLists(a.bottom, b.bottom);
}

/**
 * Headless row pinning. Inert until the host passes `enabled`;
 * omit the prop and this hook still runs (Rules of Hooks) but every action no-ops.
 *
 * @public
 */
export function useRowPinning<TRow>(options: {
  enabled: boolean;
  pinnedRowIds?: RowPinState;
  onPinnedRowIdsChange?: (next: RowPinState) => void;
  getRowId: (row: TRow) => string;
  labels: RowPinLabels;
}): RowPinningState<TRow> {
  const { enabled, labels } = options;
  const controlledValue = options.pinnedRowIds;
  const onChange = options.onPinnedRowIdsChange;
  const [internal, setInternal] = useState<RowPinState>(EMPTY_ROW_PIN_STATE);
  const controlled = controlledValue !== undefined;
  const state = controlledValue ?? internal;

  const modeRef = useRef({ controlled, onChange, state, enabled });
  modeRef.current = { controlled, onChange, state, enabled };

  const commit = useCallback((next: RowPinState) => {
    const live = modeRef.current;
    if (!live.enabled) return;
    if (sameState(live.state, next)) return;
    if (live.controlled) {
      live.onChange?.(next);
    } else {
      setInternal(next);
    }
  }, []);

  const pin = useEventCallback((rowId: string, side: RowPinSide) => {
    commit(applyRowPin(modeRef.current.state, rowId, side));
  });
  const unpin = useEventCallback((rowId: string) => {
    commit(applyRowPin(modeRef.current.state, rowId, undefined));
  });

  const sideOf = useCallback(
    (rowId: string): RowPinSide | undefined => {
      if (state.top.includes(rowId)) return "top";
      if (state.bottom.includes(rowId)) return "bottom";
      return undefined;
    },
    [state]
  );

  const getRowId = useEventCallback(options.getRowId);

  const actions = useMemo<readonly RowAction<TRow>[]>(() => {
    if (!enabled) return [];
    return [
      {
        key: PIN_TOP_ACTION_KEY,
        label: labels.pinToTop,
        isHidden: (row) => sideOf(getRowId(row)) === "top",
        onClick: (row) => {
          pin(getRowId(row), "top");
        },
      },
      {
        key: PIN_BOTTOM_ACTION_KEY,
        label: labels.pinToBottom,
        isHidden: (row) => sideOf(getRowId(row)) === "bottom",
        onClick: (row) => {
          pin(getRowId(row), "bottom");
        },
      },
      {
        key: UNPIN_ROW_ACTION_KEY,
        label: labels.unpinRow,
        isHidden: (row) => sideOf(getRowId(row)) === undefined,
        onClick: (row) => {
          unpin(getRowId(row));
        },
      },
    ];
  }, [enabled, getRowId, labels, pin, sideOf, unpin]);

  return useMemo(
    () => ({ state, sideOf, pin, unpin, actions }),
    [actions, pin, sideOf, state, unpin]
  );
}
