// packages/angular/adapter-angular-unstyled/src/components/columnHeaderRename.ts
/**
 * Direct rename of a column from its header: a pencil, then the name field,
 * over the binding's rename editor.
 */
import type { TableLabels } from "@adapttable/angular";
import {
  AdaptAttrs,
  AdaptLiveRegion,
  injectColumnRenameEditor,
} from "@adapttable/angular/adapter";
import { Component, computed, input } from "@angular/core";

/**
 * The header's caption, replaced by the name field while a rename is open.
 *
 * The host's `onRename` is the layout's `setName`, which keeps the name and
 * tells the host.
 */
@Component({
  selector: "adapt-column-header-rename",
  imports: [AdaptAttrs, AdaptLiveRegion],
  template: `
    <button
      type="button"
      data-adapttable-part="header-rename-button"
      [attr.aria-label]="renameLabel()"
      [disabled]="editor.editing()"
      (click)="editor.begin()"
    >
      <span aria-hidden="true">✎</span>
    </button>
    @if (editor.editing()) {
      <form
        data-adapttable-part="header-rename-form"
        style="display: inline-flex; align-items: center; gap: 4px"
        (submit)="save($event)"
      >
        <label
          [attr.for]="editor.inputId"
          data-adapttable-part="header-rename-label"
        >
          {{ labels().columnName }}
        </label>
        <input
          data-adapttable-part="header-rename-input"
          [adaptAttrs]="editor.inputAttrs()"
        />
        @if (editor.error(); as error) {
          <span
            [id]="editor.errorId"
            role="alert"
            data-adapttable-part="header-rename-error"
          >
            {{ error }}
          </span>
        }
        <button type="submit" data-adapttable-part="header-rename-save">
          {{ labels().saveColumnName }}
        </button>
        <button
          type="button"
          data-adapttable-part="header-rename-cancel"
          (click)="editor.cancel()"
        >
          {{ labels().cancelColumnRename }}
        </button>
      </form>
    } @else {
      <ng-content />
    }
    <div
      [adaptLiveRegion]="editor.announcement()"
      data-adapttable-part="header-rename-announcer"
      part="header-rename-announcer"
    ></div>
  `,
})
export class AdaptColumnHeaderRename {
  /** The column's stable key. */
  readonly columnKey = input.required<string>();
  /** The name on screen. */
  readonly name = input.required<string>();
  /** Writes the new name. */
  readonly onRename = input.required<(key: string, name: string) => void>();
  /** The table's labels. */
  readonly labels = input.required<Required<TableLabels>>();

  private readonly column = computed(() => ({
    key: this.columnKey(),
    name: this.name(),
    onRename: this.onRename(),
    requiredMessage: this.labels().columnNameRequired,
    renamedMessage: this.labels().columnRenamed,
  }));

  /** The open editor. */
  protected readonly editor = injectColumnRenameEditor({
    column: this.column,
  });

  /** The pencil's accessible name. */
  protected readonly renameLabel = computed(
    () => `${this.labels().renameColumn}: ${this.name()}`
  );

  /** Save from the form or Enter, and keep the keypress from sorting. */
  protected save(event: Event): void {
    event.preventDefault();
    this.editor.submit();
  }
}

// packages/adapter-unstyled/src/components/ColumnHeaderRename.tsx
import {
  type ColumnHeaderRenameSlotProps,
  LiveRegion,
  useColumnRenameEditor,
} from "@adapttable/core/adapter";

import { useClassNames } from "./classNamesContext";

function focusRenameInput(input: HTMLInputElement | null): void {
  input?.focus();
}

/** Native direct-header column rename controls, loaded by `columnMenu()`. */
export function ColumnHeaderRename({
  columnKey,
  name,
  labels,
  onRenameColumn,
  children,
}: Readonly<ColumnHeaderRenameSlotProps>) {
  const classNames = useClassNames();
  const editor = useColumnRenameEditor({
    key: columnKey,
    name,
    onRename: onRenameColumn,
    requiredMessage: labels.columnNameRequired,
    renamedMessage: labels.columnRenamed,
  });
  return (
    <>
      <button
        type="button"
        aria-label={`${labels.renameColumn}: ${name}`}
        data-adapttable-part="header-rename-button"
        className={classNames.headerRenameButton}
        disabled={editor.editing}
        onClick={editor.begin}
      >
        <span aria-hidden>✎</span>
      </button>
      {editor.editing ? (
        <form
          data-adapttable-part="header-rename-form"
          className={classNames.headerRenameForm}
          style={{ display: "inline-flex", alignItems: "center", gap: 4 }}
          onSubmit={(event) => {
            event.preventDefault();
            editor.submit();
          }}
        >
          <label
            htmlFor={editor.inputId}
            data-adapttable-part="header-rename-label"
            className={classNames.headerRenameLabel}
          >
            {labels.columnName}
          </label>
          <input
            ref={focusRenameInput}
            id={editor.inputId}
            value={editor.draft}
            aria-invalid={editor.error ? true : undefined}
            aria-describedby={editor.error ? editor.errorId : undefined}
            data-adapttable-part="header-rename-input"
            className={classNames.headerRenameInput}
            onChange={(event) => editor.setDraft(event.currentTarget.value)}
            onBlur={editor.blur}
            onKeyDown={(event) => {
              editor.onKeyDown(event);
              if (event.key === "Enter") {
                event.preventDefault();
                editor.submit();
              }
            }}
          />
          {editor.error ? (
            <span
              id={editor.errorId}
              role="alert"
              data-adapttable-part="header-rename-error"
              className={classNames.headerRenameError}
            >
              {editor.error}
            </span>
          ) : null}
          <button
            type="submit"
            data-adapttable-part="header-rename-save"
            className={classNames.headerRenameSave}
          >
            {labels.saveColumnName}
          </button>
          <button
            type="button"
            data-adapttable-part="header-rename-cancel"
            className={classNames.headerRenameCancel}
            onClick={editor.cancel}
          >
            {labels.cancelColumnRename}
          </button>
        </form>
      ) : (
        children
      )}
      <LiveRegion part="header-rename-announcer" statusRole={false}>
        {editor.announcement}
      </LiveRegion>
    </>
  );
}
