// packages/angular/angular/src/grouping/groupMoreButton.ts
/**
 * The offer that reveals the next page of groups, or of a group's rows.
 *
 * Wording and the part name stay here so they cannot drift. Kits pass the
 * button the end user clicks.
 */
import type {
  GroupMoreButtonProps,
  GroupMoreButtonSlotProps,
} from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import { AdaptControl } from "../control";

export type {
  GroupMoreButtonProps,
  GroupMoreButtonSlotProps,
} from "@adapttable/core/binding";

/**
 * Kit-supplied controls for {@link AdaptGroupMoreButtonChrome}.
 *
 * @public
 */
export interface GroupMoreButtonSlots {
  /** Renders a button; receives {@link GroupMoreButtonSlotProps}. */
  readonly Button: Type<unknown>;
}

/**
 * Renders the offer through the kit's button.
 *
 * @public
 */
@Component({
  selector: "adapt-group-more-button-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <ng-container
      [adaptControl]="slots().Button"
      [adaptControlProps]="buttonProps()"
    />
  `,
})
export class AdaptGroupMoreButtonChrome {
  /** Groups or rows. */
  readonly scope = input.required<GroupMoreButtonProps["scope"]>();
  /** How many are still hidden. */
  readonly remaining = input.required<number>();
  /** The group whose rows are revealed, for a `"rows"` offer. */
  readonly groupKey = input<string>();
  /** Resolved labels. */
  readonly labels = input.required<GroupMoreButtonProps["labels"]>();
  /** Reveal the next page. */
  readonly onShowMore = input.required<GroupMoreButtonProps["onShowMore"]>();
  /** The kit's components for each part. */
  readonly slots = input.required<GroupMoreButtonSlots>();

  protected readonly buttonProps = computed((): GroupMoreButtonSlotProps => {
    const scope = this.scope();
    const remaining = this.remaining();
    const labels = this.labels();
    const groupKey = this.groupKey();
    const onShowMore = this.onShowMore();
    return {
      label:
        scope === "groups"
          ? labels.moreGroups(remaining)
          : labels.moreRowsInGroup(remaining),
      onClick: () => {
        onShowMore({ scope, groupKey });
      },
    };
  });
}

// packages/core/src/grouping/GroupMoreButton.tsx
/**
 * The offer that reveals the next page of groups, or of a group's rows.
 *
 * Wording and the part name stay here so they cannot drift. Adapters pass
 * the button the end user clicks.
 */
import type { ReactElement, ReactNode } from "react";

import type { TableLabels } from "../types";

/**
 * Props for an adapter `GroupMoreButton` — no slots on the public API.
 *
 * @public
 */
export interface GroupMoreButtonProps {
  /** Whether this offers more groups or more rows inside one. */
  scope: "groups" | "rows";
  /** How many are still hidden. */
  remaining: number;
  /** The group whose rows are being revealed, for a `"rows"` offer. */
  groupKey?: string;
  /** Labels; falls back to the built-in English. */
  labels: Required<TableLabels>;
  /** Reveal the next page. */
  onShowMore: (entry: { scope: "groups" | "rows"; groupKey?: string }) => void;
}

/**
 * Kit button the group-more chrome calls.
 *
 * @public
 */
export interface GroupMoreButtonSlotProps {
  /** Accessible name for the control. */
  readonly label: string;
  /** Called when pressed. */
  readonly onClick: () => void;
}

/**
 * Adapter-supplied controls for {@link GroupMoreButtonChrome}.
 *
 * @public
 */
export interface GroupMoreButtonSlots {
  readonly Button: (props: GroupMoreButtonSlotProps) => ReactNode;
}

/**
 * Props for {@link GroupMoreButtonChrome}.
 *
 * @public
 */
export interface GroupMoreButtonChromeProps extends GroupMoreButtonProps {
  /** The kit's components for each part. */
  readonly slots: GroupMoreButtonSlots;
}

/**
 * Renders the offer through the adapter's button.
 *
 * @public
 */
export function GroupMoreButtonChrome({
  scope,
  remaining,
  groupKey,
  labels,
  onShowMore,
  slots,
}: Readonly<GroupMoreButtonChromeProps>): ReactElement {
  const Button = slots.Button;
  return (
    <Button
      label={
        scope === "groups"
          ? labels.moreGroups(remaining)
          : labels.moreRowsInGroup(remaining)
      }
      onClick={() => {
        onShowMore({ scope, groupKey });
      }}
    />
  );
}
