// packages/react/src/editing/ApprovalReviewChrome.tsx
/**
 * The body of an approval review — the same one wherever it is drawn.
 *
 * The assistant window, the strip above the table and the modal differ in
 * how they frame a review, never in what it says. This is that shared
 * middle: the headline, the running tally, the first few changes or all of
 * them, the per-row controls when the write can be split, and the two
 * summary controls whose labels follow what they will actually do.
 *
 * Structure and part names live here; every visible control is a kit slot.
 */
import type { TableLabels } from "@adapttable/core";
import { type ReactElement, type ReactNode, useId } from "react";

import type {
  AgentApprovalButtonProps,
  AgentApprovalListProps,
  AgentApprovalProposal,
} from "./AgentApprovalChrome";
import type { ApprovalReview, ApprovalReviewItem } from "./approvalReview";

/** Controls a kit supplies to the shared review body. @public */
export interface ApprovalReviewSlots {
  /** Renders an approve control — the summary one, and one per change. */
  readonly Approve: (props: AgentApprovalButtonProps) => ReactNode;
  /** Renders a reject control — the summary one, and one per change. */
  readonly Reject: (props: AgentApprovalButtonProps) => ReactNode;
  /** Renders the list region. */
  readonly List: (props: AgentApprovalListProps) => ReactNode;
  /**
   * Renders a quiet control that decides nothing — opening the full list,
   * or going back to the conversation. Adapters draw it as a link or a
   * tertiary button, never as a third decision.
   */
  readonly Action: (props: AgentApprovalButtonProps) => ReactNode;
}

/** Props for {@link ApprovalReviewChrome}. @public */
export interface ApprovalReviewChromeProps {
  /** The review to draw. */
  readonly review: ApprovalReview;
  /** Labels; falls back to the built-in English. */
  readonly labels?: TableLabels;
  /** Kit controls. */
  readonly slots: ApprovalReviewSlots;
  /** Show every change rather than the first few. */
  readonly expanded?: boolean;
  /** Asked to show every change. Omit to draw no expansion control. */
  readonly onExpand?: () => void;
  /** Asked to leave the full list. Omit to draw no back control. */
  readonly onBack?: () => void;
  /** Approve what is still undecided. */
  readonly onApprove: () => void;
  /** Reject what is still undecided. */
  readonly onReject: () => void;
  /** Decide one change. Omit when the write cannot be split. */
  readonly onDecide?: (index: number, approved: boolean) => void;
  /**
   * Approve this, and stop asking about this capability for the session.
   *
   * Omit when the write is not one the reader may settle that way. The
   * control is drawn only when this is here, rather than drawn and refusing.
   */
  readonly onAlwaysAllow?: () => void;
  /** Class for the region. */
  readonly className?: string;
  /** Class for each button. */
  readonly buttonClassName?: string;
}

/**
 * Read one change as a line the reader can act on.
 *
 * `Unavailable` and `—` are kept apart deliberately: a value nobody could
 * look up is not an empty cell.
 */
function describeItem(
  proposal: AgentApprovalProposal,
  labels: TableLabels | undefined
): string {
  const describe =
    labels?.proposalChange ??
    (({ row, column, before, after }) => {
      const field = column ? `${row} · ${column}` : row;
      if (before === undefined && after === undefined) return field;
      return `${field}: ${before ?? "—"} → ${after ?? "—"}`;
    });
  return describe({
    row: proposal.rowLabel ?? proposal.rowKey,
    ...(proposal.column === undefined
      ? {}
      : { column: proposal.columnLabel ?? proposal.column }),
    // The column's own wording wins where it has one: the card a reader
    // agrees on should read in the same units as the table behind it.
    before: proposal.beforeUnavailable
      ? (labels?.proposalValueUnavailable ?? "Unavailable")
      : (proposal.beforeText ?? display(proposal.before)),
    after: proposal.afterText ?? display(proposal.after),
  });
}

function display(value: unknown): string | undefined {
  if (value === undefined) return undefined;
  if (value === null) return "—";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(value);
}

/**
 * The shared body of an approval review.
 *
 * @param props - See {@link ApprovalReviewChromeProps}.
 * @returns The review body.
 *
 * @public
 */
export function ApprovalReviewChrome({
  review,
  labels,
  slots,
  expanded = false,
  onExpand,
  onBack,
  onApprove,
  onReject,
  onDecide,
  onAlwaysAllow,
  className,
  buttonClassName,
}: Readonly<ApprovalReviewChromeProps>): ReactElement {
  const headingId = useId();
  const shown = expanded ? review.items : review.preview;
  const Approve = slots.Approve;
  const Reject = slots.Reject;
  const Action = slots.Action;
  // Computed once rather than spread conditionally inside the markup: an
  // optional prop decided in the middle of a conditional branch is a second
  // condition to read.
  const buttonClass: { className?: string } = buttonClassName
    ? { className: buttonClassName }
    : {};

  return (
    <div
      data-adapttable-part="approval-review"
      className={className}
      aria-labelledby={headingId}
      style={{ display: "flex", flexDirection: "column", gap: "0.5em" }}
    >
      <p
        data-adapttable-part="approval-review-summary"
        id={headingId}
        style={{ margin: 0 }}
      >
        {review.summary}
      </p>
      {review.tally ? (
        <p data-adapttable-part="approval-review-tally" style={{ margin: 0 }}>
          {review.tally}
        </p>
      ) : null}

      {review.operation ? (
        <div
          data-adapttable-part="approval-review-operation"
          style={{ display: "flex", flexDirection: "column", gap: "0.25em" }}
        >
          <span data-adapttable-part="approval-review-operation-name">
            {review.operation.title ?? review.operation.capability}
          </span>
          {/* The arguments it was called with, and nothing invented beside
              them — an opaque server operation has no row count to show. */}
          <code data-adapttable-part="approval-review-operation-arguments">
            {JSON.stringify(review.operation.arguments)}
          </code>
        </div>
      ) : null}

      {shown.length > 0 ? (
        <div
          data-adapttable-part="approval-review-scroll"
          style={{ overflowY: "auto", maxHeight: "16em", minHeight: 0 }}
        >
          <slots.List
            part="agent-approval-list"
            label={review.summary}
            className={className}
          >
            {shown.map((item) => (
              <ReviewRow
                key={item.id}
                item={item}
                labels={labels}
                perItem={review.perItem}
                Approve={Approve}
                Reject={Reject}
                buttonClassName={buttonClassName}
                {...(onDecide ? { onDecide } : {})}
              />
            ))}
          </slots.List>
        </div>
      ) : null}

      {!expanded && review.reviewAllLabel && onExpand ? (
        <Action
          label={review.reviewAllLabel}
          part="approval-review-expand"
          {...buttonClass}
          onClick={onExpand}
        />
      ) : null}
      {expanded && onBack ? (
        <Action
          label={labels?.backToConversation ?? "Back to conversation"}
          part="approval-review-back"
          {...buttonClass}
          onClick={onBack}
        />
      ) : null}

      <div
        data-adapttable-part="approval-review-actions"
        style={{ display: "flex", gap: "0.5em", justifyContent: "flex-end" }}
      >
        {/* A standing decision sits apart from the two that answer only this
            write, and it reads as the quieter choice — it is the one a reader
            should take deliberately, not the one the thumb lands on. */}
        {onAlwaysAllow ? (
          <Action
            label={labels?.alwaysAllowProposal ?? "Always allow"}
            part="agent-approval-always-allow"
            {...buttonClass}
            onClick={onAlwaysAllow}
          />
        ) : null}
        <Reject
          label={review.rejectLabel}
          part="agent-approval-reject"
          {...buttonClass}
          onClick={onReject}
        />
        <Approve
          label={review.approveLabel}
          part="agent-approval-approve"
          {...buttonClass}
          onClick={onApprove}
        />
      </div>
    </div>
  );
}

/** One change, with its own decision controls when the write can be split. */
function ReviewRow({
  item,
  labels,
  perItem,
  Approve,
  Reject,
  onDecide,
  buttonClassName,
}: {
  readonly item: ApprovalReviewItem;
  readonly labels: TableLabels | undefined;
  readonly perItem: boolean;
  readonly Approve: (props: AgentApprovalButtonProps) => ReactNode;
  readonly Reject: (props: AgentApprovalButtonProps) => ReactNode;
  readonly onDecide?: (index: number, approved: boolean) => void;
  readonly buttonClassName?: string;
}): ReactElement {
  const text = describeItem(item.proposal, labels);
  const buttonClass: { className?: string } = buttonClassName
    ? { className: buttonClassName }
    : {};
  return (
    // A list item named for the change, so "Approve" is announced with the
    // row it belongs to. Putting the whole sentence on the button instead
    // names it correctly and then prints that sentence on the control — and
    // a real element carries the semantics where role= support is patchy.
    <li
      data-adapttable-part="agent-approval-row"
      data-decision={item.decision}
      aria-label={text}
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "0.5em",
        listStyle: "none",
        // A decision has to be visible on the row it was taken on, or the
        // reader has only a tally to go by.
        opacity: item.decision === "pending" ? 1 : 0.55,
        textDecoration: item.decision === "rejected" ? "line-through" : "none",
      }}
    >
      <span data-adapttable-part="approval-review-change">{text}</span>
      {perItem && onDecide ? (
        <span
          data-adapttable-part="approval-review-row-actions"
          style={{ display: "flex", gap: "0.25em", flex: "0 0 auto" }}
        >
          <Reject
            label={labels?.rejectProposal ?? "Reject"}
            part="approval-review-row-reject"
            {...buttonClass}
            onClick={() => onDecide(item.index, false)}
          />
          <Approve
            label={labels?.approveProposal ?? "Approve"}
            part="approval-review-row-approve"
            {...buttonClass}
            onClick={() => onDecide(item.index, true)}
          />
        </span>
      ) : null}
    </li>
  );
}

// packages/angular/angular/src/editing/approvalReviewChrome.ts
/**
 * The shared approval review body. Core owns the review model; this Chrome
 * owns its structure and every control is supplied by the kit.
 */
import type {
  AgentApprovalProposal,
  ApprovalReview,
  ApprovalReviewItem,
  TableLabels,
} from "@adapttable/core";
import type {
  AgentApprovalButtonProps,
  AgentApprovalListProps as NeutralAgentApprovalListProps,
} from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type TemplateRef,
  type Type,
  viewChild,
} from "@angular/core";

import { AdaptControl } from "../control";

let nextHeadingId = 0;

/** Props for the kit's list, whose children are an Angular template. @public */
export type AgentApprovalListProps = NeutralAgentApprovalListProps<
  TemplateRef<unknown> | undefined
>;

/** Required kit controls, each receiving a single `props` input. @public */
export interface ApprovalReviewSlots {
  /** Approve one change or everything still undecided. */
  readonly Approve: Type<unknown>;
  /** Reject one change or everything still undecided. */
  readonly Reject: Type<unknown>;
  /** A real list that outlets the proposal-row template. */
  readonly List: Type<unknown>;
  /** The quieter expansion, back and optional always-allow control. */
  readonly Action: Type<unknown>;
}

/** The inputs accepted by the shared review body. @public */
export interface ApprovalReviewChromeProps {
  /** The shared, framework-neutral review model. */
  readonly review: ApprovalReview;
  /** Localized copy; omitted labels retain English defaults. */
  readonly labels?: TableLabels;
  /** The kit's own controls. */
  readonly slots: ApprovalReviewSlots;
  /** Show the complete list instead of the preview. */
  readonly expanded?: boolean;
  /** Expand the list; absent means no expansion control. */
  readonly onExpand?: () => void;
  /** Return to the preview; absent means no back control. */
  readonly onBack?: () => void;
  /** Approve everything still undecided. */
  readonly onApprove: () => void;
  /** Reject everything still undecided. */
  readonly onReject: () => void;
  /** Decide one proposal, when the write can be split. */
  readonly onDecide?: (index: number, approved: boolean) => void;
  /** Approve and remember this capability for the current session. */
  readonly onAlwaysAllow?: () => void;
  /** Class on the review and the proposal list. */
  readonly className?: string;
  /** Class on every kit button. */
  readonly buttonClassName?: string;
}

/** A readable value, preserving the difference between absent and empty. */
function display(value: unknown): string | undefined {
  if (value === undefined) return undefined;
  if (value === null) return "—";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(value);
}

/** Prefer the column's own display units and the reader's vocabulary. */
function describeItem(
  proposal: AgentApprovalProposal,
  labels: TableLabels | undefined
): string {
  const describe =
    labels?.proposalChange ??
    (({ row, column, before, after }) => {
      const field = column ? `${row} · ${column}` : row;
      if (before === undefined && after === undefined) return field;
      return `${field}: ${before ?? "—"} → ${after ?? "—"}`;
    });
  return describe({
    row: proposal.rowLabel ?? proposal.rowKey,
    ...(proposal.column === undefined
      ? {}
      : { column: proposal.columnLabel ?? proposal.column }),
    before: proposal.beforeUnavailable
      ? (labels?.proposalValueUnavailable ?? "Unavailable")
      : (proposal.beforeText ?? display(proposal.before)),
    after: proposal.afterText ?? display(proposal.after),
  });
}

/** The arguments a host receives, read as pairs without inventing row data. */
function argumentPairs(
  args: unknown
): readonly { name: string; value: string }[] {
  if (!args || typeof args !== "object" || Array.isArray(args)) {
    const single = display(args);
    return single === undefined ? [] : [{ name: "", value: single }];
  }
  return Object.entries(args as Record<string, unknown>).map(
    ([name, value]) => ({
      name: name
        .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
        .replace(/^./, (first) => first.toUpperCase()),
      value: display(value) ?? "—",
    })
  );
}

/**
 * The same review body in the table strip, assistant and modal. No visible
 * controls are drawn here: even the list is a required kit slot.
 *
 * @public
 */
@Component({
  selector: "adapt-approval-review-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  templateUrl: "./approvalReviewChrome.html",
})
export class AdaptApprovalReviewChrome {
  /** Shared review model. */
  readonly review = input.required<ApprovalReview>();
  /** Kit controls. */
  readonly slots = input.required<ApprovalReviewSlots>();
  /** Localized labels. */
  readonly labels = input<TableLabels>();
  /** Whether to show every proposal. */
  readonly expanded = input<boolean | undefined>(false);
  /** Expand the list. */
  readonly onExpand = input<() => void>();
  /** Return to the preview. */
  readonly onBack = input<() => void>();
  /** Approve all undecided proposals. */
  readonly onApprove = input.required<() => void>();
  /** Reject all undecided proposals. */
  readonly onReject = input.required<() => void>();
  /** Optional per-proposal decision callback. */
  readonly onDecide = input<(index: number, approved: boolean) => void>();
  /** Optional session-wide decision callback. */
  readonly onAlwaysAllow = input<() => void>();
  /** Class for the review and list. */
  readonly className = input<string>();
  /** Class for kit controls. */
  readonly buttonClassName = input<string>();

  /** Unique heading, including when two tables are mounted together. */
  protected readonly headingId = `approval-review-${String(++nextHeadingId)}`;
  private readonly rowsTemplate =
    viewChild<TemplateRef<unknown>>("rowsTemplate");

  protected readonly pairs = computed(() =>
    argumentPairs(this.review().operation?.arguments)
  );

  private readonly shown = computed(() =>
    this.expanded() ? this.review().items : this.review().preview
  );

  protected readonly perItem = computed(
    () =>
      this.review().perItem &&
      this.shown().length > 1 &&
      this.onDecide() !== undefined
  );

  protected readonly rows = computed(
    (): readonly {
      readonly item: ApprovalReviewItem;
      readonly text: string;
      readonly approve: AgentApprovalButtonProps;
      readonly reject: AgentApprovalButtonProps;
    }[] => {
      const labels = this.labels();
      const decide = this.onDecide();
      return this.shown().map((item) => ({
        item,
        text: describeItem(item.proposal, labels),
        approve: this.button(
          labels?.approveProposal ?? "Approve",
          "approval-review-row-approve",
          () => decide?.(item.index, true)
        ),
        reject: this.button(
          labels?.rejectProposal ?? "Reject",
          "approval-review-row-reject",
          () => decide?.(item.index, false)
        ),
      }));
    }
  );

  protected readonly listProps = computed((): AgentApprovalListProps => ({
    part: "agent-approval-list",
    label: this.review().summary,
    children: this.rowsTemplate(),
    ...(this.className() ? { className: this.className()! } : {}),
  }));

  protected readonly approveProps = computed(() =>
    this.button(
      this.review().approveLabel,
      "agent-approval-approve",
      this.onApprove()
    )
  );

  protected readonly rejectProps = computed(() =>
    this.button(
      this.review().rejectLabel,
      "agent-approval-reject",
      this.onReject()
    )
  );

  protected readonly expandProps = computed(() => {
    const label = this.review().reviewAllLabel;
    const expand = this.onExpand();
    return !this.expanded() && label && expand
      ? this.button(label, "approval-review-expand", expand)
      : undefined;
  });

  protected readonly backProps = computed(() => {
    const back = this.onBack();
    return this.expanded() && back
      ? this.button(
          this.labels()?.backToConversation ?? "Back to conversation",
          "approval-review-back",
          back
        )
      : undefined;
  });

  protected readonly alwaysAllowProps = computed(() => {
    const allow = this.onAlwaysAllow();
    return allow
      ? this.button(
          this.labels()?.alwaysAllowProposal ?? "Always allow",
          "agent-approval-always-allow",
          allow
        )
      : undefined;
  });

  private button(
    label: string,
    part: string,
    onClick: () => void
  ): AgentApprovalButtonProps {
    const className = this.buttonClassName();
    return { label, part, onClick, ...(className ? { className } : {}) };
  }
}
