// packages/angular/angular/sparkline/sparkline.ts
/**
 * Inline sparkline charts — `@adapttable/angular/sparkline`.
 *
 * Bar, line and area, drawn as SVG so a cell never downloads a chart
 * library. The entry is a separate package path: a table that does not
 * import this file never pays for it.
 */
import type { ColumnDef } from "@adapttable/angular";
import {
  finiteSparklineValues,
  SPARKLINE_DEFAULT_HEIGHT,
  SPARKLINE_DEFAULT_WIDTH,
  sparklineAreaPath,
  sparklineBars,
  sparklineExportValue,
  type SparklineKind,
  sparklineLinePath,
  sparklineSortValue,
  sparklineSummary,
} from "@adapttable/core";
import { Component, computed, input } from "@angular/core";

export type { ColumnDef };
export {
  finiteSparklineValues,
  sparklineExportValue,
  type SparklineKind,
  sparklineSummary,
} from "@adapttable/core";

/** How a sparkline column draws, kept beside the column object. */
interface SparklineDraw<TRow> {
  readonly kind?: SparklineKind;
  readonly width?: number;
  readonly height?: number;
  readonly color?: string;
  readonly label?: (values: readonly number[], row: TRow) => string;
}

const draws = new WeakMap<object, SparklineDraw<unknown>>();

/**
 * Props for {@link AdaptSparkline} when a host draws the chart itself.
 *
 * @public
 */
export interface SparklineProps {
  /** The series, oldest first. Non-finite values are dropped. */
  values: readonly number[];
  /** Default `"line"`. */
  kind?: SparklineKind;
  /** SVG width in CSS pixels. Default 80. */
  width?: number;
  /** SVG height in CSS pixels. Default 28. */
  height?: number;
  /** Stroke / bar fill. Default `currentColor` so the kit theme wins. */
  color?: string;
  /** Accessible summary. Defaults to {@link sparklineSummary}. */
  label?: string;
}

/**
 * How {@link sparklineColumn} is declared.
 *
 * @public
 */
export interface SparklineColumnSpec<TRow> {
  /** Stable key for the entry. */
  key: string;
  /** Caption for the column. */
  header?: string;
  /** The series on this row. */
  values: (row: TRow) => readonly number[];
  /** Which sparkline to draw. */
  kind?: SparklineKind;
  /** Width in pixels. */
  width?: number;
  /** Height in pixels. */
  height?: number;
  /** Stroke or bar fill. Defaults to `currentColor` so the kit theme wins. */
  color?: string;
  /** Override the default numeric summary. */
  label?: (values: readonly number[], row: TRow) => string;
  /** Extra ColumnDef fields. Accessor, sort, export and the cell win. */
  column?: Partial<ColumnDef<TRow>>;
}

/**
 * A mini chart sized to a cell. Fixed width and height — no observers — so a
 * virtualized row can mount and unmount it without measuring.
 *
 * As a column cell it reads the series from the cell's `value` and the draw
 * options stored for that column. As a standalone chart it reads its inputs.
 *
 * @public
 */
@Component({
  selector: "adapt-sparkline",
  template: `
    <svg
      role="img"
      [attr.aria-label]="summary()"
      [attr.width]="boxWidth()"
      [attr.height]="boxHeight()"
      [attr.viewBox]="'0 0 ' + boxWidth() + ' ' + boxHeight()"
      data-adapttable-part="sparkline"
      [attr.data-kind]="mark()"
      style="display: block; direction: ltr"
    >
      <title>{{ summary() }}</title>
      @switch (mark()) {
        @case ("bar") {
          <g [attr.fill]="ink()">
            @for (bar of bars(); track $index) {
              <rect
                [attr.x]="bar.x"
                [attr.y]="bar.y"
                [attr.width]="bar.width"
                [attr.height]="bar.height"
              />
            }
          </g>
        }
        @case ("area") {
          <path [attr.d]="area()" [attr.fill]="ink()" fill-opacity="0.25" />
          <path
            [attr.d]="line()"
            fill="none"
            [attr.stroke]="ink()"
            stroke-width="1.25"
          />
        }
        @default {
          <path
            [attr.d]="line()"
            fill="none"
            [attr.stroke]="ink()"
            stroke-width="1.25"
          />
        }
      }
    </svg>
  `,
})
export class AdaptSparkline {
  /** The series, when a host draws the chart itself. */
  readonly values = input<readonly number[] | undefined>(undefined);
  /** The cell's accessor value: the series, when this is a column cell. */
  readonly value = input<unknown>(undefined);
  /** The row, when this is a column cell. */
  readonly row = input<unknown>(undefined);
  /** The column, when this is a column cell. */
  readonly column = input<ColumnDef<unknown> | undefined>(undefined);
  /** Which mark to draw. A column's own kind wins. */
  readonly kind = input<SparklineKind>("line");
  /** SVG width. A column's own width wins. */
  readonly width = input(SPARKLINE_DEFAULT_WIDTH);
  /** SVG height. A column's own height wins. */
  readonly height = input(SPARKLINE_DEFAULT_HEIGHT);
  /** Stroke or bar fill. A column's own color wins. */
  readonly color = input("currentColor");
  /** Accessible summary. A column's own label wins, then this. */
  readonly label = input<string | undefined>(undefined);

  private readonly draw = computed(() => draws.get(this.column() ?? {}) ?? {});

  /** The series the host passed, or the cell value when this is a column. */
  private readonly raw = computed((): readonly number[] => {
    const explicit = this.values();
    if (explicit !== undefined) return explicit;
    const value = this.value();
    return Array.isArray(value) ? (value as readonly number[]) : [];
  });

  private readonly series = computed(() => finiteSparklineValues(this.raw()));

  /** The mark actually drawn. */
  protected readonly mark = computed(() => this.draw().kind ?? this.kind());

  /** The box width. */
  protected readonly boxWidth = computed(
    () => this.draw().width ?? this.width()
  );

  /** The box height. */
  protected readonly boxHeight = computed(
    () => this.draw().height ?? this.height()
  );

  /** The stroke or fill. */
  protected readonly ink = computed(() => this.draw().color ?? this.color());

  /** What a screen reader hears. */
  protected readonly summary = computed(() => {
    const values = this.raw();
    const fromColumn = this.draw().label?.(values, this.row());
    return fromColumn ?? this.label() ?? sparklineSummary(values);
  });

  /** Bars for the bar mark. */
  protected readonly bars = computed(() =>
    sparklineBars(this.series(), this.boxWidth(), this.boxHeight())
  );

  /** The line path. */
  protected readonly line = computed(() =>
    sparklineLinePath(this.series(), this.boxWidth(), this.boxHeight())
  );

  /** The area path. */
  protected readonly area = computed(() =>
    sparklineAreaPath(this.series(), this.boxWidth(), this.boxHeight())
  );
}

/**
 * A column whose cell is a sparkline.
 *
 * Sort and export read the numbers, never the SVG.
 *
 * @public
 */
export function sparklineColumn<TRow>(
  spec: SparklineColumnSpec<TRow>
): ColumnDef<TRow> {
  const column: ColumnDef<TRow> = {
    ...spec.column,
    key: spec.key,
    header: spec.header ?? spec.column?.header,
    accessor: (row) => spec.values(row),
    cell: AdaptSparkline,
    sortValue: (row) => sparklineSortValue(spec.values(row)),
    exportValue: (row) => sparklineExportValue(spec.values(row)),
  };
  draws.set(column, {
    kind: spec.kind,
    width: spec.width,
    height: spec.height,
    color: spec.color,
    label: spec.label as SparklineDraw<unknown>["label"],
  });
  return column;
}

// packages/core/src/columns/sparkline.tsx
/**
 * Inline sparkline charts — `@adapttable/core/sparkline`.
 *
 * Bar, line and area, drawn as SVG so a cell never downloads a chart
 * library. The entry is a separate package path: a table that does not
 * import this file never pays for it.
 */
import { createElement, type ReactElement, type ReactNode } from "react";

import type { ColumnDef } from "../types";

/** The three marks this entry draws. */
export type SparklineKind = "bar" | "line" | "area";

/** One bar in the bar mark. */
interface SparklineBar {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Props for {@link Sparkline}.
 *
 * @public
 */
export interface SparklineProps {
  /** The series, oldest first. Non-finite values are dropped. */
  values: readonly number[];
  /** Default `"line"`. */
  kind?: SparklineKind;
  /** SVG width in CSS pixels. Default 80. */
  width?: number;
  /** SVG height in CSS pixels. Default 28. */
  height?: number;
  /** Stroke / bar fill. Default `currentColor` so the kit theme wins. */
  color?: string;
  /** Accessible summary. Defaults to {@link sparklineSummary}. */
  label?: string;
}

/**
 * How {@link sparklineColumn} is declared.
 *
 * @public
 */
export interface SparklineColumnSpec<TRow> {
  /** Stable key for the entry. */
  key: string;
  /** Caption for the column. */
  header?: ReactNode;
  /** The series on this row. */
  values: (row: TRow) => readonly number[];
  /** Which sparkline to draw. */
  kind?: SparklineKind;
  /** Width in pixels. */
  width?: number;
  /** Height in pixels. */
  height?: number;
  /** Stroke or bar fill. Defaults to `currentColor` so the kit theme wins. */
  color?: string;
  /** Override the default numeric summary. */
  label?: (values: readonly number[], row: TRow) => string;
  /** Extra ColumnDef fields. Accessor / sort / export from this helper win. */
  column?: Partial<ColumnDef<TRow>>;
}

const DEFAULT_WIDTH = 80;
const DEFAULT_HEIGHT = 28;
const PAD = 2;
const BAR_GAP = 1;

/**
 * Drop NaN / Infinity so a bad point cannot collapse the scale.
 *
 * @public
 */
export function finiteSparklineValues(values: readonly number[]): number[] {
  return values.filter((value) => Number.isFinite(value));
}

/**
 * Default accessible summary — numbers only, so it is locale-neutral.
 *
 * @public
 */
export function sparklineSummary(values: readonly number[]): string {
  const series = finiteSparklineValues(values);
  if (series.length === 0) return "no values";
  const first = series[0];
  if (series.length === 1) {
    return `1 value, ${first}`;
  }
  let min = first ?? 0;
  let max = first ?? 0;
  for (const value of series) {
    if (value < min) min = value;
    if (value > max) max = value;
  }
  const last = series.at(-1);
  return `${series.length} values, min ${min}, max ${max}, last ${last}`;
}

/**
 * CSV / xlsx fallback — the numbers, not the SVG.
 *
 * @public
 */
export function sparklineExportValue(values: readonly number[]): string {
  return finiteSparklineValues(values).join(", ");
}

function scaleY(
  value: number,
  min: number,
  max: number,
  height: number
): number {
  const inner = height - PAD * 2;
  if (min === max) return PAD + inner / 2;
  return PAD + inner * (1 - (value - min) / (max - min));
}

function extent(series: readonly number[]): { min: number; max: number } {
  const first = series[0] ?? 0;
  let min = first;
  let max = first;
  for (const value of series) {
    if (value < min) min = value;
    if (value > max) max = value;
  }
  return { min, max };
}

function sparklineBars(
  series: readonly number[],
  width: number,
  height: number
): SparklineBar[] {
  if (series.length === 0) return [];
  const { min, max } = extent(series);
  const inner = width - PAD * 2;
  const barWidth = Math.max(
    1,
    (inner - BAR_GAP * (series.length - 1)) / series.length
  );
  const baseline = height - PAD;
  return series.map((value, index) => {
    const x = PAD + index * (barWidth + BAR_GAP);
    const top = scaleY(value, min, max, height);
    return { x, y: top, width: barWidth, height: Math.max(1, baseline - top) };
  });
}

function sparklinePoints(
  series: readonly number[],
  width: number,
  height: number
): { x: number; y: number }[] {
  if (series.length === 0) return [];
  const { min, max } = extent(series);
  const inner = width - PAD * 2;
  if (series.length === 1) {
    return [{ x: width / 2, y: scaleY(series[0] ?? 0, min, max, height) }];
  }
  return series.map((value, index) => ({
    x: PAD + (inner * index) / (series.length - 1),
    y: scaleY(value, min, max, height),
  }));
}

function sparklineLinePath(
  series: readonly number[],
  width: number,
  height: number
): string {
  const points = sparklinePoints(series, width, height);
  if (points.length === 0) return "";
  const first = points[0];
  if (first === undefined) return "";
  if (points.length === 1) {
    return `M${first.x} ${first.y} h0.01`;
  }
  return points
    .map((point, index) =>
      index === 0 ? `M${point.x} ${point.y}` : `L${point.x} ${point.y}`
    )
    .join(" ");
}

function sparklineAreaPath(
  series: readonly number[],
  width: number,
  height: number
): string {
  const line = sparklineLinePath(series, width, height);
  if (line === "") return "";
  const points = sparklinePoints(series, width, height);
  const last = points.at(-1);
  const first = points[0];
  if (last === undefined || first === undefined) return "";
  const baseline = height - PAD;
  return `${line} L${last.x} ${baseline} L${first.x} ${baseline} Z`;
}

/**
 * A mini chart sized to a cell. Fixed width/height — no observers — so a
 * virtualized row can mount and unmount it without measuring.
 *
 * @public
 */
export function Sparkline({
  values,
  kind = "line",
  width = DEFAULT_WIDTH,
  height = DEFAULT_HEIGHT,
  color = "currentColor",
  label,
}: Readonly<SparklineProps>): ReactElement {
  const series = finiteSparklineValues(values);
  const summary = label ?? sparklineSummary(values);
  const bars = sparklineBars(series, width, height);
  const line = sparklineLinePath(series, width, height);
  const area = sparklineAreaPath(series, width, height);
  let mark: ReactElement;
  if (kind === "bar") {
    mark = createElement(
      "g",
      { fill: color },
      bars.map((bar) =>
        createElement("rect", {
          key: `${bar.x}:${bar.y}`,
          x: bar.x,
          y: bar.y,
          width: bar.width,
          height: bar.height,
        })
      )
    );
  } else if (kind === "area") {
    mark = createElement("g", null, [
      createElement("path", {
        key: "fill",
        d: area,
        fill: color,
        fillOpacity: 0.25,
      }),
      createElement("path", {
        key: "line",
        d: line,
        fill: "none",
        stroke: color,
        strokeWidth: 1.25,
      }),
    ]);
  } else {
    mark = createElement("path", {
      d: line,
      fill: "none",
      stroke: color,
      strokeWidth: 1.25,
    });
  }
  return (
    <svg
      role="img"
      aria-label={summary}
      width={width}
      height={height}
      viewBox={`0 0 ${width} ${height}`}
      data-adapttable-part="sparkline"
      data-kind={kind}
      style={{ display: "block", direction: "ltr" }}
    >
      <title>{summary}</title>
      {mark}
    </svg>
  );
}

/**
 * A column whose cell is a sparkline.
 *
 * Sort and export read the numbers, never the SVG.
 *
 * @public
 */
export function sparklineColumn<TRow>(
  spec: SparklineColumnSpec<TRow>
): ColumnDef<TRow> {
  return {
    ...spec.column,
    key: spec.key,
    header: spec.header,
    accessor: (row) => {
      const values = spec.values(row);
      return (
        <Sparkline
          values={values}
          kind={spec.kind}
          width={spec.width}
          height={spec.height}
          color={spec.color}
          label={spec.label?.(values, row)}
        />
      );
    },
    sortValue: (row) => {
      const series = finiteSparklineValues(spec.values(row));
      if (series.length === 0) return undefined;
      return series.at(-1);
    },
    exportValue: (row) => sparklineExportValue(spec.values(row)),
  };
}
