// packages/angular/adapter-ngx-bootstrap/assistant/assistant.ts
/** Native HTML is this kit: buttons, textarea, disclosure and dialog. */
import type { TableAssistantProps } from "@adapttable/angular";
import {
  AdaptAssistantContent,
  AdaptTableAssistantChrome,
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantSheetProps,
  type TableAssistantSlots,
  type TableAssistantWindowProps,
} from "@adapttable/angular/adapter";
import {
  ɵbootstrapModal as bootstrapModal,
  ɵinjectBootstrapOverlayContainer as injectBootstrapOverlayContainer,
} from "@adapttable/ngx-bootstrap";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";
import {
  BsDropdownDirective,
  BsDropdownMenuDirective,
  BsDropdownToggleDirective,
} from "ngx-bootstrap/dropdown";

let nextSheetId = 0;

/** Every assistant action is a native button with an accessible name. @public */
@Component({
  selector: "adapt-assistant-button",
  imports: [AdaptAssistantContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapttable-ngx-bootstrap", style: "display: contents" },
  template: `<button
    class="btn btn-outline-secondary btn-sm"
    type="button"
    [attr.title]="props().tooltip"
    [attr.aria-label]="props().label"
    [attr.aria-expanded]="props().expanded"
    [attr.data-adapttable-part]="props().part"
    [attr.data-variant]="props().variant"
    [class]="props().className"
    [disabled]="props().disabled === true"
    [style]="launcherStyle()"
    (click)="props().onClick()"
  >
    <adapt-assistant-content [content]="props().icon" />
    @if (!props().iconOnly) {
      <adapt-assistant-content [content]="props().children ?? props().label" />
    }
  </button>`,
})
export class AdaptAssistantButton {
  readonly props = input.required<TableAssistantButtonProps>();
  protected readonly launcherStyle = computed(() =>
    this.props().part === "assistant-launcher"
      ? {
          inlineSize: "56px",
          blockSize: "56px",
          borderRadius: "50%",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 0,
        }
      : {}
  );
}

/** Native multiline entry; keyboard events travel unchanged to the binding. @public */
@Component({
  selector: "adapt-assistant-input",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<textarea
    class="form-control form-control-sm"
    rows="2"
    [attr.aria-label]="props().label"
    [placeholder]="props().placeholder"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [value]="props().value"
    [disabled]="props().disabled === true"
    style="width:100%;min-width:0;box-sizing:border-box;font:inherit;resize:vertical"
    (input)="changed($event)"
    (keydown)="props().onKeyDown($event)"
  ></textarea>`,
})
export class AdaptAssistantInput {
  readonly props = input.required<TableAssistantComposerProps>();
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLTextAreaElement).value);
  }
}

/** Native connection badge. @public */
@Component({
  selector: "adapt-assistant-badge",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<span
    class="badge text-bg-secondary"
    [attr.data-adapttable-part]="props().part"
    [attr.data-tone]="props().tone"
    [class]="props().className"
    >{{ props().label }}</span
  >`,
})
export class AdaptAssistantBadge {
  readonly props = input.required<TableAssistantBadgeProps>();
}

/** The in-flow conversation surface. @public */
@Component({
  selector: "adapt-assistant-panel",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<section
    class="card"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </section>`,
})
export class AdaptAssistantPanel {
  readonly props = input.required<TableAssistantPanelProps>();
}

/** ngx-bootstrap modal owns focus containment and backdrop. @public */
@Component({
  selector: "adapt-assistant-sheet",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapttable-ngx-bootstrap", style: "display: contents" },
  template: `<ng-template #content>
    <div
      style="height: 100%; min-height: 0; padding: 16px; box-sizing: border-box"
      [attr.aria-label]="props().label"
      [attr.dir]="props().dir"
      [attr.data-adapttable-part]="props().part"
      [class]="props().className"
    >
      <span class="visually-hidden" [id]="titleId">{{ props().label }}</span>
      <ng-container [ngTemplateOutlet]="props().children" />
    </div>
  </ng-template>`,
})
export class AdaptAssistantSheet {
  readonly props = input.required<TableAssistantSheetProps>();
  protected readonly titleId = `adapt-ngx-bootstrap-assistant-${nextSheetId++}`;
  private readonly content =
    viewChild.required<TemplateRef<unknown>>("content");
  private readonly element = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() {
    bootstrapModal({
      open: () => this.props().open,
      content: () => this.content(),
      container: () => this.element.nativeElement,
      titleId: this.titleId,
      sheet: true,
      onClose: () => this.props().onClose(),
    });
  }
}

/** A nonmodal native dialog leaves the table behind it operable. @public */
@Component({
  selector: "adapt-assistant-window",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<section
    class="card"
    role="dialog"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [style]="props().style"
    style="margin:0;padding:0;border:0"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </section>`,
})
export class AdaptAssistantWindow {
  readonly props = input.required<TableAssistantWindowProps>();
}

/** Native dictation language selection. @public */
@Component({
  selector: "adapt-assistant-language-chip",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapttable-ngx-bootstrap", style: "display: contents" },
  template: `<select
    class="form-select form-select-sm"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [value]="props().value"
    [disabled]="props().disabled === true"
    (change)="changed($event)"
  >
    @for (option of props().options; track option.value) {
      <option [value]="option.value">{{ option.label }}</option>
    }
  </select>`,
})
export class AdaptAssistantLanguageChip {
  readonly props = input.required<TableAssistantLanguageChipProps>();
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLSelectElement).value);
  }
}

/** The platform's disclosure keeps examples local and handles nested Escape. @public */
@Component({
  selector: "adapt-assistant-menu",
  imports: [
    AdaptAssistantContent,
    BsDropdownDirective,
    BsDropdownMenuDirective,

    BsDropdownToggleDirective,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<div
    dropdown
    class="dropdown"
    [isDisabled]="props().disabled === true"
    [isAnimated]="false"
    [container]="overlayContainer()"
    [autoClose]="true"
    [insideClick]="true"
    #dropdown="bs-dropdown"
    data-adapttable-part="assistant-examples"
  >
    <button
      class="btn btn-outline-secondary btn-sm"
      type="button"
      dropdownToggle
      #trigger
      [attr.aria-label]="props().label"
      [title]="props().label"
      [attr.data-adapttable-part]="props().part"
      [class]="props().className"
      [disabled]="props().disabled === true"
    >
      <adapt-assistant-content [content]="props().icon" />
    </button>
    <div
      class="dropdown-menu"
      *dropdownMenu
      data-ngx-bootstrap-part="assistant-examples-list"
      (keydown.escape)="
        $event.preventDefault();
        $event.stopPropagation();
        dropdown.hide();
        trigger.focus()
      "
      [style.max-height]="props().maxHeight"
      style="overflow-y:auto"
    >
      @for (item of props().items; track item.id) {
        <li>
          <button
            class="dropdown-item"
            type="button"
            [attr.data-adapttable-part]="item.part"
            [disabled]="props().disabled === true"
            (click)="select(item.id)"
          >
            <adapt-assistant-content [content]="item.icon" /><span>{{
              item.title
            }}</span>
            @if (item.description) {
              <small>{{ item.description }}</small>
            }
          </button>
        </li>
      }
    </div>
  </div>`,
})
export class AdaptAssistantMenu {
  protected readonly overlayContainer = injectBootstrapOverlayContainer();
  readonly props = input.required<TableAssistantMenuProps>();
  private readonly dropdown = viewChild.required(BsDropdownDirective);
  private readonly trigger =
    viewChild.required<ElementRef<HTMLElement>>("trigger");
  protected select(id: string): void {
    if (this.props().disabled) return;
    this.dropdown().hide();
    this.trigger().nativeElement.focus();
    this.props().onSelect(id);
  }
}

/** Every control in the native assistant, including its optional voice and examples. @public */
export const TABLE_ASSISTANT_SLOTS: TableAssistantSlots = {
  Panel: AdaptAssistantPanel,
  Sheet: AdaptAssistantSheet,
  Window: AdaptAssistantWindow,
  Button: AdaptAssistantButton,
  Composer: AdaptAssistantInput,
  Badge: AdaptAssistantBadge,
  Menu: AdaptAssistantMenu,
  LanguageChip: AdaptAssistantLanguageChip,
};

/** A complete native assistant, directly mountable beside a table. @public */
@Component({
  selector: "adapt-table-assistant",
  imports: [AdaptTableAssistantChrome],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapttable-ngx-bootstrap", style: "display: contents" },
  template: `<adapt-table-assistant-chrome
    [props]="accented()"
    [slots]="slots"
  />`,
})
export class AdaptTableAssistant {
  readonly props = input.required<TableAssistantProps>();
  protected readonly accented = computed((): TableAssistantProps => ({
    accent: "AccentColor",
    ...this.props(),
  }));
  protected readonly slots = TABLE_ASSISTANT_SLOTS;
}

/** Compose the native assistant into TABLE_ASSISTANT. @public */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(AdaptTableAssistant);
}

// packages/adapter-antd/src/assistant.tsx
/**
 * The assistant panel in Ant Design — `@adapttable/antd/assistant`.
 */
import {
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  TableAssistantChrome,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantProps,
  type TableAssistantSheetProps,
  type TableAssistantSuggestionProps,
  type TableAssistantWindowProps,
} from "@adapttable/react/adapter";
import {
  Button,
  Card,
  Drawer,
  Dropdown,
  Input,
  Select,
  Tag,
  Tooltip,
  Typography,
} from "antd";

const TAG_COLOR: Record<string, string | undefined> = {
  neutral: undefined,
  busy: "processing",
  warning: "warning",
  danger: "error",
};

/** How this kit spells the three prominences the chrome asks for. */
const KIT_VARIANT = {
  primary: "primary",
  secondary: "default",
  subtle: "text",
} as const;

function AssistantButton({
  label,
  part,
  className,
  onClick,
  disabled,
  children,
  expanded,
  icon,
  iconOnly,
  tooltip,
  variant = "secondary",
}: Readonly<TableAssistantButtonProps>) {
  if (iconOnly) {
    const control = (
      <Button
        type="text"
        size="small"
        icon={icon}
        aria-label={label}
        aria-expanded={expanded}
        data-adapttable-part={part}
        className={className}
        disabled={disabled}
        onClick={onClick}
      />
    );
    return tooltip ? <Tooltip title={tooltip}>{control}</Tooltip> : control;
  }
  return (
    <Button
      htmlType="button"
      size="small"
      type={KIT_VARIANT[variant]}
      aria-label={label}
      aria-expanded={expanded}
      data-adapttable-part={part}
      className={className}
      disabled={disabled}
      onClick={onClick}
    >
      {children ?? label}
    </Button>
  );
}

function AssistantInput({
  label,
  placeholder,
  part,
  className,
  value,
  disabled,
  onChange,
  onKeyDown,
}: Readonly<TableAssistantComposerProps>) {
  return (
    <Input.TextArea
      autoSize={{ minRows: 1, maxRows: 6 }}
      aria-label={label}
      placeholder={placeholder}
      data-adapttable-part={part}
      className={className}
      value={value}
      disabled={disabled}
      onChange={(event) => {
        onChange(event.target.value);
      }}
      onKeyDown={onKeyDown}
    />
  );
}

function AssistantBadge({
  label,
  part,
  className,
  tone,
}: Readonly<TableAssistantBadgeProps>) {
  return (
    <Tag
      color={TAG_COLOR[tone]}
      data-adapttable-part={part}
      data-tone={tone}
      className={className}
    >
      {label}
    </Tag>
  );
}

function AssistantPanel({
  label,
  part,
  className,
  children,
}: Readonly<TableAssistantPanelProps>) {
  return (
    <Card
      size="small"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      styles={{
        body: {
          height: "100%",
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
        },
      }}
      style={{ height: "100%" }}
    >
      {children}
    </Card>
  );
}

function AssistantSheet({
  label,
  part,
  className,
  open,
  onClose,
  dir,
  children,
}: Readonly<TableAssistantSheetProps>) {
  return (
    <Drawer
      placement="bottom"
      open={open}
      onClose={onClose}
      title={label}
      // antd's Drawer takes no `dir` of its own, and its own direction comes
      // from ConfigProvider — which a host may not have set for this subtree.
      // `rootStyle` reaches the portalled root, which is the element that has
      // to carry it.
      rootStyle={dir ? { direction: dir } : undefined}
      data-adapttable-part={part}
      // antd forwards `data-*` to the content wrapper but `className` to the
      // drawer root, which would put the host's class on a different element
      // from the part it names. `classNames.wrapper` lands them together.
      classNames={{ wrapper: className }}
      styles={{
        wrapper: { height: "90%" },
        body: {
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
          overflow: "hidden",
        },
      }}
    >
      {children}
    </Drawer>
  );
}

function AssistantWindow({
  label,
  part,
  className,
  style,
  children,
}: Readonly<TableAssistantWindowProps>) {
  return (
    <Card
      size="small"
      role="dialog"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{ ...style, boxShadow: "var(--ant-box-shadow-secondary)" }}
      styles={{
        body: {
          height: "100%",
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
        },
      }}
    >
      {children}
    </Card>
  );
}

function AssistantSuggestion({
  title,
  description,
  icon,
  part,
  className,
  onClick,
  disabled,
}: Readonly<TableAssistantSuggestionProps>) {
  return (
    <button
      type="button"
      data-adapttable-part={part}
      className={className}
      disabled={disabled}
      onClick={onClick}
      style={{
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        padding: 8,
        borderRadius: "var(--ant-border-radius)",
        border: "1px solid var(--ant-color-border)",
        background: "var(--ant-color-bg-container)",
        color: "inherit",
        font: "inherit",
        textAlign: "start",
        width: "100%",
        cursor: "pointer",
      }}
    >
      <Typography.Text
        type="secondary"
        style={{ display: "flex", marginTop: 2 }}
      >
        {icon}
      </Typography.Text>
      <span>
        <Typography.Text
          strong
          style={{ display: "block" }}
          data-adapttable-part="assistant-suggestion-title"
        >
          {title}
        </Typography.Text>
        {description ? (
          <Typography.Text
            type="secondary"
            style={{ display: "block", fontSize: 12 }}
            data-adapttable-part="assistant-suggestion-description"
          >
            {description}
          </Typography.Text>
        ) : null}
      </span>
    </button>
  );
}

/**
 * Ask this table a question, in Ant Design.
 *
 * @public
 */
/**
 * The dictation language chooser, in antd.
 *
 * Drawn only beside a mic that is already there, and only when more than one
 * language is offered — the chrome decides both. This is the kit's own
 * chooser, not a button with a list bolted on.
 */
function AssistantLanguageChip({
  label,
  value,
  options,
  part,
  className,
  onChange,
  disabled,
}: Readonly<TableAssistantLanguageChipProps>) {
  return (
    <Select
      size="small"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{ minWidth: "7.5rem" }}
      value={value}
      disabled={disabled}
      options={options.map((option) => ({
        value: option.value,
        label: option.label,
      }))}
      onChange={onChange}
    />
  );
}

/**
 * The examples menu, as Ant Design's own dropdown — its overlay, its
 * placement and the keyboard an antd reader already knows.
 */
function AssistantMenu({
  label,
  part,
  className,
  icon,
  disabled,
  items,
  onSelect,
  maxHeight,
}: Readonly<TableAssistantMenuProps>) {
  return (
    <Dropdown
      placement="topLeft"
      trigger={["click"]}
      menu={{
        items: items.map((item) => ({
          key: item.id,
          icon: item.icon,
          label: (
            <span data-adapttable-part={item.part}>
              <Typography.Text>{item.title}</Typography.Text>
              {item.description ? (
                <Typography.Text type="secondary" style={{ display: "block" }}>
                  {item.description}
                </Typography.Text>
              ) : null}
            </span>
          ),
        })),
        onClick: (event) => {
          onSelect(event.key);
        },
        style: { maxHeight, overflowY: "auto" },
      }}
    >
      <Tooltip title={label}>
        <Button
          type="text"
          size="small"
          aria-label={label}
          data-adapttable-part={part}
          className={className}
          disabled={disabled}
          icon={icon}
        />
      </Tooltip>
    </Dropdown>
  );
}

export function TableAssistant(props: Readonly<TableAssistantProps>) {
  return (
    <TableAssistantChrome
      {...props}
      slots={{
        Panel: AssistantPanel,
        Sheet: AssistantSheet,
        Button: AssistantButton,
        Composer: AssistantInput,
        Badge: AssistantBadge,
        Window: AssistantWindow,
        Suggestion: AssistantSuggestion,
        Menu: AssistantMenu,
        LanguageChip: AssistantLanguageChip,
      }}
    />
  );
}

/**
 * Bind this kit's assistant panel to the assistant slot.
 *
 * @public
 */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(TableAssistant);
}
