// packages/angular/adapter-ng-zorro/assistant/assistant.ts
/** NG-ZORRO surfaces and controls for the shared assistant Chrome. */
import type { TableAssistantProps } from "@adapttable/angular";
import {
  AdaptAssistantContent,
  AdaptTableAssistantChrome,
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantSheetProps,
  type TableAssistantSlots,
  type TableAssistantWindowProps,
} from "@adapttable/angular/adapter";
import { AdaptOverlayOrigin } from "@adapttable/ng-zorro";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  signal,
  viewChild,
  ViewEncapsulation,
} from "@angular/core";
import { FormsModule } from "@angular/forms";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzDrawerModule } from "ng-zorro-antd/drawer";
import { NzDropdownModule } from "ng-zorro-antd/dropdown";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzSelectModule } from "ng-zorro-antd/select";
import { NzTagModule } from "ng-zorro-antd/tag";
import { NzTooltipModule } from "ng-zorro-antd/tooltip";
import { NzTypographyModule } from "ng-zorro-antd/typography";

const NONINTERACTIVE_TOOLTIP = `
.cdk-overlay-pane:has(> .adapt-ng-zorro-assistant-tooltip) {
  pointer-events: none;
}
`;

/** Every assistant action uses the kit's button and optional tooltip. @public */
@Component({
  selector: "adapt-assistant-button",
  encapsulation: ViewEncapsulation.None,
  styles: [NONINTERACTIVE_TOOLTIP],
  imports: [AdaptAssistantContent, NzButtonModule, NzTooltipModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<button
    nz-button
    nz-tooltip
    nzTooltipOverlayClassName="adapt-ng-zorro-assistant-tooltip"
    [nzTooltipOverlayStyle]="{ 'pointer-events': 'none' }"
    [nzTooltipTitle]="props().iconOnly ? (props().tooltip ?? null) : null"
    [nzType]="
      props().iconOnly || props().variant === 'subtle'
        ? 'text'
        : props().variant === 'primary'
          ? 'primary'
          : 'default'
    "
    [nzSize]="props().part === 'assistant-launcher' ? 'large' : 'small'"
    type="button"
    [attr.aria-label]="props().label"
    [attr.aria-expanded]="props().expanded"
    [attr.data-adapttable-part]="props().part"
    [attr.data-variant]="props().variant"
    [class]="props().className"
    [disabled]="props().disabled === true"
    [style]="launcherStyle()"
    (click)="props().onClick()"
  >
    <adapt-assistant-content [content]="props().icon" />
    @if (!props().iconOnly) {
      <adapt-assistant-content [content]="props().children ?? props().label" />
    }
  </button>`,
})
export class AdaptAssistantButton {
  readonly props = input.required<TableAssistantButtonProps>();
  protected readonly launcherStyle = computed(() =>
    this.props().part === "assistant-launcher"
      ? {
          inlineSize: "56px",
          blockSize: "56px",
          borderRadius: "50%",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 0,
        }
      : {}
  );
}

/** Kit textarea; keyboard events travel unchanged to the binding. @public */
@Component({
  selector: "adapt-assistant-input",
  imports: [NzInputModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<textarea
    nz-input
    rows="2"
    [attr.aria-label]="props().label"
    [placeholder]="props().placeholder"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [value]="props().value"
    [disabled]="props().disabled === true"
    style="width:100%;min-width:0;box-sizing:border-box;field-sizing:content;min-block-size:2.5em;max-block-size:10em;resize:vertical"
    (input)="changed($event)"
    (keydown)="props().onKeyDown($event)"
  ></textarea>`,
})
export class AdaptAssistantInput {
  readonly props = input.required<TableAssistantComposerProps>();
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLTextAreaElement).value);
  }
}

/** Kit connection tag. @public */
@Component({
  selector: "adapt-assistant-badge",
  imports: [NzTagModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<nz-tag
    [nzColor]="color()"
    [attr.data-adapttable-part]="props().part"
    [attr.data-tone]="props().tone"
    [class]="props().className"
    >{{ props().label }}</nz-tag
  >`,
})
export class AdaptAssistantBadge {
  readonly props = input.required<TableAssistantBadgeProps>();
  protected readonly color = computed(() => {
    const tone = this.props().tone;
    if (tone === "busy") return "processing";
    if (tone === "warning") return "warning";
    if (tone === "danger") return "error";
    return undefined;
  });
}

/** The in-flow conversation card. @public */
@Component({
  selector: "adapt-assistant-panel",
  imports: [NgTemplateOutlet, NzCardModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<nz-card
    nzSize="small"
    role="region"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [nzBodyStyle]="{
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      minHeight: '0',
    }"
    style="height:100%"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </nz-card>`,
})
export class AdaptAssistantPanel {
  readonly props = input.required<TableAssistantPanelProps>();
}

/** The bottom drawer owns backdrop, focus containment and portal stacking. @public */
@Component({
  selector: "adapt-assistant-sheet",
  imports: [NgTemplateOutlet, NzCardModule, NzDrawerModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<div [dir]="props().dir ?? 'ltr'" style="display:contents">
    <nz-drawer
      nzPlacement="bottom"
      nzHeight="90%"
      [nzZIndex]="10050"
      [nzVisible]="props().open"
      [nzClosable]="false"
      [nzMask]="true"
      [nzKeyboard]="false"
      [nzBodyStyle]="{ padding: '0', overflow: 'hidden' }"
      (nzOnClose)="props().onClose()"
    >
      <ng-container *nzDrawerContent>
        <nz-card
          nzSize="small"
          [nzBordered]="false"
          role="dialog"
          aria-modal="true"
          [dir]="props().dir ?? 'ltr'"
          [attr.aria-label]="props().label"
          [attr.data-adapttable-part]="props().part"
          [class]="props().className"
          [nzBodyStyle]="{
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            minHeight: '0',
          }"
          style="height:100%"
          (keydown)="onKeyDown($event)"
        >
          <ng-container [ngTemplateOutlet]="props().children" />
        </nz-card>
      </ng-container>
    </nz-drawer>
  </div>`,
})
export class AdaptAssistantSheet {
  readonly props = input.required<TableAssistantSheetProps>();
  protected onKeyDown(event: KeyboardEvent): void {
    if (event.key !== "Escape" || event.defaultPrevented) return;
    event.preventDefault();
    event.stopPropagation();
    this.props().onClose();
  }
}

/** A nonmodal floating card leaves the table behind it operable. @public */
@Component({
  selector: "adapt-assistant-window",
  imports: [NgTemplateOutlet, NzCardModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<nz-card
    nzSize="small"
    role="dialog"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [style]="props().style"
    [nzBodyStyle]="{
      height: '100%',
      display: 'flex',
      flexDirection: 'column',
      minHeight: '0',
    }"
    style="margin:0;box-shadow:0 6px 20px #0002"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </nz-card>`,
})
export class AdaptAssistantWindow {
  readonly props = input.required<TableAssistantWindowProps>();
}

/** Kit dictation language selection. @public */
@Component({
  selector: "adapt-assistant-language-chip",
  imports: [AdaptOverlayOrigin, FormsModule, NzSelectModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<nz-select
    adaptOverlayOrigin
    nzSize="small"
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [ngModel]="props().value"
    [ngModelOptions]="{ standalone: true }"
    [nzDisabled]="props().disabled === true"
    style="min-width:7.5rem"
    (ngModelChange)="props().onChange($event)"
  >
    @for (option of props().options; track option.value) {
      <nz-option [nzValue]="option.value" [nzLabel]="option.label" />
    }
  </nz-select>`,
})
export class AdaptAssistantLanguageChip {
  readonly props = input.required<TableAssistantLanguageChipProps>();
}

/** The kit dropdown keeps examples local and consumes its nested Escape. @public */
@Component({
  selector: "adapt-assistant-menu",
  encapsulation: ViewEncapsulation.None,
  styles: [NONINTERACTIVE_TOOLTIP],
  imports: [
    AdaptAssistantContent,
    NzButtonModule,
    NzDropdownModule,
    NzTooltipModule,
    NzTypographyModule,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  templateUrl: "./assistant.html",
})
export class AdaptAssistantMenu {
  readonly props = input.required<TableAssistantMenuProps>();
  protected readonly open = signal(false);
  private readonly trigger = viewChild.required<
    ElementRef<HTMLButtonElement>,
    ElementRef<HTMLButtonElement>
  >("trigger", { read: ElementRef });
  protected select(id: string): void {
    if (this.props().disabled) return;
    this.open.set(false);
    this.trigger().nativeElement.focus();
    this.props().onSelect(id);
  }
  protected onKeyDown(event: KeyboardEvent): void {
    if (event.key === "Escape" && this.open()) {
      event.preventDefault();
      event.stopPropagation();
      this.open.set(false);
      this.trigger().nativeElement.focus();
    }
  }
}

/** Every control in the kit assistant, including optional voice and examples. @public */
export const TABLE_ASSISTANT_SLOTS: TableAssistantSlots = {
  Panel: AdaptAssistantPanel,
  Sheet: AdaptAssistantSheet,
  Window: AdaptAssistantWindow,
  Button: AdaptAssistantButton,
  Composer: AdaptAssistantInput,
  Badge: AdaptAssistantBadge,
  Menu: AdaptAssistantMenu,
  LanguageChip: AdaptAssistantLanguageChip,
};

/** A complete NG-ZORRO assistant, directly mountable beside a table. @public */
@Component({
  selector: "adapt-table-assistant",
  imports: [AdaptTableAssistantChrome, NzCardModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `<div [dir]="props().dir ?? 'ltr'" style="display:contents">
    <adapt-table-assistant-chrome [props]="accented()" [slots]="slots" />
  </div>`,
})
export class AdaptTableAssistant {
  readonly props = input.required<TableAssistantProps>();
  protected readonly accented = computed((): TableAssistantProps => ({
    accent: "var(--ant-primary-color, #1677ff)",
    ...this.props(),
  }));
  protected readonly slots = TABLE_ASSISTANT_SLOTS;
}

/** Compose the kit assistant into TABLE_ASSISTANT. @public */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(AdaptTableAssistant);
}

// packages/adapter-antd/src/assistant.tsx
/**
 * The assistant panel in Ant Design — `@adapttable/antd/assistant`.
 */
import {
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  TableAssistantChrome,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantProps,
  type TableAssistantSheetProps,
  type TableAssistantSuggestionProps,
  type TableAssistantWindowProps,
} from "@adapttable/react/adapter";
import {
  Button,
  Card,
  Drawer,
  Dropdown,
  Input,
  Select,
  Tag,
  Tooltip,
  Typography,
} from "antd";

const TAG_COLOR: Record<string, string | undefined> = {
  neutral: undefined,
  busy: "processing",
  warning: "warning",
  danger: "error",
};

/** How this kit spells the three prominences the chrome asks for. */
const KIT_VARIANT = {
  primary: "primary",
  secondary: "default",
  subtle: "text",
} as const;

function AssistantButton({
  label,
  part,
  className,
  onClick,
  disabled,
  children,
  expanded,
  icon,
  iconOnly,
  tooltip,
  variant = "secondary",
}: Readonly<TableAssistantButtonProps>) {
  if (iconOnly) {
    const control = (
      <Button
        type="text"
        size="small"
        icon={icon}
        aria-label={label}
        aria-expanded={expanded}
        data-adapttable-part={part}
        className={className}
        disabled={disabled}
        onClick={onClick}
      />
    );
    return tooltip ? <Tooltip title={tooltip}>{control}</Tooltip> : control;
  }
  return (
    <Button
      htmlType="button"
      size="small"
      type={KIT_VARIANT[variant]}
      aria-label={label}
      aria-expanded={expanded}
      data-adapttable-part={part}
      className={className}
      disabled={disabled}
      onClick={onClick}
    >
      {children ?? label}
    </Button>
  );
}

function AssistantInput({
  label,
  placeholder,
  part,
  className,
  value,
  disabled,
  onChange,
  onKeyDown,
}: Readonly<TableAssistantComposerProps>) {
  return (
    <Input.TextArea
      autoSize={{ minRows: 1, maxRows: 6 }}
      aria-label={label}
      placeholder={placeholder}
      data-adapttable-part={part}
      className={className}
      value={value}
      disabled={disabled}
      onChange={(event) => {
        onChange(event.target.value);
      }}
      onKeyDown={onKeyDown}
    />
  );
}

function AssistantBadge({
  label,
  part,
  className,
  tone,
}: Readonly<TableAssistantBadgeProps>) {
  return (
    <Tag
      color={TAG_COLOR[tone]}
      data-adapttable-part={part}
      data-tone={tone}
      className={className}
    >
      {label}
    </Tag>
  );
}

function AssistantPanel({
  label,
  part,
  className,
  children,
}: Readonly<TableAssistantPanelProps>) {
  return (
    <Card
      size="small"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      styles={{
        body: {
          height: "100%",
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
        },
      }}
      style={{ height: "100%" }}
    >
      {children}
    </Card>
  );
}

function AssistantSheet({
  label,
  part,
  className,
  open,
  onClose,
  dir,
  children,
}: Readonly<TableAssistantSheetProps>) {
  return (
    <Drawer
      placement="bottom"
      open={open}
      onClose={onClose}
      title={label}
      // antd's Drawer takes no `dir` of its own, and its own direction comes
      // from ConfigProvider — which a host may not have set for this subtree.
      // `rootStyle` reaches the portalled root, which is the element that has
      // to carry it.
      rootStyle={dir ? { direction: dir } : undefined}
      data-adapttable-part={part}
      // antd forwards `data-*` to the content wrapper but `className` to the
      // drawer root, which would put the host's class on a different element
      // from the part it names. `classNames.wrapper` lands them together.
      classNames={{ wrapper: className }}
      styles={{
        wrapper: { height: "90%" },
        body: {
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
          overflow: "hidden",
        },
      }}
    >
      {children}
    </Drawer>
  );
}

function AssistantWindow({
  label,
  part,
  className,
  style,
  children,
}: Readonly<TableAssistantWindowProps>) {
  return (
    <Card
      size="small"
      role="dialog"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{ ...style, boxShadow: "var(--ant-box-shadow-secondary)" }}
      styles={{
        body: {
          height: "100%",
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
        },
      }}
    >
      {children}
    </Card>
  );
}

function AssistantSuggestion({
  title,
  description,
  icon,
  part,
  className,
  onClick,
  disabled,
}: Readonly<TableAssistantSuggestionProps>) {
  return (
    <button
      type="button"
      data-adapttable-part={part}
      className={className}
      disabled={disabled}
      onClick={onClick}
      style={{
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        padding: 8,
        borderRadius: "var(--ant-border-radius)",
        border: "1px solid var(--ant-color-border)",
        background: "var(--ant-color-bg-container)",
        color: "inherit",
        font: "inherit",
        textAlign: "start",
        width: "100%",
        cursor: "pointer",
      }}
    >
      <Typography.Text
        type="secondary"
        style={{ display: "flex", marginTop: 2 }}
      >
        {icon}
      </Typography.Text>
      <span>
        <Typography.Text
          strong
          style={{ display: "block" }}
          data-adapttable-part="assistant-suggestion-title"
        >
          {title}
        </Typography.Text>
        {description ? (
          <Typography.Text
            type="secondary"
            style={{ display: "block", fontSize: 12 }}
            data-adapttable-part="assistant-suggestion-description"
          >
            {description}
          </Typography.Text>
        ) : null}
      </span>
    </button>
  );
}

/**
 * Ask this table a question, in Ant Design.
 *
 * @public
 */
/**
 * The dictation language chooser, in antd.
 *
 * Drawn only beside a mic that is already there, and only when more than one
 * language is offered — the chrome decides both. This is the kit's own
 * chooser, not a button with a list bolted on.
 */
function AssistantLanguageChip({
  label,
  value,
  options,
  part,
  className,
  onChange,
  disabled,
}: Readonly<TableAssistantLanguageChipProps>) {
  return (
    <Select
      size="small"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{ minWidth: "7.5rem" }}
      value={value}
      disabled={disabled}
      options={options.map((option) => ({
        value: option.value,
        label: option.label,
      }))}
      onChange={onChange}
    />
  );
}

/**
 * The examples menu, as Ant Design's own dropdown — its overlay, its
 * placement and the keyboard an antd reader already knows.
 */
function AssistantMenu({
  label,
  part,
  className,
  icon,
  disabled,
  items,
  onSelect,
}: Readonly<TableAssistantMenuProps>) {
  return (
    <Dropdown
      placement="topLeft"
      trigger={["click"]}
      menu={{
        items: items.map((item) => ({
          key: item.id,
          icon: item.icon,
          label: (
            <span data-adapttable-part={item.part}>
              <Typography.Text>{item.title}</Typography.Text>
              {item.description ? (
                <Typography.Text type="secondary" style={{ display: "block" }}>
                  {item.description}
                </Typography.Text>
              ) : null}
            </span>
          ),
        })),
        onClick: (event) => {
          onSelect(event.key);
        },
      }}
    >
      <Tooltip title={label}>
        <Button
          type="text"
          size="small"
          aria-label={label}
          data-adapttable-part={part}
          className={className}
          disabled={disabled}
          icon={icon}
        />
      </Tooltip>
    </Dropdown>
  );
}

export function TableAssistant(props: Readonly<TableAssistantProps>) {
  return (
    <TableAssistantChrome
      {...props}
      slots={{
        Panel: AssistantPanel,
        Sheet: AssistantSheet,
        Button: AssistantButton,
        Composer: AssistantInput,
        Badge: AssistantBadge,
        Window: AssistantWindow,
        Suggestion: AssistantSuggestion,
        Menu: AssistantMenu,
        LanguageChip: AssistantLanguageChip,
      }}
    />
  );
}

/**
 * Bind this kit's assistant panel to the assistant slot.
 *
 * @public
 */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(TableAssistant);
}
