// packages/angular/angular/src/editing/multiSelectEditorChrome.ts
/**
 * Multi-select editor structure for kits whose select holds one value.
 * The kit supplies every checkbox; the binding owns the group and focus.
 */
import {
  editorValidationProps,
  formatMultiDraft,
  readMultiDraft,
} from "@adapttable/core";
import type { MultiSelectEditorCheckboxProps as NeutralMultiSelectEditorCheckboxProps } from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import { AdaptControl } from "../control";
import type { EditableCellEditorCtrl } from "./editableCellShared";

/**
 * Props passed to each kit checkbox through its `props` input.
 *
 * @public
 */
export type MultiSelectEditorCheckboxProps =
  NeutralMultiSelectEditorCheckboxProps<unknown, KeyboardEvent>;

/**
 * Required kit controls for {@link AdaptMultiSelectEditorChrome}.
 *
 * @public
 */
export interface MultiSelectEditorSlots {
  /** The kit's checkbox, accepting {@link MultiSelectEditorCheckboxProps}. */
  readonly Checkbox: Type<unknown>;
}

/**
 * A named group of kit checkboxes standing in for a multi-value select.
 * Native-capable kits can keep their native multi-select editor.
 *
 * @public
 */
@Component({
  selector: "adapt-multi-select-editor-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let v = validation();
    <div
      #group
      role="group"
      [attr.aria-label]="label()"
      data-adapttable-part="edit-cell-editor"
      [attr.aria-invalid]="v['aria-invalid'] ?? null"
      [attr.aria-describedby]="v['aria-describedby'] ?? null"
      [attr.aria-busy]="v['aria-busy'] ?? null"
      [attr.data-conflict]="v['data-conflict'] ?? null"
      style="display: flex; flex-wrap: wrap; align-items: center; gap: 8px; min-width: 0"
      (focusout)="onBlur($event, group)"
    >
      @for (option of options(); track option.value) {
        <ng-container
          [adaptControl]="slots().Checkbox"
          [adaptControlProps]="option"
        />
      }
    </div>
  `,
})
export class AdaptMultiSelectEditorChrome {
  /** The active cell's editor controller. */
  readonly ctrl = input.required<EditableCellEditorCtrl>();
  /** Localized accessible name for the group. */
  readonly label = input.required<string>();
  /** Kit key handling, already wired to the editor controller. */
  readonly onKeyDown = input.required<(event: KeyboardEvent) => void>();
  /** The kit's checkbox component. */
  readonly slots = input.required<MultiSelectEditorSlots>();

  protected readonly validation = computed(() =>
    editorValidationProps(this.ctrl())
  );

  protected readonly options = computed(
    (): readonly MultiSelectEditorCheckboxProps[] => {
      const ctrl = this.ctrl();
      const selected = readMultiDraft(ctrl.draft);
      return ctrl.selectOptions.map((option, index) => ({
        label: option.label,
        value: option.value,
        checked: selected.includes(option.value),
        onToggle: () => {
          const next = selected.includes(option.value)
            ? selected.filter((value) => value !== option.value)
            : [...selected, option.value];
          ctrl.setDraft(
            formatMultiDraft(
              ctrl.selectOptions
                .map((item) => item.value)
                .filter((value) => next.includes(value))
            )
          );
        },
        onKeyDown: this.onKeyDown(),
        focusRef: index === 0 ? ctrl.focusRef : undefined,
      }));
    }
  );

  protected onBlur(event: FocusEvent, group: HTMLElement): void {
    if (
      event.relatedTarget instanceof Node &&
      group.contains(event.relatedTarget)
    ) {
      return;
    }
    this.ctrl().commitOnBlur();
  }
}

// packages/core/src/editing/MultiSelectEditorChrome.tsx
/**
 * Multi-select cell editor, for kits whose select holds one value.
 *
 * A native `<select multiple>` is the compact answer, and the kits that wrap
 * one — MUI, Ant Design, Mantine, Chakra — use theirs. Radix Themes and Base UI
 * build their select out of a button and a popup, which by construction picks a
 * single item, so those kits express "several of these" as a list of their own
 * checkboxes instead.
 *
 * That list is structure — the group, its accessible name, which option takes
 * focus, when a blur means "done" — so it lives here, and each kit supplies the
 * checkbox. Three adapters rendering three copies of the same `<div role=
 * "group">` is the defect this exists to avoid.
 */
import type { KeyboardEvent, ReactNode } from "react";

import { formatMultiDraft, readMultiDraft } from "./cellEditing";
import {
  type EditableCellEditorCtrl,
  editorValidationProps,
} from "./EditableCellGate";

/**
 * One option's checkbox, rendered by the adapter with its kit's control.
 *
 * @public
 */
export interface MultiSelectEditorCheckboxProps {
  /** The option's visible text. */
  readonly label: ReactNode;
  /** The option's value — unique within the editor. */
  readonly value: string;
  /** Whether the draft currently holds this value. */
  readonly checked: boolean;
  /** Add or remove this value from the draft. */
  readonly onToggle: () => void;
  /**
   * Present on the FIRST option only. Attach it to the kit's control so the
   * editor takes focus when the cell opens, exactly as a single-control editor
   * does through {@link EditableCellEditorCtrl.focusRef}.
   */
  readonly focusRef?: (node: { focus: () => void } | null) => void;
  /**
   * The editor's key handling — Enter commits, Escape cancels. It belongs on
   * the controls themselves rather than the group: a group is not an
   * interactive element, and keys arrive at whichever option has focus.
   */
  readonly onKeyDown: (event: KeyboardEvent) => void;
}

/**
 * Adapter-supplied controls for {@link MultiSelectEditorChrome}.
 *
 * @public
 */
export interface MultiSelectEditorSlots {
  readonly Checkbox: (props: MultiSelectEditorCheckboxProps) => ReactNode;
}

/**
 * Props for {@link MultiSelectEditorChrome}.
 *
 * @public
 */
export interface MultiSelectEditorChromeProps {
  /** The active cell's editor controller. */
  readonly ctrl: EditableCellEditorCtrl;
  /** Accessible name for the group — the table's edit label. */
  readonly label: string;
  /** The adapter's key handling, already wired to `ctrl.onEditorKeyDown`. */
  readonly onKeyDown: (event: KeyboardEvent) => void;
  readonly slots: MultiSelectEditorSlots;
}

/**
 * A group of kit checkboxes standing in for `<select multiple>`.
 *
 * @param props - See {@link MultiSelectEditorChromeProps}.
 * @returns The editor, named and focusable as one control.
 *
 * @public
 */
export function MultiSelectEditorChrome({
  ctrl,
  label,
  onKeyDown,
  slots,
}: Readonly<MultiSelectEditorChromeProps>): ReactNode {
  const selected = readMultiDraft(ctrl.draft);
  const Checkbox = slots.Checkbox;

  const toggle = (value: string) => {
    const next = selected.includes(value)
      ? selected.filter((item) => item !== value)
      : [...selected, value];
    // Written in the editor's own option order, so a round-trip through the
    // draft never reshuffles what the reader ticked.
    ctrl.setDraft(
      formatMultiDraft(
        ctrl.selectOptions
          .map((option) => option.value)
          .filter((option) => next.includes(option))
      )
    );
  };

  return (
    <div
      role="group"
      aria-label={label}
      data-adapttable-part="edit-cell-editor"
      {...editorValidationProps(ctrl)}
      style={{
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        gap: 8,
        minWidth: 0,
      }}
      onBlur={(event) => {
        // Moving between this group's own checkboxes is not leaving the
        // editor — committing there would close the cell on the first Tab.
        if (event.currentTarget.contains(event.relatedTarget)) return;
        ctrl.commitOnBlur();
      }}
    >
      {ctrl.selectOptions.map((option, index) => (
        <Checkbox
          key={option.value}
          label={option.label}
          value={option.value}
          checked={selected.includes(option.value)}
          onToggle={() => toggle(option.value)}
          onKeyDown={onKeyDown}
          focusRef={index === 0 ? ctrl.focusRef : undefined}
        />
      ))}
    </div>
  );
}
