// packages/adapter-unstyled/src/components/ColumnMenu.tsx
import {
  ACTIONS_COLUMN_KEY,
  columnMenuRows,
  columnReorderKeyProps,
  REORDER_COLUMN_KEY,
  useColumnDragState,
  type UseColumnLayoutResult,
} from "@adapttable/core";
import {
  type ColumnDragState,
  columnMenuActions,
  type ColumnMenuChoice,
  type ColumnMenuItem,
  type ColumnMenuLabels,
  type ColumnMenuRow,
  type ColumnMenuSlotProps,
  type ColumnRenameEditorState,
  EyeIcon,
  filterColumnMenuRows,
  GripIcon,
  hideAllColumns,
  LiveRegion,
  nextPinSide,
  pinActionLabel,
  PinIcon,
  showAllColumns,
  unpinAllColumns,
  useColumnRenameEditor,
  useFeatureHost,
} from "@adapttable/core/adapter";
import { useState } from "react";
import { createPortal } from "react-dom";

import { cx } from "../cx";
import type { DataTableClassNames } from "../types";
import { MENU_PANEL_STYLE, useMenuPopover } from "./menuPopover";

const NOOP_RENAME = () => undefined;

function isColumnMenuChoice(item: ColumnMenuItem): item is ColumnMenuChoice {
  return "kind" in item && item.kind === "choice";
}

function focusRenameInput(input: HTMLInputElement | null): void {
  input?.focus();
}

function ColumnRenameEditor({
  editor,
  labels,
  classNames,
}: Readonly<{
  editor: ColumnRenameEditorState;
  labels: ColumnMenuLabels;
  classNames: DataTableClassNames;
}>) {
  if (!editor.editing) return null;
  return (
    <form
      data-adapttable-part="column-rename-form"
      className={classNames.columnRenameForm}
      onSubmit={(event) => {
        event.preventDefault();
        editor.submit();
      }}
    >
      <label
        htmlFor={editor.inputId}
        data-adapttable-part="column-rename-label"
        className={classNames.columnRenameLabel}
      >
        {labels.columnName}
      </label>
      <input
        ref={focusRenameInput}
        id={editor.inputId}
        value={editor.draft}
        aria-invalid={editor.error ? true : undefined}
        aria-describedby={editor.error ? editor.errorId : undefined}
        data-adapttable-part="column-rename-input"
        className={classNames.columnRenameInput}
        onChange={(event) => editor.setDraft(event.currentTarget.value)}
        onBlur={editor.blur}
        onKeyDown={editor.onKeyDown}
      />
      {editor.error ? (
        <span
          id={editor.errorId}
          role="alert"
          data-adapttable-part="column-rename-error"
          className={classNames.columnRenameError}
        >
          {editor.error}
        </span>
      ) : null}
      <button
        type="submit"
        data-adapttable-part="column-rename-save"
        className={classNames.columnRenameSave}
      >
        {labels.saveColumnName}
      </button>
      <button
        type="button"
        data-adapttable-part="column-rename-cancel"
        className={classNames.columnRenameCancel}
        onClick={editor.cancel}
      >
        {labels.cancelColumnRename}
      </button>
    </form>
  );
}

/** Menu labels: the shared chrome contract plus the actions row's name. */
type ColumnMenuRowLabels = ColumnMenuLabels & {
  actions: string;
  reorderRow: string;
};

/** The eye toggle shared by data-column rows and the actions row. */
function VisibilityToggle({
  hidden,
  name,
  labels,
  classNames,
  onToggle,
  disabled = false,
}: Readonly<{
  hidden: boolean;
  name: string;
  labels: Pick<ColumnMenuLabels, "showColumn" | "hideColumn">;
  classNames: DataTableClassNames;
  onToggle: () => void;
  disabled?: boolean;
}>) {
  return (
    <button
      type="button"
      data-adapttable-part="column-menu-visibility"
      data-active={!hidden || undefined}
      aria-pressed={!hidden}
      aria-label={`${hidden ? labels.showColumn : labels.hideColumn}: ${name}`}
      className={classNames.columnMenuVisibility}
      disabled={disabled}
      onClick={onToggle}
    >
      <EyeIcon off={hidden} />
    </button>
  );
}

/** The row's name caption, shared by data-column rows and the actions row. */
function RowName({
  hidden,
  name,
  classNames,
}: Readonly<{
  hidden: boolean;
  name: string;
  classNames: DataTableClassNames;
}>) {
  return (
    <span
      data-adapttable-part="column-menu-label"
      data-hidden={hidden || undefined}
      className={classNames.columnMenuLabel}
    >
      {name}
    </span>
  );
}

/** The pin toggle shared by data-column rows and the actions row. */
function PinToggle({
  active,
  actionLabel,
  classNames,
  onClick,
  disabled = false,
}: Readonly<{
  active: boolean;
  /** What clicking will DO next (e.g. "Pin right: Actions"). */
  actionLabel: string;
  classNames: DataTableClassNames;
  onClick: () => void;
  disabled?: boolean;
}>) {
  return (
    <button
      type="button"
      data-adapttable-part="column-menu-pin"
      data-active={active || undefined}
      aria-pressed={active}
      aria-label={actionLabel}
      className={classNames.columnMenuPin}
      disabled={disabled}
      onClick={onClick}
    >
      <PinIcon />
    </button>
  );
}

interface ColumnMenuRowProps<TRow> {
  row: ColumnMenuRow<TRow>;
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuLabels;
  classNames: DataTableClassNames;
  drag: ColumnDragState;
  sortBy?: string;
  sortDir?: "asc" | "desc";
  onSortColumn?: (key: string, dir: "asc" | "desc") => void;
  onAutoSizeColumn?: (key: string) => void;
  onFilterColumn?: (key: string) => void;
  onRenameColumn?: (key: string, name: string) => void;
  groupingPanel?: NonNullable<ColumnMenuSlotProps<TRow>["groupingPanel"]>;
}

function ColumnMenuRowItem<TRow>({
  row,
  layout,
  labels,
  classNames,
  drag,
  sortBy,
  sortDir,
  onSortColumn,
  onAutoSizeColumn,
  onFilterColumn,
  onRenameColumn,
  groupingPanel,
}: Readonly<ColumnMenuRowProps<TRow>>) {
  const { key, name, hidden, pinned, index, canMove, canHide, canPin } = row;
  const [open, setOpen] = useState(false);
  const featureHost = useFeatureHost<TRow>();
  const rename = useColumnRenameEditor({
    key,
    name,
    onRename: onRenameColumn ?? NOOP_RENAME,
    requiredMessage: labels.columnNameRequired,
    renamedMessage: labels.columnRenamed,
  });
  const actions = columnMenuActions(row, {
    featureHost,
    labels,
    layout,
    sortBy,
    sortDir,
    onSortColumn,
    onAutoSizeColumn,
    onFilterColumn,
    onBeginRename: onRenameColumn ? rename.begin : undefined,
    groupingPanel,
  });
  return (
    <div
      data-adapttable-part="column-menu-item"
      data-hidden={hidden || undefined}
      data-pinned={pinned}
      className={classNames.columnMenuItem}
      style={{ cursor: canMove ? "grab" : "default" }}
      {...(canMove
        ? {
            ...drag.rowDragProps(key, index),
            ...drag.dropProps(index, layout.move),
            ...drag.rowAttrs(key, index),
          }
        : {})}
    >
      <span
        data-adapttable-part="column-menu-grip"
        className={classNames.columnMenuGrip}
        aria-disabled={!canMove || undefined}
        {...(canMove
          ? columnReorderKeyProps(
              key,
              index,
              layout.move,
              `${labels.moveStart} / ${labels.moveEnd}: ${name}`
            )
          : {})}
      >
        <GripIcon />
      </span>
      <VisibilityToggle
        hidden={hidden}
        name={name}
        labels={labels}
        classNames={classNames}
        disabled={!canHide}
        onToggle={() => layout.toggleVisible(key)}
      />
      <RowName hidden={hidden} name={name} classNames={classNames} />
      <PinToggle
        active={pinned !== undefined}
        actionLabel={`${pinActionLabel(pinned, labels)}: ${name}`}
        classNames={classNames}
        disabled={!canPin}
        onClick={() => layout.setPinned(key, nextPinSide(pinned))}
      />
      <button
        type="button"
        data-adapttable-part="column-menu-more"
        aria-expanded={open}
        aria-label={`${labels.columnActions}: ${name}`}
        className={classNames.columnMenuMore}
        onClick={() => setOpen((value) => !value)}
      >
        ⋯
      </button>
      {open ? (
        <div
          data-adapttable-part="column-menu-submenu"
          className={classNames.columnMenuSubmenu}
        >
          {actions.map((action) => {
            if (isColumnMenuChoice(action)) {
              return (
                <label
                  key={action.id}
                  data-adapttable-part="column-menu-choice"
                  className={classNames.columnMenuChoice}
                >
                  <span
                    data-adapttable-part="column-menu-choice-label"
                    className={classNames.columnMenuChoiceLabel}
                  >
                    {action.label}
                  </span>
                  <select
                    aria-label={action.label}
                    value={action.value}
                    disabled={action.disabled}
                    data-adapttable-part="column-menu-choice-select"
                    className={classNames.columnMenuChoiceSelect}
                    onChange={(event) =>
                      action.onChange(event.currentTarget.value)
                    }
                  >
                    {action.options.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </label>
              );
            }
            return (
              <button
                key={action.id}
                type="button"
                data-adapttable-part="column-menu-action"
                className={classNames.columnMenuAction}
                disabled={
                  action.disabled || (action.id === "rename" && rename.editing)
                }
                onClick={() => {
                  action.run();
                  if (action.id !== "rename") setOpen(false);
                }}
              >
                {action.label}
              </button>
            );
          })}
          <ColumnRenameEditor
            editor={rename}
            labels={labels}
            classNames={classNames}
          />
        </div>
      ) : null}
      <LiveRegion part="column-rename-announcer" statusRole={false}>
        {rename.announcement}
      </LiveRegion>
    </div>
  );
}

interface ActionsMenuRowProps<TRow> {
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuRowLabels;
  classNames: DataTableClassNames;
}

/**
 * The injected row-actions column as a first-class menu row: the same eye
 * toggle as a data column plus a ONE-CLICK end-pin toggle (right ↔ unpinned).
 * The column always trails, so there is no left pin and no reorder grip.
 */
function ActionsMenuRowItem<TRow>({
  layout,
  labels,
  classNames,
}: Readonly<ActionsMenuRowProps<TRow>>) {
  const hidden = layout.isHidden(ACTIONS_COLUMN_KEY);
  const pinned = layout.state.pinned[ACTIONS_COLUMN_KEY] !== undefined;
  const name = labels.actions;
  return (
    <div
      data-adapttable-part="column-menu-item"
      data-actions=""
      data-hidden={hidden || undefined}
      data-pinned={pinned ? "end" : undefined}
      className={classNames.columnMenuItem}
    >
      <VisibilityToggle
        hidden={hidden}
        name={name}
        labels={labels}
        classNames={classNames}
        onToggle={() => layout.toggleVisible(ACTIONS_COLUMN_KEY)}
      />
      <RowName hidden={hidden} name={name} classNames={classNames} />
      <PinToggle
        active={pinned}
        actionLabel={`${pinned ? labels.unpin : labels.pinEnd}: ${name}`}
        classNames={classNames}
        onClick={() =>
          layout.setPinned(ACTIONS_COLUMN_KEY, pinned ? undefined : "end")
        }
      />
    </div>
  );
}

/**
 * The injected row-reorder column as a first-class menu row: the same eye
 * toggle as a data column plus a one-click start-pin toggle. The column
 * always leads, so there is no end pin and no reorder grip.
 */
function ReorderMenuRowItem<TRow>({
  layout,
  labels,
  classNames,
}: Readonly<ActionsMenuRowProps<TRow>>) {
  const hidden = layout.isHidden(REORDER_COLUMN_KEY);
  const pinned = layout.state.pinned[REORDER_COLUMN_KEY] !== undefined;
  const name = labels.reorderRow;
  return (
    <div
      data-adapttable-part="column-menu-item"
      data-reorder=""
      data-hidden={hidden || undefined}
      data-pinned={pinned ? "start" : undefined}
      className={classNames.columnMenuItem}
    >
      <VisibilityToggle
        hidden={hidden}
        name={name}
        labels={labels}
        classNames={classNames}
        onToggle={() => layout.toggleVisible(REORDER_COLUMN_KEY)}
      />
      <RowName hidden={hidden} name={name} classNames={classNames} />
      <PinToggle
        active={pinned}
        actionLabel={`${pinned ? labels.unpin : labels.pinStart}: ${name}`}
        classNames={classNames}
        onClick={() =>
          layout.setPinned(REORDER_COLUMN_KEY, pinned ? undefined : "start")
        }
      />
    </div>
  );
}

/** The shared Columns-menu contract, plus this kit's class map. */
export interface ColumnMenuProps<TRow> extends ColumnMenuSlotProps<TRow> {
  /** Class map for the menu's parts. */
  classNames: DataTableClassNames;
}

/**
 * Column-management popover: a disclosure button + a panel where each column
 * has a drag grip (reorder), an eye toggle (show/hide), and a pin toggle.
 * Closes on outside-click or Escape. Ships no styles — target the
 * `data-adapttable-part` hooks or the `columnMenu*` className slots.
 */
export function ColumnMenu<TRow>({
  allColumns,
  layout,
  labels,
  classNames,
  hasRowActions,
  hasRowReorder,
  onAutoSize,
  onAutoSizeColumn,
  onSortColumn,
  onFilterColumn,
  onRenameColumn,
  groupingPanel,
  sortBy,
  sortDir,
  dir,
}: Readonly<ColumnMenuProps<TRow>>) {
  const drag = useColumnDragState();
  const { open, setOpen, rootRef, triggerRef, panelRef } = useMenuPopover();
  const [query, setQuery] = useState("");
  const rows = filterColumnMenuRows(columnMenuRows(allColumns, layout), query);

  return (
    <div
      ref={rootRef}
      data-adapttable-part="column-menu"
      className={classNames.columnMenu}
      style={{ position: "relative" }}
    >
      <button
        ref={triggerRef}
        type="button"
        aria-expanded={open}
        aria-haspopup="true"
        data-adapttable-part="column-menu-button"
        data-active={open || undefined}
        className={classNames.columnMenuButton}
        style={{ flexShrink: 0, whiteSpace: "nowrap" }}
        onClick={() => setOpen((v) => !v)}
      >
        {labels.columns}
      </button>
      {open &&
        createPortal(
          <fieldset
            ref={panelRef}
            aria-label={labels.columns}
            dir={dir}
            data-adapttable-part="column-menu-panel"
            className={classNames.columnMenuPanel}
            style={MENU_PANEL_STYLE}
          >
            <div
              data-adapttable-part="column-menu-header"
              className={classNames.columnMenuHeader}
            >
              <span
                data-adapttable-part="column-menu-title"
                className={classNames.columnMenuTitle}
              >
                {labels.columns}
              </span>
            </div>
            <input
              type="search"
              data-adapttable-part="column-menu-search"
              className={classNames.columnMenuSearch}
              placeholder={labels.searchColumns}
              aria-label={labels.searchColumns}
              value={query}
              onChange={(event) => setQuery(event.target.value)}
            />
            <div
              data-adapttable-part="column-menu-bulk"
              className={classNames.columnMenuBulk}
            >
              <button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                className={classNames.columnMenuBulkButton}
                onClick={() => showAllColumns(rows, layout)}
              >
                {labels.showAllColumns}
              </button>
              <button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                className={classNames.columnMenuBulkButton}
                onClick={() => hideAllColumns(rows, layout)}
              >
                {labels.hideAllColumns}
              </button>
              <button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                className={classNames.columnMenuBulkButton}
                onClick={() => unpinAllColumns(rows, layout)}
              >
                {labels.unpinAllColumns}
              </button>
            </div>
            {rows.map((row) => (
              <ColumnMenuRowItem
                key={row.key}
                row={row}
                layout={layout}
                labels={labels}
                classNames={classNames}
                drag={drag}
                sortBy={sortBy}
                sortDir={sortDir}
                onSortColumn={onSortColumn}
                onAutoSizeColumn={onAutoSizeColumn}
                onFilterColumn={onFilterColumn}
                onRenameColumn={onRenameColumn}
                groupingPanel={groupingPanel}
              />
            ))}
            {(hasRowReorder === true || hasRowActions === true) && (
              <hr
                data-adapttable-part="column-menu-separator"
                className={classNames.columnMenuSeparator}
              />
            )}
            {hasRowReorder && (
              <ReorderMenuRowItem
                layout={layout}
                labels={labels}
                classNames={classNames}
              />
            )}
            {hasRowActions && (
              <ActionsMenuRowItem
                layout={layout}
                labels={labels}
                classNames={classNames}
              />
            )}
            <button
              type="button"
              data-adapttable-part="column-menu-auto-size"
              className={cx(classNames.columnMenuAutoSize)}
              onClick={onAutoSize}
            >
              {labels.autoSizeColumns}
            </button>
            <button
              type="button"
              data-adapttable-part="column-menu-reset"
              className={cx(classNames.columnMenuReset)}
              onClick={() => layout.reset()}
            >
              {labels.resetColumns}
            </button>
          </fieldset>,
          document.body
        )}
    </div>
  );
}

// packages/angular/adapter-material/src/components/columnMenu.ts
/**
 * The Columns menu: a disclosure button and a panel where each column has a
 * reorder grip, an eye toggle, a pin toggle and a submenu of actions — drawn
 * with native controls, over the menu model in `@adapttable/angular`.
 */
import {
  ACTIONS_COLUMN_KEY,
  AdaptAttrs,
  AdaptIcon,
  AdaptLiveRegion,
  ADAPTTABLE_SLOT_TABLE,
  type ColumnDrag,
  type ColumnLayout,
  columnMenuActions,
  type ColumnMenuChoice,
  type ColumnMenuItem,
  type ColumnMenuRow,
  columnMenuRows,
  type ColumnMenuSlotProps,
  eyeIcon,
  filterColumnMenuRows,
  GRIP_ICON,
  hideAllColumns,
  injectColumnDrag,
  injectColumnRenameEditor,
  nextPinSide,
  PIN_ICON,
  pinActionLabel,
  REORDER_COLUMN_KEY,
  showAllColumns,
  unpinAllColumns,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  Injector,
  input,
  signal,
  viewChild,
} from "@angular/core";
import { MatButtonModule } from "@angular/material/button";
import { MatFormFieldModule } from "@angular/material/form-field";
import { MatInputModule } from "@angular/material/input";

import { AdaptMaterialPopover } from "./materialPopover";
import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";

/** The menu's props, with the row type erased as every slot erases it. */

const NOOP_RENAME = (): void => undefined;

/** Whether a submenu item is a choice rather than a plain action. */
function isChoice(item: ColumnMenuItem): item is ColumnMenuChoice {
  return "kind" in item && item.kind === "choice";
}

/**
 * One column's row: grip, eye, name, pin, and the "more" submenu with the
 * rename editor.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-row",
  imports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    AdaptAttrs,
    AdaptIcon,
    AdaptLiveRegion,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let r = row();
    @let p = props();
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-hidden]="r.hidden ? '' : null"
      [attr.data-pinned]="r.pinned ?? null"
      [style.cursor]="r.canMove ? 'grab' : 'default'"
      [adaptAttrs]="
        r.canMove ? drag().rowAttrs(r.key, r.index, p.layout.move) : {}
      "
    >
      <button
        mat-icon-button
        type="button"
        class="adapt-material-column-menu-grip"
        [attr.aria-disabled]="r.canMove ? null : 'true'"
        [adaptAttrs]="
          r.canMove
            ? drag().gripAttrs(
                r.key,
                r.index,
                p.layout.move,
                p.labels.moveStart + ' / ' + p.labels.moveEnd + ': ' + r.name
              )
            : {}
        "
      >
        <svg [adaptIcon]="gripIcon"></svg>
      </button>
      <button
        mat-button
        type="button"
        class="adapt-material-column-menu-visibility"
        [attr.data-active]="r.hidden ? null : ''"
        [attr.aria-pressed]="!r.hidden"
        [attr.aria-label]="
          (r.hidden ? p.labels.showColumn : p.labels.hideColumn) + ': ' + r.name
        "
        [disabled]="!r.canHide"
        (click)="p.layout.toggleVisible(r.key)"
      >
        <svg [adaptIcon]="r.hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        class="adapt-material-column-menu-label"
        [attr.data-hidden]="r.hidden ? '' : null"
        >{{ r.name }}</span
      >
      <button
        mat-button
        type="button"
        class="adapt-material-column-menu-pin"
        [attr.data-active]="r.pinned !== undefined ? '' : null"
        [attr.aria-pressed]="r.pinned !== undefined"
        [attr.aria-label]="pinLabel(r, p) + ': ' + r.name"
        [disabled]="!r.canPin"
        (click)="p.layout.setPinned(r.key, nextPin(r))"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
      <button
        mat-button
        type="button"
        data-adapttable-part="column-menu-more"
        [attr.aria-expanded]="open()"
        [attr.aria-label]="p.labels.columnActions + ': ' + r.name"
        (click)="open.set(!open())"
      >
        ⋯
      </button>
      @if (open()) {
        <div data-adapttable-part="column-menu-submenu">
          @for (item of actions(); track item.id) {
            @if (asChoice(item); as choice) {
              <label data-adapttable-part="column-menu-choice">
                <span class="adapt-material-column-menu-choice-label">{{
                  choice.label
                }}</span>
                <mat-form-field appearance="outline" subscriptSizing="dynamic"
                  ><select
                    matNativeControl
                    class="adapt-material-column-menu-choice-select"
                    [attr.aria-label]="choice.label"
                    [value]="choice.value"
                    [disabled]="choice.disabled"
                    (change)="choice.onChange($any($event.target).value)"
                  >
                    @for (option of choice.options; track option.value) {
                      <option [value]="option.value">{{ option.label }}</option>
                    }
                  </select></mat-form-field
                >
              </label>
            } @else {
              <button
                mat-button
                type="button"
                data-adapttable-part="column-menu-action"
                [disabled]="
                  asAction(item).disabled ||
                  (item.id === 'rename' && rename.editing())
                "
                (click)="runAction(item)"
              >
                {{ item.label }}
              </button>
            }
          }
          @if (rename.editing()) {
            <form
              data-adapttable-part="column-rename-form"
              (submit)="$event.preventDefault(); rename.submit()"
            >
              <label
                data-adapttable-part="column-rename-label"
                [attr.for]="rename.inputId"
                >{{ p.labels.columnName }}</label
              >
              <mat-form-field appearance="outline" subscriptSizing="dynamic"
                ><input
                  matInput
                  data-adapttable-part="column-rename-input"
                  [adaptAttrs]="rename.inputAttrs()"
              /></mat-form-field>
              @if (rename.error(); as error) {
                <span
                  data-adapttable-part="column-rename-error"
                  role="alert"
                  [attr.id]="rename.errorId"
                  >{{ error }}</span
                >
              }
              <button
                mat-button
                type="submit"
                data-adapttable-part="column-rename-save"
              >
                {{ p.labels.saveColumnName }}
              </button>
              <button
                mat-button
                type="button"
                data-adapttable-part="column-rename-cancel"
                (click)="rename.cancel()"
              >
                {{ p.labels.cancelColumnRename }}
              </button>
            </form>
          }
        </div>
      }
      <div
        [adaptLiveRegion]="rename.announcement()"
        part="column-rename-announcer"
      ></div>
    </div>
  `,
})
export class AdaptColumnMenuRow {
  /** The row. */
  readonly row = input.required<ColumnMenuRow<never>>();
  /** The menu's props. */
  readonly props = input.required<ColumnMenuSlotProps<never>>();
  /** The menu's drag state. */
  readonly drag = input.required<ColumnDrag>();

  protected readonly open = signal(false);
  protected readonly gripIcon = GRIP_ICON;
  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
  private readonly table = inject(ADAPTTABLE_SLOT_TABLE);

  protected readonly rename = injectColumnRenameEditor({
    column: computed(() => ({
      key: this.row().key,
      name: this.row().name,
      onRename: this.props().onRenameColumn ?? NOOP_RENAME,
      requiredMessage: this.props().labels.columnNameRequired,
      renamedMessage: this.props().labels.columnRenamed,
    })),
  });

  protected readonly actions = computed(() => {
    const props = this.props();
    return columnMenuActions(this.row(), {
      featureHost: this.table.featureHost as never,
      labels: props.labels,
      layout: props.layout,
      sortBy: props.sortBy,
      sortDir: props.sortDir,
      onSortColumn: props.onSortColumn,
      onAutoSizeColumn: props.onAutoSizeColumn,
      onFilterColumn: props.onFilterColumn,
      onBeginRename: props.onRenameColumn ? this.rename.begin : undefined,
      groupingPanel: props.groupingPanel,
    });
  });

  protected pinLabel(
    row: ColumnMenuRow<never>,
    props: ColumnMenuSlotProps<never>
  ): string {
    return pinActionLabel(row.pinned, props.labels);
  }

  protected nextPin(row: ColumnMenuRow<never>): ReturnType<typeof nextPinSide> {
    return nextPinSide(row.pinned);
  }

  protected asChoice(item: ColumnMenuItem): ColumnMenuChoice | undefined {
    return isChoice(item) ? item : undefined;
  }

  protected asAction(item: ColumnMenuItem): { disabled: boolean } {
    return item;
  }

  protected runAction(item: ColumnMenuItem): void {
    if (isChoice(item)) return;
    item.run();
    if (item.id !== "rename") this.open.set(false);
  }
}

/**
 * A reserved column's row — row actions or the reorder grip — with its eye
 * and a one-click pin to the edge it always sits at.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-edge-row",
  imports: [MatButtonModule, AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let hidden = layout().isHidden(columnKey());
    @let pinned = layout().state.pinned[columnKey()] !== undefined;
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-actions]="side() === 'end' ? '' : null"
      [attr.data-reorder]="side() === 'start' ? '' : null"
      [attr.data-hidden]="hidden ? '' : null"
      [attr.data-pinned]="pinned ? side() : null"
    >
      <button
        mat-button
        type="button"
        class="adapt-material-column-menu-visibility"
        [attr.data-active]="hidden ? null : ''"
        [attr.aria-pressed]="!hidden"
        [attr.aria-label]="(hidden ? showLabel() : hideLabel()) + ': ' + name()"
        (click)="layout().toggleVisible(columnKey())"
      >
        <svg [adaptIcon]="hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        class="adapt-material-column-menu-label"
        [attr.data-hidden]="hidden ? '' : null"
        >{{ name() }}</span
      >
      <button
        mat-button
        type="button"
        class="adapt-material-column-menu-pin"
        [attr.data-active]="pinned ? '' : null"
        [attr.aria-pressed]="pinned"
        [attr.aria-label]="(pinned ? unpinLabel() : pinLabel()) + ': ' + name()"
        (click)="layout().setPinned(columnKey(), pinned ? undefined : side())"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
    </div>
  `,
})
export class AdaptColumnMenuEdgeRow {
  /** The column layout. */
  readonly layout = input.required<ColumnLayout<never>>();
  /** The reserved column's key. */
  readonly columnKey = input.required<string>();
  /** The edge it pins to. */
  readonly side = input.required<"start" | "end">();
  /** Its name. */
  readonly name = input.required<string>();
  /** "Show column". */
  readonly showLabel = input.required<string>();
  /** "Hide column". */
  readonly hideLabel = input.required<string>();
  /** "Pin to start" or "Pin to end". */
  readonly pinLabel = input.required<string>();
  /** "Unpin". */
  readonly unpinLabel = input.required<string>();

  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
}

/**
 * The Columns menu in the toolbar.
 *
 * @public
 */
@Component({
  selector: "adapt-column-menu",
  imports: [
    AdaptMaterialPopover,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    AdaptColumnMenuRow,
    AdaptColumnMenuEdgeRow,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <div #root class="adapt-material-column-menu" style="position: relative">
      <button
        mat-button
        #trigger
        type="button"
        data-adapttable-part="column-menu-button"
        aria-haspopup="true"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        {{ p.labels.columns }}
      </button>
      @if (popover.open()) {
        <adapt-material-popover
          [origin]="triggerElement()!.nativeElement"
          (dismiss)="popover.close()"
        >
          <fieldset
            #panel
            class="adapt-material-column-menu-panel"
            [attr.aria-label]="p.labels.columns"
            [attr.dir]="p.dir ?? null"
            [style]="panelStyle"
          >
            <div class="adapt-material-column-menu-header">
              <span class="adapt-material-column-menu-title">{{
                p.labels.columns
              }}</span>
            </div>
            <mat-form-field appearance="outline" subscriptSizing="dynamic"
              ><input
                matInput
                type="search"
                data-adapttable-part="column-menu-search"
                [attr.placeholder]="p.labels.searchColumns"
                [attr.aria-label]="p.labels.searchColumns"
                [value]="query()"
                (input)="query.set($any($event.target).value)"
            /></mat-form-field>
            <div data-adapttable-part="column-menu-bulk">
              <button
                mat-button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="showAll()"
              >
                {{ p.labels.showAllColumns }}
              </button>
              <button
                mat-button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="hideAll()"
              >
                {{ p.labels.hideAllColumns }}
              </button>
              <button
                mat-button
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="unpinAll()"
              >
                {{ p.labels.unpinAllColumns }}
              </button>
            </div>
            @for (row of rows(); track row.key) {
              <adapt-column-menu-row [row]="row" [props]="p" [drag]="drag" />
            }
            @if (p.hasRowReorder || p.hasRowActions) {
              <hr class="adapt-material-column-menu-separator" />
            }
            @if (p.hasRowReorder) {
              <adapt-column-menu-edge-row
                [layout]="p.layout"
                [columnKey]="reorderKey"
                side="start"
                [name]="p.labels.reorderRow"
                [showLabel]="p.labels.showColumn"
                [hideLabel]="p.labels.hideColumn"
                [pinLabel]="p.labels.pinStart"
                [unpinLabel]="p.labels.unpin"
              />
            }
            @if (p.hasRowActions) {
              <adapt-column-menu-edge-row
                [layout]="p.layout"
                [columnKey]="actionsKey"
                side="end"
                [name]="p.labels.actions"
                [showLabel]="p.labels.showColumn"
                [hideLabel]="p.labels.hideColumn"
                [pinLabel]="p.labels.pinEnd"
                [unpinLabel]="p.labels.unpin"
              />
            }
            <button
              mat-button
              type="button"
              class="adapt-material-column-menu-auto-size"
              (click)="p.onAutoSize()"
            >
              {{ p.labels.autoSizeColumns }}
            </button>
            <button
              mat-button
              type="button"
              class="adapt-material-column-menu-reset"
              (click)="p.layout.reset()"
            >
              {{ p.labels.resetColumns }}
            </button>
          </fieldset>
        </adapt-material-popover>
      }
    </div>
  `,
})
export class AdaptColumnMenu {
  /** The slot's props. */
  readonly props = input.required<ColumnMenuSlotProps<never>>();

  protected readonly query = signal("");
  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly reorderKey = REORDER_COLUMN_KEY;
  protected readonly actionsKey = ACTIONS_COLUMN_KEY;
  protected readonly drag = injectColumnDrag();
  protected readonly rows = computed(() =>
    filterColumnMenuRows(
      columnMenuRows(this.props().allColumns, this.props().layout),
      this.query()
    )
  );

  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  protected readonly triggerElement = viewChild<
    unknown,
    ElementRef<HTMLElement>
  >("trigger", { read: ElementRef });
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.triggerElement()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    inject(Injector)
  );

  protected showAll(): void {
    showAllColumns(this.rows(), this.props().layout);
  }

  protected hideAll(): void {
    hideAllColumns(this.rows(), this.props().layout);
  }

  protected unpinAll(): void {
    unpinAllColumns(this.rows(), this.props().layout);
  }
}
