// packages/angular/adapter-ng-zorro/src/components/savedViewsMenu.ts
/**
 * The saved-views menu: a button and a panel listing the saved views —
 * click one to apply it, or delete it — above a row that saves the table's
 * current state under a name.
 */
import {
  injectSavedViews,
  type SavedViewsControllerOptions,
  type SavedViewsState,
} from "@adapttable/angular";
import type { SavedViewsSlotProps } from "@adapttable/angular/adapter";
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  Injector,
  input,
  type OnInit,
  signal,
  viewChild,
} from "@angular/core";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzDividerModule } from "ng-zorro-antd/divider";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzPopoverModule } from "ng-zorro-antd/popover";

import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";
import { OVERLAY_Z } from "./overlayPlacement";

/**
 * The saved-views toolbar control.
 *
 * @internal
 */
@Component({
  selector: "adapt-saved-views-menu",
  imports: [
    NzButtonModule,
    NzCardModule,
    NzDividerModule,
    NzInputModule,
    NzPopoverModule,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let l = props().labels;
    <div #root style="position: relative">
      <button
        nz-button
        #trigger
        nz-popover
        [nzPopoverTrigger]="null"
        [nzPopoverVisible]="popover.open()"
        [nzPopoverBackdrop]="false"
        [nzPopoverContent]="content"
        [nzPopoverPlacement]="
          direction() === 'rtl'
            ? ['bottomLeft', 'bottomRight', 'topLeft', 'topRight']
            : ['bottomRight', 'bottomLeft', 'topRight', 'topLeft']
        "
        [nzPopoverOverlayStyle]="overlayStyle"
        type="button"
        aria-haspopup="true"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        <span>{{ l.savedViews }} </span>
      </button>
      <ng-template #content>
        @if (popover.open()) {
          <div #panel [dir]="direction()" [style]="panelStyle">
            @for (view of views()?.views() ?? []; track view.name) {
              <div [style]="rowStyle">
                <button nz-button type="button" (click)="apply(view.name)">
                  <span>{{ view.name }} </span>
                </button>
                <button
                  nz-button
                  type="button"
                  [attr.aria-label]="l.deleteView + ': ' + view.name"
                  (click)="views()?.remove(view.name)"
                >
                  <span>× </span>
                </button>
              </div>
            }
            <nz-divider />
            <div [style]="rowStyle">
              <input
                #nameInput
                nz-input
                [style]="inputStyle"
                [attr.aria-label]="l.viewName"
                [attr.placeholder]="l.viewName"
                [value]="name()"
                (input)="name.set($any($event.target).value)"
              />
              <button
                nz-button
                type="button"
                [disabled]="trimmed() === ''"
                (click)="save()"
              >
                <span>{{ l.saveView }} </span>
              </button>
            </div>
          </div>
        }
      </ng-template>
    </div>
  `,
})
export class AdaptSavedViewsMenu implements OnInit {
  /** The slot's props. */
  readonly props =
    input.required<SavedViewsSlotProps<SavedViewsControllerOptions>>();

  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly overlayStyle = { zIndex: String(OVERLAY_Z) };
  protected readonly direction = signal<"ltr" | "rtl">("ltr");
  protected readonly rowStyle = {
    display: "flex",
    "align-items": "center",
    gap: "6px",
  };
  /** The input's intrinsic size would set the panel wider than a phone. */
  protected readonly inputStyle = {
    flex: "1 1 10rem",
    "inline-size": "10rem",
    "min-inline-size": "0",
  };
  protected readonly name = signal("");
  protected readonly trimmed = computed(() => this.name().trim());
  /** The views, once the props say where they are kept. */
  protected readonly views = signal<SavedViewsState | undefined>(undefined);

  private readonly injector = inject(Injector);
  private readonly nameInput =
    viewChild<ElementRef<HTMLInputElement>>("nameInput");
  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  private readonly trigger = viewChild<
    ElementRef<HTMLElement>,
    ElementRef<HTMLElement>
  >("trigger", {
    read: ElementRef,
  });
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.trigger()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    this.injector
  );

  constructor() {
    afterRenderEffect(() => {
      const root = this.root()?.nativeElement;
      this.direction.set(
        root?.closest<HTMLElement>("[dir]")?.dir === "rtl" ? "rtl" : "ltr"
      );
    });
  }

  /** Open the views where the props say they are kept. */
  ngOnInit(): void {
    this.views.set(
      injectSavedViews(
        computed(() => ({ ...this.props().options, injector: this.injector }))
      )
    );
  }

  protected apply(name: string): void {
    this.views()?.apply(name);
    this.popover.close();
  }

  protected save(): void {
    this.views()?.save(this.trimmed());
    this.name.set("");
    this.nameInput()?.nativeElement.focus();
  }
}

// packages/react/adapter-antd/src/components/SavedViewsMenu.tsx
import { useSavedViews, type UseSavedViewsOptions } from "@adapttable/react";
import type { Direction, TableLabels } from "@adapttable/react/adapter";
import { Button, Divider, Flex, Input, Popover } from "antd";
import { useEffect, useRef, useState } from "react";

/**
 * The label strings the saved-views menu renders.
 *
 * @public
 */
export type SavedViewsLabels = Pick<
  Required<TableLabels>,
  "savedViews" | "saveView" | "viewName" | "deleteView"
>;

/**
 * Props for {@link SavedViewsMenu}.
 *
 * @public
 */
export interface SavedViewsMenuProps {
  /** Storage + URL wiring, forwarded to core's `useSavedViews`. */
  options: UseSavedViewsOptions;
  /** Resolved labels. */
  labels: SavedViewsLabels;
  /** Writing direction, so the overlay opens on the correct side. */
  dir?: Direction;
}

/** The input's intrinsic size would set the panel wider than a phone. */
const NAME_INPUT_STYLE = { flex: "1 1 10rem", width: "10rem", minWidth: 0 };

/**
 * AntD saved-views popover on core's headless `useSavedViews`: a list of
 * captured views (click re-applies one to the table's URL state, a trailing
 * button deletes it) plus a name-input row that saves the table's CURRENT
 * state. Controlled open state so Escape dismisses it (antd's Popover has no
 * built-in Escape handling) and the trigger reports `aria-expanded`, matching
 * the ColumnMenu beside it.
 *
 * @public
 */
export function SavedViewsMenu({
  options,
  labels,
  dir,
}: Readonly<SavedViewsMenuProps>) {
  const { views, save, apply, remove } = useSavedViews(options);
  const [open, setOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const [name, setName] = useState("");
  useEffect(() => {
    if (!open) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        setOpen(false);
        triggerRef.current?.focus();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [open]);
  const trimmed = name.trim();
  const content = (
    <div
      style={{
        padding: 8,
        minWidth: "min(240px, calc(100vw - 48px))",
        maxHeight: "min(70vh, 360px)",
        overflowY: "auto",
      }}
    >
      {views.map((view) => (
        <Flex key={view.name} align="center" gap={4}>
          <Button
            size="small"
            type="text"
            style={{ flex: 1, justifyContent: "flex-start" }}
            onClick={() => {
              apply(view.name);
              setOpen(false);
            }}
          >
            {view.name}
          </Button>
          <Button
            size="small"
            type="text"
            aria-label={`${labels.deleteView}: ${view.name}`}
            onClick={() => remove(view.name)}
          >
            <span aria-hidden="true">×</span>
          </Button>
        </Flex>
      ))}
      <Divider style={{ margin: "8px 0" }} />
      <Flex align="center" gap={4}>
        <Input
          size="small"
          style={NAME_INPUT_STYLE}
          placeholder={labels.viewName}
          aria-label={labels.viewName}
          value={name}
          onChange={(event) => setName(event.currentTarget.value)}
        />
        <Button
          size="small"
          disabled={trimmed === ""}
          onClick={() => {
            save(trimmed);
            setName("");
          }}
        >
          {labels.saveView}
        </Button>
      </Flex>
    </div>
  );
  return (
    <Popover
      trigger="click"
      open={open}
      onOpenChange={setOpen}
      placement={dir === "rtl" ? "bottomLeft" : "bottomRight"}
      autoAdjustOverflow={{ adjustX: 1, adjustY: 0 }}
      content={content}
      styles={{ content: { padding: 0 } }}
    >
      <Button ref={triggerRef} aria-expanded={open} aria-haspopup="true">
        {labels.savedViews}
      </Button>
    </Popover>
  );
}
