// packages/core/src/virtual/ColumnSpacer.tsx
/**
 * The cell that holds open the columns outside the horizontal window.
 *
 * It is one empty cell per side, sized to everything the window skipped, so
 * the table's scroll width matches the columns it claims to have. Aria-hidden
 * because it is scaffolding, not data — a screen reader walking the row would
 * otherwise meet two blank cells whose only job is width.
 */
import type { ReactElement } from "react";

/**
 * Props for {@link ColumnSpacer}.
 *
 * @public
 */
export interface ColumnSpacerProps {
  /** Pixel width of the columns this cell stands in for. */
  width: number;
  /** Which side of the window it sits on, for the part name. */
  side: "start" | "end";
  /** The element to render — a kit's own cell component, or `"td"`. */
  as?: "td" | "th";
}

/**
 * Renders the spacer, or nothing when there is nothing to hold open.
 *
 * @public
 */
export function ColumnSpacer({
  width,
  side,
  as = "td",
}: Readonly<ColumnSpacerProps>): ReactElement | null {
  if (width <= 0) return null;
  const Cell = as;
  return (
    <Cell
      aria-hidden="true"
      data-adapttable-part={`column-spacer-${side}`}
      style={{ width, minWidth: width, padding: 0, border: 0 }}
    />
  );
}

// packages/angular/angular/src/virtual/columnSpacer.ts
/**
 * The cell that holds open the columns outside the horizontal window.
 *
 * One empty cell per side, sized to everything the window skipped, so the
 * table's scroll width matches the columns it claims. Aria-hidden: it is
 * scaffolding, not data.
 */
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";

/**
 * Renders the spacer cell, or nothing when there is nothing to hold open.
 *
 * @public
 */
@Component({
  selector: "adapt-column-spacer",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (width() > 0) {
      @if (header()) {
        <th
          aria-hidden="true"
          [attr.data-adapttable-part]="part()"
          [style]="cellStyle()"
        ></th>
      } @else {
        <td
          aria-hidden="true"
          [attr.data-adapttable-part]="part()"
          [style]="cellStyle()"
        ></td>
      }
    }
  `,
})
export class AdaptColumnSpacer {
  /** Pixel width of the columns this cell stands in for. */
  readonly width = input.required<number>();
  /** Which side of the window it sits on, for the part name. */
  readonly side = input.required<"start" | "end">();
  /** A header cell or a body cell. */
  readonly as = input<"td" | "th">("td");

  protected readonly header = computed(() => this.as() === "th");
  protected readonly part = computed(() => `column-spacer-${this.side()}`);
  protected readonly cellStyle = computed(() => {
    const width = `${String(this.width())}px`;
    return { width, minWidth: width, padding: "0", border: "0" };
  });
}
