// packages/angular/angular/src/rows/rowReorderHandle.ts
/**
 * Row-reorder Chrome: the grip, the mobile up/down pair, and the live
 * region — structure and wiring only. Every visible control is the kit's.
 */
import { resolveLabels } from "@adapttable/core";
import type {
  RowMoveMenuSlotProps,
  RowReorderButtonsProps as NeutralRowReorderButtonsProps,
  RowReorderHandleProps as NeutralRowReorderHandleProps,
  RowReorderHandleSlotProps as NeutralRowReorderHandleSlotProps,
  RowReorderLabels,
  RowReorderMoveButtonProps,
} from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import { AdaptLiveRegion } from "../a11y/liveRegion";
import { AdaptControl } from "../control";
import type { RowReorderState } from "./rowReorder";

/**
 * Props for an adapter row-reorder grip — core's handle props over Angular's
 * reorder state.
 *
 * @public
 */
export type RowReorderHandleProps<TRow> = NeutralRowReorderHandleProps<
  TRow,
  RowReorderState<TRow>
>;

/**
 * Kit grip the reorder Chrome calls — core's handle slot props with DOM events.
 *
 * @public
 */
export type RowReorderHandleSlotProps = NeutralRowReorderHandleSlotProps<
  KeyboardEvent,
  DragEvent
>;

/**
 * Kit-supplied controls for {@link AdaptRowReorderHandleChrome}.
 *
 * @public
 */
export interface RowReorderHandleSlots {
  /** The drag grip. */
  readonly Handle: Type<unknown>;
  /** The destination menu and confirmation. */
  readonly Menu: Type<unknown>;
}

/**
 * Props for an adapter mobile reorder pair — core's buttons props over
 * Angular's reorder state.
 *
 * @public
 */
export type RowReorderButtonsProps<TRow> = NeutralRowReorderButtonsProps<
  TRow,
  RowReorderState<TRow>
>;

/**
 * Kit-supplied controls for {@link AdaptRowReorderButtonsChrome}.
 *
 * @public
 */
export interface RowReorderButtonsSlots {
  /** One move-up or move-down button. */
  readonly Button: Type<unknown>;
  /** The destination menu and confirmation. */
  readonly Menu: Type<unknown>;
}

export type {
  RowMoveConfirmationProps,
  RowMoveMenuItemProps,
  RowMoveMenuSlotProps,
  RowReorderMoveButtonProps,
} from "@adapttable/core/binding";

/**
 * The destination menu both reorder controls offer, and the state it needs.
 */
function moveMenuProps<TRow>(
  reorder: RowReorderState<TRow>,
  labels: RowReorderLabels,
  row: TRow,
  moveLocked: boolean
): RowMoveMenuSlotProps | undefined {
  const copy = resolveLabels(labels);
  const menu = reorder.moveMenu?.(row);
  if (!menu) return undefined;
  const ownsPending =
    reorder.isMovePending?.(row) ?? reorder.pendingMove?.row === row;
  const pending = ownsPending ? reorder.pendingMove : undefined;
  const from =
    pending?.kind === "group"
      ? pending.fromGroup.label
      : pending?.fromParent.label;
  const to =
    pending?.kind === "group" ? pending.toGroup.label : pending?.toParent.label;
  return {
    label: menu.label,
    items: menu.targets.map((target) => ({
      id: target.id,
      label: target.label,
      disabled: moveLocked || target.disabledReason !== undefined,
      disabledReason: target.disabledReason,
      onSelect: () => {
        reorder.selectMoveTarget(target);
      },
    })),
    confirmation:
      pending && from && to
        ? {
            title: copy.confirmRowMoveTitle,
            description: copy.confirmRowMoveDescription(
              pending.rowLabel,
              from,
              to
            ),
            confirmLabel: copy.confirmRowMove,
            cancelLabel: copy.cancel,
            onConfirm: reorder.confirmMove,
            onCancel: reorder.cancelMove,
          }
        : undefined,
  };
}

/**
 * Desktop grip: pointer drag plus Space-lift keyboard. Kits wrap this in
 * their own cell so the handle looks like the rest of the row.
 *
 * @public
 */
@Component({
  selector: "adapt-row-reorder-handle-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let handle = handleProps();
    <ng-container
      [adaptControl]="slots().Handle"
      [adaptControlProps]="handle"
    />
    @if (menu(); as menuProps) {
      <ng-container
        [adaptControl]="slots().Menu"
        [adaptControlProps]="menuProps"
      />
    }
  `,
})
export class AdaptRowReorderHandleChrome<TRow> {
  /** Live reorder state. */
  readonly reorder = input.required<RowReorderState<TRow>>();
  /** Resolved reorder labels. */
  readonly labels = input.required<RowReorderLabels>();
  /** Identity of the row this control moves. */
  readonly rowId = input.required<string>();
  /** The row's index within the rendered window. */
  readonly localIndex = input.required<number>();
  /** The row being rendered. */
  readonly row = input.required<TRow>();
  /** Index of the first rendered row. */
  readonly windowStart = input.required<number>();
  /** Rows in the rendered window. */
  readonly rowCount = input.required<number>();
  /** Optional class for the grip. */
  readonly className = input<string>();
  /** The kit's controls. */
  readonly slots = input.required<RowReorderHandleSlots>();

  protected readonly moveLocked = computed(() => {
    const state = this.reorder();
    return Boolean(state.hostConfirmPending || state.pendingMove);
  });

  protected readonly handleProps = computed((): RowReorderHandleSlotProps => {
    const reorder = this.reorder();
    const rowId = this.rowId();
    const localIndex = this.localIndex();
    const row = this.row();
    const windowStart = this.windowStart();
    const rowCount = this.rowCount();
    return {
      label: this.labels().reorderRow,
      pressed: reorder.isLifted(rowId),
      dragging: reorder.isLifted(rowId),
      disabled: this.moveLocked(),
      className: this.className(),
      dragProps: reorder.dragProps(rowId, localIndex),
      onKeyDown: (event) => {
        reorder.handleKeyDown(
          event,
          rowId,
          localIndex,
          row,
          windowStart,
          rowCount
        );
      },
    };
  });

  protected readonly menu = computed(() =>
    moveMenuProps(this.reorder(), this.labels(), this.row(), this.moveLocked())
  );
}

/**
 * Mobile up/down — a drag handle on a card is unusable. Each press swaps
 * with the neighbour; the ends disable rather than wrapping.
 *
 * @public
 */
@Component({
  selector: "adapt-row-reorder-buttons-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <span data-adapttable-part="row-reorder-buttons" [class]="className()">
      <ng-container
        [adaptControl]="slots().Button"
        [adaptControlProps]="upProps()"
      />
      <ng-container
        [adaptControl]="slots().Button"
        [adaptControlProps]="downProps()"
      />
      @if (menu(); as menuProps) {
        <ng-container
          [adaptControl]="slots().Menu"
          [adaptControlProps]="menuProps"
        />
      }
    </span>
  `,
})
export class AdaptRowReorderButtonsChrome<TRow> {
  /** Live reorder state. */
  readonly reorder = input.required<RowReorderState<TRow>>();
  /** Resolved reorder labels. */
  readonly labels = input.required<RowReorderLabels>();
  /** The row's index within the rendered window. */
  readonly localIndex = input.required<number>();
  /** The row being rendered. */
  readonly row = input.required<TRow>();
  /** Index of the first rendered row. */
  readonly windowStart = input.required<number>();
  /** Rows in the rendered window. */
  readonly rowCount = input.required<number>();
  /** Optional class for the pair. */
  readonly className = input<string>();
  /** Optional class for the up button. */
  readonly upClassName = input<string>();
  /** Optional class for the down button. */
  readonly downClassName = input<string>();
  /** The kit's controls. */
  readonly slots = input.required<RowReorderButtonsSlots>();

  protected readonly moveLocked = computed(() => {
    const state = this.reorder();
    return Boolean(state.hostConfirmPending || state.pendingMove);
  });

  protected readonly upProps = computed((): RowReorderMoveButtonProps => {
    const reorder = this.reorder();
    const localIndex = this.localIndex();
    const row = this.row();
    const windowStart = this.windowStart();
    const rowCount = this.rowCount();
    return {
      label: this.labels().moveRowUp,
      part: "row-reorder-up",
      disabled: this.moveLocked() || localIndex <= 0,
      className: this.upClassName(),
      onClick: () => {
        reorder.moveBy(localIndex, -1, row, windowStart, rowCount);
      },
    };
  });

  protected readonly downProps = computed((): RowReorderMoveButtonProps => {
    const reorder = this.reorder();
    const localIndex = this.localIndex();
    const row = this.row();
    const windowStart = this.windowStart();
    const rowCount = this.rowCount();
    return {
      label: this.labels().moveRowDown,
      part: "row-reorder-down",
      disabled: this.moveLocked() || localIndex >= rowCount - 1,
      className: this.downClassName(),
      onClick: () => {
        reorder.moveBy(localIndex, 1, row, windowStart, rowCount);
      },
    };
  });

  protected readonly menu = computed(() =>
    moveMenuProps(this.reorder(), this.labels(), this.row(), this.moveLocked())
  );
}

/**
 * The live region for row reorder. Kits render this only while reorder is composed.
 *
 * @public
 */
@Component({
  selector: "adapt-row-reorder-announcer",
  imports: [AdaptLiveRegion],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <output
      [adaptLiveRegion]="props().announcement"
      part="row-reorder-announcer"
    ></output>
  `,
})
export class AdaptRowReorderAnnouncer {
  /** What to announce — the slot fill's single props bag. */
  readonly props = input.required<{ readonly announcement: string }>();
}

// packages/core/src/rows/RowReorderHandle.tsx
/**
 * Row-reorder layout. The live region stays here. Adapters pass the grip
 * and the mobile up/down buttons the end user clicks.
 */
import type { KeyboardEvent, ReactElement, ReactNode } from "react";

import { LiveRegion } from "../a11y/LiveRegion";
import type { RowReorderLabels, RowReorderState } from "./rowReorder";

export type { RowReorderLabels };

/**
 * Props for an adapter `RowReorderHandle` — no slots on the public API.
 *
 * @public
 */
export interface RowReorderHandleProps<TRow> {
  /** Row-reorder state: what is being dragged and where it may land. */
  reorder: RowReorderState<TRow>;
  /** Resolved labels, every key filled. */
  labels: RowReorderLabels;
  /** Identity of the row this control moves. */
  rowId: string;
  /** The row's index within the rendered window. */
  localIndex: number;
  /** The row being rendered. */
  row: TRow;
  /** Index of the first rendered row, so a windowed index maps back. */
  windowStart: number;
  /** Rows in the whole dataset, for the move bounds. */
  rowCount: number;
  /** Class for the element. */
  className?: string;
}

/**
 * Kit grip the reorder chrome calls.
 *
 * @public
 */
export interface RowReorderHandleSlotProps {
  /** Accessible name for the control. */
  readonly label: string;
  /** Whether the grip is held. */
  readonly pressed: boolean;
  /** Whether a drag is in progress. */
  readonly dragging: boolean;
  /** Whether another move already owns confirmation. */
  readonly disabled: boolean;
  /** Class for the element. */
  readonly className?: string;
  /** Pointer bindings that start and track the drag. */
  readonly dragProps: ReturnType<RowReorderState<unknown>["dragProps"]>;
  /** Handles the keyboard move keys. */
  readonly onKeyDown: (event: KeyboardEvent<HTMLElement>) => void;
}

/**
 * Adapter-supplied controls for {@link RowReorderHandleChrome}.
 *
 * @public
 */
export interface RowReorderHandleSlots {
  /** Renders the drag grip. */
  readonly Handle: (props: RowReorderHandleSlotProps) => ReactNode;
  /** Renders the nested-row destination menu and confirmation. */
  readonly Menu: (props: RowMoveMenuSlotProps) => ReactNode;
}

/**
 * One option in the adapter-owned row destination menu.
 *
 * @public
 */
export interface RowMoveMenuItemProps {
  /** Stable destination id. */
  readonly id: string;
  /** Human-readable destination. */
  readonly label: string;
  /** Whether the destination is unavailable. */
  readonly disabled: boolean;
  /** Explanation exposed for an unavailable destination. */
  readonly disabledReason?: string;
  /** Selects this destination. */
  readonly onSelect: () => void;
}

/**
 * Pending move shown inside the adapter-owned menu surface.
 *
 * @public
 */
export interface RowMoveConfirmationProps {
  /** Confirmation heading. */
  readonly title: string;
  /** Concrete source-to-destination change. */
  readonly description: string;
  /** Approval button label. */
  readonly confirmLabel: string;
  /** Cancellation button label. */
  readonly cancelLabel: string;
  /** Commits the pending move. */
  readonly onConfirm: () => void;
  /** Discards the pending move. */
  readonly onCancel: () => void;
}

/**
 * Props for an adapter-owned nested row destination menu.
 *
 * @public
 */
export interface RowMoveMenuSlotProps {
  /** Accessible menu trigger and content label. */
  readonly label: string;
  /** Loaded move destinations. */
  readonly items: readonly RowMoveMenuItemProps[];
  /** Pending move to approve, when confirm policy is active. */
  readonly confirmation?: RowMoveConfirmationProps;
}

/**
 * Props for {@link RowReorderHandleChrome}.
 *
 * @public
 */
export interface RowReorderHandleChromeProps<
  TRow,
> extends RowReorderHandleProps<TRow> {
  /** The kit's components for each part. */
  readonly slots: RowReorderHandleSlots;
}

/**
 * Desktop grip: pointer drag plus Space-lift keyboard. Kits wrap this in
 * their own `<td>` / `<th>` so the cell looks like the rest of the row.
 *
 * @public
 */
export function RowReorderHandleChrome<TRow>({
  reorder,
  labels,
  rowId,
  localIndex,
  row,
  windowStart,
  rowCount,
  className,
  slots,
}: Readonly<RowReorderHandleChromeProps<TRow>>): ReactElement {
  const lifted = reorder.isLifted(rowId);
  const Handle = slots.Handle;
  const Menu = slots.Menu;
  const menu = reorder.moveMenu?.(row);
  const moveLocked = Boolean(reorder.hostConfirmPending || reorder.pendingMove);
  const ownsPending =
    reorder.isMovePending?.(row) ?? reorder.pendingMove?.row === row;
  const pending = ownsPending ? reorder.pendingMove : undefined;
  const from =
    pending?.kind === "group"
      ? pending.fromGroup.label
      : pending?.fromParent.label;
  const to =
    pending?.kind === "group" ? pending.toGroup.label : pending?.toParent.label;
  return (
    <>
      <Handle
        label={labels.reorderRow}
        pressed={lifted}
        dragging={lifted}
        disabled={moveLocked}
        className={className}
        dragProps={reorder.dragProps(rowId, localIndex)}
        onKeyDown={(event) => {
          reorder.handleKeyDown(
            event,
            rowId,
            localIndex,
            row,
            windowStart,
            rowCount
          );
        }}
      />
      {menu ? (
        <Menu
          label={menu.label}
          items={menu.targets.map((target) => ({
            id: target.id,
            label: target.label,
            disabled: moveLocked || target.disabledReason !== undefined,
            disabledReason: target.disabledReason,
            onSelect: () => reorder.selectMoveTarget(target),
          }))}
          confirmation={
            pending && from && to
              ? {
                  title: labels.confirmRowMoveTitle ?? "Confirm row move",
                  description:
                    labels.confirmRowMoveDescription?.(
                      pending.rowLabel,
                      from,
                      to
                    ) ?? `Move ${pending.rowLabel} from ${from} to ${to}?`,
                  confirmLabel: labels.confirmRowMove ?? "Move",
                  cancelLabel: labels.cancel ?? "Cancel",
                  onConfirm: reorder.confirmMove,
                  onCancel: reorder.cancelMove,
                }
              : undefined
          }
        />
      ) : null}
    </>
  );
}

/**
 * Props for an adapter `RowReorderButtons` — no slots on the public API.
 *
 * @public
 */
export interface RowReorderButtonsProps<TRow> {
  /** Row-reorder state: what is being dragged and where it may land. */
  reorder: RowReorderState<TRow>;
  /** Resolved labels, every key filled. */
  labels: RowReorderLabels;
  /** The row's index within the rendered window. */
  localIndex: number;
  /** The row being rendered. */
  row: TRow;
  /** Index of the first rendered row, so a windowed index maps back. */
  windowStart: number;
  /** Rows in the whole dataset, for the move bounds. */
  rowCount: number;
  /** Class for the element. */
  className?: string;
  /** Class for the move-up button. */
  upClassName?: string;
  /** Class for the move-down button. */
  downClassName?: string;
}

/**
 * Kit button the mobile reorder chrome calls.
 *
 * @public
 */
export interface RowReorderMoveButtonProps {
  /** Accessible name for the control. */
  readonly label: string;
  /** Part name, so styling can target this element. */
  readonly part: string;
  /** Whether the control is offered but not available. */
  readonly disabled: boolean;
  /** Class for the element. */
  readonly className?: string;
  /** Called when pressed. */
  readonly onClick: () => void;
}

/**
 * Adapter-supplied controls for {@link RowReorderButtonsChrome}.
 *
 * @public
 */
export interface RowReorderButtonsSlots {
  /** Renders one move button. */
  readonly Button: (props: RowReorderMoveButtonProps) => ReactNode;
  /** Renders the nested-row destination menu and confirmation. */
  readonly Menu: (props: RowMoveMenuSlotProps) => ReactNode;
}

/**
 * Props for {@link RowReorderButtonsChrome}.
 *
 * @public
 */
export interface RowReorderButtonsChromeProps<
  TRow,
> extends RowReorderButtonsProps<TRow> {
  /** The kit's components for each part. */
  readonly slots: RowReorderButtonsSlots;
}

/**
 * Mobile up/down — a drag handle on a card is unusable. Each press swaps
 * with the neighbour; the ends disable rather than wrapping.
 *
 * @public
 */
export function RowReorderButtonsChrome<TRow>({
  reorder,
  labels,
  localIndex,
  row,
  windowStart,
  rowCount,
  className,
  upClassName,
  downClassName,
  slots,
}: Readonly<RowReorderButtonsChromeProps<TRow>>): ReactElement {
  const Button = slots.Button;
  const Menu = slots.Menu;
  const menu = reorder.moveMenu?.(row);
  const moveLocked = Boolean(reorder.hostConfirmPending || reorder.pendingMove);
  const ownsPending =
    reorder.isMovePending?.(row) ?? reorder.pendingMove?.row === row;
  const pending = ownsPending ? reorder.pendingMove : undefined;
  const from =
    pending?.kind === "group"
      ? pending.fromGroup.label
      : pending?.fromParent.label;
  const to =
    pending?.kind === "group" ? pending.toGroup.label : pending?.toParent.label;
  return (
    <span data-adapttable-part="row-reorder-buttons" className={className}>
      <Button
        label={labels.moveRowUp}
        part="row-reorder-up"
        disabled={moveLocked || localIndex <= 0}
        className={upClassName}
        onClick={() => {
          reorder.moveBy(localIndex, -1, row, windowStart, rowCount);
        }}
      />
      <Button
        label={labels.moveRowDown}
        part="row-reorder-down"
        disabled={moveLocked || localIndex >= rowCount - 1}
        className={downClassName}
        onClick={() => {
          reorder.moveBy(localIndex, 1, row, windowStart, rowCount);
        }}
      />
      {menu ? (
        <Menu
          label={menu.label}
          items={menu.targets.map((target) => ({
            id: target.id,
            label: target.label,
            disabled: moveLocked || target.disabledReason !== undefined,
            disabledReason: target.disabledReason,
            onSelect: () => reorder.selectMoveTarget(target),
          }))}
          confirmation={
            pending && from && to
              ? {
                  title: labels.confirmRowMoveTitle ?? "Confirm row move",
                  description:
                    labels.confirmRowMoveDescription?.(
                      pending.rowLabel,
                      from,
                      to
                    ) ?? `Move ${pending.rowLabel} from ${from} to ${to}?`,
                  confirmLabel: labels.confirmRowMove ?? "Move",
                  cancelLabel: labels.cancel ?? "Cancel",
                  onConfirm: reorder.confirmMove,
                  onCancel: reorder.cancelMove,
                }
              : undefined
          }
        />
      ) : null}
    </span>
  );
}

/**
 * The live region for row reorder. Kits mount this only when reorder is armed.
 *
 * @public
 */
export function RowReorderAnnouncer(
  props: Readonly<{ announcement: string }>
): ReactElement {
  return (
    <LiveRegion part="row-reorder-announcer">{props.announcement}</LiveRegion>
  );
}

export type { SortByOption } from "../types";
