// packages/angular/angular/src/export/exportAnnouncer.ts
/**
 * The live region that says an export finished — or did not.
 *
 * A download is silent. The file lands in the browser's downloads with no
 * focus change, so a screen-reader user who presses Export hears nothing
 * unless this region was already on the page.
 */
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

import { AdaptLiveRegion } from "../a11y/liveRegion";

/**
 * Says how the export ended. Always mounted beside the button, because a
 * region that appears together with its message is missed.
 *
 * @public
 */
@Component({
  selector: "adapt-export-announcer",
  imports: [AdaptLiveRegion],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <output [adaptLiveRegion]="announcement()" part="export-announcer"></output>
  `,
})
export class AdaptExportAnnouncer {
  /** `exportAnnouncement` from {@link injectExportHandler}. Empty until an export ends. */
  readonly announcement = input("");
}

// packages/core/src/export/ExportAnnouncer.tsx
/**
 * The live region that says an export finished — or did not.
 *
 * A download is silent. The file lands in the browser's downloads with no
 * focus change and no visible confirmation inside the page, so a screen-reader
 * user who presses Export hears nothing at all and cannot tell success from
 * failure. That is the whole reason this exists, and why it is an announcement
 * rather than a toast: the toast would need dismissing, styling in eight kits,
 * and a decision about where it goes.
 */
import type { ReactElement } from "react";

import { LiveRegion } from "../a11y/LiveRegion";

/**
 * Props for {@link ExportAnnouncer}.
 *
 * @public
 */
export interface ExportAnnouncerProps {
  /** `exportAnnouncement` from `useExportHandler`. Empty until an export ends. */
  announcement: string;
}

/**
 * Renders the export's outcome announcement. Always mounted beside the button,
 * because a region that appears together with its message is missed.
 *
 * @param props - See {@link ExportAnnouncerProps}.
 *
 * @public
 */
export function ExportAnnouncer({
  announcement,
}: Readonly<ExportAnnouncerProps>): ReactElement {
  return <LiveRegion part="export-announcer">{announcement}</LiveRegion>;
}
