// packages/react/src/layout/SidePanelChrome.tsx
/**
 * The side panel: table settings docked beside the table instead of
 * floating over it.
 *
 * A popover is right for a control you touch once and dismiss. It is wrong
 * for the work of setting a table up — choosing columns, building a filter,
 * arranging a pivot — because that is iterative: change one thing, look at
 * the rows, change another. A popover closes when you look away, and the
 * rows are behind it while it is open. A docked panel stays put and shares
 * the width, which is why every serious grid grows one.
 *
 * What core owns here is the part a kit would get subtly wrong: the tabs
 * are a real `tablist` with roving focus, arrow keys wrap and move the
 * selection with them, Escape closes from anywhere inside, and the panel
 * body is a `tabpanel` labelled by its tab. Which panel is showing is
 * state, and state belongs here rather than in seven copies. Putting focus
 * back after a close belongs to whatever opened the panel, which is the
 * only thing that knows where focus was.
 *
 * What the kit owns is everything visible: the panel's frame, the tab
 * buttons, the close control. There is no fallback for those — a docked
 * panel drawn in raw HTML inside an MUI table is exactly the mismatch the
 * slots law exists to prevent.
 *
 * The panels themselves are content the caller supplies. That is what lets
 * the same chrome hold a filter form, a column list, or a pivot builder
 * without knowing what any of them are.
 */
import type { TableLabels } from "@adapttable/core";
import { type KeyboardEvent, type ReactNode, useCallback, useRef } from "react";

/**
 * One panel in the side panel's strip.
 *
 * @public
 */
export interface SidePanelEntry {
  /** Stable identity, used for the open-panel state and the URL. */
  key: string;
  /** The tab's caption, already localized. */
  label: string;
  /** What the panel shows when it is the selected one. */
  content: ReactNode;
}

/**
 * Props an adapter's panel frame receives.
 *
 * @public
 */
export interface SidePanelFrameProps {
  /** The tab strip and the panel body, in order. */
  readonly children: ReactNode;
  /** Which edge the panel is docked to, already resolved for direction. */
  readonly side: "start" | "end";
  /** Class for the element. */
  readonly className?: string;
}

/**
 * Props an adapter's tab button receives.
 *
 * @public
 */
export interface SidePanelTabProps {
  /** The side-panel tab being rendered. */
  readonly panel: SidePanelEntry;
  /** Whether this item is selected. */
  readonly selected: boolean;
  /** Spread onto the button: role, tabindex, aria wiring, id and keys. */
  readonly buttonProps: {
    readonly id: string;
    readonly role: "tab";
    readonly type: "button";
    readonly tabIndex: number;
    readonly "aria-selected": boolean;
    readonly "aria-controls": string;
    readonly "data-adapttable-part": "side-panel-tab";
    readonly onClick: () => void;
    readonly onKeyDown: (event: KeyboardEvent<HTMLElement>) => void;
  };
}

/**
 * Props an adapter's close control receives.
 *
 * @public
 */
export interface SidePanelCloseProps {
  /** Accessible name for the control. */
  readonly label: string;
  /** Closes the panel. */
  readonly onClose: () => void;
}

/**
 * Adapter-owned rendering for {@link SidePanelChrome}.
 *
 * @public
 */
export interface SidePanelSlots {
  /** The docked frame around everything. */
  readonly Frame: (props: SidePanelFrameProps) => ReactNode;
  /** One tab in the strip. Omitted when there is only one panel. */
  readonly Tab: (props: SidePanelTabProps) => ReactNode;
  /** The control that closes the panel. */
  readonly Close: (props: SidePanelCloseProps) => ReactNode;
}

/**
 * What the side panel needs to render.
 *
 * @public
 */
export interface SidePanelChromeProps {
  /** The panels, in tab order. Rendering nothing when empty. */
  panels: readonly SidePanelEntry[];
  /** Which panel is showing. */
  openPanel: string;
  /** Show a different panel. */
  onOpenPanel: (key: string) => void;
  /** Close the panel entirely. */
  onClose: () => void;
  /** Which edge to dock to. Defaults to `"end"`. */
  side?: "start" | "end";
  /** Labels; falls back to the built-in English. */
  labels?: TableLabels;
  /** A unique id root, so two tables on a page do not collide. */
  idPrefix?: string;
  /** A kit's own class for the frame. */
  className?: string;
  /** Adapter-owned visible components. */
  slots: SidePanelSlots;
}

/**
 * Move the roving tab stop.
 *
 * Arrow keys wrap, Home and End jump to the ends — the pattern a `tablist`
 * is expected to follow, and the reason the tabs are not seven buttons.
 */
function nextIndex(key: string, at: number, count: number): number | undefined {
  if (key === "ArrowRight" || key === "ArrowDown") return (at + 1) % count;
  if (key === "ArrowLeft" || key === "ArrowUp") return (at - 1 + count) % count;
  if (key === "Home") return 0;
  if (key === "End") return count - 1;
  return undefined;
}

/**
 * Renders the side panel, or nothing when there are no panels to show.
 *
 * @param props - The panels, which one is open, and the kit's slots.
 * @returns The docked panel.
 *
 * @public
 */
export function SidePanelChrome(props: Readonly<SidePanelChromeProps>) {
  const { panels, openPanel, onOpenPanel, onClose, slots } = props;
  const tabsRef = useRef<HTMLDivElement | null>(null);
  const prefix = props.idPrefix ?? "adapttable-side-panel";
  const selectedIndex = Math.max(
    0,
    panels.findIndex((panel) => panel.key === openPanel)
  );
  const selected = panels[selectedIndex];

  // The keys are handled on the tabs rather than on the strip around them:
  // the tab is what has focus, and a `tablist` that listens for keys is a
  // container the user can never be inside of.
  const onKeyDown = useCallback(
    (event: KeyboardEvent<HTMLElement>) => {
      if (event.key === "Escape") {
        event.stopPropagation();
        onClose();
        return;
      }
      const to = nextIndex(event.key, selectedIndex, panels.length);
      if (to === undefined) return;
      const panel = panels[to];
      if (!panel) return;
      event.preventDefault();
      onOpenPanel(panel.key);
      // Focus follows selection in an automatic tablist, and the newly
      // selected tab is the only one still in the tab order.
      const id = CSS.escape(`${prefix}-tab-${panel.key}`);
      tabsRef.current?.querySelector<HTMLElement>(`#${id}`)?.focus();
    },
    [onClose, onOpenPanel, panels, prefix, selectedIndex]
  );

  if (panels.length === 0 || !selected) return null;

  const labels = props.labels;
  return (
    <slots.Frame side={props.side ?? "end"} className={props.className}>
      <div
        data-adapttable-part="side-panel-header"
        style={{ display: "flex", alignItems: "center", gap: 8 }}
      >
        {panels.length > 1 && (
          <div
            ref={tabsRef}
            role="tablist"
            aria-label={labels?.sidePanel ?? "Table settings"}
            data-adapttable-part="side-panel-tabs"
            style={{ display: "flex", flex: 1, gap: 4 }}
          >
            {panels.map((panel, index) => (
              <slots.Tab
                key={panel.key}
                panel={panel}
                selected={index === selectedIndex}
                buttonProps={{
                  id: `${prefix}-tab-${panel.key}`,
                  role: "tab",
                  type: "button",
                  tabIndex: index === selectedIndex ? 0 : -1,
                  "aria-selected": index === selectedIndex,
                  "aria-controls": `${prefix}-body`,
                  "data-adapttable-part": "side-panel-tab",
                  onClick: () => {
                    onOpenPanel(panel.key);
                  },
                  onKeyDown,
                }}
              />
            ))}
          </div>
        )}
        <slots.Close
          label={labels?.closePanel ?? "Close panel"}
          onClose={onClose}
        />
      </div>
      <div
        id={`${prefix}-body`}
        role={panels.length > 1 ? "tabpanel" : undefined}
        aria-labelledby={
          panels.length > 1 ? `${prefix}-tab-${selected.key}` : undefined
        }
        data-adapttable-part="side-panel-body"
        // A single-panel side panel has no tab to be labelled by, so it
        // names itself — otherwise the region is anonymous to a screen
        // reader the moment a host asks for only one panel.
        aria-label={panels.length > 1 ? undefined : selected.label}
        onKeyDown={(event) => {
          if (event.key !== "Escape") return;
          event.stopPropagation();
          onClose();
        }}
      >
        {selected.content}
      </div>
    </slots.Frame>
  );
}

/**
 * What {@link SidePanelLayout} arranges.
 *
 * @public
 */
export interface SidePanelLayoutProps {
  /** The table itself — everything the panel sits beside. */
  body: ReactNode;
  /** The rendered side panel, or nothing when none is open. */
  panel?: ReactNode;
  /** Which edge the panel is docked to. Defaults to `"end"`. */
  side?: "start" | "end";
}

/**
 * Put the table and its panel side by side.
 *
 * This is structure, not appearance — a flex row and a `min-width: 0` so the
 * table can still scroll horizontally inside it — which is why it lives in
 * core rather than in eight copies. Without a panel it renders the body
 * alone and adds no element at all, so a table that never asks for one has
 * exactly the DOM it always had.
 *
 * It exists as a component rather than as a ternary in each adapter for a
 * reason worth stating: the same "if the host asked for it, wrap; otherwise
 * do not" shape written eight times is eight chances to differ, and one
 * kit's copy already tripped a complexity limit when the status bar took
 * that form.
 *
 * @param props - The body, the panel, and which side it docks to.
 * @returns The arranged region.
 *
 * @public
 */
export function SidePanelLayout(props: Readonly<SidePanelLayoutProps>) {
  if (!props.panel) return <>{props.body}</>;
  return (
    <div
      data-adapttable-part="table-region"
      style={{
        display: "flex",
        gap: 12,
        alignItems: "flex-start",
        flexDirection: props.side === "start" ? "row-reverse" : "row",
      }}
    >
      {/* `min-width: 0` is what lets the table keep its own horizontal
          scrollbar instead of forcing the row wider than its container. */}
      <div
        data-adapttable-part="table-region-main"
        style={{ flex: 1, minWidth: 0 }}
      >
        {props.body}
      </div>
      {props.panel}
    </div>
  );
}

// packages/angular/angular/src/layout/sidePanelChrome.ts
/**
 * The side panel: a docked frame beside the table, and the row that holds it.
 *
 * The tabs are a real tablist. Arrows wrap, Home and End jump, and Escape
 * closes. The kit draws the frame, each tab and the close control. The
 * header, the strip and the body stay here so every kit shares them.
 */
import type { SidePanelPanel } from "@adapttable/angular/features";
import {
  DEFAULT_SIDE_PANEL_ID_PREFIX,
  handleSidePanelBodyKey,
  handleSidePanelTabKey,
  sidePanelModel,
  sidePanelTabId,
  type TableLabels,
} from "@adapttable/core";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  TemplateRef,
  type Type,
  viewChild,
} from "@angular/core";

import { AdaptControl } from "../control";

/**
 * The kit's controls for {@link AdaptSidePanelChrome}. Each is a standalone
 * component with one `props` input.
 *
 * @public
 */
export interface SidePanelSlots {
  /** The docked frame. It outlets the header and the body. */
  readonly Frame: Type<unknown>;
  /** One tab. Omitted from the strip when there is only one panel. */
  readonly Tab: Type<unknown>;
  /** The control that closes the panel. */
  readonly Close: Type<unknown>;
}

/**
 * Place a panel beside the table body.
 *
 * Absent a panel, the body is projected unchanged: the region exists only
 * while something is beside it.
 *
 * @public
 */
@Component({
  selector: "adapt-side-panel-layout",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-template #body><ng-content /></ng-template>
    @if (panel(); as docked) {
      <div
        data-adapttable-part="table-region"
        style="display: flex; gap: 12px; align-items: flex-start"
        [style.flex-direction]="side() === 'start' ? 'row-reverse' : 'row'"
      >
        <div
          data-adapttable-part="table-region-main"
          style="flex: 1; min-width: 0"
        >
          <ng-container [ngTemplateOutlet]="body" />
        </div>
        <ng-container [ngTemplateOutlet]="docked" />
      </div>
    } @else {
      <ng-container [ngTemplateOutlet]="body" />
    }
  `,
})
export class AdaptSidePanelLayout {
  /** The panel beside the body. Absent, the body stands alone. */
  readonly panel = input<TemplateRef<unknown>>();
  /** Which edge the panel sits on. */
  readonly side = input<"start" | "end">("end");
}

/**
 * Renders the side panel, or nothing when there is nothing to show.
 *
 * @public
 */
@Component({
  selector: "adapt-side-panel-chrome",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AdaptControl, NgTemplateOutlet],
  template: `
    @if (model(); as model) {
      <ng-template #header>
        <div
          data-adapttable-part="side-panel-header"
          style="display: flex; align-items: center; gap: 8px"
        >
          @if (model.tabbed) {
            <div
              role="tablist"
              data-adapttable-part="side-panel-tabs"
              [attr.aria-label]="model.tablistLabel"
              style="display: flex; flex: 1; gap: 4px"
            >
              @for (tab of tabProps(); track tab.buttonProps.id) {
                <ng-container
                  [adaptControl]="slots().Tab"
                  [adaptControlProps]="tab"
                />
              }
            </div>
          }
          <ng-container
            [adaptControl]="slots().Close"
            [adaptControlProps]="closeProps()"
          />
        </div>
      </ng-template>
      <ng-template #body>
        <div
          data-adapttable-part="side-panel-body"
          [id]="model.bodyId"
          [attr.role]="model.bodyRole"
          [attr.aria-labelledby]="model.bodyLabelledBy"
          [attr.aria-label]="model.bodyLabel"
          (keydown)="onBodyKey($event)"
        >
          @if (contentTemplate(); as tpl) {
            <ng-container [ngTemplateOutlet]="tpl" />
          } @else {
            {{ contentText() }}
          }
        </div>
      </ng-template>
      <ng-container
        [adaptControl]="slots().Frame"
        [adaptControlProps]="frameProps()"
      />
    }
  `,
})
export class AdaptSidePanelChrome {
  /** The panels, in tab order. Nothing renders when this is empty. */
  readonly panels = input.required<readonly SidePanelPanel[]>();
  /** Which panel is showing. */
  readonly openPanel = input.required<string>();
  /** Show a different panel. */
  readonly onOpenPanel = input.required<(key: string) => void>();
  /** Close the panel entirely. */
  readonly onClose = input.required<() => void>();
  /** Which edge to dock to. */
  readonly side = input<"start" | "end" | undefined>("end");
  /** Labels; gaps fall back to English. */
  readonly labels = input<TableLabels | undefined>(undefined);
  /** A unique id root, so two tables on a page do not collide. */
  readonly idPrefix = input<string | undefined>(undefined);
  /** A kit's own class for the frame. */
  readonly className = input<string | undefined>(undefined);
  /** The kit's frame, tabs and close control. */
  readonly slots = input.required<SidePanelSlots>();

  private readonly headerTpl = viewChild<TemplateRef<unknown>>("header");
  private readonly bodyTpl = viewChild<TemplateRef<unknown>>("body");

  /** The tab strip, the body and which panel is selected. */
  protected readonly model = computed(() =>
    sidePanelModel({
      panels: this.panels().map((panel) => ({
        ...panel,
        label: panel.label ?? panel.key,
      })),
      openPanel: this.openPanel(),
      idPrefix: this.idPrefix(),
      labels: this.labels(),
    })
  );

  /** The selected panel's template, when its content is one. */
  protected readonly contentTemplate = computed(() => {
    const content = this.model()?.selected.content;
    return content instanceof TemplateRef ? content : undefined;
  });

  /** The selected panel's text, when its content is not a template. */
  protected readonly contentText = computed(() => {
    const content = this.model()?.selected.content;
    return typeof content === "string" ? content : "";
  });

  /** Props for the kit's frame. */
  protected readonly frameProps = computed(() => ({
    side: this.side() ?? "end",
    className: this.className(),
    header: this.headerTpl(),
    body: this.bodyTpl(),
  }));

  /** Props for the kit's close control. Read only while a panel is showing. */
  protected readonly closeProps = computed(() => ({
    label: this.model()!.closeLabel,
    onClose: () => {
      this.onClose()();
    },
  }));

  /** Props for each kit tab. Stable until the strip or the handlers change. */
  protected readonly tabProps = computed(() =>
    this.model()!.tabs.map((tab) => this.tabBinding(tab))
  );

  /** Props for one kit tab. */
  private tabBinding(tab: {
    readonly panel: SidePanelPanel;
    readonly key: string;
    readonly id: string;
    readonly selected: boolean;
    readonly tabIndex: number;
    readonly controls: string;
  }): {
    readonly panel: SidePanelPanel;
    readonly selected: boolean;
    readonly buttonProps: {
      readonly id: string;
      readonly role: "tab";
      readonly type: "button";
      readonly tabIndex: number;
      readonly "aria-selected": boolean;
      readonly "aria-controls": string;
      readonly "data-adapttable-part": "side-panel-tab";
      readonly onClick: () => void;
      readonly onKeyDown: (event: KeyboardEvent) => void;
    };
  } {
    return {
      panel: tab.panel,
      selected: tab.selected,
      buttonProps: {
        id: tab.id,
        role: "tab",
        type: "button",
        tabIndex: tab.tabIndex,
        "aria-selected": tab.selected,
        "aria-controls": tab.controls,
        "data-adapttable-part": "side-panel-tab",
        onClick: () => {
          this.onOpenPanel()(tab.key);
        },
        onKeyDown: (event: KeyboardEvent) => {
          this.onTabKey(event);
        },
      },
    };
  }

  /** Escape closes. Arrows, Home and End move the selection, then focus. */
  private onTabKey(event: KeyboardEvent): void {
    const model = this.model()!;
    const key = handleSidePanelTabKey(event, {
      panels: this.panels(),
      selectedIndex: model.selectedIndex,
      onOpenPanel: (next) => {
        this.onOpenPanel()(next);
      },
      onClose: () => {
        this.onClose()();
      },
    });
    if (key === undefined) return;
    const prefix = this.idPrefix() ?? DEFAULT_SIDE_PANEL_ID_PREFIX;
    const id = CSS.escape(sidePanelTabId(prefix, key));
    const current = event.currentTarget;
    if (!(current instanceof Element)) return;
    current
      .closest('[data-adapttable-part="side-panel-tabs"]')
      ?.querySelector<HTMLElement>(`#${id}`)
      ?.focus();
  }

  /** Escape inside the body closes the panel and stops there. */
  protected onBodyKey(event: KeyboardEvent): void {
    handleSidePanelBodyKey(event, () => {
      this.onClose()();
    });
  }
}
