// packages/angular/angular/src/filters/headerFilterOverlay.ts
/**
 * One header filter's overlay session: which column is open, when a finished
 * write dismisses it, and what counts as a press outside it.
 *
 * Core owns the session. This wires that controller to signals, including a
 * shared open host for a kit that remounts its headers on every write.
 */
import {
  bindHeaderFilterDismiss,
  createHeaderFilterOverlay,
  type FilterDef,
  type FilterFormSource,
  type FilterTypeRegistry,
  headerFilterInsideSelector,
  type HeaderFilterOpenHost,
  isHeaderFilterOpen,
  watchOverlayDismiss,
} from "@adapttable/core";
import { computed, effect, inject, Injector, type Signal } from "@angular/core";

import { fromStore, type MaybeSignal, readMaybe } from "../store";

let nextSession = 0;

/** A fresh id that marks what counts as inside one header filter. */
function sessionId(): string {
  nextSession += 1;
  return `hf-${String(nextSession)}`;
}

/** The current value of an optional signal or plain value. */
function readOptional<T>(value: MaybeSignal<T> | undefined): T | undefined {
  if (value === undefined) return undefined;
  return readMaybe(value);
}

/**
 * Open state for one header filter, plus a source that can dismiss the
 * overlay after a finished single-control write.
 *
 * Call it from a component. The definition and the source may be inputs:
 * nothing is read until the overlay is. `closeOnSelect` stays off unless it
 * is true. An outside press or Escape dismisses it; a nested kit dropdown
 * named in `nestedSelector` does not. Pass `pointerDismiss: false` when the
 * kit closes the overlay itself.
 *
 * @param props - The column's definition, the filter source, and whether a
 *   finished write closes the overlay.
 * @param options - The shared open host, what else counts as inside, and
 *   whether a press outside dismisses.
 * @returns The open signal, the writer, the wrapped source, the session id
 *   and the reset key.
 *
 * @public
 */
export function injectHeaderFilterOverlay<TRow>(
  props: {
    readonly def: MaybeSignal<FilterDef<TRow>>;
    readonly source: MaybeSignal<FilterFormSource<TRow>>;
    readonly closeOnSelect?: MaybeSignal<boolean>;
    readonly registry?: MaybeSignal<FilterTypeRegistry>;
  },
  options?: {
    readonly nestedSelector?: MaybeSignal<string>;
    readonly pointerDismiss?: MaybeSignal<boolean>;
    readonly host?: MaybeSignal<HeaderFilterOpenHost | null>;
    readonly injector?: Injector;
  }
): {
  readonly open: Signal<boolean>;
  readonly setOpen: (open: boolean) => void;
  readonly source: Signal<FilterFormSource<TRow>>;
  readonly sessionId: string;
  readonly resetKey: Signal<number>;
} {
  const injector = options?.injector ?? inject(Injector);
  const id = sessionId();
  const controller = createHeaderFilterOverlay({ key: "" });
  const snapshot = fromStore(controller, { injector });

  const sync = (): HeaderFilterOpenHost | null => {
    const host = readOptional(options?.host) ?? null;
    controller.configure({ key: readMaybe(props.def).key, host });
    return host;
  };

  const open = computed(() => {
    const host = readOptional(options?.host) ?? null;
    return isHeaderFilterOpen(
      host,
      readMaybe(props.def).key,
      snapshot().localOpen
    );
  });

  const source = computed(() => {
    const def = readMaybe(props.def);
    sync();
    return bindHeaderFilterDismiss(readMaybe(props.source), {
      def,
      closeOnSelect: readOptional(props.closeOnSelect) === true,
      dismiss: controller.dismiss,
      registry: readOptional(props.registry),
    });
  });

  effect(
    (onCleanup) => {
      const host = sync();
      const watch = readOptional(options?.pointerDismiss) !== false;
      if (!watch || !open()) return;
      onCleanup(
        watchOverlayDismiss(
          document,
          headerFilterInsideSelector({
            sessionId: id,
            sharedHost: host != null,
            nestedSelector: readOptional(options?.nestedSelector),
          }),
          controller.dismiss
        )
      );
    },
    { injector }
  );

  return {
    open,
    setOpen: (next) => {
      sync();
      controller.setOpen(next);
    },
    source,
    sessionId: id,
    resetKey: computed(() => snapshot().resetKey),
  };
}

// packages/react/react/src/filters/headerFilterOverlay.ts
/**
 * Header-filter overlay session — the React binding.
 *
 * Core's overlay model owns the session: the overlay stays open while the
 * field is incomplete, ignores nested kit dropdowns as "outside", and
 * optionally dismisses once a complete value is written (`closeOnSelect`).
 * This module holds the shared open state in React context for kits whose
 * headers remount on writes, and wires the model to React.
 */
import {
  bindHeaderFilterDismiss as bindNeutralDismiss,
  createHeaderFilterOverlay,
  type FilterDef,
  type FilterTypeRegistry,
  HEADER_FILTER_SESSION_ATTR,
  headerFilterInsideSelector,
  type HeaderFilterOpenHost,
  isHeaderFilterOpen,
  watchOverlayDismiss,
} from "@adapttable/core";
import {
  createContext,
  createElement,
  type ReactNode,
  useContext,
  useEffect,
  useId,
  useMemo,
  useState,
  useSyncExternalStore,
} from "react";

import type { FilterFormSource } from "./filterForm";

export {
  headerFilterFieldIsComplete,
  type HeaderFilterOpenHost,
  HEADER_FILTER_SESSION_ATTR as SESSION_ATTR,
} from "@adapttable/core";

/**
 * Props that keep one header filter's overlay session together.
 *
 * @public
 */
export interface HeaderFilterSessionProps {
  /** Ties the trigger and its overlay to one editing session. */
  readonly [HEADER_FILTER_SESSION_ATTR]: string;
}

/**
 * Context filled by {@link HeaderFilterOpenProvider}.
 *
 * @public
 */
export const HeaderFilterOpenContext =
  createContext<HeaderFilterOpenHost | null>(null);

/**
 * Hold header-filter open state above kit headers that remount on writes.
 *
 * @public
 */
export function HeaderFilterOpenProvider({
  children,
}: {
  readonly children: ReactNode;
}): ReactNode {
  const [openKey, setOpenKey] = useState<string | null>(null);
  const value = useMemo(() => ({ openKey, setOpenKey }), [openKey]);
  return createElement(HeaderFilterOpenContext.Provider, { value }, children);
}

/**
 * Wrap a filter source so a complete write can dismiss the overlay.
 * Off unless `closeOnSelect` is true — the default is stay open.
 *
 * @public
 */
export function bindHeaderFilterDismiss<TRow>(
  source: FilterFormSource<TRow>,
  options: {
    def: FilterDef<TRow>;
    closeOnSelect?: boolean;
    dismiss: () => void;
    registry?: FilterTypeRegistry;
  }
): FilterFormSource<TRow> {
  return bindNeutralDismiss(source, options);
}

/**
 * Dismiss on a true outside press or Escape. Nested kit dropdowns (and a
 * focused native `<select>` whose OS list is open) are not outside.
 *
 * @public
 */
export function usePointerDismiss(
  open: boolean,
  dismiss: () => void,
  insideSelector: string
): void {
  useEffect(() => {
    if (!open) return undefined;
    return watchOverlayDismiss(document, insideSelector, dismiss);
  }, [open, dismiss, insideSelector]);
}

/**
 * Open state + a source that honours {@link bindHeaderFilterDismiss}.
 *
 * @public
 */
export function useHeaderFilterOverlay<TRow>(
  props: {
    source: FilterFormSource<TRow>;
    def: FilterDef<TRow>;
    closeOnSelect?: boolean;
    registry?: FilterTypeRegistry;
  },
  options?: {
    nestedSelector?: string;
    pointerDismiss?: boolean;
  }
): {
  open: boolean;
  setOpen: (open: boolean) => void;
  source: FilterFormSource<TRow>;
  sessionProps: HeaderFilterSessionProps;
  resetKey: number;
} {
  const rawId = useId();
  const id = rawId.replaceAll(":", "");
  const persistKey = props.def.key;
  const host = useContext(HeaderFilterOpenContext);
  const [controller] = useState(() =>
    createHeaderFilterOverlay({ key: persistKey, host })
  );
  controller.configure({ key: persistKey, host });
  const { localOpen, resetKey } = useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot
  );
  const open = isHeaderFilterOpen(host, persistKey, localOpen);
  const source = bindHeaderFilterDismiss(props.source, {
    def: props.def,
    closeOnSelect: props.closeOnSelect === true,
    dismiss: controller.dismiss,
    registry: props.registry,
  });
  usePointerDismiss(
    open && options?.pointerDismiss !== false,
    controller.dismiss,
    headerFilterInsideSelector({
      sessionId: id,
      sharedHost: host != null,
      nestedSelector: options?.nestedSelector,
    })
  );
  return {
    open,
    setOpen: controller.setOpen,
    source,
    sessionProps: { [HEADER_FILTER_SESSION_ATTR]: id },
    resetKey,
  };
}
