// packages/angular/angular/src/filters/filterHeaderRow.ts
/**
 * Compact per-column filter row under the header. Structure only — the kit
 * passes the search, select, range and multi controls the reader uses. The
 * same definitions and extra bag the panel uses.
 */
import {
  type BooleanChoice,
  booleanFilterWidget,
  defaultFilterRegistry,
  type FilterDef,
  filterDefForColumn,
  type FilterFormSource,
  type FilterOption,
  type FilterTypeRegistry,
  headerFilterBooleanOptions,
  headerFilterCellKind,
  headerFilterMultiModel,
  headerFilterRangeModel,
  headerFilterSelectModel,
  initialRangeFilterOp,
  initialTextFilterOp,
  rangeFilterWidget,
  renderRegisteredFilter,
  type TableLabels,
  textFilterWidget,
  type TextOp,
} from "@adapttable/core";
import type {
  FilterHeaderClassNames,
  FilterHeaderMultiProps,
  FilterHeaderRangeProps,
  FilterHeaderSearchProps,
  FilterHeaderSelectProps,
} from "@adapttable/core/binding";
import { NgComponentOutlet, NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  Injector,
  input,
  type OnInit,
  signal,
  TemplateRef,
  type Type,
} from "@angular/core";

import { resolveRenderer } from "../cell";
import { AdaptControl } from "../control";
import { AdaptColumnSpacer } from "../virtual/columnSpacer";
import { filterOptionsFor } from "./filters";

/**
 * The kit's controls for one header-filter cell. Each is a standalone
 * component with one `props` input: {@link FilterHeaderSearchProps},
 * {@link FilterHeaderSelectProps}, {@link FilterHeaderRangeProps} or
 * {@link FilterHeaderMultiProps}.
 *
 * @public
 */
export interface FilterHeaderSlots {
  /** A text search box. */
  readonly Search: Type<unknown>;
  /** A single-choice select, also used for a boolean. */
  readonly Select: Type<unknown>;
  /** One bound of a number or date range. */
  readonly Range: Type<unknown>;
  /** A compact multi-select menu. */
  readonly Multi: Type<unknown>;
}

/** Class names that are actually set, joined for a `class` attribute. */
function joinClass(
  ...names: readonly (string | undefined)[]
): string | undefined {
  const present = names.filter((name): name is string => Boolean(name));
  return present.length > 0 ? present.join(" ") : undefined;
}

/**
 * Compact control for one filter definition — one cell of the header row,
 * or a single column title.
 *
 * @public
 */
@Component({
  selector: "adapt-filter-header-control-chrome",
  imports: [AdaptControl, NgComponentOutlet, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let content = custom();
    @if (content.renderer?.template; as template) {
      <ng-container
        [ngTemplateOutlet]="template"
        [ngTemplateOutletContext]="content.context"
      />
    } @else if (content.renderer?.component; as component) {
      <ng-container
        [ngComponentOutlet]="component"
        [ngComponentOutletInputs]="content.renderer.inputs"
      />
    } @else if (content.text; as text) {
      {{ text }}
    } @else {
      @switch (kind()) {
        @case ("text") {
          <ng-container
            [adaptControl]="slots().Search"
            [adaptControlProps]="textProps()"
          />
        }
        @case ("select") {
          <ng-container
            [adaptControl]="slots().Select"
            [adaptControlProps]="selectProps()"
          />
        }
        @case ("boolean") {
          <ng-container
            [adaptControl]="slots().Select"
            [adaptControlProps]="booleanProps()"
          />
        }
        @case ("multi") {
          <ng-container
            [adaptControl]="slots().Multi"
            [adaptControlProps]="multiProps()"
          />
        }
        @case ("range") {
          <span
            data-adapttable-part="filter-header-input"
            [class]="className()"
          >
            <ng-container
              [adaptControl]="slots().Range"
              [adaptControlProps]="rangeLower()"
            />
            @if (rangeUpper(); as upper) {
              <ng-container
                [adaptControl]="slots().Range"
                [adaptControlProps]="upper"
              />
            }
          </span>
        }
      }
    }
  `,
})
export class AdaptFilterHeaderControlChrome<TRow> implements OnInit {
  /** The filter this control edits. */
  readonly def = input.required<FilterDef<TRow>>();
  /** Reads and writes the active filter values. */
  readonly source = input.required<FilterFormSource<TRow>>();
  /** Resolved labels, every key filled. */
  readonly labels = input.required<Required<TableLabels>>();
  /** The kit's controls for each filter shape. */
  readonly slots = input.required<FilterHeaderSlots>();
  /** Class for the control. */
  readonly className = input<string>();
  /** Class for a multi-select menu. */
  readonly menuClassName = input<string>();
  /** Custom filter types, beyond the built-ins. */
  readonly registry = input<FilterTypeRegistry>();

  /** Choices for a select or multi cell. Empty until `ngOnInit`. */
  protected readonly options = signal<readonly FilterOption[]>([]);

  private readonly injector = inject(Injector);
  private readonly textOp = signal<TextOp | undefined>(undefined);
  private readonly resolved = computed(
    () => this.registry() ?? defaultFilterRegistry
  );

  /** A host template, component, or text takes precedence over the kit widget. */
  protected readonly custom = computed(() => {
    const props = {
      def: this.def(),
      source: this.source(),
      labels: this.labels(),
      className: this.className(),
    };
    const value = renderRegisteredFilter(
      props.def,
      props.source,
      props.labels,
      this.resolved(),
      props.className
    );
    const context = { ...props, $implicit: props };
    let renderer: TemplateRef<typeof context> | Type<unknown> | undefined;
    if (value instanceof TemplateRef) {
      renderer = value;
    } else if (typeof value === "function" && "ɵcmp" in value) {
      renderer = value as unknown as Type<unknown>;
    }
    return {
      context,
      renderer: resolveRenderer(renderer, context),
      text:
        value && (typeof value === "string" || typeof value === "number")
          ? String(value)
          : null,
    };
  });

  /** Which built-in control this definition draws. */
  protected readonly kind = computed(() =>
    headerFilterCellKind(this.def(), this.resolved())
  );

  /** Props for a text search. */
  protected readonly textProps = computed((): FilterHeaderSearchProps => {
    const def = this.def();
    const source = this.source();
    const op = this.textOp() ?? initialTextFilterOp(def, source.extra);
    const widget = textFilterWidget(def, source, op, (next) => {
      this.textOp.set(next);
    });
    return {
      label: widget.label,
      placeholder: this.labels().search,
      value: widget.value,
      className: this.className(),
      onChange: (value) => widget.write(widget.op, value),
    };
  });

  /** Props for a single-choice select. */
  protected readonly selectProps = computed((): FilterHeaderSelectProps => {
    const model = headerFilterSelectModel(
      this.def(),
      this.source(),
      this.options(),
      this.labels()
    );
    return {
      label: model.label,
      value: model.value,
      options: model.options,
      className: this.className(),
      onChange: model.write,
    };
  });

  /** Props for a yes / no / any select. */
  protected readonly booleanProps = computed((): FilterHeaderSelectProps => {
    const widget = booleanFilterWidget(this.def(), this.source());
    return {
      label: widget.label,
      value: widget.choice,
      options: headerFilterBooleanOptions(this.labels()),
      className: this.className(),
      onChange: (value) => widget.write(value as BooleanChoice),
    };
  });

  /** Props for a compact multi-select menu. */
  protected readonly multiProps = computed((): FilterHeaderMultiProps => {
    const model = headerFilterMultiModel(
      this.def(),
      this.source(),
      this.options(),
      this.labels()
    );
    return {
      label: model.label,
      summary: model.summary,
      options: model.options,
      selected: model.selected,
      className: this.className(),
      menuClassName: this.menuClassName(),
      onToggle: model.toggle,
    };
  });

  private readonly range = computed(() => {
    const def = this.def();
    const source = this.source();
    const widget = rangeFilterWidget(
      def,
      source,
      initialRangeFilterOp(def, source.extra)
    );
    const model = headerFilterRangeModel(widget);
    const field = (
      value: string,
      onChange: (next: string) => void
    ): FilterHeaderRangeProps => ({
      label: widget.label,
      type: widget.inputType,
      value,
      onChange,
    });
    return {
      lower: field(widget.a, model.writeLower),
      upper: model.showUpper ? field(widget.b, model.writeUpper) : null,
    };
  });

  /** The lower bound, or the only bound. */
  protected readonly rangeLower = computed(() => this.range().lower);
  /** The upper bound, present only for a between pair. */
  protected readonly rangeUpper = computed(() => this.range().upper);

  /** Load the definition's choices once its input is bound. */
  ngOnInit(): void {
    const state = filterOptionsFor(this.def(), this.injector);
    this.options.set(state().options);
    effect(
      () => {
        this.options.set(state().options);
      },
      { injector: this.injector }
    );
  }
}

/**
 * Second header row of per-column quick filters. Pads and spacers match the
 * leaf header so sticky, pin offsets and column windowing stay aligned.
 * Renders nothing when the row is disabled or there is no definition.
 *
 * @public
 */
@Component({
  selector: "adapt-filter-header-chrome",
  imports: [AdaptColumnSpacer, AdaptFilterHeaderControlChrome],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (shown()) {
      <tr
        data-adapttable-part="filter-header-row"
        [attr.aria-label]="labels().headerFilters"
        [class]="rowClass()"
      >
        @if (expandable()) {
          <td
            data-adapttable-part="expand-header"
            [class]="padClass(classNames()?.expandHeader)"
            [attr.data-sticky]="stickyAttr() ? 'true' : null"
            [style]="padStyle()"
          ></td>
        }
        @if (showReorder()) {
          <td
            data-adapttable-part="reorder-header"
            [class]="padClass(classNames()?.reorderHeader)"
            [attr.data-sticky]="stickyAttr() ? 'true' : null"
            [style]="padStyle()"
          ></td>
        }
        @if (selection()) {
          <td
            data-adapttable-part="selection-header"
            [class]="padClass(classNames()?.selectionHeader)"
            [attr.data-sticky]="stickyAttr() ? 'true' : null"
            [style]="padStyle()"
          ></td>
        }
        @if (columnSpacers(); as spacers) {
          <adapt-column-spacer [width]="spacers.start" side="start" as="th" />
        }
        @for (column of columns(); track column.key) {
          <th
            data-adapttable-part="filter-header-cell"
            [attr.data-column-key]="column.key"
            [attr.data-sticky]="stickyAttr() ? 'true' : null"
            [attr.data-pinned]="pinned(column.key)"
            [class]="cellClass()"
            [style]="styled(column)"
          >
            @if (defFor(column.key); as def) {
              <adapt-filter-header-control-chrome
                [def]="def"
                [source]="source()"
                [labels]="labels()"
                [slots]="slots()"
                [className]="classNames()?.filterHeaderInput"
                [menuClassName]="classNames()?.filterHeaderMenu"
                [registry]="registry()"
              />
            }
          </th>
        }
        @if (columnSpacers(); as spacers) {
          <adapt-column-spacer [width]="spacers.end" side="end" as="th" />
        }
        @if (showActions()) {
          <td
            data-adapttable-part="actions-header"
            [class]="padClass(classNames()?.actionsHeader)"
            [attr.data-sticky]="stickyAttr() ? 'true' : null"
            [style]="padStyle()"
          ></td>
        }
      </tr>
    }
  `,
})
export class AdaptFilterHeaderChrome<TRow> {
  /** When false the row does not render, even if definitions exist. */
  readonly enabled = input(true);
  /** Visible columns, so each filter lands under its own header. */
  readonly columns = input.required<readonly { readonly key: string }[]>();
  /** Filter definitions to render. */
  readonly defs = input.required<readonly FilterDef<TRow>[]>();
  /** Reads and writes the active filter values. */
  readonly source = input.required<FilterFormSource<TRow>>();
  /** Resolved labels, every key filled. */
  readonly labels = input.required<Required<TableLabels>>();
  /** The kit's controls for each filter shape. */
  readonly slots = input.required<FilterHeaderSlots>();
  /** Custom filter types, beyond the built-ins. */
  readonly registry = input<FilterTypeRegistry>();
  /** Whether an expansion column is injected. */
  readonly expandable = input(false);
  /** Whether a reorder column is injected. */
  readonly showReorder = input(false);
  /** Whether a selection column is injected. */
  readonly selection = input(false);
  /** Whether an actions column is injected. */
  readonly showActions = input(false);
  /** Widths standing in for columns outside the window. */
  readonly columnSpacers = input<{
    readonly start: number;
    readonly end: number;
  }>();
  /** Width and sticky offsets for a column's filter cell. */
  readonly cellStyle =
    input<
      (column: {
        readonly key: string;
      }) => Readonly<Record<string, string>> | undefined
    >();
  /** Edge a column is pinned to, absent when it floats. */
  readonly pinSide = input<(key: string) => "start" | "end" | undefined>();
  /** Style for the spacer cells at either end. */
  readonly padStyle = input<Readonly<Record<string, string>>>();
  /** Present only when the row sticks, for styling hooks. */
  readonly stickyAttr = input<true>();
  /** Per-part classes for the row. */
  readonly classNames = input<FilterHeaderClassNames>();

  /** The row is drawn only when it is enabled and has a definition. */
  protected readonly shown = computed(
    () => this.enabled() && this.defs().length > 0
  );

  /** Class for the row. */
  protected rowClass(): string | undefined {
    return this.classNames()?.filterHeaderRow;
  }

  /** Class for one filter cell. */
  protected cellClass(): string | undefined {
    return joinClass(
      this.classNames()?.headerCell,
      this.classNames()?.filterHeaderCell
    );
  }

  /** Class for a pad, sharing the header-cell class. */
  protected padClass(extra: string | undefined): string | undefined {
    return joinClass(this.classNames()?.headerCell, extra);
  }

  /** The definition under this column, if the column is filterable. */
  protected defFor(key: string): FilterDef<TRow> | undefined {
    return filterDefForColumn(this.defs(), key);
  }

  /** Pin edge for a column key. */
  protected pinned(key: string): "start" | "end" | undefined {
    return this.pinSide()?.(key);
  }

  /** Inline style for one filter cell. */
  protected styled(column: {
    readonly key: string;
  }): Readonly<Record<string, string>> | undefined {
    return this.cellStyle()?.(column);
  }
}

// packages/react/src/filters/FilterHeaderRow.tsx
/**
 * Compact per-column filter row under the header. Structure only —
 * adapters pass the Search, Select, range inputs and multi menu the
 * end user clicks. Same defs and extra bag the panel uses (#282).
 */
import {
  defaultFilterRegistry,
  type FilterDef,
  filterLabel,
  filterStateKeys,
  type FilterTypeRegistry,
  renderRegisteredFilter,
  type TableLabels,
} from "@adapttable/core";
import type { CSSProperties, ReactElement, ReactNode } from "react";

import type { ColumnDef } from "../columnDef";
import { ColumnSpacer } from "../virtual/ColumnSpacer";
import {
  type FilterFormSource,
  listFilterValues,
  useBooleanFilterWidget,
  useRangeFilterWidget,
  useTextFilterWidget,
} from "./filterForm";
import { useFilterOptions } from "./useFilterOptions";

export type { FilterFormSource, FilterTypeRegistry };

/**
 * Class hooks the unstyled adapter maps onto `DataTableClassNames`.
 *
 * @public
 */
export interface FilterHeaderClassNames {
  /** Class for the filter row. */
  filterHeaderRow?: string;
  /** Class for one filter cell. */
  filterHeaderCell?: string;
  /** Class for the control inside a filter cell. */
  filterHeaderInput?: string;
  /** Class for a filter cell's popover. */
  filterHeaderMenu?: string;
  /** Class shared with the ordinary header cells. */
  headerCell?: string;
  /** Class for the expansion column's header cell. */
  expandHeader?: string;
  /** Class for the reorder column's header cell. */
  reorderHeader?: string;
  /** Class for the selection column's header cell. */
  selectionHeader?: string;
  /** Class for the actions column's header cell. */
  actionsHeader?: string;
}

/**
 * Overlay a sticky `top` on a cell or pad style.
 *
 * @public
 */
export function headerFilterStickTop(
  sticky: boolean,
  base: CSSProperties | undefined,
  top: number,
  stickyExtras?: CSSProperties
): CSSProperties | undefined {
  if (!sticky) return base;
  return { ...stickyExtras, ...base, top };
}

/**
 * Props for an adapter `FilterHeaderRow` — no slots on the public API.
 *
 * @public
 */
export interface FilterHeaderRowProps<TRow> {
  /** When false the row does not render, even if defs exist. */
  readonly enabled?: boolean;
  /** Visible columns, so each filter lands under its own header. */
  readonly columns: readonly ColumnDef<TRow>[];
  /** Filter definitions to render. */
  readonly defs: readonly FilterDef<TRow>[];
  /** Reads and writes the active filter values. */
  readonly source: FilterFormSource<TRow>;
  /** Custom filter types, beyond the built-ins. */
  readonly registry?: FilterTypeRegistry;
  /** Resolved labels, every key filled. */
  readonly labels: Required<TableLabels>;
  /** Whether an expansion column is injected. */
  readonly expandable?: boolean;
  /** Whether a reorder column is injected. */
  readonly showReorder?: boolean;
  /** Whether a selection column is injected. */
  readonly selection?: boolean;
  /** Whether an actions column is injected. */
  readonly showActions?: boolean;
  /** Widths standing in for columns outside the window. */
  readonly columnSpacers?: { start: number; end: number };
  /** Width and sticky offsets for a column's filter cell. */
  readonly cellStyle?: (column: ColumnDef<TRow>) => CSSProperties | undefined;
  /** Edge a column is pinned to, absent when it floats. */
  readonly pinSide?: (key: string) => "start" | "end" | undefined;
  /** Style for the spacer cells at either end. */
  readonly padStyle?: CSSProperties;
  /** Present only when the row sticks, for styling hooks. */
  readonly stickyAttr?: true;
  /** Per-part classes for the row. */
  readonly classNames?: FilterHeaderClassNames;
}

/**
 * Props for an adapter `FilterHeaderControl` — no slots on the public API.
 *
 * @public
 */
export interface FilterHeaderControlProps<TRow> {
  /** The filter this control edits. */
  readonly def: FilterDef<TRow>;
  /** Reads and writes the active filter values. */
  readonly source: FilterFormSource<TRow>;
  /** Resolved labels, every key filled. */
  readonly labels: Required<TableLabels>;
  /** Class for the control. */
  readonly className?: string;
  /** Custom filter types, beyond the built-ins. */
  readonly registry?: FilterTypeRegistry;
  /**
   * Dismiss the overlay after a finished single-control write. Default off.
   * Wired from the table's `closeHeaderFilterOnSelect`.
   */
  readonly closeOnSelect?: boolean;
}

/**
 * Whether a header filter holds a value worth marking its column with.
 *
 * The emptiness rules are the whole point, and they are not obvious: a cleared
 * text field leaves `""`, a cleared multi-select leaves `[]`, and a control
 * nobody touched leaves `undefined`. None of those is a filter. A funnel that
 * lights up for one is worse than no funnel at all, because a reader who trusts
 * it goes looking for a filter that is not there.
 *
 * Every adapter drew this conclusion for itself with a byte-identical copy of
 * these six lines; it belongs here, where it can be wrong in one place only.
 *
 * @public
 */
export function hasActiveHeaderFilter<TRow>(
  props: Readonly<
    Pick<FilterHeaderControlProps<TRow>, "def" | "source" | "registry">
  >
): boolean {
  return filterStateKeys(
    props.def,
    props.registry ?? defaultFilterRegistry
  ).some((key) => {
    const value = props.source.extra[key];
    if (value == null || value === "") return false;
    return !(Array.isArray(value) && value.length === 0);
  });
}

/**
 * One option in a header Select or multi menu.
 *
 * @public
 */
export interface FilterHeaderOption {
  /** Value stored when this option is chosen. */
  readonly value: string;
  /** Caption shown for the option. */
  readonly label: string;
}

/**
 * Kit search field a text header cell calls.
 *
 * @public
 */
export interface FilterHeaderSearchProps {
  /** Accessible name for the box. */
  readonly label: string;
  /** Placeholder text. */
  readonly placeholder: string;
  /** Current text. */
  readonly value: string;
  /** Class for the box. */
  readonly className?: string;
  /** Called with the new text on every keystroke. */
  readonly onChange: (value: string) => void;
}

/**
 * Kit Select a select/boolean header cell calls.
 *
 * @public
 */
export interface FilterHeaderSelectProps {
  /** Accessible name for the select. */
  readonly label: string;
  /** Currently chosen value. */
  readonly value: string;
  /** Choices to offer. */
  readonly options: readonly FilterHeaderOption[];
  /** Class for the select. */
  readonly className?: string;
  /** Called with the chosen value. */
  readonly onChange: (value: string) => void;
}

/**
 * Kit number/date field a range header cell calls.
 *
 * @public
 */
export interface FilterHeaderRangeProps {
  /** Accessible name for the field. */
  readonly label: string;
  /** Which input type the bound is edited with. */
  readonly type: "text" | "number" | "date";
  /** Current bound, as text. */
  readonly value: string;
  /** Called with the new bound. */
  readonly onChange: (value: string) => void;
}

/**
 * Kit compact multi menu a checklist/multiSelect header cell calls.
 *
 * @public
 */
export interface FilterHeaderMultiProps {
  /** Accessible name for the trigger. */
  readonly label: string;
  /** What the trigger shows for the current selection. */
  readonly summary: string;
  /** Choices to offer. */
  readonly options: readonly FilterHeaderOption[];
  /** Values currently checked. */
  readonly selected: readonly string[];
  /** Class for the trigger. */
  readonly className?: string;
  /** Class for the popover. */
  readonly menuClassName?: string;
  /** Called with a value and its new checked state. */
  readonly onToggle: (value: string, checked: boolean) => void;
}

/**
 * Adapter-supplied controls for {@link FilterHeaderChrome}.
 *
 * @public
 */
export interface FilterHeaderSlots {
  /** Renders a free-text filter. */
  readonly Search: (props: FilterHeaderSearchProps) => ReactNode;
  /** Renders a single-choice filter. */
  readonly Select: (props: FilterHeaderSelectProps) => ReactNode;
  /** Renders one bound of a range filter. */
  readonly Range: (props: FilterHeaderRangeProps) => ReactNode;
  /** Renders a multi-choice filter behind a popover. */
  readonly Multi: (props: FilterHeaderMultiProps) => ReactNode;
}

/**
 * Props for {@link FilterHeaderChrome}.
 *
 * @public
 */
export interface FilterHeaderChromeProps<
  TRow,
> extends FilterHeaderRowProps<TRow> {
  /** The kit's controls for each filter shape. */
  readonly slots: FilterHeaderSlots;
}

/**
 * Props for {@link FilterHeaderControlChrome}.
 *
 * @public
 */
export interface FilterHeaderControlChromeProps<
  TRow,
> extends FilterHeaderControlProps<TRow> {
  /** The kit's controls for each filter shape. */
  readonly slots: FilterHeaderSlots;
}

/**
 * The definition that drives a column's header filter, if any.
 *
 * @public
 */
export function filterDefForColumn<TRow>(
  defs: readonly FilterDef<TRow>[],
  key: string
): FilterDef<TRow> | undefined {
  return defs.find((def) => (def.column ?? def.key) === key);
}

function Pad({
  part,
  style,
  stickyAttr,
  className,
}: Readonly<{
  part: string;
  style?: CSSProperties;
  stickyAttr?: true;
  className?: string;
}>): ReactElement {
  return (
    <td
      data-adapttable-part={part}
      data-sticky={stickyAttr}
      style={style}
      className={className}
    />
  );
}

function TextCell<TRow>({
  def,
  source,
  labels,
  className,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  className?: string;
  slots: FilterHeaderSlots;
}>): ReactElement {
  const widget = useTextFilterWidget(def, source);
  const Search = slots.Search;
  return (
    <Search
      label={widget.label}
      placeholder={labels.search}
      value={widget.value}
      className={className}
      onChange={(value) => widget.write(widget.op, value)}
    />
  );
}

function SelectCell<TRow>({
  def,
  source,
  labels,
  className,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  className?: string;
  slots: FilterHeaderSlots;
}>): ReactElement {
  const { options } = useFilterOptions(def);
  const selected = listFilterValues(source.extra[def.key]);
  const write = (values: readonly string[]) => {
    source.setExtra(def.key, values.length > 0 ? [...values] : undefined);
  };
  const Select = slots.Select;
  return (
    <Select
      label={filterLabel(def)}
      value={selected[0] ?? ""}
      className={className}
      options={[
        { value: "", label: labels.boolAny },
        ...options.map((option) => ({
          value: option.value,
          label: option.label,
        })),
      ]}
      onChange={(value) => {
        write(value === "" ? [] : [value]);
      }}
    />
  );
}

function CompactMultiCell<TRow>({
  def,
  source,
  labels,
  className,
  menuClassName,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  className?: string;
  menuClassName?: string;
  slots: FilterHeaderSlots;
}>): ReactElement {
  const { options } = useFilterOptions(def);
  const selected = listFilterValues(source.extra[def.key]);
  const write = (values: readonly string[]) => {
    source.setExtra(def.key, values.length > 0 ? [...values] : undefined);
  };
  const first = options.find((option) => option.value === selected[0]);
  let summary = labels.boolAny;
  if (selected.length === 1) summary = first?.label ?? selected[0] ?? summary;
  if (selected.length > 1) summary = labels.groupCount(selected.length);
  const Multi = slots.Multi;
  return (
    <Multi
      label={filterLabel(def)}
      summary={summary}
      options={options.map((option) => ({
        value: option.value,
        label: option.label,
      }))}
      selected={selected}
      className={className}
      menuClassName={menuClassName}
      onToggle={(value, checked) => {
        write(
          checked
            ? [...selected, value]
            : selected.filter((item) => item !== value)
        );
      }}
    />
  );
}

function BooleanCell<TRow>({
  def,
  source,
  labels,
  className,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  className?: string;
  slots: FilterHeaderSlots;
}>): ReactElement {
  const widget = useBooleanFilterWidget(def, source);
  const Select = slots.Select;
  return (
    <Select
      label={widget.label}
      value={widget.choice}
      className={className}
      options={[
        { value: "", label: labels.boolAny },
        { value: "true", label: labels.boolTrue },
        { value: "false", label: labels.boolFalse },
      ]}
      onChange={(value) => widget.write(value as typeof widget.choice)}
    />
  );
}

function RangeCell<TRow>({
  def,
  source,
  className,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  className?: string;
  slots: FilterHeaderSlots;
}>): ReactElement {
  const widget = useRangeFilterWidget(def, source);
  // Compact header has no operator picker. An unset op would wipe the
  // value on write; `gte` is the same inference a lone lower bound uses.
  const op = widget.op ?? "gte";
  const Range = slots.Range;
  return (
    <span data-adapttable-part="filter-header-input" className={className}>
      <Range
        label={widget.label}
        type={widget.inputType}
        value={widget.a}
        onChange={(value) => widget.write(op, value, widget.b)}
      />
      {widget.arity === "two" ? (
        <Range
          label={widget.label}
          type={widget.inputType}
          value={widget.b}
          onChange={(value) => widget.write(op, widget.a, value)}
        />
      ) : null}
    </span>
  );
}

function FilterHeaderCell<TRow>({
  def,
  source,
  labels,
  className,
  menuClassName,
  registry = defaultFilterRegistry,
  slots,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  className?: string;
  menuClassName?: string;
  registry?: FilterTypeRegistry;
  slots: FilterHeaderSlots;
}>): ReactElement | null {
  const spec = registry.get(def.type);
  const custom = renderRegisteredFilter(
    def,
    source,
    labels,
    registry,
    className
  );
  if (custom) return custom as ReactElement;
  switch (spec?.widget ?? def.type) {
    case "text":
      return (
        <TextCell
          def={def}
          source={source}
          labels={labels}
          className={className}
          slots={slots}
        />
      );
    case "select":
      return (
        <SelectCell
          def={def}
          source={source}
          labels={labels}
          className={className}
          slots={slots}
        />
      );
    case "multiSelect":
    case "checklist":
      return (
        <CompactMultiCell
          def={def}
          source={source}
          labels={labels}
          className={className}
          menuClassName={menuClassName}
          slots={slots}
        />
      );
    case "boolean":
      return (
        <BooleanCell
          def={def}
          source={source}
          labels={labels}
          className={className}
          slots={slots}
        />
      );
    case "numberRange":
    case "dateRange":
      return (
        <RangeCell
          def={def}
          source={source}
          className={className}
          slots={slots}
        />
      );
    default:
      return null;
  }
}

/**
 * Compact control for one filter definition — used in the header row and antd titles.
 *
 * @public
 */
export function FilterHeaderControlChrome<TRow>({
  def,
  source,
  labels,
  className,
  registry = defaultFilterRegistry,
  slots,
}: Readonly<FilterHeaderControlChromeProps<TRow>>): ReactElement {
  return (
    <FilterHeaderCell
      def={def}
      source={source}
      labels={labels}
      className={className}
      registry={registry}
      slots={slots}
    />
  );
}

/**
 * Second header row of per-column quick filters. Pads and spacers match
 * the leaf header so sticky, pin offsets, and column windowing stay aligned.
 *
 * @public
 */
export function FilterHeaderChrome<TRow>({
  enabled = true,
  columns,
  defs,
  source,
  labels,
  expandable = false,
  showReorder = false,
  selection = false,
  showActions = false,
  columnSpacers,
  cellStyle,
  pinSide,
  padStyle,
  stickyAttr,
  classNames = {},
  registry = defaultFilterRegistry,
  slots,
}: Readonly<FilterHeaderChromeProps<TRow>>): ReactElement | null {
  if (!enabled || defs.length === 0) return null;
  const pad = (part: string, extra?: string) => (
    <Pad
      part={part}
      style={padStyle}
      stickyAttr={stickyAttr}
      className={[classNames.headerCell, extra].filter(Boolean).join(" ")}
    />
  );
  return (
    <tr
      data-adapttable-part="filter-header-row"
      className={classNames.filterHeaderRow}
      aria-label={labels.headerFilters}
    >
      {expandable ? pad("expand-header", classNames.expandHeader) : null}
      {showReorder ? pad("reorder-header", classNames.reorderHeader) : null}
      {selection ? pad("selection-header", classNames.selectionHeader) : null}
      {columnSpacers ? (
        <ColumnSpacer width={columnSpacers.start} side="start" as="th" />
      ) : null}
      {columns.map((column) => {
        const def = filterDefForColumn(defs, column.key);
        return (
          <th
            key={column.key}
            data-adapttable-part="filter-header-cell"
            data-sticky={stickyAttr}
            data-pinned={pinSide?.(column.key)}
            style={cellStyle?.(column)}
            className={
              [classNames.headerCell, classNames.filterHeaderCell]
                .filter(Boolean)
                .join(" ") || undefined
            }
            data-column-key={column.key}
          >
            {def ? (
              <FilterHeaderCell
                def={def}
                source={source}
                labels={labels}
                className={classNames.filterHeaderInput}
                menuClassName={classNames.filterHeaderMenu}
                registry={registry}
                slots={slots}
              />
            ) : null}
          </th>
        );
      })}
      {columnSpacers ? (
        <ColumnSpacer width={columnSpacers.end} side="end" as="th" />
      ) : null}
      {showActions ? pad("actions-header", classNames.actionsHeader) : null}
    </tr>
  );
}
