// packages/angular/angular/src/editing/rowEditGate.ts
/**
 * A cell inside a row that is being edited as one unit, and the controls that
 * end that edit — plus the same for a batch of pending edits.
 *
 * Row and batch modes reuse the kit's cell editor, the same validation ARIA
 * and the same conflict notice as a single cell; only where the draft lives
 * and when it reaches the host differ.
 */
import {
  batchEditBarModel,
  batchEditErrorId,
  type CellConflictAsk,
  editorSelectOptions,
  handleRowEditorKey,
  resolveCellEditor,
  rowEditActionsLayout,
  rowEditControls,
  rowEditErrorId,
  rowEditSaveBlocked,
  type TableLabels,
} from "@adapttable/core";
import type {
  BatchEditButtonProps,
  RowEditButtonProps,
  RowEditIcons,
} from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import type { ColumnDef } from "../columnDef";
import { AdaptControl } from "../control";
import {
  type EditableCellEditing,
  focusEditorOnMount,
} from "./editableCellController";
import {
  AdaptCellConflictNotice,
  AdaptEditableCellDisplay,
  type EditableCellEditorCtrl,
  type EditableCellSlots,
} from "./editableCellShared";
import type { BatchEditingState, RowEditingState } from "./editing";

export type { EditableCellEditorCtrl } from "./editableCellShared";
export type { BatchEditingState, RowEditingState } from "./editing";
export type { EditableColumnLike, TableLabels } from "@adapttable/core";
export {
  type RowEditConflict,
  type RowEditControls,
  rowEditControls,
  type RowEditControlsOptions,
} from "@adapttable/core";
export type {
  BatchEditBarProps,
  BatchEditButtonProps,
  RowEditActionsProps,
  RowEditButtonProps,
  RowEditIcons,
} from "@adapttable/core/binding";

/**
 * Kit-supplied controls for {@link AdaptRowEditActionsChrome}.
 *
 * @public
 */
export interface RowEditActionsSlots {
  /** Renders a button. */
  readonly Button: Type<unknown>;
}

/**
 * Kit-supplied controls for {@link AdaptBatchEditBarChrome}.
 *
 * @public
 */
export interface BatchEditBarSlots {
  /** Renders a button. */
  readonly Button: Type<unknown>;
}

/**
 * The row's edit / save / cancel controls.
 *
 * @public
 */
@Component({
  selector: "adapt-row-edit-actions-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let layout = actionsLayout();
    @if (layout.kind === "begin") {
      <ng-container
        [adaptControl]="slots().Button"
        [adaptControlProps]="beginProps()"
      />
    } @else if (layout.kind === "open") {
      <span
        data-adapttable-part="row-edit-actions"
        [class]="className()"
        style="display: inline-flex; gap: 4px"
      >
        @if (layout.showSave) {
          <ng-container
            [adaptControl]="slots().Button"
            [adaptControlProps]="saveProps()"
          />
        }
        <ng-container
          [adaptControl]="slots().Button"
          [adaptControlProps]="cancelProps()"
        />
      </span>
    }
  `,
})
export class AdaptRowEditActionsChrome<TRow> {
  /** The row-editing state. */
  readonly rowEditing = input.required<RowEditingState<TRow>>();
  /** The row these controls belong to. */
  readonly row = input.required<TRow>();
  /** Its stable id. */
  readonly rowId = input.required<string>();
  /** Labels for the controls. */
  readonly labels = input<Partial<TableLabels>>();
  /** Class for the open-row group. */
  readonly className = input<string>();
  /** Class for each button. */
  readonly buttonClassName = input<string>();
  /** Optional glyphs for begin / save / cancel. */
  readonly icons = input<RowEditIcons>();
  /** Whether this row is waiting on a conflict answer. */
  readonly conflict = input<{ asking: boolean } | undefined>();
  /**
   * Whether to draw the begin control. False when a host action owns the
   * trigger and the row is closed.
   */
  readonly showBegin = input<boolean>(true);
  /** The kit's components for each part. */
  readonly slots = input.required<RowEditActionsSlots>();

  private readonly controls = computed(() =>
    rowEditControls({
      rowEditing: this.rowEditing(),
      row: this.row(),
      rowId: this.rowId(),
      labels: this.labels(),
    })
  );

  protected readonly actionsLayout = computed(() =>
    rowEditActionsLayout(this.controls(), this.conflict(), this.showBegin())
  );

  protected readonly beginProps = computed((): RowEditButtonProps => {
    const controls = this.controls();
    const icons = this.icons();
    return {
      label: controls.editLabel,
      part: "row-edit-begin",
      icon: icons?.begin,
      className: this.buttonClassName(),
      onClick: (event: { stopPropagation: () => void }) => {
        event.stopPropagation();
        controls.begin();
      },
    };
  });

  protected readonly saveProps = computed((): RowEditButtonProps => {
    const controls = this.controls();
    const icons = this.icons();
    return {
      label: controls.saveLabel,
      part: "row-edit-save",
      icon: icons?.save,
      className: this.buttonClassName(),
      onClick: (event: { stopPropagation: () => void }) => {
        event.stopPropagation();
        controls.save();
      },
    };
  });

  protected readonly cancelProps = computed((): RowEditButtonProps => {
    const controls = this.controls();
    const icons = this.icons();
    return {
      label: controls.cancelLabel,
      part: "row-edit-cancel",
      icon: icons?.cancel,
      className: this.buttonClassName(),
      onClick: (event: { stopPropagation: () => void }) => {
        event.stopPropagation();
        controls.cancel();
      },
    };
  });
}

/**
 * The bar that ends a batch: how many rows are waiting, save all, cancel all.
 *
 * @public
 */
@Component({
  selector: "adapt-batch-edit-bar-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (model(); as m) {
      <div
        data-adapttable-part="batch-edit-bar"
        [class]="className()"
        style="display: flex; align-items: center; gap: 0.5em"
      >
        <output data-adapttable-part="batch-edit-count">{{ m.count }}</output>
        @if (m.conflictMessage !== undefined) {
          <output data-adapttable-part="batch-edit-conflict">{{
            m.conflictMessage
          }}</output>
        } @else {
          <ng-container
            [adaptControl]="slots().Button"
            [adaptControlProps]="saveProps()"
          />
        }
        <ng-container
          [adaptControl]="slots().Button"
          [adaptControlProps]="cancelProps()"
        />
      </div>
    }
  `,
})
export class AdaptBatchEditBarChrome<TRow> {
  /** The batch state. */
  readonly batch = input.required<BatchEditingState<TRow>>();
  /** Whether any pending row is waiting on a conflict answer. */
  readonly contested = input(false);
  /** Labels for the bar. */
  readonly labels = input<Partial<TableLabels>>();
  /** Class for the bar. */
  readonly className = input<string>();
  /** Class for each button. */
  readonly buttonClassName = input<string>();
  /** The kit's components for each part. */
  readonly slots = input.required<BatchEditBarSlots>();

  protected readonly model = computed(() =>
    batchEditBarModel(this.batch(), this.contested(), this.labels())
  );

  protected readonly saveProps = computed((): BatchEditButtonProps => {
    const model = this.model()!;
    return {
      label: model.saveLabel,
      part: "batch-edit-save",
      className: this.buttonClassName(),
      onClick: () => {
        this.batch().saveAll();
      },
    };
  });

  protected readonly cancelProps = computed((): BatchEditButtonProps => {
    const model = this.model()!;
    return {
      label: model.cancelLabel,
      part: "batch-edit-cancel",
      className: this.buttonClassName(),
      onClick: () => {
        this.batch().cancelAll();
      },
    };
  });
}

/**
 * One cell of a row being edited: the kit's editor bound to the row's draft,
 * or the plain display when the column is not editable.
 *
 * @public
 */
@Component({
  selector: "adapt-row-edit-cell",
  imports: [AdaptControl, AdaptCellConflictNotice, AdaptEditableCellDisplay],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (hasEditor()) {
      <ng-container
        [adaptControl]="editor()"
        [adaptControlProps]="editorCtrl()"
      />
      @if (ask(); as currentAsk) {
        @if (conflictLabels(); as labels) {
          @if (slots(); as cellSlots) {
            <adapt-cell-conflict-notice
              [ask]="currentAsk"
              [labels]="labels"
              [errorId]="errorId()"
              [errorClassName]="errorClassName()"
              [slots]="cellSlots"
            />
          }
        }
      }
    } @else {
      <adapt-editable-cell-display [props]="display()" />
    }
  `,
})
export class AdaptRowEditCell<TRow> {
  /** The row-editing state from the chrome. */
  readonly rowEditing = input.required<RowEditingState<TRow>>();
  /** The column this cell belongs to. */
  readonly column = input.required<ColumnDef<TRow>>();
  /** The cell's display content, for a column that is not editable. */
  readonly display = input.required<unknown>();
  /** Accessible name for the editor. */
  readonly editLabel = input.required<string>();
  /**
   * Whether this is the first editable column — the field that takes focus
   * when the row opens.
   */
  readonly takesFocus = input.required<boolean>();
  /** Kit editor component — receives {@link EditableCellEditorCtrl}. */
  readonly editor = input.required<Type<unknown>>();
  /** The incoming value waiting on this field, when one is asking. */
  readonly ask = input<CellConflictAsk>();
  /** Whether any field of this row is waiting on an answer. */
  readonly rowAsking = input<boolean>();
  /** Labels for the notice — already resolved. */
  readonly conflictLabels =
    input<NonNullable<EditableCellEditing<never>["conflictLabels"]>>();
  /** Class for the notice. */
  readonly errorClassName = input<string>();
  /** The kit's components, for the notice's buttons. */
  readonly slots = input<EditableCellSlots>();

  protected readonly resolved = computed(() =>
    resolveCellEditor(this.column(), this.rowEditing().featureHost)
  );

  protected readonly hasEditor = computed(() => Boolean(this.resolved()));

  protected readonly errorId = computed(() =>
    rowEditErrorId(this.column().key)
  );

  protected readonly editorCtrl = computed((): EditableCellEditorCtrl => {
    const rowEditing = this.rowEditing();
    const column = this.column();
    const editor = this.resolved()!;
    const ask = this.ask();
    const saveBlocked = rowEditSaveBlocked(ask, this.rowAsking());
    return {
      draft: rowEditing.draftFor(column.key),
      setDraft: (value) => {
        rowEditing.setDraft(column.key, value);
      },
      onEditorKeyDown: (event) => {
        handleRowEditorKey(event, rowEditing, saveBlocked);
      },
      commitOnBlur: () => undefined,
      editor,
      selectOptions: editorSelectOptions(editor),
      label: this.editLabel(),
      validating: false,
      conflict: ask !== undefined,
      errorId: this.errorId(),
      focusRef: this.takesFocus() ? focusEditorOnMount : () => undefined,
    };
  });
}

/**
 * One cell while a batch is being edited: always a field, never an activate
 * control.
 *
 * @public
 */
@Component({
  selector: "adapt-batch-edit-cell",
  imports: [AdaptControl, AdaptCellConflictNotice, AdaptEditableCellDisplay],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (hasEditor()) {
      <span
        data-adapttable-part="batch-edit-cell"
        [attr.data-changed]="changed() ? '' : null"
      >
        <ng-container
          [adaptControl]="editor()"
          [adaptControlProps]="editorCtrl()"
        />
        @if (ask(); as currentAsk) {
          @if (conflictLabels(); as labels) {
            @if (slots(); as cellSlots) {
              <adapt-cell-conflict-notice
                [ask]="currentAsk"
                [labels]="labels"
                [errorId]="errorId()"
                [errorClassName]="errorClassName()"
                [slots]="cellSlots"
              />
            }
          }
        }
      </span>
    } @else {
      <adapt-editable-cell-display [props]="display()" />
    }
  `,
})
export class AdaptBatchEditCell<TRow> {
  /** The batch state from the chrome. */
  readonly batch = input.required<BatchEditingState<TRow>>();
  /** The row this cell belongs to. */
  readonly row = input.required<TRow>();
  /** Its stable id. */
  readonly rowId = input.required<string>();
  /** The column this cell belongs to. */
  readonly column = input.required<ColumnDef<TRow>>();
  /** The cell's display content, for a column that is not editable. */
  readonly display = input.required<unknown>();
  /** Accessible name for the editor. */
  readonly editLabel = input.required<string>();
  /** Kit editor component — receives {@link EditableCellEditorCtrl}. */
  readonly editor = input.required<Type<unknown>>();
  /** The incoming value waiting on this cell. */
  readonly ask = input<CellConflictAsk>();
  /** Labels for the notice — already resolved. */
  readonly conflictLabels =
    input<NonNullable<EditableCellEditing<never>["conflictLabels"]>>();
  /** Class for the notice. */
  readonly errorClassName = input<string>();
  /** The kit's components, for the notice's buttons. */
  readonly slots = input<EditableCellSlots>();

  protected readonly resolved = computed(() =>
    resolveCellEditor(this.column(), this.batch().featureHost)
  );

  protected readonly hasEditor = computed(() => Boolean(this.resolved()));

  protected readonly errorId = computed(() =>
    batchEditErrorId(this.rowId(), this.column().key)
  );

  protected readonly changed = computed(() =>
    this.batch().isChanged(this.rowId(), this.column().key)
  );

  protected readonly editorCtrl = computed((): EditableCellEditorCtrl => {
    const batch = this.batch();
    const column = this.column();
    const row = this.row();
    const rowId = this.rowId();
    const editor = this.resolved()!;
    const ask = this.ask();
    return {
      draft: batch.draftFor(row, rowId, column.key),
      setDraft: (value) => {
        batch.setDraft(row, rowId, column.key, value);
      },
      onEditorKeyDown: () => undefined,
      commitOnBlur: () => undefined,
      editor,
      selectOptions: editorSelectOptions(editor),
      label: this.editLabel(),
      validating: false,
      conflict: ask !== undefined,
      errorId: this.errorId(),
      focusRef: () => undefined,
    };
  });
}

// packages/react/src/editing/RowEditGate.tsx
/**
 * A cell inside a row that is being edited as one unit, and the controls that
 * end that edit.
 *
 * Row mode reuses everything cell mode already has — the same editor set, the
 * same validation ARIA, the same custom-editor contract — so the only thing that
 * differs is where the draft lives and when it reaches the host. Both live here
 * rather than in nine adapters, because a second copy of "which editor does this
 * column want" is a second place for the answer to drift.
 */
import {
  type CellEditor,
  type DisplayValue,
  type EditableColumnLike,
  isCustomEditor,
  normalizeEditorOptions,
  resolveCellEditor,
  type TableLabels,
} from "@adapttable/core";
import type { ReactElement, ReactNode } from "react";

import type { BatchEditingState } from "./batchEditing";
import {
  type EditableCellEditing,
  focusEditorOnMount,
} from "./editableCellController";
import {
  type CellConflictAsk,
  CellConflictNotice,
  type EditableCellEditorCtrl,
  type EditableCellSlots,
} from "./EditableCellGate";
import type { RowEditingState } from "./rowEditing";

export type {
  BatchEditingState,
  EditableCellEditorCtrl,
  EditableColumnLike,
  RowEditingState,
  TableLabels,
};

/**
 * Props for {@link RowEditCell}.
 *
 * @public
 */
export interface RowEditCellProps<TRow> {
  /** The row-editing state from the chrome. */
  rowEditing: RowEditingState<TRow>;
  /** The column this cell belongs to. */
  column: EditableColumnLike<TRow>;
  /** The cell's display content, for a column that is not editable. */
  display: ReactElement | string | number | null;
  /** Accessible name for the editor (`labels.editCell`). */
  editLabel: string;
  /**
   * Whether this is the first editable column of the row, and so the field the
   * table hands focus to when the row opens. Every field calling focus on mount
   * would leave the reader at the last column of the row they just opened.
   *
   * Not the DOM's `autoFocus`: focus moves because a reader asked to edit this
   * row, which is the case the accessibility guidance carves out.
   */
  takesFocus: boolean;
  /**
   * Render the kit's own editor from a controller — the same callback shape the
   * cell gate uses, so a kit writes one editor and both modes use it.
   */
  renderEditor: (ctrl: EditableCellEditorCtrl) => ReactElement;
  /**
   * The incoming value waiting on this field, when the row changed underneath
   * the form and this is one of the fields that moved.
   */
  ask?: CellConflictAsk;
  /** Labels for the notice — already resolved. */
  conflictLabels?: NonNullable<EditableCellEditing<never>["conflictLabels"]>;
  /** Class for the notice. */
  errorClassName?: string;
  /** The kit's components, for the notice's buttons. */
  slots?: EditableCellSlots;
}

/**
 * One cell of a row being edited: the kit's editor bound to the row's draft, or
 * the plain display when the column is not editable.
 *
 * @typeParam TRow - The row type.
 * @param props - See {@link RowEditCellProps}.
 * @returns The editor, or the display content.
 *
 * @public
 */
export function RowEditCell<TRow>({
  rowEditing,
  column,
  display,
  editLabel,
  takesFocus,
  renderEditor,
  ask,
  conflictLabels,
  errorClassName,
  slots,
}: Readonly<RowEditCellProps<TRow>>): ReactElement {
  const editor = resolveCellEditor(column, rowEditing.featureHost);
  if (!editor) return <>{display}</>;
  const focusRef = takesFocus ? focusEditorOnMount : () => undefined;
  const errorId = `adapttable-row-edit-${column.key}`;

  const ctrl: EditableCellEditorCtrl = {
    draft: rowEditing.draftFor(column.key),
    setDraft: (value) => {
      rowEditing.setDraft(column.key, value);
    },
    // Enter saves the whole row, Escape cancels it: in row mode the unit is the
    // row, so a per-cell commit would be a different feature wearing this one's
    // keys. Enter does nothing while a field is waiting on an answer — saving
    // then would write over a value the reader has not looked at.
    onEditorKeyDown: (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        if (!ask) rowEditing.save();
      } else if (event.key === "Escape") {
        event.preventDefault();
        rowEditing.cancel();
      }
    },
    // Nothing commits on blur: the reader is moving between fields of one form.
    commitOnBlur: () => undefined,
    editor,
    selectOptions: selectOptionsFor(editor),
    validating: false,
    conflict: ask !== undefined,
    errorId,
    focusRef,
  };

  if (isCustomEditor(editor)) {
    return editor.render({
      draft: ctrl.draft,
      setDraft: ctrl.setDraft,
      commit: rowEditing.save,
      cancel: rowEditing.cancel,
      onKeyDown: ctrl.onEditorKeyDown,
      onBlur: ctrl.commitOnBlur,
      focusRef,
      label: editLabel,
      validating: false,
      errorId: ctrl.errorId,
    }) as ReactElement;
  }
  return (
    <>
      {renderEditor(ctrl)}
      {slots ? (
        <CellConflictNotice
          ask={ask}
          labels={conflictLabels}
          errorId={errorId}
          errorClassName={errorClassName}
          slots={slots}
        />
      ) : null}
    </>
  );
}

/** The options a chooser editor carries, normalized. */
function selectOptionsFor(editor: CellEditor) {
  if (
    typeof editor === "object" &&
    (editor.type === "select" || editor.type === "multi-select")
  ) {
    return normalizeEditorOptions(editor.options);
  }
  return [];
}

/**
 * An incoming change to the row a form has open.
 *
 * The fields that moved carry the question themselves, each with the notice a
 * cell shows; this is what the row's own controls need to know — that an
 * answer is outstanding, so there is nothing to save yet.
 *
 * @public
 */
export interface RowEditConflict {
  /** Whether this row is waiting on an answer. */
  readonly asking: boolean;
}

/**
 * Props for {@link rowEditControls}.
 *
 * @public
 */
export interface RowEditControlsOptions<TRow> {
  /** The row-editing state from the chrome. */
  rowEditing: RowEditingState<TRow>;
  /** The row this control set belongs to. */
  row: TRow;
  /** Its stable id. */
  rowId: string;
  /** Labels; falls back to the built-in English. */
  labels?: TableLabels;
}

/**
 * What a kit needs to render the row's edit / save / cancel controls.
 *
 * @public
 */
export interface RowEditControls {
  /** Whether this row is the one being edited. */
  editing: boolean;
  /** Open this row for editing. */
  begin: () => void;
  /** Hand the host everything that changed. */
  save: () => void;
  /** Throw the drafts away. */
  cancel: () => void;
  /** Accessible name for the control that opens the row. */
  editLabel: string;
  /** Accessible name for save. */
  saveLabel: string;
  /** Accessible name for cancel. */
  cancelLabel: string;
  /** Whether anything actually changed — a save with nothing to save is inert. */
  dirty: boolean;
}

/**
 * The row-mode controls, resolved.
 *
 * A helper rather than a component because each kit renders its own buttons —
 * what is shared is which ones exist, what they are called, and what they do.
 *
 * @typeParam TRow - The row type.
 * @param options - See {@link RowEditControlsOptions}.
 * @returns The controls to render.
 *
 * @public
 */
export function rowEditControls<TRow>({
  rowEditing,
  row,
  rowId,
  labels,
}: Readonly<RowEditControlsOptions<TRow>>): RowEditControls {
  return {
    editing: rowEditing.isEditing(rowId),
    begin: () => {
      rowEditing.begin(row, rowId);
    },
    save: rowEditing.save,
    cancel: rowEditing.cancel,
    editLabel: labels?.editRow ?? "Edit row",
    saveLabel: labels?.saveRow ?? "Save row",
    cancelLabel: labels?.cancel ?? "Cancel",
    dirty: rowEditing.isDirty,
  };
}

/**
 * Glyphs for the row-mode controls.
 *
 * Each kit draws its own pencil, check and cross, with `labels.editRow`,
 * `labels.saveRow` and `labels.cancel` as both the accessible name and the
 * hover title — an actions column is a narrow place, and three words per
 * control crowd out the row. Pass a node to use your own glyph instead, or
 * `false` to show the label as text.
 *
 * @public
 */
export interface RowEditIcons {
  /** The control that opens the row. */
  readonly begin?: DisplayValue | false;
  /** The control that hands the host the patch. */
  readonly save?: DisplayValue | false;
  /** The control that throws the drafts away. */
  readonly cancel?: DisplayValue | false;
}

/**
 * Props for an adapter `RowEditActions` — no slots on the public API.
 *
 * @public
 */
export interface RowEditActionsProps<
  TRow,
> extends RowEditControlsOptions<TRow> {
  /** Class for the control group. */
  className?: string;
  /** Class for each button. */
  buttonClassName?: string;
  /** Glyph overrides — see {@link RowEditIcons}. */
  icons?: RowEditIcons;
  /**
   * Whether an incoming change to this row is waiting on the reader, and what
   * happens either way. The open form is measured against the row it opened
   * on, so a change underneath is a question only the reader can answer.
   */
  conflict?: RowEditConflict;
  /**
   * Whether to draw the control that opens the row. `false` when a host row
   * action carries `editsRow` and owns that trigger — see
   * `resolveRowEditTrigger`. Save and cancel are unaffected: they belong to
   * the open row, not to whatever opened it.
   */
  showBegin?: boolean;
}

/**
 * Kit button the row-edit chrome calls.
 *
 * @public
 */
export interface RowEditButtonProps {
  /** Accessible name for the control, and its hover title. */
  readonly label: string;
  /** Part name, so styling can target this element. */
  readonly part: string;
  /**
   * What to draw inside the button. A node is the glyph to use; `false` asks
   * for the label as text; `undefined` leaves the choice to the kit, which
   * draws its own glyph for this part.
   */
  readonly icon?: DisplayValue | false;
  /** Class for the element. */
  readonly className?: string;
  /** Called when pressed. */
  readonly onClick: (event: { stopPropagation: () => void }) => void;
}

/**
 * Adapter-supplied controls for {@link RowEditActionsChrome}.
 *
 * @public
 */
export interface RowEditActionsSlots {
  /** Renders a button. */
  readonly Button: (props: RowEditButtonProps) => ReactNode;
}

/**
 * Props for {@link RowEditActionsChrome}.
 *
 * @public
 */
export interface RowEditActionsChromeProps<
  TRow,
> extends RowEditActionsProps<TRow> {
  /** The kit's components for each part. */
  readonly slots: RowEditActionsSlots;
}

/**
 * The row's edit / save / cancel controls.
 *
 * Layout and the shared {@link rowEditControls} contract — adapters pass the
 * buttons the end user clicks. A kit with a strong opinion about its buttons
 * can still use {@link rowEditControls} directly instead.
 *
 * @typeParam TRow - The row type.
 * @param props - See {@link RowEditActionsChromeProps}.
 * @returns The controls for this row, or nothing when a host action owns the
 *   trigger and the row is not open.
 *
 * @public
 */
export function RowEditActionsChrome<TRow>({
  className,
  buttonClassName,
  showBegin,
  icons,
  conflict,
  slots,
  ...options
}: Readonly<RowEditActionsChromeProps<TRow>>): ReactElement | null {
  const controls = rowEditControls(options);
  const Button = slots.Button;
  // While the notice above the row holds the question, the row offers no way
  // to save: a form measured against a row that has since moved would write
  // over a change the reader never saw.
  if (controls.editing && conflict?.asking === true) return null;
  if (!controls.editing) {
    // A host action already opens this row, so drawing the built-in control
    // would put two identical triggers side by side.
    if (showBegin === false) return null;
    return (
      <Button
        label={controls.editLabel}
        part="row-edit-begin"
        icon={icons?.begin}
        className={buttonClassName}
        onClick={(event) => {
          event.stopPropagation();
          controls.begin();
        }}
      />
    );
  }
  return (
    <span
      data-adapttable-part="row-edit-actions"
      className={className}
      style={{ display: "inline-flex", gap: 4 }}
    >
      <Button
        label={controls.saveLabel}
        part="row-edit-save"
        icon={icons?.save}
        className={buttonClassName}
        onClick={(event) => {
          event.stopPropagation();
          controls.save();
        }}
      />
      <Button
        label={controls.cancelLabel}
        part="row-edit-cancel"
        icon={icons?.cancel}
        className={buttonClassName}
        onClick={(event) => {
          event.stopPropagation();
          controls.cancel();
        }}
      />
    </span>
  );
}

/**
 * Props for {@link BatchEditCell}.
 *
 * @public
 */
export interface BatchEditCellProps<TRow> {
  /** The batch state from the chrome. */
  batch: BatchEditingState<TRow>;
  /** The row this cell belongs to. */
  row: TRow;
  /** Its stable id. */
  rowId: string;
  /** The column this cell belongs to. */
  column: EditableColumnLike<TRow>;
  /** The cell's display content, for a column that is not editable. */
  display: ReactElement | string | number | null;
  /** Accessible name for the editor (`labels.editCell`). */
  editLabel: string;
  /** Render the kit's own editor from a controller. */
  renderEditor: (ctrl: EditableCellEditorCtrl) => ReactElement;
}

/**
 * One cell while a batch is being edited: always a field, never an activate
 * control.
 *
 * Batch mode's premise is that the reader is walking a list correcting values,
 * so making them open each cell first would be the friction the mode exists to
 * remove. A changed cell carries `data-changed`, which is how the reader finds
 * their way back to what they touched.
 *
 * @typeParam TRow - The row type.
 * @param props - See {@link BatchEditCellProps}.
 * @returns The field, or the display content.
 *
 * @public
 */
export function BatchEditCell<TRow>({
  batch,
  row,
  rowId,
  column,
  display,
  editLabel,
  renderEditor,
}: Readonly<BatchEditCellProps<TRow>>): ReactElement {
  const editor = resolveCellEditor(column, batch.featureHost);
  if (!editor) return <>{display}</>;

  const ctrl: EditableCellEditorCtrl = {
    draft: batch.draftFor(row, rowId, column.key),
    setDraft: (value) => {
      batch.setDraft(row, rowId, column.key, value);
    },
    // No key ends a batch: the reader is moving through a list, and Enter would
    // send everything they have not finished.
    onEditorKeyDown: () => undefined,
    commitOnBlur: () => undefined,
    editor,
    selectOptions: selectOptionsFor(editor),
    validating: false,
    errorId: `adapttable-batch-edit-${rowId}-${column.key}`,
    // Nothing steals focus: every cell is a field, and the reader chose where
    // to start.
    focusRef: () => undefined,
  };

  if (isCustomEditor(editor)) {
    return editor.render({
      draft: ctrl.draft,
      setDraft: ctrl.setDraft,
      commit: () => undefined,
      cancel: () => {
        batch.cancelRow(rowId);
      },
      onKeyDown: ctrl.onEditorKeyDown,
      onBlur: ctrl.commitOnBlur,
      focusRef: ctrl.focusRef,
      label: editLabel,
      validating: false,
      errorId: ctrl.errorId,
    }) as ReactElement;
  }
  return (
    <span
      data-adapttable-part="batch-edit-cell"
      data-changed={batch.isChanged(rowId, column.key) ? "" : undefined}
    >
      {renderEditor(ctrl)}
    </span>
  );
}

/**
 * Props for an adapter `BatchEditBar` — no slots on the public API.
 *
 * @public
 */
export interface BatchEditBarProps<TRow> {
  /** The batch state from the chrome. */
  batch: BatchEditingState<TRow>;
  /** Labels; falls back to the built-in English. */
  labels?: TableLabels;
  /** Class for the bar. */
  className?: string;
  /** Class for each button. */
  buttonClassName?: string;
}

/**
 * Kit button the batch-edit bar calls.
 *
 * @public
 */
export interface BatchEditButtonProps {
  /** Accessible name for the control. */
  readonly label: string;
  /** Part name, so styling can target this element. */
  readonly part: string;
  /** Class for the element. */
  readonly className?: string;
  /** Called when pressed. */
  readonly onClick: () => void;
}

/**
 * Adapter-supplied controls for {@link BatchEditBarChrome}.
 *
 * @public
 */
export interface BatchEditBarSlots {
  /** Renders a button. */
  readonly Button: (props: BatchEditButtonProps) => ReactNode;
}

/**
 * Props for {@link BatchEditBarChrome}.
 *
 * @public
 */
export interface BatchEditBarChromeProps<TRow> extends BatchEditBarProps<TRow> {
  /** The kit's components for each part. */
  readonly slots: BatchEditBarSlots;
}

/**
 * The bar that ends a batch: how many rows are waiting, save all, cancel all.
 *
 * Rendered only while something is pending — a bar that is always there says
 * the table is in a mode, when what matters is that there are unsaved changes.
 *
 * @typeParam TRow - The row type.
 * @param props - See {@link BatchEditBarChromeProps}.
 * @returns The bar, or nothing.
 *
 * @public
 */
export function BatchEditBarChrome<TRow>({
  batch,
  labels,
  className,
  buttonClassName,
  slots,
}: Readonly<BatchEditBarChromeProps<TRow>>): ReactElement | null {
  if (!batch.pending) return null;
  const count = (labels?.pendingRows ?? defaultPendingRows)(batch.count);
  const Button = slots.Button;
  return (
    <div
      data-adapttable-part="batch-edit-bar"
      className={className}
      style={{ display: "flex", alignItems: "center", gap: "0.5em" }}
    >
      <output data-adapttable-part="batch-edit-count">{count}</output>
      <Button
        label={labels?.saveAll ?? "Save all"}
        part="batch-edit-save"
        className={buttonClassName}
        onClick={batch.saveAll}
      />
      <Button
        label={labels?.cancelAll ?? "Cancel all"}
        part="batch-edit-cancel"
        className={buttonClassName}
        onClick={batch.cancelAll}
      />
    </div>
  );
}

/** "3 unsaved rows" — replaceable through `labels.pendingRows`. */
function defaultPendingRows(count: number): string {
  return count === 1 ? "1 unsaved row" : `${String(count)} unsaved rows`;
}
