// packages/angular/angular/src/focus/fillHandle.ts
/** The selection-corner gate; the kit owns the visible fill handle. */
import { sameGridCell } from "@adapttable/core";
import type { FillHandleSlotProps } from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import { AdaptControl } from "../control";
import type { GridFocus } from "./gridFocus";

export type { FillHandleSlotProps } from "@adapttable/core/binding";

/** The row-independent focus state the handle consumes. @public */
export type FillHandleFocus = Pick<
  GridFocus<unknown>,
  "fillHandleCell" | "fillHandleLabel" | "getFillHandleProps"
>;

/** Kit-owned handle control, receiving one `props` input. @public */
export interface FillHandleSlots {
  /** The visible drag affordance. */
  readonly Handle: Type<unknown>;
}

/** Placement and styling for a cell's fill handle. @public */
export interface FillHandleChromeProps {
  /** The table's live grid state. */
  readonly focus: FillHandleFocus | undefined;
  /** Row index within the rendered window. */
  readonly windowIndex: number;
  /** Column index in the grid. */
  readonly col: number;
  /** Dataset offset of the rendered window. */
  readonly firstRowIndex?: number;
  /** Kit-specific class for the visible handle. */
  readonly className?: string;
}

/** Renders the required kit control only at the selection corner. @public */
@Component({
  selector: "adapt-fill-handle-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (handleProps(); as props) {
      <ng-container
        [adaptControl]="slots().Handle"
        [adaptControlProps]="props"
      />
    }
  `,
})
export class AdaptFillHandleChrome {
  /** The grid state, absent when cell navigation is off. */
  readonly focus = input<FillHandleFocus>();
  /** Row index in the rendered window. */
  readonly windowIndex = input.required<number>();
  /** Column index in the grid. */
  readonly col = input.required<number>();
  /** Dataset offset of the rendered window. */
  readonly firstRowIndex = input(0);
  /** Kit-specific class for the visible handle. */
  readonly className = input<string>();
  /** Required kit control; the binding has no visible fallback. */
  readonly slots = input.required<FillHandleSlots>();

  /** The current corner's localized drag props. @internal */
  protected readonly handleProps = computed((): FillHandleSlotProps | null => {
    const focus = this.focus();
    const corner = focus?.fillHandleCell();
    if (
      !focus ||
      !corner ||
      !sameGridCell(corner, {
        row: this.firstRowIndex() + this.windowIndex(),
        col: this.col(),
      })
    )
      return null;
    return {
      label: focus.fillHandleLabel(),
      handleProps: focus.getFillHandleProps(),
      className: this.className(),
    };
  });
}

// packages/core/src/focus/FillHandle.tsx
/**
 * Headless fill-handle gate. Core decides whether the current cell is the
 * selection corner and supplies the drag props; the adapter renders the
 * visible handle with its own component and styling.
 */
import type { ReactNode } from "react";

import { sameGridCell } from "./gridFocus";
import type { GridFocusState } from "./useGridFocus";

/**
 * Props passed to an adapter's visible fill-handle component.
 *
 * @internal
 */
export interface FillHandleSlotProps {
  /** Localized accessible title for the pointer affordance. */
  readonly label: string;
  /** Event handlers and drag metadata from the grid-focus engine. */
  readonly handleProps: Readonly<Record<string, unknown>>;
  /** Adapter-defined class supplied by its table component. */
  readonly className?: string;
}

/**
 * Adapter-owned rendering for {@link FillHandleChrome}.
 *
 * @internal
 */
export interface FillHandleSlots {
  /** Renders the drag handle. */
  readonly Handle: (props: FillHandleSlotProps) => ReactNode;
}

/**
 * Props for {@link FillHandleChrome}.
 *
 * @internal
 */
export interface FillHandleChromeProps {
  /** The grid focus state, straight from `table.gridFocus`. */
  readonly focus: GridFocusState | undefined;
  /** The cell's index in the RENDERED window — what an adapter already has. */
  readonly windowIndex: number;
  /** The cell's column index. */
  readonly col: number;
  /** Where the rendered window starts in the dataset. Zero unless paged. */
  readonly firstRowIndex?: number;
  /** A kit's own class for the visible affordance. */
  readonly className?: string;
  /** Adapter-owned visible component. */
  readonly slots: FillHandleSlots;
}

/**
 * Renders the fill handle when this cell is the selection's corner, and
 * nothing at all otherwise — so an adapter renders it unconditionally in every
 * cell and the opt-in promise still holds.
 *
 * @internal
 */
export function FillHandleChrome({
  focus,
  windowIndex,
  col,
  firstRowIndex = 0,
  className,
  slots,
}: Readonly<FillHandleChromeProps>): ReactNode {
  const corner = focus?.fillHandleCell;
  if (!corner || !focus) return null;
  if (!sameGridCell(corner, { row: firstRowIndex + windowIndex, col })) {
    return null;
  }
  const Handle = slots.Handle;
  return (
    <Handle
      label={focus.fillHandleLabel}
      handleProps={focus.getFillHandleProps()}
      className={className}
    />
  );
}
