// packages/react/src/rows/mobileCard.ts
/**
 * The React face of the neutral mobile-card model.
 */
import type { MobileCardField, MobileCardModel } from "@adapttable/core";
import type { ReactNode } from "react";

/**
 * One field of a mobile card, as a React host receives it.
 *
 * The neutral model types `value` as `DisplayValue`, because a non-React
 * binding stores whatever it renders. Here the value is already React content
 * — the column's `Cell` or accessor, wrapped in the cell editor when editing
 * is armed — so it can go straight into JSX.
 *
 * @public
 */
export interface ReactMobileCardField<TRow> extends Omit<
  MobileCardField<TRow>,
  "value"
> {
  /** The value, rendered exactly as the built-in card renders it. */
  value: ReactNode;
}

/**
 * A mobile card's model, as a React host receives it.
 *
 * @public
 */
export interface ReactMobileCardModel<TRow> extends Omit<
  MobileCardModel<TRow>,
  "fields"
> {
  /** The fields the built-in card would have laid out, in order. */
  fields: readonly ReactMobileCardField<TRow>[];
}

/**
 * Replace a mobile card's body in a React table.
 *
 * @typeParam TRow - The row type.
 * @returns The card's content, rendered inside the shell the table owns.
 *
 * @public
 */
export type ReactMobileCardRenderer<TRow> = (
  row: TRow,
  card: ReactMobileCardModel<TRow>
) => ReactNode;

// packages/angular/angular/src/rows/mobileCard.ts
/**
 * Angular mobile-card bodies: host templates and components receive the
 * same labelled, editable fields as the kit's built-in card.
 */
import type {
  MobileCardField as CoreMobileCardField,
  MobileCardModel,
} from "@adapttable/core";
import type { TemplateRef } from "@angular/core";

import type { CellContext, ColumnDef, Renderer } from "../columnDef";

/**
 * One card field. Stamp `value` with `context` through `NgTemplateOutlet`
 * to retain the column's cell renderer and its composed editor.
 *
 * @public
 */
export interface MobileCardField<TRow> extends Omit<
  CoreMobileCardField<TRow>,
  "column" | "label" | "value"
> {
  /** The Angular column. */
  readonly column: ColumnDef<TRow>;
  /** Its resolved mobile caption, absent for `mobileLabel: ""`. */
  readonly label: string | undefined;
  /** The actual value content, including its editor when editing is armed. */
  readonly value: TemplateRef<CellContext<TRow>>;
  /** The context to pass when stamping `value`. */
  readonly context: CellContext<TRow>;
}

/**
 * A custom body's template context or component inputs. Only the body is
 * replaced; the kit keeps selection, expansion, reorder and row actions.
 *
 * @public
 */
export interface MobileCardContext<TRow> extends Readonly<
  Omit<MobileCardModel<TRow>, "fields">
> {
  /** The row, for a template's `let-row`. */
  readonly $implicit: TRow;
  /** The row. */
  readonly row: TRow;
  /** The same fields the default card would draw, in column order. */
  readonly fields: readonly MobileCardField<TRow>[];
}

/**
 * Replace a mobile card's field layout with a template or component.
 *
 * @public
 */
export type MobileCardRenderer<TRow> = Renderer<MobileCardContext<TRow>>;
