// packages/angular/angular/src/tree/treeToggle.ts
/**
 * The tree toggle's layout. The leaf spacer stays here (display only); kits
 * pass the chevron button the end user clicks.
 */
import { resolveLabels } from "@adapttable/core";
import type {
  TableLabels,
  TreeEntry,
  TreeToggleButtonProps,
} from "@adapttable/core/binding";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type Type,
} from "@angular/core";

import { AdaptControl } from "../control";

export type {
  TreeToggleButtonProps,
  TreeToggleProps,
} from "@adapttable/core/binding";

/**
 * Kit-supplied controls for {@link AdaptTreeToggleChrome}.
 *
 * @public
 */
export interface TreeToggleSlots {
  /** Renders the chevron; receives `TreeToggleButtonProps`. */
  readonly Button: Type<unknown>;
}

/**
 * The chevron for a row with children, or an equal-width spacer for a leaf
 * so the column stays aligned.
 *
 * @public
 */
@Component({
  selector: "adapt-tree-toggle-chrome",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (buttonProps(); as props) {
      <ng-container
        [adaptControl]="slots().Button"
        [adaptControlProps]="props"
      />
    } @else {
      <span
        aria-hidden="true"
        data-adapttable-part="tree-spacer"
        [class]="spacerClassName() ?? ''"
        style="display: inline-block; width: 1.5em; flex-shrink: 0"
      ></span>
    }
  `,
})
export class AdaptTreeToggleChrome {
  /** The row's place in the tree. */
  readonly entry = input.required<TreeEntry<unknown>>();
  /** Labels; falls back to the built-in English. */
  readonly labels = input<TableLabels>();
  /** Open or close a node. */
  readonly onToggle = input.required<(id: string) => void>();
  /** Class for the chevron. */
  readonly toggleClassName = input<string>();
  /** Class for a leaf's placeholder. */
  readonly spacerClassName = input<string>();
  /** The kit's components for each part. */
  readonly slots = input.required<TreeToggleSlots>();

  /** The chevron's props, or `undefined` for a leaf. @internal */
  protected readonly buttonProps = computed(
    (): TreeToggleButtonProps | undefined => {
      const entry = this.entry();
      if (!entry.hasChildren) return undefined;
      const labels = resolveLabels(this.labels());
      const onToggle = this.onToggle();
      return {
        label: entry.expanded ? labels.collapseRow : labels.expandRow,
        expanded: entry.expanded,
        loading: entry.loading === true,
        className: this.toggleClassName(),
        onClick: () => {
          onToggle(entry.key);
        },
      };
    }
  );
}

// packages/core/src/tree/TreeToggle.tsx
/**
 * Tree-toggle layout. The leaf spacer stays here (display only). Adapters
 * pass the chevron button the end user clicks.
 */
import type { ReactElement, ReactNode } from "react";

import type { TableLabels } from "../types";
import type { TreeEntry } from "./treeRows";

/**
 * Props for an adapter `TreeToggle` — no slots on the public API.
 *
 * @public
 */
export interface TreeToggleProps<TRow> {
  /** The row's place in the tree. */
  entry: TreeEntry<TRow>;
  /** Labels; falls back to the built-in English. */
  labels?: TableLabels;
  /** Open or close this node. */
  onToggle: (id: string) => void;
  /** Class for the chevron — the unstyled kit's `treeToggle` hook. */
  toggleClassName?: string;
  /** Class for a leaf's placeholder — the unstyled kit's `treeSpacer` hook. */
  spacerClassName?: string;
}

/**
 * Kit chevron the tree layout calls.
 *
 * @public
 */
export interface TreeToggleButtonProps {
  readonly label: string;
  readonly expanded: boolean;
  readonly loading: boolean;
  readonly className?: string;
  readonly onClick: () => void;
}

/**
 * Adapter-supplied controls for {@link TreeToggleChrome}.
 *
 * @public
 */
export interface TreeToggleSlots {
  readonly Button: (props: TreeToggleButtonProps) => ReactNode;
}

/**
 * Props for {@link TreeToggleChrome}.
 *
 * @public
 */
export interface TreeToggleChromeProps<TRow> extends TreeToggleProps<TRow> {
  readonly slots: TreeToggleSlots;
}

/**
 * Renders the chevron for a row with children, or an equal-width spacer for a
 * leaf so the column stays aligned.
 *
 * @public
 */
export function TreeToggleChrome<TRow>({
  entry,
  labels,
  onToggle,
  toggleClassName,
  spacerClassName,
  slots,
}: Readonly<TreeToggleChromeProps<TRow>>): ReactElement {
  if (!entry.hasChildren) {
    return (
      <span
        aria-hidden="true"
        data-adapttable-part="tree-spacer"
        className={spacerClassName}
        style={{ display: "inline-block", width: "1.5em", flexShrink: 0 }}
      />
    );
  }
  const Button = slots.Button;
  return (
    <Button
      label={
        entry.expanded
          ? (labels?.collapseRow ?? "Collapse row")
          : (labels?.expandRow ?? "Expand row")
      }
      expanded={entry.expanded}
      loading={entry.loading === true}
      className={toggleClassName}
      onClick={() => {
        onToggle(entry.key);
      }}
    />
  );
}
