// packages/adapter-mui/src/components/BulkActionBar.tsx
/** Selection bar with the bulk actions and cross-page banner. */
import { useBulkActionRunner } from "@adapttable/core";
import {
  bulkActionErrorMessage,
  type BulkBarChromeProps,
  offersAllMatching,
  resolveDisabledReason,
} from "@adapttable/core/adapter";
import { Button, Stack, Tooltip, Typography } from "@mui/material";

/** Selection toolbar. */
export function BulkBar({
  selection,
  total,
  bulkActions,
  confirm,
  labels,
}: Readonly<BulkBarChromeProps>) {
  const {
    selectedIds,
    selectedCount,
    visibleIds,
    allMatching,
    selectAllMatching,
    clear,
  } = selection;
  const { pending, error, run } = useBulkActionRunner({
    confirm,
    cancelLabel: labels.cancel,
    // Clear only on success — a failed run keeps the selection for retry.
    onComplete: (outcome) => {
      if (outcome.status === "success") clear();
    },
  });
  if (selectedCount === 0) return null;
  const errorMessage = bulkActionErrorMessage(error);
  const ids = [...selectedIds];
  // Offer "select all N matching" only when the whole page is selected and
  // more rows match beyond it; once active, show the cross-page scope.
  const showBanner = offersAllMatching(selection, total);
  return (
    <Stack
      data-adapttable-part="bulk-bar"
      direction="row"
      spacing={1}
      useFlexGap
      sx={{
        alignItems: "center",
        justifyContent: "space-between",
        flexWrap: "wrap",
      }}
    >
      <Stack
        direction="row"
        spacing={1}
        useFlexGap
        data-adapttable-part="select-all-banner"
        sx={{ alignItems: "center", flexWrap: "wrap" }}
      >
        <Typography variant="body2">
          {labels.selectedCount(selectedCount)}
        </Typography>
        {showBanner &&
          (allMatching ? (
            <>
              <Typography
                variant="body2"
                color="text.secondary"
                data-adapttable-part="select-all-text"
              >
                {labels.allMatchingSelected(total)}
              </Typography>
              <Button
                size="small"
                variant="text"
                data-adapttable-part="select-all-button"
                onClick={clear}
                disabled={pending !== null}
              >
                {labels.clearAll}
              </Button>
            </>
          ) : (
            <>
              <Typography
                variant="body2"
                color="text.secondary"
                data-adapttable-part="select-all-text"
              >
                {labels.pageSelected(visibleIds.length)}
              </Typography>
              <Button
                size="small"
                variant="text"
                data-adapttable-part="select-all-button"
                onClick={selectAllMatching}
                disabled={pending !== null}
              >
                {labels.selectAllMatching(total)}
              </Button>
            </>
          ))}
      </Stack>
      <Stack direction="row" spacing={1} useFlexGap sx={{ flexWrap: "wrap" }}>
        <Button
          size="small"
          variant="text"
          onClick={clear}
          disabled={pending !== null}
        >
          {labels.clearAll}
        </Button>
        {bulkActions.map((action) => {
          const reason = resolveDisabledReason(action.disabledReason?.(ids));
          return (
            <Tooltip key={action.key} title={reason ?? ""}>
              <span>
                <Button
                  data-adapttable-part="bulk-button"
                  size="small"
                  variant="contained"
                  color={action.color as "primary" | undefined}
                  startIcon={action.icon}
                  disabled={reason !== undefined || pending !== null}
                  onClick={() =>
                    run(
                      action,
                      ids,
                      allMatching ? { allMatching: true, total } : undefined
                    )
                  }
                >
                  {action.label}
                </Button>
              </span>
            </Tooltip>
          );
        })}
        {errorMessage !== null && (
          <Typography
            data-adapttable-part="bulk-error"
            variant="body2"
            color="error"
            role="alert"
          >
            {`${labels.errorTitle}: ${errorMessage}`}
          </Typography>
        )}
      </Stack>
    </Stack>
  );
}

// packages/angular/adapter-taiga-ui/src/components/bulkActionBar.ts
import {
  bulkActionErrorMessage,
  type BulkBarSlotProps,
  type ConfirmHandler,
  injectBulkActionRunner,
  offersAllMatching,
  resolveDisabledReason,
  type SelectionState,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";

import { TAIGA_CONTROLS } from "../taigaControls";

/**
 * The selection bar that acts on the selected rows, drawn with native
 * elements.
 */

/**
 * The selection bar: how many rows are selected, "select all matching"
 * across pages, clear, and one button per bulk action.
 *
 * @internal
 */
@Component({
  imports: [...TAIGA_CONTROLS],
  selector: "adapt-bulk-bar",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    @let s = p.selection;
    @if (s.selectedCount > 0) {
      <div data-adapttable-part="bulk-bar">
        <output>{{ p.labels.selectedCount(s.selectedCount) }}</output>
        @if (banner()) {
          <div data-adapttable-part="select-all-banner">
            <span data-adapttable-part="select-all-text">{{
              s.allMatching
                ? p.labels.allMatchingSelected(p.total)
                : p.labels.pageSelected(s.visibleIds.length)
            }}</span>
            <button
              tuiButton
              size="s"
              appearance="secondary"
              type="button"
              data-adapttable-part="select-all-button"
              (click)="s.allMatching ? s.clear() : s.selectAllMatching()"
            >
              {{
                s.allMatching
                  ? p.labels.clearAll
                  : p.labels.selectAllMatching(p.total)
              }}
            </button>
          </div>
        }
        <button
          tuiButton
          size="s"
          appearance="secondary"
          type="button"
          [disabled]="runner.pending() !== null"
          (click)="s.clear()"
        >
          {{ p.labels.clearAll }}
        </button>
        @for (action of actions(); track action.action.key) {
          <button
            tuiButton
            size="s"
            appearance="secondary"
            type="button"
            data-adapttable-part="bulk-button"
            [attr.title]="action.reason ?? null"
            [attr.data-color]="action.action.color ?? null"
            [disabled]="
              action.reason !== undefined || runner.pending() !== null
            "
            (click)="run(action.action)"
          >
            {{ action.action.label }}
          </button>
        }
        @if (errorMessage(); as message) {
          <span data-adapttable-part="bulk-error" role="alert">{{
            p.labels.errorTitle + ": " + message
          }}</span>
        }
      </div>
    }
  `,
})
export class AdaptBulkBar {
  /** The slot's props. */
  readonly props = input.required<BulkBarSlotProps<SelectionState>>();

  // The runner reads its options when an action runs, after the props
  // have arrived.
  protected readonly runner = injectBulkActionRunner(
    ((bar: AdaptBulkBar) => ({
      confirm: (request: Parameters<ConfirmHandler>[0]) => {
        bar.props().confirm(request);
      },
      get cancelLabel(): string {
        return bar.props().labels.cancel;
      },
      onComplete: (outcome: { status: string }) => {
        if (outcome.status === "success") bar.props().selection.clear();
      },
    }))(this)
  );
  protected readonly ids = computed(() => [
    ...this.props().selection.selectedIds,
  ]);
  protected readonly banner = computed(() =>
    offersAllMatching(this.props().selection, this.props().total)
  );
  protected readonly errorMessage = computed(() =>
    bulkActionErrorMessage(this.runner.error())
  );
  protected readonly actions = computed(() =>
    this.props().bulkActions.map((action) => ({
      action,
      reason: resolveDisabledReason(action.disabledReason?.(this.ids())),
    }))
  );

  protected run(
    action: BulkBarSlotProps<SelectionState>["bulkActions"][number]
  ): void {
    const { selection, total } = this.props();
    this.runner.run(
      action,
      this.ids(),
      selection.allMatching ? { allMatching: true, total } : undefined
    );
  }
}
