// packages/adapter-antd/src/components/RowActionButtons.tsx
/** The trailing row-action buttons, shared by rows and cards. */
import type {
  ConfirmHandler,
  RowAction,
  RowActionsLayout,
  RowActionsRenderer,
  TableLabels,
} from "@adapttable/core";
import { runRowAction, visibleRowActions } from "@adapttable/core";
import { resolveDisabledReason } from "@adapttable/react/adapter";
import { Button, Dropdown, Tooltip } from "antd";
import type { ReactNode } from "react";

import { isDangerColor } from "../colors";
import { iconForRowAction, MoreVerticalIcon } from "../icons";

interface RowActionButtonsProps<TRow> {
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
  layout?: RowActionsLayout;
  render?: RowActionsRenderer<TRow>;
}

function ActionStrip<TRow>({
  row,
  actions,
  confirm,
  cancelLabel,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  cancelLabel: string;
}>): ReactNode {
  return (
    <>
      {actions.map((action) => {
        const reason = resolveDisabledReason(action.disabledReason?.(row));
        const disabled =
          reason !== undefined || (action.isDisabled?.(row) ?? false);
        const icon = iconForRowAction(action);
        return (
          <Tooltip key={action.key} title={reason ?? action.label}>
            <Button
              size="small"
              type="text"
              danger={isDangerColor(action.color)}
              disabled={disabled}
              icon={icon}
              title={reason}
              aria-label={action.label}
              data-adapttable-part="action-button"
              onClick={
                disabled
                  ? undefined
                  : (event) => {
                      event.stopPropagation();
                      runRowAction(action, row, confirm, cancelLabel);
                    }
              }
            >
              {icon ? undefined : action.label}
            </Button>
          </Tooltip>
        );
      })}
    </>
  );
}

/** Tags the dropdown surface with its part name for adapter styling hooks. */
function renderMenuSurface(menu: ReactNode): ReactNode {
  return <div data-adapttable-part="row-actions-menu">{menu}</div>;
}

function ActionMenu<TRow>({
  row,
  actions,
  confirm,
  labels,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
}>): ReactNode {
  return (
    <Dropdown
      trigger={["click"]}
      popupRender={renderMenuSurface}
      menu={{
        items: actions.map((action) => {
          const reason = resolveDisabledReason(action.disabledReason?.(row));
          const disabled =
            reason !== undefined || (action.isDisabled?.(row) ?? false);
          return {
            key: action.key,
            label: action.label,
            icon: iconForRowAction(action),
            disabled,
            danger: isDangerColor(action.color),
            title: reason,
          };
        }),
        onClick: (info) => {
          const action = actions.find((item) => item.key === info.key);
          if (!action) return;
          runRowAction(action, row, confirm, labels.cancel);
        },
      }}
    >
      <Button
        size="small"
        type="text"
        aria-label={labels.rowActionsMenu}
        data-adapttable-part="row-actions-trigger"
        icon={<MoreVerticalIcon />}
        onClick={(event) => event.stopPropagation()}
      />
    </Dropdown>
  );
}

export function RowActionButtons<TRow>({
  row,
  actions,
  confirm,
  labels,
  layout,
  render,
}: Readonly<RowActionButtonsProps<TRow>>): ReactNode {
  const visible = visibleRowActions(actions, row);
  let content: ReactNode = null;
  if (render) {
    content = render({ row, actions, confirm, labels }) as ReactNode;
  } else if (visible.length > 0) {
    content =
      layout === "menu" ? (
        <ActionMenu
          row={row}
          actions={visible}
          confirm={confirm}
          labels={labels}
        />
      ) : (
        <ActionStrip
          row={row}
          actions={visible}
          confirm={confirm}
          cancelLabel={labels.cancel}
        />
      );
  }
  return content;
}

// packages/angular/adapter-taiga-ui/src/components/rowActionButtons.ts
import {
  type ConfirmHandler,
  resolveDisabledReason,
  resolveRenderer,
  type RowAction,
  type RowActionsContext,
  type RowActionsLayout,
  type RowActionsRenderer,
  runRowAction,
  type TableLabels,
  visibleRowActions,
} from "@adapttable/angular";
import { NgComponentOutlet, NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  signal,
  viewChild,
} from "@angular/core";

import { TuiDropdownDirective } from "@taiga-ui/core";

import { TAIGA_CONTROLS } from "../taigaControls";
import { type DataTableClassNames } from "../types";

/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 */

/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 *
 * @internal
 */
@Component({
  selector: "adapt-row-actions",
  imports: [...TAIGA_CONTROLS, NgComponentOutlet, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  templateUrl: "./rowActionButtons.html",
})
export class AdaptRowActions<TRow> {
  protected readonly menuOpen = signal(false);
  private readonly dropdown = viewChild(TuiDropdownDirective);

  constructor() {
    effect(() => {
      const popup = this.dropdown()?.ref()?.location.nativeElement;
      popup?.setAttribute("aria-label", this.labels().rowActionsMenu);
    });
  }
  /** The row. */
  readonly row = input.required<TRow>();
  /** Its actions. */
  readonly actions = input.required<readonly RowAction<TRow>[]>();
  /** Asks before an action that declares a `confirm`. */
  readonly confirm = input.required<ConfirmHandler>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();
  /** A strip of buttons, or a menu. */
  readonly layout = input<RowActionsLayout | undefined>();

  /** Host override, handed the same resolved actions and confirmation gate. */
  readonly render = input<RowActionsRenderer<TRow>>();
  /** Class hooks shared by desktop and mobile actions. */
  readonly classNames = input<DataTableClassNames>({});

  protected readonly context = computed<RowActionsContext<TRow>>(() => ({
    $implicit: this.row(),
    row: this.row(),
    actions: this.actions(),
    confirm: this.confirm(),
    labels: this.labels(),
  }));

  protected readonly renderer = computed(() =>
    resolveRenderer(this.render(), this.context())
  );

  protected readonly items = computed(() =>
    visibleRowActions(this.actions(), this.row()).map((action) => {
      const reason = resolveDisabledReason(action.disabledReason?.(this.row()));
      return {
        action,
        reason,
        disabled:
          reason !== undefined || (action.isDisabled?.(this.row()) ?? false),
      };
    })
  );

  protected run(event: Event, action: RowAction<TRow>): void {
    event.stopPropagation();
    this.menuOpen.set(false);
    runRowAction(action, this.row(), this.confirm(), this.labels().cancel);
  }
}
