// packages/adapter-unstyled/src/components/RowActionButtons.tsx
/** The trailing row-action buttons, shared by rows and cards. */
import { runRowAction, visibleRowActions } from "@adapttable/core";
import type {
  ConfirmHandler,
  RowAction,
  RowActionsLayout,
  RowActionsRenderer,
  TableLabels,
} from "@adapttable/core";
import { resolveDisabledReason } from "@adapttable/react/adapter";
import type { MouseEvent, ReactNode, RefObject } from "react";
import { useRef } from "react";

import type { DataTableClassNames } from "../types";
import { iconForRowAction, MoreVerticalIcon } from "./icons";

interface RowActionButtonsProps<TRow> {
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
  classNames: DataTableClassNames;
  layout?: RowActionsLayout;
  render?: RowActionsRenderer<TRow>;
}

interface ActionItemProps<TRow> {
  action: RowAction<TRow>;
  row: TRow;
  confirm: ConfirmHandler;
  cancelLabel: string;
  className: string | undefined;
  /** Close a parent `<details>` after the click (menu layout). */
  detailsRef?: RefObject<HTMLDetailsElement | null>;
}

function ActionItem<TRow>({
  action,
  row,
  confirm,
  cancelLabel,
  className,
  detailsRef,
}: Readonly<ActionItemProps<TRow>>) {
  const reason = resolveDisabledReason(action.disabledReason?.(row));
  const disabled = reason !== undefined || (action.isDisabled?.(row) ?? false);
  const handleClick = disabled
    ? undefined
    : (e: MouseEvent) => {
        e.stopPropagation();
        detailsRef?.current?.removeAttribute("open");
        runRowAction(action, row, confirm, cancelLabel);
      };
  const icon = iconForRowAction(action);
  return (
    <button
      type="button"
      disabled={disabled}
      title={reason ?? (icon ? action.label : undefined)}
      aria-label={action.label}
      data-adapttable-part="action-button"
      data-color={action.color}
      className={className}
      onClick={handleClick}
    >
      {icon ?? action.label}
    </button>
  );
}

function ActionStrip<TRow>({
  row,
  actions,
  confirm,
  cancelLabel,
  className,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  cancelLabel: string;
  className: string | undefined;
}>): ReactNode {
  return (
    <>
      {actions.map((action) => (
        <ActionItem
          key={action.key}
          action={action}
          row={row}
          confirm={confirm}
          cancelLabel={cancelLabel}
          className={className}
        />
      ))}
    </>
  );
}

function ActionMenu<TRow>({
  row,
  actions,
  confirm,
  labels,
  classNames,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
  classNames: DataTableClassNames;
}>): ReactNode {
  const detailsRef = useRef<HTMLDetailsElement>(null);
  return (
    <details
      ref={detailsRef}
      data-adapttable-part="row-actions-menu"
      className={classNames.rowActionsMenu}
      onPointerDown={(event) => event.stopPropagation()}
    >
      <summary
        data-adapttable-part="row-actions-trigger"
        className={classNames.rowActionsTrigger}
        aria-label={labels.rowActionsMenu}
        onClick={(event) => event.stopPropagation()}
      >
        <MoreVerticalIcon />
      </summary>
      {actions.map((action) => (
        <ActionItem
          key={action.key}
          action={action}
          row={row}
          confirm={confirm}
          cancelLabel={labels.cancel}
          className={classNames.actionButton}
          detailsRef={detailsRef}
        />
      ))}
    </details>
  );
}

export function RowActionButtons<TRow>({
  row,
  actions,
  confirm,
  labels,
  classNames,
  layout,
  render,
}: Readonly<RowActionButtonsProps<TRow>>): ReactNode {
  const visible = visibleRowActions(actions, row);
  let content: ReactNode = null;
  if (render) {
    content = render({ row, actions, confirm, labels }) as ReactNode;
  } else if (visible.length > 0) {
    content =
      layout === "menu" ? (
        <ActionMenu
          row={row}
          actions={visible}
          confirm={confirm}
          labels={labels}
          classNames={classNames}
        />
      ) : (
        <ActionStrip
          row={row}
          actions={visible}
          confirm={confirm}
          cancelLabel={labels.cancel}
          className={classNames.actionButton}
        />
      );
  }
  return content;
}

// packages/angular/adapter-angular-cdk/src/components/rowActionButtons.ts
/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 */
import type {
  ConfirmHandler,
  RowAction,
  RowActionsContext,
  RowActionsLayout,
  RowActionsRenderer,
  TableLabels,
} from "@adapttable/angular";
import {
  resolveDisabledReason,
  resolveRenderer,
  runRowAction,
  visibleRowActions,
} from "@adapttable/angular/adapter";
import { A11yModule } from "@angular/cdk/a11y";
import { CdkMenuModule, CdkMenuTrigger } from "@angular/cdk/menu";
import { NgComponentOutlet, NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  viewChild,
} from "@angular/core";

import type { DataTableClassNames } from "../types";
import { AdaptCdkMenuDirection } from "./cdkMenuDirection";

/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 *
 * @internal
 */
@Component({
  selector: "adapt-row-actions",
  imports: [
    CdkMenuModule,
    A11yModule,
    AdaptCdkMenuDirection,
    NgComponentOutlet,
    NgTemplateOutlet,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  templateUrl: "./rowActionButtons.html",
})
export class AdaptRowActions<TRow> {
  /** The row. */
  readonly row = input.required<TRow>();
  /** Its actions. */
  readonly actions = input.required<readonly RowAction<TRow>[]>();
  /** Asks before an action that declares a `confirm`. */
  readonly confirm = input.required<ConfirmHandler>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();
  /** A strip of buttons, or a menu. */
  readonly layout = input<RowActionsLayout | undefined>();

  /** Host override, handed the same resolved actions and confirmation gate. */
  readonly render = input<RowActionsRenderer<TRow>>();
  /** Class hooks shared by desktop and mobile actions. */
  readonly classNames = input<DataTableClassNames>({});

  protected readonly context = computed<RowActionsContext<TRow>>(() => ({
    $implicit: this.row(),
    row: this.row(),
    actions: this.actions(),
    confirm: this.confirm(),
    labels: this.labels(),
  }));

  protected readonly renderer = computed(() =>
    resolveRenderer(this.render(), this.context())
  );

  private readonly menu = viewChild(CdkMenuTrigger);

  protected readonly items = computed(() =>
    visibleRowActions(this.actions(), this.row()).map((action) => {
      const reason = resolveDisabledReason(action.disabledReason?.(this.row()));
      return {
        action,
        reason,
        disabled:
          reason !== undefined || (action.isDisabled?.(this.row()) ?? false),
      };
    })
  );

  protected run(event: Event, action: RowAction<TRow>): void {
    event.stopPropagation();
    this.menu()?.close();
    runRowAction(action, this.row(), this.confirm(), this.labels().cancel);
  }
}
