// packages/adapter-unstyled/src/components/SavedViewsPanel.tsx
/** The saved-views management panel, in native HTML. */
import {
  SavedViewsPanelChrome,
  type SavedViewsPanelChromeProps,
  type SavedViewsPanelEmptyProps,
  type SavedViewsPanelInputProps,
  type SavedViewsPanelRowProps,
  type SavedViewsPanelSlots,
  type SavedViewsPanelSurfaceProps,
} from "@adapttable/core/adapter";
import type { CSSProperties } from "react";

import type { DataTableClassNames } from "../types";
import { ClassNamesProvider, useClassNames } from "./classNamesContext";

/**
 * One saved view and its controls.
 *
 * The classes are the map's, on the two keys the saved-views *menu* already
 * uses for these two shapes: `viewsItem` for the view's own name, which fills
 * the row and applies it, and `viewsDelete` for the compact icon controls
 * beside it. One preset therefore styles the menu and the panel that manages
 * it, and a native panel mounted beside a styled table is styled with it.
 *
 * The slot reads the map from context rather than closing over it, which is
 * what keeps the rename box from being remounted — and losing the caret —
 * on every keystroke.
 */
function Row({
  name,
  viewName,
  isEditing,
  isDefault,
  readOnly,
  defaultLabel,
  readOnlyLabel,
  onApply,
  applyLabel,
  controls,
  layout,
  ...rest
}: Readonly<SavedViewsPanelRowProps>) {
  const { viewsRow, viewsItem, viewsDelete } = useClassNames();
  return (
    <div className={viewsRow} style={layout.row} {...rest}>
      <div style={layout.caption} data-adapttable-part="saved-view-caption">
        {isEditing ? (
          name
        ) : (
          <button
            type="button"
            className={viewsItem}
            title={applyLabel}
            style={{
              flex: "1 1 auto",
              minWidth: 0,
              textAlign: "start",
              fontWeight: isDefault ? 600 : 400,
            }}
            onClick={onApply}
          >
            {viewName}
          </button>
        )}
        {readOnly && (
          <span data-adapttable-part="saved-view-readonly">
            {readOnlyLabel}
          </span>
        )}
        {isDefault && (
          <span data-adapttable-part="saved-view-default">{defaultLabel}</span>
        )}
      </div>
      <div style={layout.controls} data-adapttable-part="saved-view-controls">
        {controls.map((control) => (
          <button
            key={control.key}
            type="button"
            className={viewsDelete}
            style={layout.control}
            aria-label={control.label}
            aria-pressed={control.pressed}
            title={control.label}
            disabled={!control.onPress}
            onClick={control.onPress}
          >
            {control.icon}
          </button>
        ))}
      </div>
    </div>
  );
}

/** The inline rename box, on the `viewsInput` key the menu's own box uses. */
function Input({
  label,
  ref,
  value,
  onChange,
  onCommit,
  onCancel,
}: Readonly<SavedViewsPanelInputProps>) {
  const { viewsInput } = useClassNames();
  return (
    <input
      aria-label={label}
      className={viewsInput}
      value={value}
      ref={ref}
      style={{ flex: "1 1 auto", minWidth: 0 }}
      onChange={(event) => {
        onChange(event.target.value);
      }}
      onKeyDown={(event) => {
        if (event.key === "Enter") onCommit();
        if (event.key === "Escape") onCancel();
      }}
    />
  );
}

/**
 * The panel body. Every other kit stacks its rows with the kit's own Stack;
 * native has none, and a row that wraps its controls onto a second line runs
 * into the next view's name without one.
 */
const LIST: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 2,
  minWidth: 0,
};

/** The card's heading. Native has no typography scale, so this is the shape. */
const TITLE: CSSProperties = {
  display: "block",
  marginBlockEnd: 8,
  fontSize: "0.7rem",
  fontWeight: 700,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  opacity: 0.7,
};

const FOOTER: CSSProperties = {
  display: "block",
  marginBlockStart: 10,
  fontSize: "0.78rem",
  opacity: 0.75,
};

const slots: SavedViewsPanelSlots = {
  Surface: ({
    children,
    className,
    title,
    footer,
    ...rest
  }: SavedViewsPanelSurfaceProps) => (
    <div className={className} style={{ minWidth: 0 }} {...rest}>
      <span style={TITLE} data-adapttable-part="saved-views-title">
        {title}
      </span>
      <div style={LIST}>{children}</div>
      {footer && (
        <span style={FOOTER} data-adapttable-part="saved-views-footer">
          {footer}
        </span>
      )}
    </div>
  ),
  Empty: ({ message }: SavedViewsPanelEmptyProps) => <p>{message}</p>,
  Input,
  Row,
};

/**
 * Manage saved views: apply, rename, reorder, default, delete.
 *
 * Native markup carries no look of its own, so the panel takes the same
 * `classNames` map the table does and honors the `views*` keys — a panel
 * mounted beside a styled table would otherwise be raw HTML beside it.
 *
 * @public
 */
export function SavedViewsPanel(
  props: Readonly<
    Omit<SavedViewsPanelChromeProps, "slots"> & {
      classNames?: DataTableClassNames;
    }
  >
) {
  const { classNames, ...rest } = props;
  return (
    <ClassNamesProvider classNames={classNames}>
      <SavedViewsPanelChrome
        {...rest}
        className={classNames?.viewsPanel}
        slots={slots}
      />
    </ClassNamesProvider>
  );
}

// packages/angular/adapter-angular-cdk/src/components/savedViewsPanel.ts
/**
 * Manage saved views: apply, rename, reorder, default, delete.
 *
 * Native markup carries no look of its own. The card, the row and the
 * controls are the binding's; this fills them with buttons and a text field.
 */
import type { SavedView, TableLabels } from "@adapttable/angular";
import {
  AdaptSavedViewGlyph,
  AdaptSavedViewsPanelChrome,
  type SavedViewsPanelSlots,
} from "@adapttable/angular/adapter";
import { A11yModule } from "@angular/cdk/a11y";
import { NgTemplateOutlet } from "@angular/common";
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";

/** One row's layout, as the chrome computed it. */
interface SavedViewsLayoutView {
  readonly row: Readonly<Record<string, string>>;
  readonly caption: Readonly<Record<string, string>>;
  readonly controls: Readonly<Record<string, string>>;
  readonly control: Readonly<Record<string, string>>;
}

/** One icon control on a row. */
interface SavedViewControlView {
  readonly key: string;
  readonly label: string;
  readonly glyph: {
    readonly paths: readonly string[];
    readonly filled: boolean;
  };
  readonly onPress?: () => void;
  readonly pressed?: boolean;
}

/** What the card receives. */
interface SavedViewsSurfaceView {
  readonly title: string;
  readonly className?: string;
  readonly children?: TemplateRef<unknown>;
  readonly footer?: TemplateRef<unknown>;
}

/** What one row receives. */
interface SavedViewsRowView {
  readonly name?: TemplateRef<unknown>;
  readonly viewName: string;
  readonly isEditing: boolean;
  readonly isDefault: boolean;
  readonly readOnly: boolean;
  readonly defaultLabel: string;
  readonly readOnlyLabel: string;
  readonly onApply: () => void;
  readonly applyLabel: string;
  readonly controls: readonly SavedViewControlView[];
  readonly layout: SavedViewsLayoutView;
}

/** The rename field. */
interface SavedViewsInputView {
  readonly label: string;
  readonly value: string;
  readonly onChange: (next: string) => void;
  readonly onCommit: () => void;
  readonly onCancel: () => void;
}

/** The empty list. */
interface SavedViewsEmptyView {
  readonly message: string;
}

/** The name, growing, with the weight of the default view. */
function nameButtonStyle(isDefault: boolean): Record<string, string> {
  return {
    flex: "1 1 auto",
    minWidth: "0",
    textAlign: "start",
    fontWeight: isDefault ? "600" : "400",
  };
}

/** The card. */
@Component({
  selector: "adapt-saved-views-surface",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  template: `<div
    data-adapttable-part="saved-views-panel"
    [class]="props().className"
    style="min-width: 0"
  >
    <span data-adapttable-part="saved-views-title" [style]="titleStyle">{{
      props().title
    }}</span>
    <div [style]="listStyle">
      @if (props().children; as children) {
        <ng-container [ngTemplateOutlet]="children" />
      }
    </div>
    @if (props().footer; as footer) {
      <span data-adapttable-part="saved-views-footer" [style]="footerStyle">
        <ng-container [ngTemplateOutlet]="footer" />
      </span>
    }
  </div>`,
})
class AdaptSavedViewsSurface {
  readonly props = input.required<SavedViewsSurfaceView>();

  protected readonly titleStyle = {
    display: "block",
    marginBlockEnd: "8px",
    fontSize: "0.7rem",
    fontWeight: "700",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    opacity: "0.7",
  };

  protected readonly listStyle = {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: "0",
  };

  protected readonly footerStyle = {
    display: "block",
    marginBlockStart: "10px",
    fontSize: "0.78rem",
    opacity: "0.75",
  };
}

/** One view: its name applies it, and the icon cluster follows. */
@Component({
  selector: "adapt-saved-views-row",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [A11yModule, AdaptSavedViewGlyph, NgTemplateOutlet],
  template: `<div
    data-adapttable-part="saved-view-row"
    [style]="props().layout.row"
  >
    <div
      data-adapttable-part="saved-view-caption"
      [style]="props().layout.caption"
    >
      @if (props().isEditing) {
        <ng-container [ngTemplateOutlet]="props().name" />
      } @else {
        <button
          cdkMonitorElementFocus
          data-adapttable-cdk-control
          type="button"
          [attr.title]="props().applyLabel"
          [style]="nameStyle()"
          (click)="props().onApply()"
        >
          {{ props().viewName }}
        </button>
      }
      @if (props().readOnly) {
        <span data-adapttable-part="saved-view-readonly">{{
          props().readOnlyLabel
        }}</span>
      }
      @if (props().isDefault) {
        <span data-adapttable-part="saved-view-default">{{
          props().defaultLabel
        }}</span>
      }
    </div>
    <div
      data-adapttable-part="saved-view-controls"
      [style]="props().layout.controls"
    >
      @for (control of props().controls; track control.key) {
        @if (control.onPress; as run) {
          <button
            cdkMonitorElementFocus
            data-adapttable-cdk-control
            type="button"
            [attr.data-control]="control.key"
            [style]="props().layout.control"
            [attr.aria-label]="control.label"
            [attr.aria-pressed]="control.pressed"
            [attr.title]="control.label"
            (click)="run()"
          >
            <adapt-saved-view-glyph [glyph]="control.glyph" />
          </button>
        } @else {
          <button
            cdkMonitorElementFocus
            data-adapttable-cdk-control
            type="button"
            disabled
            [attr.data-control]="control.key"
            [style]="props().layout.control"
            [attr.aria-label]="control.label"
            [attr.aria-pressed]="control.pressed"
            [attr.title]="control.label"
          >
            <adapt-saved-view-glyph [glyph]="control.glyph" />
          </button>
        }
      }
    </div>
  </div>`,
})
class AdaptSavedViewsRow {
  readonly props = input.required<SavedViewsRowView>();

  /** The name's weight: the default view is the one the table opens with. */
  protected readonly nameStyle = computed(() =>
    nameButtonStyle(this.props().isDefault)
  );
}

/**
 * The inline rename field. Focus moves here when the field arrives, because
 * a rename that leaves focus on the button it replaced is a rename the
 * keyboard cannot finish.
 */
@Component({
  imports: [A11yModule],
  selector: "adapt-saved-views-input",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<input
    cdkMonitorElementFocus
    data-adapttable-cdk-control
    #box
    [attr.aria-label]="props().label"
    [value]="props().value"
    style="flex: 1 1 auto; min-width: 0"
    (input)="changed($event)"
    (keydown)="key($event)"
  />`,
})
class AdaptSavedViewsInput {
  readonly props = input.required<SavedViewsInputView>();

  private readonly box =
    viewChild.required<ElementRef<HTMLInputElement>>("box");

  constructor() {
    afterNextRender(() => {
      this.box().nativeElement.focus();
    });
  }

  /** Keep the draft as the reader types. */
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLInputElement).value);
  }

  /** Enter keeps the name. Escape puts the old one back. */
  protected key(event: KeyboardEvent): void {
    if (event.key === "Enter") this.props().onCommit();
    if (event.key === "Escape") this.props().onCancel();
  }
}

/** The empty list. */
@Component({
  selector: "adapt-saved-views-empty",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p>{{ props().message }}</p>`,
})
class AdaptSavedViewsEmpty {
  readonly props = input.required<SavedViewsEmptyView>();
}

const SLOTS: SavedViewsPanelSlots = {
  Surface: AdaptSavedViewsSurface,
  Row: AdaptSavedViewsRow,
  Input: AdaptSavedViewsInput,
  Empty: AdaptSavedViewsEmpty,
};

/**
 * The management card for a table's saved views.
 *
 * The toolbar menu switches views. This renames, reorders, picks the default
 * and deletes. Mount it where the list is managed; it does not replace the
 * menu.
 *
 * @public
 */
@Component({
  selector: "adapt-saved-views-panel",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AdaptSavedViewsPanelChrome],
  template: `<adapt-saved-views-panel-chrome
    [views]="views()"
    [onApply]="onApply()"
    [onRename]="onRename()"
    [onMove]="onMove()"
    [onSetDefault]="onSetDefault()"
    [onRemove]="onRemove()"
    [labels]="labels()"
    [footer]="footer()"
    [className]="className()"
    [slots]="slots"
  />`,
})
export class AdaptSavedViewsPanel {
  /** The list, in the order to show it. */
  readonly views = input.required<readonly SavedView[]>();

  /** Apply a view. */
  readonly onApply = input.required<(name: string) => void>();

  /** Rename a view. */
  readonly onRename = input.required<(from: string, to: string) => void>();

  /** Move a view by one step. */
  readonly onMove = input.required<(name: string, delta: number) => void>();

  /** Make a view the default, or clear it. */
  readonly onSetDefault = input.required<(name: string) => void>();

  /** Delete a view. */
  readonly onRemove = input.required<(name: string) => void>();

  /** Label overrides. Omitted keys keep the English default. */
  readonly labels = input<Partial<TableLabels>>();

  /** A note under the list. */
  readonly footer = input<TemplateRef<unknown> | string>();

  /** Class on the card. */
  readonly className = input<string>();

  /** The native card, row, field and empty state. */
  protected readonly slots = SLOTS;
}
