// packages/adapter-unstyled/src/components/toolbarExtras.tsx
/**
 * The optional toolbar controls, as semantic HTML with class hooks.
 *
 * They render through `TOOLBAR_EXTRAS`, so the button and the feature that
 * makes it work arrive together: a table that never imports `/export` carries
 * neither the handler nor this button. There is no kit to borrow components
 * from here — native elements ARE this kit — so each control keeps its
 * `data-adapttable-part` name and its `classNames` key.
 */
import {
  ExportAnnouncer,
  ExportProgressChrome,
  type ExportProgressSurfaceSlotProps,
  type ToolbarExtrasSlotProps,
} from "@adapttable/core/adapter";
import type { ReactNode } from "react";

import type { DataTableClassNames } from "../types";

/** The class map the unstyled kit styles its controls through. */
const classesOf = (props: Readonly<ToolbarExtrasSlotProps>) =>
  (props.classNames ?? {}) as DataTableClassNames;

export function UndoRedoButtons(
  props: Readonly<ToolbarExtrasSlotProps>
): ReactNode {
  const { onUndo, onRedo, canUndo, canRedo, undoLabel, redoLabel } = props;
  const classNames = classesOf(props);
  if (!onUndo || !onRedo) return null;
  return (
    <>
      <button
        type="button"
        data-adapttable-part="undo-button"
        className={classNames.undoButton}
        disabled={canUndo !== true}
        onClick={onUndo}
      >
        {undoLabel}
      </button>
      <button
        type="button"
        data-adapttable-part="redo-button"
        className={classNames.redoButton}
        disabled={canRedo !== true}
        onClick={onRedo}
      >
        {redoLabel}
      </button>
    </>
  );
}

export function ExportCsvButton(
  props: Readonly<ToolbarExtrasSlotProps>
): ReactNode {
  const {
    onExportCsv,
    exportBusy,
    exportAnnouncement = "",
    exportProgressState = null,
    exportLabel,
    exportDisabled = false,
    exportDisabledReason = "",
    labels,
  } = props;
  const classNames = classesOf(props);
  if (!onExportCsv) return null;
  return (
    <>
      <button
        type="button"
        data-adapttable-part="export-csv-button"
        className={classNames.exportCsvButton}
        style={{ flexShrink: 0, whiteSpace: "nowrap" }}
        onClick={onExportCsv}
        disabled={exportBusy === true || exportDisabled}
        aria-busy={exportBusy}
        title={exportDisabled ? exportDisabledReason : undefined}
      >
        {/* No kit to borrow a loading button from, so the affordance is an
            element the host can style — `aria-hidden` because the announcement
            below is what a screen reader should hear, not a decoration. */}
        {exportBusy && (
          <span
            aria-hidden="true"
            data-adapttable-part="export-spinner"
            className={classNames.exportSpinner}
          />
        )}
        {exportLabel}
      </button>
      <ExportProgressChrome
        progress={exportProgressState}
        labels={labels}
        slots={{
          Surface: (surface) => (
            <ExportProgressSurface {...surface} classNames={classNames} />
          ),
        }}
      />
      <ExportAnnouncer announcement={exportAnnouncement} />
    </>
  );
}

function ExportProgressSurface({
  status,
  heading,
  message,
  error,
  progress,
  progressLabel,
  cancel,
  retry,
  download,
  classNames,
}: Readonly<
  ExportProgressSurfaceSlotProps & { classNames: DataTableClassNames }
>): ReactNode {
  return (
    <section
      aria-label={heading}
      data-adapttable-part="export-progress-surface"
      className={classNames.exportProgressSurface}
      style={{
        position: "fixed",
        zIndex: 1400,
        insetInlineEnd: 16,
        bottom: 16,
        width: 320,
        maxWidth: "calc(100vw - 32px)",
        padding: 16,
        border: "1px solid currentColor",
        borderRadius: 8,
        background: "Canvas",
        color: "CanvasText",
        boxShadow: "0 8px 28px rgb(0 0 0 / 18%)",
      }}
    >
      <strong>{heading}</strong>
      {status === "busy" ? (
        <progress
          value={progress}
          max={100}
          aria-label={progressLabel}
          data-adapttable-part="export-progress-bar"
          className={classNames.exportProgressBar}
          style={{ display: "block", width: "100%", marginBlock: 12 }}
        />
      ) : null}
      {message ? (
        <p
          data-adapttable-part="export-progress-message"
          className={classNames.exportProgressMessage}
        >
          {message}
        </p>
      ) : null}
      {error ? (
        <p
          data-adapttable-part="export-progress-message"
          className={classNames.exportProgressMessage}
        >
          {error}
        </p>
      ) : null}
      <div
        data-adapttable-part="export-progress-actions"
        className={classNames.exportProgressActions}
        style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}
      >
        {cancel ? (
          <button
            type="button"
            className={classNames.exportProgressCancel}
            onClick={cancel.onAction}
            data-adapttable-part="export-progress-cancel"
          >
            {cancel.label}
          </button>
        ) : null}
        {retry ? (
          <button
            type="button"
            className={classNames.exportProgressRetry}
            onClick={retry.onAction}
            data-adapttable-part="export-progress-retry"
          >
            {retry.label}
          </button>
        ) : null}
        {download ? (
          <a
            href={download.url}
            download
            className={classNames.exportProgressDownload}
            data-adapttable-part="export-progress-download"
          >
            {download.label}
          </a>
        ) : null}
      </div>
    </section>
  );
}

export function PrintButton(
  props: Readonly<ToolbarExtrasSlotProps>
): ReactNode {
  const { onPrint, printLabel } = props;
  const classNames = classesOf(props);
  if (!onPrint) return null;
  return (
    <button
      type="button"
      data-adapttable-part="print-button"
      className={classNames.printButton}
      onClick={onPrint}
    >
      {printLabel}
    </button>
  );
}

export function DensityButton(
  props: Readonly<ToolbarExtrasSlotProps>
): ReactNode {
  const { density, onDensityChange, labels } = props;
  const classNames = classesOf(props);
  return (
    <button
      type="button"
      aria-label={labels.density}
      data-adapttable-part="density-toggle"
      className={classNames.densityToggle}
      onClick={() => {
        onDensityChange(density === "compact" ? "comfortable" : "compact");
      }}
    >
      {density === "compact"
        ? labels.densityCompact
        : labels.densityComfortable}
    </button>
  );
}

export function FullscreenButton(
  props: Readonly<ToolbarExtrasSlotProps>
): ReactNode {
  const { onToggleFullscreen, isFullscreen, labels } = props;
  const classNames = classesOf(props);
  if (!onToggleFullscreen) return null;
  return (
    <button
      type="button"
      aria-label={
        isFullscreen === true ? labels.exitFullscreen : labels.enterFullscreen
      }
      data-adapttable-part="fullscreen-toggle"
      className={classNames.fullscreenToggle}
      onClick={onToggleFullscreen}
    >
      {isFullscreen === true ? "✕" : "⛶"}
    </button>
  );
}

// packages/angular/adapter-angular-cdk/src/components/toolbarExtras.ts
/**
 * The toolbar's optional controls, drawn natively. Each renders through the
 * toolbar-extras slot, so a table that never composes a feature carries
 * neither its handler nor its button.
 */
import {
  AdaptExportAnnouncer,
  AdaptExportProgressChrome,
  type ExportProgressSlots,
  type ExportProgressSurfaceSlotProps,
  type ToolbarExtrasSlotProps,
} from "@adapttable/angular/adapter";
import { A11yModule } from "@angular/cdk/a11y";
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

/** Switches between comfortable and compact rows. @internal */
@Component({
  imports: [A11yModule],
  selector: "adapt-density-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <button
      cdkMonitorElementFocus
      data-adapttable-cdk-control
      type="button"
      data-adapttable-part="density-toggle"
      [attr.aria-label]="p.labels.density"
      (click)="
        p.onDensityChange(p.density === 'compact' ? 'comfortable' : 'compact')
      "
    >
      {{
        p.density === "compact"
          ? p.labels.densityCompact
          : p.labels.densityComfortable
      }}
    </button>
  `,
})
export class AdaptDensityButton {
  /** The slot's props. */
  readonly props = input.required<ToolbarExtrasSlotProps>();
}

/** Takes the table fullscreen, and back. @internal */
@Component({
  imports: [A11yModule],
  selector: "adapt-fullscreen-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    @if (p.onToggleFullscreen; as toggle) {
      <button
        cdkMonitorElementFocus
        data-adapttable-cdk-control
        type="button"
        data-adapttable-part="fullscreen-toggle"
        [attr.aria-label]="
          p.isFullscreen ? p.labels.exitFullscreen : p.labels.enterFullscreen
        "
        (click)="toggle()"
      >
        {{ p.isFullscreen ? "✕" : "⛶" }}
      </button>
    }
  `,
})
export class AdaptFullscreenButton {
  /** The slot's props. */
  readonly props = input.required<ToolbarExtrasSlotProps>();
}

/** The server-export progress surface. @internal */
@Component({
  imports: [A11yModule],
  selector: "adapt-export-progress-surface",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <section
      [attr.aria-label]="p.heading"
      data-adapttable-part="export-progress-surface"
      style="position: fixed; z-index: 20; inset-inline-end: 16px; bottom: 16px; width: 320px; max-width: calc(100vw - 32px); padding: 16px; border: 1px solid currentColor; border-radius: 8px; background: Canvas; color: CanvasText"
    >
      <div style="display: flex; align-items: center; gap: 8px">
        <strong style="flex: 1">{{ p.heading }}</strong>
        @if (p.dismiss; as dismiss) {
          <button
            cdkMonitorElementFocus
            data-adapttable-cdk-control
            type="button"
            data-adapttable-part="export-progress-dismiss"
            (click)="dismiss.onAction()"
          >
            {{ dismiss.label }}
          </button>
        }
      </div>
      @if (p.status === "busy") {
        <progress
          data-adapttable-part="export-progress-bar"
          max="100"
          [attr.value]="p.progress ?? null"
          [attr.aria-label]="p.progressLabel"
          style="display: block; width: 100%; margin-block: 12px"
        ></progress>
      }
      @if (p.message) {
        <p data-adapttable-part="export-progress-message">{{ p.message }}</p>
      }
      @if (p.error) {
        <p data-adapttable-part="export-progress-message">{{ p.error }}</p>
      }
      <div
        data-adapttable-part="export-progress-actions"
        style="display: flex; justify-content: flex-end; gap: 8px"
      >
        @if (p.cancel; as cancel) {
          <button
            cdkMonitorElementFocus
            data-adapttable-cdk-control
            type="button"
            data-adapttable-part="export-progress-cancel"
            (click)="cancel.onAction()"
          >
            {{ cancel.label }}
          </button>
        }
        @if (p.retry; as retry) {
          <button
            cdkMonitorElementFocus
            data-adapttable-cdk-control
            type="button"
            data-adapttable-part="export-progress-retry"
            (click)="retry.onAction()"
          >
            {{ retry.label }}
          </button>
        }
        @if (p.download; as download) {
          <a
            [href]="download.url"
            download
            data-adapttable-part="export-progress-download"
          >
            {{ download.label }}
          </a>
        }
      </div>
    </section>
  `,
})
export class AdaptExportProgressSurface {
  /** The view from the progress chrome. */
  readonly props = input.required<ExportProgressSurfaceSlotProps>();
}

const EXPORT_SLOTS: ExportProgressSlots = {
  Surface: AdaptExportProgressSurface,
};

/** Exports the current view, and says how it went. @internal */
@Component({
  selector: "adapt-export-button",
  imports: [A11yModule, AdaptExportAnnouncer, AdaptExportProgressChrome],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    @if (p.onExportCsv; as start) {
      <button
        cdkMonitorElementFocus
        data-adapttable-cdk-control
        type="button"
        data-adapttable-part="export-csv-button"
        style="flex-shrink: 0; white-space: nowrap"
        [disabled]="p.exportBusy === true || p.exportDisabled === true"
        [attr.aria-busy]="p.exportBusy ?? null"
        [attr.title]="p.exportDisabled ? p.exportDisabledReason : null"
        (click)="start()"
      >
        @if (p.exportBusy) {
          <span aria-hidden="true" data-adapttable-part="export-spinner"></span>
        }
        {{ p.exportLabel }}
      </button>
      <adapt-export-progress-chrome
        [progress]="p.exportProgressState ?? null"
        [labels]="p.labels"
        [slots]="slots"
      />
      <adapt-export-announcer [announcement]="p.exportAnnouncement ?? ''" />
    }
  `,
})
export class AdaptExportButton {
  /** The slot's props. */
  readonly props = input.required<ToolbarExtrasSlotProps>();

  /** The progress surface. */
  protected readonly slots = EXPORT_SLOTS;
}

/** Prints the table. @internal */
@Component({
  imports: [A11yModule],
  selector: "adapt-print-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    @if (p.onPrint; as print) {
      <button
        cdkMonitorElementFocus
        data-adapttable-cdk-control
        type="button"
        data-adapttable-part="print-button"
        (click)="print()"
      >
        {{ p.printLabel }}
      </button>
    }
  `,
})
export class AdaptPrintButton {
  /** The slot's props. */
  readonly props = input.required<ToolbarExtrasSlotProps>();
}

/** Native controls for the table's edit history. @internal */
@Component({
  imports: [A11yModule],
  selector: "adapt-undo-redo-buttons",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    @if (p.onUndo && p.onRedo) {
      <button
        cdkMonitorElementFocus
        data-adapttable-cdk-control
        type="button"
        data-adapttable-part="undo-button"
        [class]="p.classNames?.['undoButton']"
        [disabled]="p.canUndo !== true"
        (click)="p.onUndo()"
      >
        {{ p.undoLabel }}
      </button>
      <button
        cdkMonitorElementFocus
        data-adapttable-cdk-control
        type="button"
        data-adapttable-part="redo-button"
        [class]="p.classNames?.['redoButton']"
        [disabled]="p.canRedo !== true"
        (click)="p.onRedo()"
      >
        {{ p.redoLabel }}
      </button>
    }
  `,
})
export class AdaptUndoRedoButtons {
  /** The current history controls and labels. */
  readonly props = input.required<ToolbarExtrasSlotProps>();
}
