// packages/angular/angular/src/features/grouping.ts
/**
 * Grouping for Angular: the `grouping()` feature, and the live grouped model
 * a table renders from while it is composed.
 *
 * Collapse, paging and the flat grouped model come from `@adapttable/core`;
 * this module holds them as signals. A table that composes neither
 * `grouping()` nor `groupingPanel()` never builds any of it.
 */
import {
  declaredAggregates,
  devWarn,
  type ExtraRow,
  formatGroupBy,
  type GroupAggregatesFn,
  type GroupByInput,
  type GroupedFlatEntry,
  groupedRowModel,
  groupingAggregates,
  groupingIgnoredWarning,
  type GroupingRuntimeSource,
  type GroupNode,
  groupShowMoreRequest,
  type GroupSort,
  parseGroupBy,
  type TableSource,
} from "@adapttable/core";
import {
  coreGrouping,
  type GroupCollapseState,
} from "@adapttable/core/binding";
import {
  assertInInjectionContext,
  computed,
  effect,
  inject,
  Injector,
  type Signal,
} from "@angular/core";

import type { DataTable } from "../dataTable";
import { type AdaptTableFeature, featureOptionsOf } from "../featureHost";
import { injectGroupCollapse } from "../grouping/groupCollapse";
import { injectGroupPaging } from "../grouping/groupPaging";
import { type MaybeSignalOptional, readMaybe } from "../store";

export type { GroupSort } from "@adapttable/core";

/**
 * Everything grouping can be told.
 *
 * @public
 */
export interface GroupingExtras<TRow = unknown> {
  /** Told when the keys change, so a host can mirror them. */
  readonly onGroupByChange?: (groupBy: readonly string[]) => void;
  /** Draw a footer row under each group. */
  readonly groupFooters?: boolean;
  /** Show this many groups at a time. */
  readonly groupPageSize?: number;
  /** Show this many rows inside each group. */
  readonly groupRowPageSize?: number;
  /** Keep only the groups this accepts — each with its value, label and rows. */
  readonly groupFilter?: (group: GroupNode<TRow>) => boolean;
  /** Order the groups themselves. */
  readonly groupSort?: GroupSort<TRow>;
  /** Per-group subtotals, the same mapper shape as a summary row. */
  readonly groupAggregates?: (rows: readonly TRow[]) => unknown;
  /** Controlled collapse state. */
  readonly collapsedGroupIds?: readonly string[];
  /** Told when a group opens or closes. */
  readonly onCollapsedGroupIdsChange?: (ids: string[]) => void;
  /** Fetch the rest of a group on demand. */
  readonly onGroupLoadMore?: (groupKey: string) => void;
}

/**
 * Group rows under collapsible headers.
 *
 * ```ts
 * import { grouping } from "@adapttable/angular-unstyled/grouping";
 *
 * features: [grouping("team", { groupAggregates: (rows) => ({ points: sum(rows) }) })]
 * ```
 *
 * @param groupBy - The grouping keys, outermost first.
 * @param extras - See {@link GroupingExtras}.
 * @returns The feature.
 *
 * @public
 */
export function grouping<TRow = unknown>(
  groupBy: string | readonly string[],
  extras: GroupingExtras<TRow> = {}
): AdaptTableFeature {
  return coreGrouping<TRow>(groupBy, extras) as AdaptTableFeature;
}

/**
 * The grouped table a kit renders: its keys, collapse state and flat
 * entries, and the actions that change them.
 *
 * @public
 */
export interface TableGrouping<TRow> {
  /** The grouping keys in order — one for a flat group, more for nested. */
  readonly groupBy: readonly string[];
  /** Which groups are closed. */
  readonly collapsed: GroupCollapseState;
  /** The per-group subtotals, with the reader's overrides applied. */
  readonly aggregates: GroupAggregatesFn<TRow> | undefined;
  /** Group headers, footers, "show more" rows, leaves and extras, in order. */
  readonly entries: readonly GroupedFlatEntry<TRow>[];
  /** Change the grouping keys. */
  readonly setGroupBy: (key: GroupByInput) => void;
  /** Open every group. */
  readonly expandAll: () => void;
  /** Close every group, at every level. */
  readonly collapseAll: () => void;
  /** Show the tree down to `depth`: `0` leaves only the outermost headers. */
  readonly collapseToDepth: (depth: number) => void;
  /** Reveal the next page of groups, or of one group's rows. */
  readonly showMore: (entry: {
    scope: "groups" | "rows";
    groupKey?: string;
  }) => void;
}

/**
 * Options for {@link injectGrouping}.
 *
 * @public
 */
export interface GroupingOptions<TRow> {
  /** The headless table: its columns and row identity. */
  readonly table: Pick<DataTable<TRow>, "allColumns" | "rowKey">;
  /** The live source, before grouping widens it. */
  readonly source: Signal<TableSource<TRow>>;
  /** The composed features; grouping arms on `grouping` or `groupingPanel`. */
  readonly features: readonly AdaptTableFeature[];
  /** Active locale, for a grouped column's `i18n` path. */
  readonly locale?: MaybeSignalOptional<string>;
  /** The injector to run in. */
  readonly injector?: Injector;
}

/** The grouping panel feature's own extras, for its declared aggregates. */
interface PanelFeature extends AdaptTableFeature {
  readonly extras?: { readonly groupAggregates?: unknown };
}

/**
 * The live grouped model while `grouping()` or `groupingPanel()` is composed,
 * `undefined` when neither is. The signal holds `undefined` while nothing
 * groups — no keys, or a source that cannot group.
 *
 * Render from `groupedViewSource(source)` while the signal holds a model: a
 * group spans pages, so the grouped table shows the full filtered set.
 *
 * @param options - See {@link GroupingOptions}.
 * @returns The model as a signal, or `undefined` when grouping is not composed.
 *
 * @public
 */
export function injectGrouping<TRow>(
  options: GroupingOptions<TRow>
): Signal<TableGrouping<TRow> | undefined> | undefined {
  const { features, table } = options;
  const panel = features.find(
    (feature): feature is PanelFeature => feature.id === "grouping-panel"
  );
  const armed =
    panel !== undefined || features.some((f) => f.id === "grouping");
  if (!armed) return undefined;
  if (!options.injector) assertInInjectionContext(injectGrouping);
  const injector = options.injector ?? inject(Injector);

  const extras = featureOptionsOf(features) as GroupingExtras<TRow> & {
    readonly groupBy?: string | readonly string[];
    readonly extraRows?: readonly ExtraRow[];
  };
  const panelDeclared = declaredAggregates(panel?.extras?.groupAggregates);
  const collapse = injectGroupCollapse({
    collapsedGroupIds: extras.collapsedGroupIds,
    onCollapsedGroupIdsChange: extras.onCollapsedGroupIdsChange,
    injector,
  });
  const paging = injectGroupPaging({ injector });

  const groupByKeys = computed(
    () => parseGroupBy(extras.groupBy ?? options.source().groupBy),
    { equal: sameKeys }
  );
  // Only the fields grouping reads, so a page or a search does not rebuild
  // the grouped model.
  const groupingSource = computed(
    (): GroupingRuntimeSource<TRow> => {
      const source = options.source();
      return {
        allFilteredRows: source.allFilteredRows,
        groups: source.groups,
        capabilities: source.capabilities,
        honorsAggregates: source.honorsAggregates,
        aggregateOperations: source.aggregateOperations,
        groupAggregateOverrides: source.groupAggregateOverrides,
        queryAggregates: source.queryAggregates,
        groupAggregations: source.groupAggregations,
      };
    },
    { equal: sameFields }
  );

  effect(
    () => {
      const warning = groupingIgnoredWarning(groupByKeys(), groupingSource());
      if (warning !== undefined) devWarn(warning);
    },
    { injector }
  );

  const setGroupBy = (key: GroupByInput): void => {
    options.source().setGroupBy(formatGroupBy(key));
    extras.onGroupByChange?.(parseGroupBy(key));
  };
  const aggregates = computed(() =>
    groupingAggregates({
      source: groupingSource(),
      columns: table.allColumns(),
      groupAggregates: extras.groupAggregates,
      panelDeclared,
    })
  );

  return computed((): TableGrouping<TRow> | undefined => {
    const collapsed = collapse();
    const pagingState = paging();
    const model = groupedRowModel({
      groupByKeys: groupByKeys(),
      source: groupingSource(),
      columns: table.allColumns(),
      locale: options.locale && readMaybe(options.locale),
      getRowId: (row) => table.rowKey(row),
      collapsedGroupIds: collapsed.collapsedGroupIds,
      aggregates: aggregates(),
      groupFooters: extras.groupFooters,
      groupSort: extras.groupSort,
      groupFilter: extras.groupFilter,
      groupPageSize: extras.groupPageSize,
      groupRowPageSize: extras.groupRowPageSize,
      paging: pagingState.paging,
      extraRows: extras.extraRows,
    });
    if (!model) return undefined;
    const { openGroups } = model;
    return {
      groupBy: groupByKeys(),
      collapsed,
      aggregates: aggregates().aggregates,
      entries: model.entries,
      setGroupBy,
      showMore: (entry) => {
        const request = groupShowMoreRequest(entry, {
          groupPageSize: extras.groupPageSize,
          groupRowPageSize: extras.groupRowPageSize,
        });
        pagingState.showMore(request.pageSize, request.groupKey);
        if (request.loadMoreKey !== undefined) {
          extras.onGroupLoadMore?.(request.loadMoreKey);
        }
      },
      expandAll: collapsed.expandAll,
      collapseAll: () => {
        collapsed.collapseToDepth(0, openGroups);
      },
      collapseToDepth: (depth) => {
        collapsed.collapseToDepth(depth, openGroups);
      },
    };
  });
}

/** Whether two key lists name the same keys in the same order. */
function sameKeys(left: readonly string[], right: readonly string[]): boolean {
  return (
    left.length === right.length &&
    left.every((key, index) => key === right[index])
  );
}

/** Whether two records hold the same value under every key. */
function sameFields(left: object, right: object): boolean {
  const leftRecord = left as Readonly<Record<string, unknown>>;
  const rightRecord = right as Readonly<Record<string, unknown>>;
  const keys = Object.keys(leftRecord);
  return (
    keys.length === Object.keys(rightRecord).length &&
    keys.every((key) => Object.is(leftRecord[key], rightRecord[key]))
  );
}

// packages/react/src/features/grouping.tsx
/**
 * Grouping — `@adapttable/<kit>/grouping`.
 *
 * Collapse, paging and the flat grouped model live on this entry. A table
 * that never imports it never carries that math. The hooks mount in-tree
 * through {@link GROUPING_LIVE}.
 */
import {
  aggregationModel,
  capabilityReason,
  computedAggregateKeys,
  computePagination,
  declaredAggregates,
  devWarn,
  effectiveAggregateOps,
  formatGroupBy,
  type GroupByInput,
  groupedEntriesForStrategy,
  groupingComputationKind,
  type GroupSort,
  insertExtraRows,
  parseGroupBy,
  serializeGroupAggregateOverrides,
  sourceCapabilities,
  withGroupAggregateOverrides,
} from "@adapttable/core";
import { type ReactNode, useCallback, useEffect, useMemo } from "react";

import { useGroupCollapse } from "../grouping/useGroupCollapse";
import { useGroupPaging } from "../grouping/useGroupPaging";
import { slotRender } from "./providers";
import { type ChromeExtraSlotProps, GROUPING_LIVE } from "./slotKeys";
import type { StaticTableFeature, TableFeature } from "./tableFeature";

function LiveGrouping({
  chrome,
  props,
  children,
}: ChromeExtraSlotProps<never>): ReactNode {
  const source = chrome.source;
  const requestedGroupBy =
    props.groupBy === undefined ? source.groupBy : props.groupBy;
  const groupByKeys = useMemo(
    () => parseGroupBy(requestedGroupBy),
    [requestedGroupBy]
  );
  const serverGroups = source.groups;
  const groupCollapse = useGroupCollapse({
    collapsedGroupIds: props.collapsedGroupIds,
    onCollapsedGroupIdsChange: props.onCollapsedGroupIdsChange,
  });
  const capabilities = source.capabilities;
  const canGroup = sourceCapabilities({
    allFilteredRows: source.allFilteredRows,
    groups: serverGroups,
    capabilities,
  }).grouping;
  useEffect(() => {
    if (groupByKeys.length === 0 || canGroup !== false) return;
    devWarn(
      `groupBy is ignored: ${capabilityReason("grouping")} Grouping needs either the full filtered set (\`allFilteredRows\`, which the frontend tier provides) or a source that groups server-side.`
    );
  }, [groupByKeys, canGroup]);

  const { onGroupByChange } = props;
  const { setGroupBy: sourceSetGroupBy } = source;
  const setGroupBy = useCallback(
    (key: GroupByInput) => {
      sourceSetGroupBy(formatGroupBy(key));
      onGroupByChange?.(parseGroupBy(key));
    },
    [onGroupByChange, sourceSetGroupBy]
  );
  const getRowId = chrome.getRowId;
  const groupPaging = useGroupPaging();
  const {
    groupAggregates,
    groupFooters,
    groupSort,
    groupFilter,
    groupPageSize,
    groupRowPageSize,
    onGroupLoadMore,
    extraRows,
  } = props;
  // The reader's aggregation choices, as a value. The mapper below is a new
  // closure every render, so nothing downstream can tell one choice from
  // another by identity — this is what says the answer changed.
  const aggregateOverrideKey = serializeGroupAggregateOverrides(
    source.groupAggregateOverrides ?? {}
  );
  const aggregationSource = useMemo(
    () => ({
      grouping: sourceCapabilities({
        allFilteredRows: source.allFilteredRows,
        groups: serverGroups,
        capabilities,
      }).grouping,
      aggregateOperations:
        source.honorsAggregates === false ? [] : source.aggregateOperations,
    }),
    [
      capabilities,
      serverGroups,
      source.aggregateOperations,
      source.allFilteredRows,
      source.honorsAggregates,
    ]
  );
  const effectiveGroupAggregates = useMemo(
    () =>
      withGroupAggregateOverrides(
        groupAggregates,
        source.groupAggregateOverrides ?? {},
        chrome.allColumns,
        aggregationSource
      ),
    [
      aggregationSource,
      chrome.allColumns,
      groupAggregates,
      source.groupAggregateOverrides,
    ]
  );

  const grouping = useMemo(() => {
    if (groupByKeys.length === 0) return undefined;
    const kind = groupingComputationKind({
      groupByKeys,
      sourceGroups: serverGroups,
      allFilteredRows: source.allFilteredRows,
      capabilities,
    });
    if (kind === "none") return undefined;
    const entries = groupedEntriesForStrategy({
      kind,
      groupByKeys,
      sourceGroups: serverGroups,
      allFilteredRows: source.allFilteredRows,
      columns: chrome.columnLayout.visibleColumns,
      getRowId,
      collapsedGroupIds: groupCollapse.collapsedGroupIds,
      aggregates: effectiveGroupAggregates,
      footers: groupFooters === true,
      sort: groupSort,
      filter: groupFilter,
      groupPageSize,
      rowPageSize: groupRowPageSize,
      paging: groupPaging.paging,
      derivedKey: aggregateOverrideKey,
      // Server groups: only metadata tied to the displayed response.
      // `undefined` means the operation is unknown — never the reader's
      // latest request. Local groups: the operation actually applied after
      // defaults, host declarations and validated overrides.
      aggregateOps:
        kind === "source"
          ? source.groupAggregations
          : effectiveAggregateOps({
              columns: chrome.allColumns,
              overrides: source.groupAggregateOverrides ?? {},
              declared:
                declaredAggregates(effectiveGroupAggregates) ??
                chrome.groupingPanel?.declaredAggregates,
              queryAggregates: source.queryAggregates,
              source: aggregationSource,
            }),
    });
    const openGroups = entries.flatMap((entry) =>
      entry.kind === "group" ? [{ key: entry.key, level: entry.level }] : []
    );
    const withExtras = insertExtraRows(entries, extraRows, (entry) =>
      entry.kind === "row" ? entry.key : undefined
    );
    return {
      groupBy: groupByKeys,
      collapsed: groupCollapse,
      aggregates: effectiveGroupAggregates,
      entries: withExtras,
      setGroupBy,
      showMore: (entry: { scope: "groups" | "rows"; groupKey?: string }) => {
        const size =
          entry.scope === "groups"
            ? (groupPageSize ?? 0)
            : (groupRowPageSize ?? 0);
        groupPaging.showMore(size, entry.groupKey);
        if (entry.scope === "rows" && entry.groupKey) {
          onGroupLoadMore?.(entry.groupKey);
        }
      },
      expandAll: groupCollapse.expandAll,
      collapseAll: () => {
        groupCollapse.collapseToDepth(0, openGroups);
      },
      collapseToDepth: (depth: number) => {
        groupCollapse.collapseToDepth(depth, openGroups);
      },
    };
  }, [
    groupByKeys,
    serverGroups,
    capabilities,
    source.allFilteredRows,
    chrome.columnLayout.visibleColumns,
    getRowId,
    groupCollapse,
    aggregateOverrideKey,
    source.groupAggregateOverrides,
    source.groupAggregations,
    effectiveGroupAggregates,
    groupFooters,
    groupSort,
    groupFilter,
    groupPageSize,
    groupRowPageSize,
    onGroupLoadMore,
    extraRows,
    groupPaging,
    setGroupBy,
    aggregationSource,
    chrome.allColumns,
    chrome.groupingPanel,
    source.queryAggregates,
  ]);

  const viewSource =
    grouping && source.allFilteredRows
      ? {
          ...source,
          rows: source.allFilteredRows,
          page: 1,
          limit: Math.max(source.allFilteredRows.length, 1),
          total: source.allFilteredRows.length,
          hasNextPage: false,
          isFetchingNextPage: false,
        }
      : source;
  const groupingArmed = grouping !== undefined;
  const groupingPanel = useMemo(() => {
    if (!chrome.groupingPanel) return undefined;
    const computedKeys = grouping
      ? computedAggregateKeys(grouping.entries)
      : [];
    return {
      ...chrome.groupingPanel,
      groupBy: groupByKeys,
      aggregations: aggregationModel({
        columns: chrome.allColumns,
        overrides: source.groupAggregateOverrides ?? {},
        declared: chrome.groupingPanel.declaredAggregates,
        queryAggregates: source.queryAggregates,
        computedKeys,
        source: aggregationSource,
      }),
    };
  }, [
    aggregationSource,
    chrome.allColumns,
    chrome.groupingPanel,
    groupByKeys,
    grouping,
    source.groupAggregateOverrides,
    source.queryAggregates,
  ]);
  return children({
    ...chrome,
    grouping,
    groupingPanel,
    groupingArmed,
    source: viewSource,
    editingRows: viewSource.rows,
    hasRowReorder: chrome.hasRowReorder,
    rowReorder: chrome.rowReorder,
    table: {
      ...chrome.table,
      pagination: computePagination({
        page: viewSource.page,
        limit: viewSource.limit,
        total: viewSource.total,
      }),
    },
  });
}

/**
 * What grouping can be told that says nothing about the row type.
 *
 * Paging, collapse state and the footer flag are the same whatever the table
 * holds, so configuring only these keeps the feature row-independent — and
 * composable into any table with no annotation.
 *
 * @public
 */
export interface StaticGroupingExtras {
  /** Told when the keys change, so a host can mirror them. */
  onGroupByChange?: (groupBy: readonly string[]) => void;
  /** Draw a footer row under each group. */
  groupFooters?: boolean;
  /** Show this many groups at a time. */
  groupPageSize?: number;
  /** Show this many rows inside each group. */
  groupRowPageSize?: number;
  /** Keep only the groups this accepts. */
  groupFilter?: (group: unknown) => boolean;
  /** Controlled collapse state. */
  collapsedGroupIds?: readonly string[];
  /** Told when a group opens or closes. */
  onCollapsedGroupIdsChange?: (ids: string[]) => void;
  /** Fetch the rest of a group on demand. */
  onGroupLoadMore?: (groupKey: string) => void;
}

/**
 * Everything grouping can be told, including the row-shaped parts.
 *
 * Supplying either of the two below makes the feature row-aware, and the row
 * comes from the callback you wrote — no type argument needed.
 *
 * @public
 */
export interface GroupingExtras<TRow> extends StaticGroupingExtras {
  /** Per-group subtotals, the same mapper shape as `summaryRow`. */
  groupAggregates?: (rows: readonly TRow[]) => unknown;
  /** Order the groups themselves. */
  groupSort?: GroupSort<TRow>;
}

/**
 * Group rows under collapsible headers.
 *
 * By a key alone this says nothing about the row type, so it composes into any
 * table with no annotation. Pass {@link GroupingExtras} and it becomes
 * row-aware, taking its row from the callback you supplied.
 *
 * @public
 */
export function grouping(
  groupBy: string | readonly string[]
): StaticTableFeature;
/**
 * Group rows with row-aware extras.
 *
 * @public
 */
export function grouping<TRow>(
  groupBy: string | readonly string[],
  extras: GroupingExtras<TRow>
): TableFeature<TRow>;
/**
 * Group rows under collapsible headers.
 *
 * @public
 */
export function grouping<TRow>(
  groupBy: string | readonly string[],
  extras?: GroupingExtras<TRow>
): TableFeature<TRow> {
  return {
    id: "grouping",
    apply: () => ({ groupBy, ...extras }),
    renders: [
      slotRender(GROUPING_LIVE, (props) => <LiveGrouping {...props} />),
    ],
  };
}

export type { GroupSort } from "@adapttable/core";
