// packages/angular/adapter-ng-zorro/src/components/savedViewsPanel.ts
/**
 * Manage saved views: apply, rename, reorder, default, delete.
 *
 * NG-ZORRO supplies the card, the row and the
 * controls are the binding's; this fills them with buttons and a text field.
 */
import type { SavedView, TableLabels } from "@adapttable/angular";
import {
  AdaptSavedViewGlyph,
  AdaptSavedViewsPanelChrome,
  type SavedViewsPanelSlots,
} from "@adapttable/angular/adapter";
import { NgTemplateOutlet } from "@angular/common";
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  input,
  type TemplateRef,
  viewChild,
} from "@angular/core";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzTagModule } from "ng-zorro-antd/tag";
import { NzTypographyModule } from "ng-zorro-antd/typography";

/** One row's layout, as the chrome computed it. */
interface SavedViewsLayoutView {
  readonly row: Readonly<Record<string, string>>;
  readonly caption: Readonly<Record<string, string>>;
  readonly controls: Readonly<Record<string, string>>;
  readonly control: Readonly<Record<string, string>>;
}

/** One icon control on a row. */
interface SavedViewControlView {
  readonly key: string;
  readonly label: string;
  readonly glyph: {
    readonly paths: readonly string[];
    readonly filled: boolean;
  };
  readonly onPress?: () => void;
  readonly pressed?: boolean;
}

/** What the card receives. */
interface SavedViewsSurfaceView {
  readonly title: string;
  readonly className?: string;
  readonly children?: TemplateRef<unknown>;
  readonly footer?: TemplateRef<unknown>;
}

/** What one row receives. */
interface SavedViewsRowView {
  readonly name?: TemplateRef<unknown>;
  readonly viewName: string;
  readonly isEditing: boolean;
  readonly isDefault: boolean;
  readonly readOnly: boolean;
  readonly defaultLabel: string;
  readonly readOnlyLabel: string;
  readonly onApply: () => void;
  readonly applyLabel: string;
  readonly controls: readonly SavedViewControlView[];
  readonly layout: SavedViewsLayoutView;
}

/** The rename field. */
interface SavedViewsInputView {
  readonly label: string;
  readonly value: string;
  readonly onChange: (next: string) => void;
  readonly onCommit: () => void;
  readonly onCancel: () => void;
}

/** The empty list. */
interface SavedViewsEmptyView {
  readonly message: string;
}

/** The name, growing, with the weight of the default view. */
function nameButtonStyle(isDefault: boolean): Record<string, string> {
  return {
    flex: "1 1 auto",
    minWidth: "0",
    textAlign: "start",
    fontWeight: isDefault ? "600" : "400",
  };
}

/** The card. */
@Component({
  selector: "adapt-saved-views-surface",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, NzCardModule, NzTypographyModule],
  template: `<nz-card
    nzSize="small"
    data-adapttable-part="saved-views-panel"
    [class]="props().className"
    style="min-width: 0"
  >
    <span
      nz-typography
      data-adapttable-part="saved-views-title"
      [style]="titleStyle"
      >{{ props().title }}</span
    >
    <div [style]="listStyle">
      @if (props().children; as children) {
        <ng-container [ngTemplateOutlet]="children" />
      }
    </div>
    @if (props().footer; as footer) {
      <span
        nz-typography
        data-adapttable-part="saved-views-footer"
        [style]="footerStyle"
      >
        <ng-container [ngTemplateOutlet]="footer" />
      </span>
    }
  </nz-card>`,
})
class AdaptSavedViewsSurface {
  readonly props = input.required<SavedViewsSurfaceView>();

  protected readonly titleStyle = {
    display: "block",
    marginBlockEnd: "8px",
    fontSize: "0.7rem",
    fontWeight: "700",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    opacity: "0.7",
  };

  protected readonly listStyle = {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    minWidth: "0",
  };

  protected readonly footerStyle = {
    display: "block",
    marginBlockStart: "10px",
    fontSize: "0.78rem",
    opacity: "0.75",
  };
}

/** One view: its name applies it, and the icon cluster follows. */
@Component({
  selector: "adapt-saved-views-row",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AdaptSavedViewGlyph, NgTemplateOutlet, NzButtonModule, NzTagModule],
  template: `<div
    data-adapttable-part="saved-view-row"
    [style]="props().layout.row"
  >
    <div
      data-adapttable-part="saved-view-caption"
      [style]="props().layout.caption"
    >
      @if (props().isEditing) {
        <ng-container [ngTemplateOutlet]="props().name" />
      } @else {
        <button
          nz-button
          type="button"
          [attr.title]="props().applyLabel"
          [style]="nameStyle()"
          (click)="props().onApply()"
        >
          <span>{{ props().viewName }} </span>
        </button>
      }
      @if (props().readOnly) {
        <nz-tag data-adapttable-part="saved-view-readonly">{{
          props().readOnlyLabel
        }}</nz-tag>
      }
      @if (props().isDefault) {
        <nz-tag data-adapttable-part="saved-view-default">{{
          props().defaultLabel
        }}</nz-tag>
      }
    </div>
    <div
      data-adapttable-part="saved-view-controls"
      [style]="props().layout.controls"
    >
      @for (control of props().controls; track control.key) {
        @if (control.onPress; as run) {
          <button
            nz-button
            type="button"
            [attr.data-control]="control.key"
            [style]="props().layout.control"
            [attr.aria-label]="control.label"
            [attr.aria-pressed]="control.pressed"
            [attr.title]="control.label"
            (click)="run()"
          >
            <adapt-saved-view-glyph [glyph]="control.glyph" />
          </button>
        } @else {
          <button
            nz-button
            type="button"
            disabled
            [attr.data-control]="control.key"
            [style]="props().layout.control"
            [attr.aria-label]="control.label"
            [attr.aria-pressed]="control.pressed"
            [attr.title]="control.label"
          >
            <adapt-saved-view-glyph [glyph]="control.glyph" />
          </button>
        }
      }
    </div>
  </div>`,
})
class AdaptSavedViewsRow {
  readonly props = input.required<SavedViewsRowView>();

  /** The name's weight: the default view is the one the table opens with. */
  protected readonly nameStyle = computed(() =>
    nameButtonStyle(this.props().isDefault)
  );
}

/**
 * The inline rename field. Focus moves here when the field arrives, because
 * a rename that leaves focus on the button it replaced is a rename the
 * keyboard cannot finish.
 */
@Component({
  selector: "adapt-saved-views-input",
  imports: [NzInputModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<input
    nz-input
    #box
    [attr.aria-label]="props().label"
    [value]="props().value"
    style="flex: 1 1 auto; min-width: 0"
    (input)="changed($event)"
    (keydown)="key($event)"
  />`,
})
class AdaptSavedViewsInput {
  readonly props = input.required<SavedViewsInputView>();

  private readonly box =
    viewChild.required<ElementRef<HTMLInputElement>>("box");

  constructor() {
    afterNextRender(() => {
      this.box().nativeElement.focus();
    });
  }

  /** Keep the draft as the reader types. */
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLInputElement).value);
  }

  /** Enter keeps the name. Escape puts the old one back. */
  protected key(event: KeyboardEvent): void {
    if (event.key === "Enter") this.props().onCommit();
    if (event.key === "Escape") this.props().onCancel();
  }
}

/** The empty list. */
@Component({
  selector: "adapt-saved-views-empty",
  imports: [NzTypographyModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p nz-typography>{{ props().message }}</p>`,
})
class AdaptSavedViewsEmpty {
  readonly props = input.required<SavedViewsEmptyView>();
}

const SLOTS: SavedViewsPanelSlots = {
  Surface: AdaptSavedViewsSurface,
  Row: AdaptSavedViewsRow,
  Input: AdaptSavedViewsInput,
  Empty: AdaptSavedViewsEmpty,
};

/**
 * The management card for a table's saved views.
 *
 * The toolbar menu switches views. This renames, reorders, picks the default
 * and deletes. Mount it where the list is managed; it does not replace the
 * menu.
 *
 * @public
 */
@Component({
  selector: "adapt-saved-views-panel",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AdaptSavedViewsPanelChrome],
  template: `<adapt-saved-views-panel-chrome
    [views]="views()"
    [onApply]="onApply()"
    [onRename]="onRename()"
    [onMove]="onMove()"
    [onSetDefault]="onSetDefault()"
    [onRemove]="onRemove()"
    [labels]="labels()"
    [footer]="footer()"
    [className]="className()"
    [slots]="slots"
  />`,
})
export class AdaptSavedViewsPanel {
  /** The list, in the order to show it. */
  readonly views = input.required<readonly SavedView[]>();

  /** Apply a view. */
  readonly onApply = input.required<(name: string) => void>();

  /** Rename a view. */
  readonly onRename = input.required<(from: string, to: string) => void>();

  /** Move a view by one step. */
  readonly onMove = input.required<(name: string, delta: number) => void>();

  /** Make a view the default, or clear it. */
  readonly onSetDefault = input.required<(name: string) => void>();

  /** Delete a view. */
  readonly onRemove = input.required<(name: string) => void>();

  /** Label overrides. Omitted keys keep the English default. */
  readonly labels = input<Partial<TableLabels>>();

  /** A note under the list. */
  readonly footer = input<TemplateRef<unknown> | string>();

  /** Class on the card. */
  readonly className = input<string>();

  /** The NG-ZORRO card, row, field and empty state. */
  protected readonly slots = SLOTS;
}

// packages/adapter-antd/src/components/SavedViewsPanel.tsx
/** The saved-views management panel, in Ant Design. */
import {
  SavedViewsPanelChrome,
  type SavedViewsPanelChromeProps,
  type SavedViewsPanelEmptyProps,
  type SavedViewsPanelInputProps,
  type SavedViewsPanelRowProps,
  type SavedViewsPanelSlots,
  type SavedViewsPanelSurfaceProps,
} from "@adapttable/core/adapter";
import { Button, Card, Flex, Input, Tag, Typography } from "antd";

const slots: SavedViewsPanelSlots = {
  Surface: ({
    children,
    className,
    title,
    footer,
    ...rest
  }: SavedViewsPanelSurfaceProps) => (
    <Card
      size="small"
      title={
        <span data-adapttable-part="saved-views-title">
          <Typography.Text type="secondary" style={{ fontSize: 11 }} strong>
            {title.toUpperCase()}
          </Typography.Text>
        </span>
      }
      className={className}
      {...rest}
    >
      <Flex vertical gap={2}>
        {children}
      </Flex>
      {footer && (
        <Typography.Text
          type="secondary"
          style={{ display: "block", marginBlockStart: 10, fontSize: 12 }}
          data-adapttable-part="saved-views-footer"
        >
          {footer}
        </Typography.Text>
      )}
    </Card>
  ),
  Empty: ({ message }: SavedViewsPanelEmptyProps) => (
    <Typography.Text type="secondary">{message}</Typography.Text>
  ),
  Input: ({
    label,
    ref,
    value,
    onChange,
    onCommit,
    onCancel,
  }: SavedViewsPanelInputProps) => (
    <Input
      size="small"
      value={value}
      ref={(instance) => {
        ref(instance?.input ?? null);
      }}
      aria-label={label}
      onChange={(event) => {
        onChange(event.target.value);
      }}
      onKeyDown={(event) => {
        if (event.key === "Enter") onCommit();
        if (event.key === "Escape") onCancel();
      }}
    />
  ),
  Row: ({
    name,
    viewName,
    isEditing,
    isDefault,
    readOnly,
    defaultLabel,
    readOnlyLabel,
    onApply,
    applyLabel,
    controls,
    layout,
    ...rest
  }: SavedViewsPanelRowProps) => (
    <div style={layout.row} {...rest}>
      <div style={layout.caption} data-adapttable-part="saved-view-caption">
        {isEditing ? (
          name
        ) : (
          <Button
            type="text"
            size="small"
            title={applyLabel}
            style={{
              flex: "1 1 auto",
              minWidth: 0,
              textAlign: "start",
              fontWeight: isDefault ? 600 : 400,
            }}
            onClick={onApply}
          >
            {viewName}
          </Button>
        )}
        {readOnly && (
          <Tag
            data-adapttable-part="saved-view-readonly"
            style={{ marginInlineEnd: 0 }}
          >
            {readOnlyLabel}
          </Tag>
        )}
        {isDefault && (
          <Tag
            data-adapttable-part="saved-view-default"
            style={{ marginInlineEnd: 0 }}
          >
            {defaultLabel}
          </Tag>
        )}
      </div>
      <div style={layout.controls} data-adapttable-part="saved-view-controls">
        {controls.map((control) => (
          <Button
            key={control.key}
            type="text"
            size="small"
            danger={control.danger}
            style={layout.control}
            aria-label={control.label}
            aria-pressed={control.pressed}
            title={control.label}
            icon={control.icon}
            disabled={!control.onPress}
            onClick={control.onPress}
          />
        ))}
      </div>
    </div>
  ),
};

/**
 * Manage saved views: apply, rename, reorder, default, delete.
 *
 * @public
 */
export function SavedViewsPanel(
  props: Readonly<Omit<SavedViewsPanelChromeProps, "slots">>
) {
  return <SavedViewsPanelChrome {...props} slots={slots} />;
}
