// packages/angular/adapter-ng-bootstrap/src/components/columnMenu.ts
/**
 * The Columns menu: a disclosure button and a panel where each column has a
 * reorder grip, an eye toggle, a pin toggle and a submenu of actions — drawn
 * with native controls, over the menu model in `@adapttable/angular`.
 */
import {
  ACTIONS_COLUMN_KEY,
  AdaptAttrs,
  AdaptIcon,
  AdaptLiveRegion,
  ADAPTTABLE_SLOT_TABLE,
  type ColumnDrag,
  type ColumnLayout,
  columnMenuActions,
  type ColumnMenuChoice,
  type ColumnMenuItem,
  type ColumnMenuRow,
  columnMenuRows,
  type ColumnMenuSlotProps,
  eyeIcon,
  filterColumnMenuRows,
  GRIP_ICON,
  hideAllColumns,
  injectColumnDrag,
  injectColumnRenameEditor,
  nextPinSide,
  PIN_ICON,
  pinActionLabel,
  REORDER_COLUMN_KEY,
  showAllColumns,
  unpinAllColumns,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  signal,
  viewChild,
} from "@angular/core";
import {
  NgbDropdown,
  NgbDropdownMenu,
  NgbDropdownToggle,
} from "@ng-bootstrap/ng-bootstrap/dropdown";

/** The menu's props, with the row type erased as every slot erases it. */

const NOOP_RENAME = (): void => undefined;

/** Whether a submenu item is a choice rather than a plain action. */
function isChoice(item: ColumnMenuItem): item is ColumnMenuChoice {
  return "kind" in item && item.kind === "choice";
}

/**
 * One column's row: grip, eye, name, pin, and the "more" submenu with the
 * rename editor.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-row",
  imports: [AdaptAttrs, AdaptIcon, AdaptLiveRegion],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let r = row();
    @let p = props();
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-hidden]="r.hidden ? '' : null"
      [attr.data-pinned]="r.pinned ?? null"
      [style.cursor]="r.canMove ? 'grab' : 'default'"
      [adaptAttrs]="
        r.canMove ? drag().rowAttrs(r.key, r.index, p.layout.move) : {}
      "
    >
      <span
        data-ng-bootstrap-part="column-menu-grip"
        [attr.aria-disabled]="r.canMove ? null : 'true'"
        [adaptAttrs]="
          r.canMove
            ? drag().gripAttrs(
                r.key,
                r.index,
                p.layout.move,
                p.labels.moveStart + ' / ' + p.labels.moveEnd + ': ' + r.name
              )
            : {}
        "
        ><svg [adaptIcon]="gripIcon"></svg
      ></span>
      <button
        class="btn btn-outline-secondary btn-sm"
        type="button"
        data-ng-bootstrap-part="column-menu-visibility"
        [attr.data-active]="r.hidden ? null : ''"
        [attr.aria-pressed]="!r.hidden"
        [attr.aria-label]="
          (r.hidden ? p.labels.showColumn : p.labels.hideColumn) + ': ' + r.name
        "
        [disabled]="!r.canHide"
        (click)="p.layout.toggleVisible(r.key)"
      >
        <svg [adaptIcon]="r.hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        data-ng-bootstrap-part="column-menu-label"
        [attr.data-hidden]="r.hidden ? '' : null"
        >{{ r.name }}</span
      >
      <button
        class="btn btn-outline-secondary btn-sm"
        type="button"
        data-ng-bootstrap-part="column-menu-pin"
        [attr.data-active]="r.pinned !== undefined ? '' : null"
        [attr.aria-pressed]="r.pinned !== undefined"
        [attr.aria-label]="pinLabel(r, p) + ': ' + r.name"
        [disabled]="!r.canPin"
        (click)="p.layout.setPinned(r.key, nextPin(r))"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
      <button
        class="btn btn-outline-secondary btn-sm"
        type="button"
        data-adapttable-part="column-menu-more"
        [attr.aria-expanded]="open()"
        [attr.aria-label]="p.labels.columnActions + ': ' + r.name"
        (click)="open.set(!open())"
      >
        ⋯
      </button>
      @if (open()) {
        <div data-adapttable-part="column-menu-submenu">
          @for (item of actions(); track item.id) {
            @if (asChoice(item); as choice) {
              <label data-adapttable-part="column-menu-choice">
                <span data-ng-bootstrap-part="column-menu-choice-label">{{
                  choice.label
                }}</span>
                <select
                  class="form-select form-select-sm"
                  data-ng-bootstrap-part="column-menu-choice-select"
                  [attr.aria-label]="choice.label"
                  [value]="choice.value"
                  [disabled]="choice.disabled"
                  (change)="choice.onChange($any($event.target).value)"
                >
                  @for (option of choice.options; track option.value) {
                    <option [value]="option.value">{{ option.label }}</option>
                  }
                </select>
              </label>
            } @else {
              <button
                class="btn btn-outline-secondary btn-sm"
                type="button"
                data-adapttable-part="column-menu-action"
                [disabled]="
                  asAction(item).disabled ||
                  (item.id === 'rename' && rename.editing())
                "
                (click)="runAction(item)"
              >
                {{ item.label }}
              </button>
            }
          }
          @if (rename.editing()) {
            <form
              data-adapttable-part="column-rename-form"
              (submit)="$event.preventDefault(); rename.submit()"
            >
              <label
                data-adapttable-part="column-rename-label"
                [attr.for]="rename.inputId"
                >{{ p.labels.columnName }}</label
              >
              <input
                class="form-control form-control-sm"
                data-adapttable-part="column-rename-input"
                [adaptAttrs]="rename.inputAttrs()"
              />
              @if (rename.error(); as error) {
                <span
                  data-adapttable-part="column-rename-error"
                  role="alert"
                  [attr.id]="rename.errorId"
                  >{{ error }}</span
                >
              }
              <button
                class="btn btn-outline-secondary btn-sm"
                type="submit"
                data-adapttable-part="column-rename-save"
              >
                {{ p.labels.saveColumnName }}
              </button>
              <button
                class="btn btn-outline-secondary btn-sm"
                type="button"
                data-adapttable-part="column-rename-cancel"
                (click)="rename.cancel()"
              >
                {{ p.labels.cancelColumnRename }}
              </button>
            </form>
          }
        </div>
      }
      <div
        [adaptLiveRegion]="rename.announcement()"
        part="column-rename-announcer"
      ></div>
    </div>
  `,
})
export class AdaptColumnMenuRow {
  /** The row. */
  readonly row = input.required<ColumnMenuRow<never>>();
  /** The menu's props. */
  readonly props = input.required<ColumnMenuSlotProps<never>>();
  /** The menu's drag state. */
  readonly drag = input.required<ColumnDrag>();

  protected readonly open = signal(false);
  protected readonly gripIcon = GRIP_ICON;
  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
  private readonly table = inject(ADAPTTABLE_SLOT_TABLE);

  protected readonly rename = injectColumnRenameEditor({
    column: computed(() => ({
      key: this.row().key,
      name: this.row().name,
      onRename: this.props().onRenameColumn ?? NOOP_RENAME,
      requiredMessage: this.props().labels.columnNameRequired,
      renamedMessage: this.props().labels.columnRenamed,
    })),
  });

  protected readonly actions = computed(() => {
    const props = this.props();
    return columnMenuActions(this.row(), {
      featureHost: this.table.featureHost as never,
      labels: props.labels,
      layout: props.layout,
      sortBy: props.sortBy,
      sortDir: props.sortDir,
      onSortColumn: props.onSortColumn,
      onAutoSizeColumn: props.onAutoSizeColumn,
      onFilterColumn: props.onFilterColumn,
      onBeginRename: props.onRenameColumn ? this.rename.begin : undefined,
      groupingPanel: props.groupingPanel,
    });
  });

  protected pinLabel(
    row: ColumnMenuRow<never>,
    props: ColumnMenuSlotProps<never>
  ): string {
    return pinActionLabel(row.pinned, props.labels);
  }

  protected nextPin(row: ColumnMenuRow<never>): ReturnType<typeof nextPinSide> {
    return nextPinSide(row.pinned);
  }

  protected asChoice(item: ColumnMenuItem): ColumnMenuChoice | undefined {
    return isChoice(item) ? item : undefined;
  }

  protected asAction(item: ColumnMenuItem): { disabled: boolean } {
    return item;
  }

  protected runAction(item: ColumnMenuItem): void {
    if (isChoice(item)) return;
    item.run();
    if (item.id !== "rename") this.open.set(false);
  }
}

/**
 * A reserved column's row — row actions or the reorder grip — with its eye
 * and a one-click pin to the edge it always sits at.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-edge-row",
  imports: [AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let hidden = layout().isHidden(columnKey());
    @let pinned = layout().state.pinned[columnKey()] !== undefined;
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-actions]="side() === 'end' ? '' : null"
      [attr.data-reorder]="side() === 'start' ? '' : null"
      [attr.data-hidden]="hidden ? '' : null"
      [attr.data-pinned]="pinned ? side() : null"
    >
      <button
        class="btn btn-outline-secondary btn-sm"
        type="button"
        data-ng-bootstrap-part="column-menu-visibility"
        [attr.data-active]="hidden ? null : ''"
        [attr.aria-pressed]="!hidden"
        [attr.aria-label]="(hidden ? showLabel() : hideLabel()) + ': ' + name()"
        (click)="layout().toggleVisible(columnKey())"
      >
        <svg [adaptIcon]="hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        data-ng-bootstrap-part="column-menu-label"
        [attr.data-hidden]="hidden ? '' : null"
        >{{ name() }}</span
      >
      <button
        class="btn btn-outline-secondary btn-sm"
        type="button"
        data-ng-bootstrap-part="column-menu-pin"
        [attr.data-active]="pinned ? '' : null"
        [attr.aria-pressed]="pinned"
        [attr.aria-label]="(pinned ? unpinLabel() : pinLabel()) + ': ' + name()"
        (click)="layout().setPinned(columnKey(), pinned ? undefined : side())"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
    </div>
  `,
})
export class AdaptColumnMenuEdgeRow {
  /** The column layout. */
  readonly layout = input.required<ColumnLayout<never>>();
  /** The reserved column's key. */
  readonly columnKey = input.required<string>();
  /** The edge it pins to. */
  readonly side = input.required<"start" | "end">();
  /** Its name. */
  readonly name = input.required<string>();
  /** "Show column". */
  readonly showLabel = input.required<string>();
  /** "Hide column". */
  readonly hideLabel = input.required<string>();
  /** "Pin to start" or "Pin to end". */
  readonly pinLabel = input.required<string>();
  /** "Unpin". */
  readonly unpinLabel = input.required<string>();

  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
}

/**
 * The Columns menu in the toolbar.
 *
 * @public
 */
@Component({
  selector: "adapt-column-menu",
  imports: [
    AdaptColumnMenuRow,
    AdaptColumnMenuEdgeRow,
    NgbDropdown,
    NgbDropdownMenu,
    NgbDropdownToggle,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <div
      #root
      ngbDropdown
      autoClose="outside"
      (openChange)="menuOpen.set($event)"
      data-ng-bootstrap-part="column-menu"
      style="position: relative"
    >
      <button
        class="btn btn-outline-secondary btn-sm"
        #trigger
        ngbDropdownToggle
        type="button"
        data-adapttable-part="column-menu-button"
        aria-haspopup="true"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
      >
        {{ p.labels.columns }}
      </button>
      <div ngbDropdownMenu>
        @if (popover.open()) {
          <fieldset
            #panel
            data-ng-bootstrap-part="column-menu-panel"
            [attr.aria-label]="p.labels.columns"
            [attr.dir]="p.dir ?? null"
            [style]="panelStyle"
          >
            <div data-ng-bootstrap-part="column-menu-header">
              <span data-ng-bootstrap-part="column-menu-title">{{
                p.labels.columns
              }}</span>
            </div>
            <input
              class="form-control form-control-sm"
              type="search"
              data-adapttable-part="column-menu-search"
              [attr.placeholder]="p.labels.searchColumns"
              [attr.aria-label]="p.labels.searchColumns"
              [value]="query()"
              (input)="query.set($any($event.target).value)"
            />
            <div data-adapttable-part="column-menu-bulk">
              <button
                class="btn btn-outline-secondary btn-sm"
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="showAll()"
              >
                {{ p.labels.showAllColumns }}
              </button>
              <button
                class="btn btn-outline-secondary btn-sm"
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="hideAll()"
              >
                {{ p.labels.hideAllColumns }}
              </button>
              <button
                class="btn btn-outline-secondary btn-sm"
                type="button"
                data-adapttable-part="column-menu-bulk-button"
                (click)="unpinAll()"
              >
                {{ p.labels.unpinAllColumns }}
              </button>
            </div>
            @for (row of rows(); track row.key) {
              <adapt-column-menu-row [row]="row" [props]="p" [drag]="drag" />
            }
            @if (p.hasRowReorder || p.hasRowActions) {
              <hr data-ng-bootstrap-part="column-menu-separator" />
            }
            @if (p.hasRowReorder) {
              <adapt-column-menu-edge-row
                [layout]="p.layout"
                [columnKey]="reorderKey"
                side="start"
                [name]="p.labels.reorderRow"
                [showLabel]="p.labels.showColumn"
                [hideLabel]="p.labels.hideColumn"
                [pinLabel]="p.labels.pinStart"
                [unpinLabel]="p.labels.unpin"
              />
            }
            @if (p.hasRowActions) {
              <adapt-column-menu-edge-row
                [layout]="p.layout"
                [columnKey]="actionsKey"
                side="end"
                [name]="p.labels.actions"
                [showLabel]="p.labels.showColumn"
                [hideLabel]="p.labels.hideColumn"
                [pinLabel]="p.labels.pinEnd"
                [unpinLabel]="p.labels.unpin"
              />
            }
            <button
              class="btn btn-outline-secondary btn-sm"
              type="button"
              data-ng-bootstrap-part="column-menu-auto-size"
              (click)="p.onAutoSize()"
            >
              {{ p.labels.autoSizeColumns }}
            </button>
            <button
              class="btn btn-outline-secondary btn-sm"
              type="button"
              data-ng-bootstrap-part="column-menu-reset"
              (click)="p.layout.reset()"
            >
              {{ p.labels.resetColumns }}
            </button>
          </fieldset>
        }
      </div>
    </div>
  `,
})
export class AdaptColumnMenu {
  /** The slot's props. */
  readonly props = input.required<ColumnMenuSlotProps<never>>();

  protected readonly query = signal("");
  protected readonly panelStyle = {
    "max-height": "min(70vh, 32rem)",
    "overflow-y": "auto",
    border: "0",
    padding: "0.75rem",
  };
  protected readonly reorderKey = REORDER_COLUMN_KEY;
  protected readonly actionsKey = ACTIONS_COLUMN_KEY;
  protected readonly drag = injectColumnDrag();
  protected readonly rows = computed(() =>
    filterColumnMenuRows(
      columnMenuRows(this.props().allColumns, this.props().layout),
      this.query()
    )
  );

  protected readonly menuOpen = signal(false);
  private readonly dropdown = viewChild(NgbDropdown);
  protected readonly popover = {
    open: this.menuOpen.asReadonly(),
    toggle: (): void => this.dropdown()?.toggle(),
    close: (): void => this.dropdown()?.close(),
  };

  protected showAll(): void {
    showAllColumns(this.rows(), this.props().layout);
  }

  protected hideAll(): void {
    hideAllColumns(this.rows(), this.props().layout);
  }

  protected unpinAll(): void {
    unpinAllColumns(this.rows(), this.props().layout);
  }
}

// packages/adapter-mantine/src/components/ColumnMenu.tsx
import {
  ACTIONS_COLUMN_KEY,
  columnMenuRows,
  columnReorderKeyProps,
  REORDER_COLUMN_KEY,
  useColumnDragState,
  type UseColumnLayoutResult,
} from "@adapttable/core";
import {
  columnMenuActions,
  type ColumnMenuItem,
  type ColumnMenuLabels,
  type ColumnMenuRow,
  type ColumnMenuSlotProps,
  type ColumnRenameEditorState,
  EyeIcon,
  filterColumnMenuRows,
  GripIcon,
  type GroupingPanelState,
  hideAllColumns,
  LiveRegion,
  nextPinSide,
  pinActionLabel,
  PinIcon,
  showAllColumns,
  unpinAllColumns,
  useColumnRenameEditor,
  useFeatureHost,
} from "@adapttable/core/adapter";
import {
  ActionIcon,
  Box,
  Button,
  Divider,
  Group,
  Popover,
  Select,
  Text,
  TextInput,
} from "@mantine/core";
import { useEffect, useRef, useState } from "react";

import { useEscapeClose } from "./useEscapeClose";

/** The shared Columns-menu contract, declared once in core. */
export type ColumnMenuProps<TRow> = ColumnMenuSlotProps<TRow>;

const NOOP_RENAME = () => undefined;

/** The eye toggle + struck-through name shared by data and actions rows. */
function RowVisibility({
  hidden,
  name,
  labels,
  onToggle,
  disabled = false,
}: Readonly<{
  hidden: boolean;
  name: string;
  labels: Pick<ColumnMenuLabels, "showColumn" | "hideColumn">;
  onToggle: () => void;
  disabled?: boolean;
}>) {
  return (
    <>
      <ActionIcon
        variant={hidden ? "subtle" : "light"}
        color={hidden ? "gray" : "blue"}
        size="sm"
        aria-label={`${hidden ? labels.showColumn : labels.hideColumn}: ${name}`}
        aria-pressed={!hidden}
        disabled={disabled}
        onClick={onToggle}
      >
        <EyeIcon off={hidden} />
      </ActionIcon>
      <Text
        size="sm"
        style={{ flex: 1 }}
        c={hidden ? "dimmed" : undefined}
        td={hidden ? "line-through" : undefined}
      >
        {name}
      </Text>
    </>
  );
}

/** The pin control shared by data and actions rows. */
function PinToggle({
  pinned,
  label,
  onClick,
  disabled = false,
}: Readonly<{
  pinned: boolean;
  label: string;
  onClick: () => void;
  disabled?: boolean;
}>) {
  return (
    <ActionIcon
      variant={pinned ? "filled" : "subtle"}
      color={pinned ? "blue" : "gray"}
      size="sm"
      aria-label={label}
      disabled={disabled}
      onClick={onClick}
    >
      <PinIcon />
    </ActionIcon>
  );
}

function ColumnRenameForm({
  rename,
  labels,
}: Readonly<{
  rename: ColumnRenameEditorState;
  labels: ColumnMenuLabels;
}>) {
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    inputRef.current?.focus();
  }, []);
  return (
    <Box
      component="form"
      data-adapttable-part="column-rename-form"
      p={4}
      onSubmit={(event) => {
        event.preventDefault();
        rename.submit();
      }}
    >
      <TextInput
        ref={inputRef}
        id={rename.inputId}
        size="xs"
        label={labels.columnName}
        labelProps={{
          "data-adapttable-part": "column-rename-label",
        }}
        value={rename.draft}
        error={rename.error}
        errorProps={{
          id: rename.errorId,
          role: "alert",
          "data-adapttable-part": "column-rename-error",
        }}
        data-adapttable-part="column-rename-input"
        aria-invalid={rename.error ? "true" : undefined}
        aria-describedby={rename.error ? rename.errorId : undefined}
        onChange={(event) => rename.setDraft(event.currentTarget.value)}
        onBlur={rename.blur}
        onKeyDown={rename.onKeyDown}
      />
      <Group gap={4} mt={4}>
        <Button
          type="submit"
          size="xs"
          data-adapttable-part="column-rename-save"
        >
          {labels.saveColumnName}
        </Button>
        <Button
          type="button"
          variant="subtle"
          size="xs"
          data-adapttable-part="column-rename-cancel"
          onClick={rename.cancel}
        >
          {labels.cancelColumnRename}
        </Button>
      </Group>
    </Box>
  );
}

function ColumnSubmenu({
  actions,
  rename,
  labels,
  onClose,
}: Readonly<{
  actions: readonly ColumnMenuItem[];
  rename: ColumnRenameEditorState;
  labels: ColumnMenuLabels;
  onClose: () => void;
}>) {
  return (
    <Box data-adapttable-part="column-menu-submenu" px={4} pb={4}>
      {actions.map((action) =>
        "kind" in action ? (
          <Select
            key={action.id}
            label={action.label}
            aria-label={action.label}
            size="xs"
            value={action.value}
            disabled={action.disabled}
            allowDeselect={false}
            data-adapttable-part="column-menu-choice"
            data={action.options.map((option) => ({
              value: option.value,
              label: option.label,
            }))}
            comboboxProps={{ withinPortal: false }}
            onChange={(value) => {
              if (value !== null) action.onChange(value);
            }}
          />
        ) : (
          <Button
            key={action.id}
            variant="subtle"
            size="xs"
            fullWidth
            justify="flex-start"
            data-adapttable-part="column-menu-action"
            disabled={
              action.disabled || (action.id === "rename" && rename.editing)
            }
            onClick={() => {
              action.run();
              if (action.id !== "rename") onClose();
            }}
          >
            {action.label}
          </Button>
        )
      )}
      {rename.editing ? (
        <ColumnRenameForm rename={rename} labels={labels} />
      ) : null}
    </Box>
  );
}

/**
 * The injected actions column's menu row: the same eye toggle as data
 * columns plus a pin toggle that flips right ↔ unpinned in one click. No
 * drag grip (the column always trails) and no left pin.
 */
function ActionsRow<TRow>({
  layout,
  labels,
}: Readonly<{
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuProps<TRow>["labels"];
}>) {
  const hidden = layout.isHidden(ACTIONS_COLUMN_KEY);
  const pinned = layout.state.pinned[ACTIONS_COLUMN_KEY] === "end";
  return (
    <Group justify="flex-start" wrap="nowrap" gap={6} px={4} py={2}>
      {/* Spacer where data rows show the drag grip, keeping toggles aligned. */}
      <Box w={22} />
      <RowVisibility
        hidden={hidden}
        name={labels.actions}
        labels={labels}
        onToggle={() => layout.toggleVisible(ACTIONS_COLUMN_KEY)}
      />
      <PinToggle
        pinned={pinned}
        label={`${pinned ? labels.unpin : labels.pinEnd}: ${labels.actions}`}
        onClick={() =>
          layout.setPinned(ACTIONS_COLUMN_KEY, pinned ? undefined : "end")
        }
      />
    </Group>
  );
}

function ReorderRow<TRow>({
  layout,
  labels,
}: Readonly<{
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuProps<TRow>["labels"];
}>) {
  const hidden = layout.isHidden(REORDER_COLUMN_KEY);
  const pinned = layout.state.pinned[REORDER_COLUMN_KEY] !== undefined;
  return (
    <div data-adapttable-part="column-menu-item" data-reorder="">
      <Group justify="flex-start" wrap="nowrap" gap={6} px={4} py={2}>
        <Box w={22} />
        <RowVisibility
          hidden={hidden}
          name={labels.reorderRow}
          labels={labels}
          onToggle={() => layout.toggleVisible(REORDER_COLUMN_KEY)}
        />
        <PinToggle
          pinned={pinned}
          label={`${pinned ? labels.unpin : labels.pinStart}: ${labels.reorderRow}`}
          onClick={() =>
            layout.setPinned(REORDER_COLUMN_KEY, pinned ? undefined : "start")
          }
        />
      </Group>
    </div>
  );
}

function ColumnMenuRowItem<TRow>({
  row,
  layout,
  labels,
  drag,
  sortBy,
  sortDir,
  onSortColumn,
  onAutoSizeColumn,
  onFilterColumn,
  onRenameColumn,
  groupingPanel,
}: Readonly<{
  row: ColumnMenuRow<TRow>;
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuLabels;
  drag: ReturnType<typeof useColumnDragState>;
  sortBy?: string;
  sortDir?: "asc" | "desc";
  onSortColumn?: (key: string, dir: "asc" | "desc") => void;
  onAutoSizeColumn?: (key: string) => void;
  onFilterColumn?: (key: string) => void;
  onRenameColumn?: (key: string, name: string) => void;
  groupingPanel?: GroupingPanelState;
}>) {
  const { key, name, hidden, pinned, index, canMove, canHide, canPin } = row;
  const [open, setOpen] = useState(false);
  const featureHost = useFeatureHost<TRow>();
  const rename = useColumnRenameEditor({
    key,
    name,
    onRename: onRenameColumn ?? NOOP_RENAME,
    requiredMessage: labels.columnNameRequired,
    renamedMessage: labels.columnRenamed,
  });
  const actions = columnMenuActions(row, {
    featureHost,
    labels,
    layout,
    sortBy,
    sortDir,
    onSortColumn,
    onAutoSizeColumn,
    onFilterColumn,
    onBeginRename: onRenameColumn ? rename.begin : undefined,
    groupingPanel,
  });
  const indicator = canMove ? drag.rowAttrs(key, index) : {};
  const edge = indicator["data-drop"];
  const edgeOffset = edge === "before" ? "2px" : "-2px";
  return (
    <div
      data-adapttable-part="column-menu-item"
      data-hidden={hidden || undefined}
      data-pinned={pinned}
    >
      <Group
        justify="flex-start"
        wrap="nowrap"
        gap={6}
        px={4}
        py={2}
        style={{
          cursor: canMove ? "grab" : "default",
          opacity: "data-dragging" in indicator ? 0.4 : undefined,
          boxShadow: edge
            ? `inset 0 ${edgeOffset} 0 0 var(--mantine-primary-color-filled)`
            : undefined,
        }}
        {...(canMove
          ? {
              ...drag.rowDragProps(key, index),
              ...drag.dropProps(index, layout.move),
              ...indicator,
            }
          : {})}
      >
        <ActionIcon
          variant="subtle"
          color="gray"
          size="sm"
          disabled={!canMove}
          style={{ cursor: canMove ? "grab" : "default" }}
          {...(canMove
            ? columnReorderKeyProps(
                key,
                index,
                layout.move,
                `${labels.moveStart} / ${labels.moveEnd}: ${name}`
              )
            : {})}
        >
          <GripIcon />
        </ActionIcon>
        <RowVisibility
          hidden={hidden}
          name={name}
          labels={labels}
          disabled={!canHide}
          onToggle={() => layout.toggleVisible(key)}
        />
        <PinToggle
          pinned={pinned !== undefined}
          label={`${pinActionLabel(pinned, labels)}: ${name}`}
          disabled={!canPin}
          onClick={() => layout.setPinned(key, nextPinSide(pinned))}
        />
        <ActionIcon
          variant="subtle"
          color="gray"
          size="sm"
          data-adapttable-part="column-menu-more"
          aria-expanded={open}
          aria-label={`${labels.columnActions}: ${name}`}
          onClick={() => setOpen((value) => !value)}
        >
          ⋯
        </ActionIcon>
      </Group>
      {open ? (
        <ColumnSubmenu
          actions={actions}
          rename={rename}
          labels={labels}
          onClose={() => setOpen(false)}
        />
      ) : null}
      <LiveRegion part="column-rename-announcer" statusRole={false}>
        {rename.announcement}
      </LiveRegion>
    </div>
  );
}

/**
 * Column-management popover: per-column drag grip (reorder), eye (show/hide),
 * and pin toggle. Keyboard users focus a grip and use arrow keys.
 */
export function ColumnMenu<TRow>({
  allColumns,
  layout,
  labels,
  hasRowActions = false,
  hasRowReorder = false,
  onAutoSize,
  onAutoSizeColumn,
  onSortColumn,
  onFilterColumn,
  onRenameColumn,
  sortBy,
  sortDir,
  dir,
  groupingPanel,
}: Readonly<ColumnMenuProps<TRow>>) {
  const drag = useColumnDragState();
  const [opened, setOpened] = useState(false);
  const [query, setQuery] = useState("");
  const rows = filterColumnMenuRows(columnMenuRows(allColumns, layout), query);
  useEscapeClose(opened, () => setOpened(false));
  // A Popover, not a Menu: the panel holds checkboxes, drag handles and
  // buttons, so `role="menu"` semantics (menuitem children) would be a lie.
  return (
    <Popover
      opened={opened}
      onChange={(nextOpened) => {
        if (!nextOpened) setOpened(false);
      }}
      position="bottom-end"
      withinPortal
      returnFocus
      zIndex={10050}
      middlewares={{ flip: false, shift: { padding: 8, mainAxis: false } }}
    >
      <Popover.Target>
        <Button
          variant="default"
          size="sm"
          aria-expanded={opened}
          data-adapttable-part="column-menu-button"
          onClick={() => setOpened((value) => !value)}
        >
          {labels.columns}
        </Button>
      </Popover.Target>
      <Popover.Dropdown dir={dir} aria-label={labels.columns}>
        <Box
          p={4}
          miw={250}
          mah="min(70vh, 480px)"
          style={{ overflowY: "auto" }}
        >
          <Text size="xs" c="dimmed" fw={600} tt="uppercase" px={4} pb={6}>
            {labels.columns}
          </Text>
          <TextInput
            type="search"
            size="xs"
            mb={6}
            data-adapttable-part="column-menu-search"
            placeholder={labels.searchColumns}
            aria-label={labels.searchColumns}
            value={query}
            onChange={(event) => setQuery(event.currentTarget.value)}
          />
          <Group gap={4} mb={6} px={4} data-adapttable-part="column-menu-bulk">
            <Button
              variant="subtle"
              size="xs"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => showAllColumns(rows, layout)}
            >
              {labels.showAllColumns}
            </Button>
            <Button
              variant="subtle"
              size="xs"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => hideAllColumns(rows, layout)}
            >
              {labels.hideAllColumns}
            </Button>
            <Button
              variant="subtle"
              size="xs"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => unpinAllColumns(rows, layout)}
            >
              {labels.unpinAllColumns}
            </Button>
          </Group>
          {rows.map((row) => (
            <ColumnMenuRowItem
              key={row.key}
              row={row}
              layout={layout}
              labels={labels}
              drag={drag}
              sortBy={sortBy}
              sortDir={sortDir}
              onSortColumn={onSortColumn}
              onAutoSizeColumn={onAutoSizeColumn}
              onFilterColumn={onFilterColumn}
              onRenameColumn={onRenameColumn}
              groupingPanel={groupingPanel}
            />
          ))}
          {(hasRowReorder || hasRowActions) && <Divider my={4} />}
          {hasRowReorder && <ReorderRow layout={layout} labels={labels} />}
          {hasRowActions && <ActionsRow layout={layout} labels={labels} />}
          <Divider my={4} />
          <Button
            variant="subtle"
            size="xs"
            fullWidth
            justify="flex-start"
            onClick={onAutoSize}
          >
            {labels.autoSizeColumns}
          </Button>
          <Button
            variant="subtle"
            size="xs"
            fullWidth
            justify="flex-start"
            onClick={() => layout.reset()}
          >
            {labels.resetColumns}
          </Button>
        </Box>
      </Popover.Dropdown>
    </Popover>
  );
}
