// packages/react/adapter-radix/src/assistant.tsx
/**
 * The assistant panel in Radix Themes — `@adapttable/radix/assistant`.
 *
 * Radix Themes ships no Drawer, so the narrow-viewport surface is its Dialog:
 * a real modal with the focus trap and backdrop the primitive already owns.
 */
import {
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  TableAssistantChrome,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantProps,
  type TableAssistantSheetProps,
  type TableAssistantWindowProps,
} from "@adapttable/react/adapter";
import {
  Badge,
  Button,
  Card,
  Dialog,
  DropdownMenu,
  IconButton,
  Text,
  TextArea,
} from "@radix-ui/themes";

import { NativeSelect } from "./components/primitives";

const BADGE_COLOR = {
  neutral: "gray",
  busy: "blue",
  warning: "amber",
  danger: "red",
} as const;

/** How this kit spells the three prominences the chrome asks for. */
const KIT_VARIANT = {
  primary: "solid",
  secondary: "surface",
  subtle: "ghost",
} as const;

function AssistantButton({
  label,
  part,
  className,
  onClick,
  disabled,
  children,
  expanded,
  icon,
  iconOnly,
  tooltip,
  variant = "secondary",
}: Readonly<TableAssistantButtonProps>) {
  const launcher = part === "assistant-launcher";
  if (iconOnly) {
    const control = (
      <IconButton
        type="button"
        size={launcher ? "4" : "1"}
        radius={launcher ? "full" : undefined}
        {...(launcher ? { style: { width: 56, height: 56 } } : {})}
        variant={variant === "primary" ? "solid" : "ghost"}
        color={variant === "primary" ? undefined : "gray"}
        aria-label={label}
        title={tooltip}
        aria-expanded={expanded}
        data-adapttable-part={part}
        className={className}
        disabled={disabled}
        onClick={onClick}
      >
        {icon}
      </IconButton>
    );
    // Radix's Tooltip mounts its own dismissable layer. Inside the sheet that
    // layer becomes the topmost one and swallows Escape, so the dialog stops
    // closing. `title` gives the same hint without another layer.
    return control;
  }
  return (
    <Button
      type="button"
      size="1"
      variant={KIT_VARIANT[variant]}
      aria-label={label}
      aria-expanded={expanded}
      data-adapttable-part={part}
      className={className}
      disabled={disabled}
      onClick={onClick}
    >
      {children ?? label}
    </Button>
  );
}

function AssistantInput({
  label,
  placeholder,
  part,
  className,
  value,
  disabled,
  onChange,
  onKeyDown,
}: Readonly<TableAssistantComposerProps>) {
  return (
    <TextArea
      size="1"
      rows={2}
      style={{ width: "100%" }}
      aria-label={label}
      placeholder={placeholder}
      data-adapttable-part={part}
      className={className}
      value={value}
      disabled={disabled}
      onChange={(event) => {
        onChange(event.target.value);
      }}
      onKeyDown={onKeyDown}
    />
  );
}

function AssistantBadge({
  label,
  part,
  className,
  tone,
}: Readonly<TableAssistantBadgeProps>) {
  return (
    <Badge
      size="1"
      variant="soft"
      color={BADGE_COLOR[tone]}
      data-adapttable-part={part}
      data-tone={tone}
      className={className}
    >
      {label}
    </Badge>
  );
}

function AssistantPanel({
  label,
  part,
  className,
  children,
}: Readonly<TableAssistantPanelProps>) {
  return (
    <Card
      size="1"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{
        height: "100%",
        minHeight: 0,
        display: "flex",
        flexDirection: "column",
      }}
    >
      {children}
    </Card>
  );
}

function AssistantSheet({
  label,
  part,
  className,
  open,
  onClose,
  dir,
  children,
}: Readonly<TableAssistantSheetProps>) {
  return (
    <Dialog.Root
      open={open}
      onOpenChange={(next) => {
        if (!next) onClose();
      }}
    >
      <Dialog.Content
        aria-label={label}
        dir={dir}
        data-adapttable-part={part}
        className={className}
        style={{
          height: "90dvh",
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
        }}
      >
        <Dialog.Title style={{ margin: 0 }}>{label}</Dialog.Title>
        {children}
      </Dialog.Content>
    </Dialog.Root>
  );
}

function AssistantWindow({
  label,
  part,
  className,
  style,
  children,
}: Readonly<TableAssistantWindowProps>) {
  return (
    <Card
      size="2"
      role="dialog"
      aria-label={label}
      data-adapttable-part={part}
      className={className}
      style={{ ...style, boxShadow: "var(--shadow-5)" }}
    >
      {children}
    </Card>
  );
}

/**
 * Ask this table a question, in Radix Themes.
 *
 * @public
 */
/**
 * The dictation language chooser, in Radix Themes.
 *
 * Drawn only beside a mic that is already there, and only when more than one
 * language is offered — the chrome decides both. This is the kit's own
 * chooser, not a button with a list bolted on.
 */
function AssistantLanguageChip({
  label,
  value,
  options,
  part,
  className,
  onChange,
  disabled,
}: Readonly<TableAssistantLanguageChipProps>) {
  return (
    <NativeSelect
      size="1"
      width="7.5rem"
      className={className}
      aria-label={label}
      data-adapttable-part={part}
      value={value}
      disabled={disabled}
      options={options}
      onValueChange={onChange}
    />
  );
}

/**
 * The examples menu, as a Radix Themes dropdown — the same surface, the same
 * dismissal and the same typeahead as every other menu in the kit.
 */
function AssistantMenu({
  label,
  part,
  className,
  icon,
  disabled,
  items,
  onSelect,
  maxHeight,
}: Readonly<TableAssistantMenuProps>) {
  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger disabled={disabled}>
        <IconButton
          type="button"
          size="2"
          variant="ghost"
          color="gray"
          aria-label={label}
          title={label}
          data-adapttable-part={part}
          className={className}
          disabled={disabled}
        >
          {icon}
        </IconButton>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content
        side="top"
        align="start"
        style={{ maxHeight, overflowY: "auto" }}
      >
        {items.map((item) => (
          <DropdownMenu.Item
            key={item.id}
            data-adapttable-part={item.part}
            onSelect={() => {
              onSelect(item.id);
            }}
          >
            <span
              style={{
                display: "flex",
                gap: "var(--space-2)",
                alignItems: "flex-start",
              }}
            >
              {item.icon}
              <span>
                <Text size="2" as="div">
                  {item.title}
                </Text>
                {item.description ? (
                  <Text size="1" color="gray" as="div">
                    {item.description}
                  </Text>
                ) : null}
              </span>
            </span>
          </DropdownMenu.Item>
        ))}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
}

export function TableAssistant(props: Readonly<TableAssistantProps>) {
  return (
    <TableAssistantChrome
      // The colour the conversation is drawn in. Radix Themes' accent scale, step 9 — its solid accent.
      // Before the spread, so a host that names its own still wins.
      accent="var(--accent-9, currentColor)"
      {...props}
      slots={{
        Panel: AssistantPanel,
        Sheet: AssistantSheet,
        Button: AssistantButton,
        Composer: AssistantInput,
        Badge: AssistantBadge,
        Window: AssistantWindow,
        Menu: AssistantMenu,
        LanguageChip: AssistantLanguageChip,
      }}
    />
  );
}

/**
 * Bind this kit's assistant panel to the assistant slot.
 *
 * @public
 */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(TableAssistant);
}

// packages/angular/adapter-angular-aria/assistant/assistant.ts
/** Native HTML is this kit: buttons, textarea, disclosure and dialog. */
import type { TableAssistantProps } from "@adapttable/angular";
import {
  AdaptAssistantContent,
  AdaptTableAssistantChrome,
  createAdapterTableAssistantFeature,
  type TableAssistantBadgeProps,
  type TableAssistantButtonProps,
  type TableAssistantComposerProps,
  type TableAssistantLanguageChipProps,
  type TableAssistantMenuProps,
  type TableAssistantPanelProps,
  type TableAssistantSheetProps,
  type TableAssistantSlots,
  type TableAssistantWindowProps,
} from "@adapttable/angular/adapter";
import { NgTemplateOutlet } from "@angular/common";
import {
  afterRenderEffect,
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  input,
  viewChild,
} from "@angular/core";

/** Every assistant action is a native button with an accessible name. @public */
@Component({
  selector: "adapt-assistant-button",
  imports: [AdaptAssistantContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<button
    type="button"
    [attr.title]="props().tooltip"
    [attr.aria-label]="props().label"
    [attr.aria-expanded]="props().expanded"
    [attr.data-adapttable-part]="props().part"
    [attr.data-variant]="props().variant"
    [class]="props().className"
    [disabled]="props().disabled === true"
    [style]="launcherStyle()"
    (click)="props().onClick()"
  >
    <adapt-assistant-content [content]="props().icon" />
    @if (!props().iconOnly) {
      <adapt-assistant-content [content]="props().children ?? props().label" />
    }
  </button>`,
})
export class AdaptAssistantButton {
  readonly props = input.required<TableAssistantButtonProps>();
  protected readonly launcherStyle = computed(() =>
    this.props().part === "assistant-launcher"
      ? {
          inlineSize: "56px",
          blockSize: "56px",
          borderRadius: "50%",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 0,
        }
      : {}
  );
}

/** Native multiline entry; keyboard events travel unchanged to the binding. @public */
@Component({
  selector: "adapt-assistant-input",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<textarea
    rows="2"
    [attr.aria-label]="props().label"
    [placeholder]="props().placeholder"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [value]="props().value"
    [disabled]="props().disabled === true"
    style="width:100%;min-width:0;box-sizing:border-box;font:inherit;resize:vertical"
    (input)="changed($event)"
    (keydown)="props().onKeyDown($event)"
  ></textarea>`,
})
export class AdaptAssistantInput {
  readonly props = input.required<TableAssistantComposerProps>();
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLTextAreaElement).value);
  }
}

/** Native connection badge. @public */
@Component({
  selector: "adapt-assistant-badge",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<span
    [attr.data-adapttable-part]="props().part"
    [attr.data-tone]="props().tone"
    [class]="props().className"
    >{{ props().label }}</span
  >`,
})
export class AdaptAssistantBadge {
  readonly props = input.required<TableAssistantBadgeProps>();
}

/** The in-flow conversation surface. @public */
@Component({
  selector: "adapt-assistant-panel",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<section
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </section>`,
})
export class AdaptAssistantPanel {
  readonly props = input.required<TableAssistantPanelProps>();
}

/** Native modal owns top-layer stacking, focus containment and backdrop. @public */
@Component({
  selector: "adapt-assistant-sheet",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<dialog
    #dialog
    [attr.aria-label]="props().label"
    [attr.dir]="props().dir"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    style="inset: auto 0 0; margin: 0 auto; inline-size: min(420px, 100vw); block-size: 85dvh; max-inline-size: 100vw; max-block-size: 85dvh; padding: 16px; box-sizing: border-box; border-width: 1px; border-style: solid; border-color: color-mix(in srgb, CanvasText 16%, Canvas); border-radius: 12px 12px 0 0"
    (cancel)="cancel($event)"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </dialog>`,
})
export class AdaptAssistantSheet {
  readonly props = input.required<TableAssistantSheetProps>();
  private readonly dialog =
    viewChild.required<ElementRef<HTMLDialogElement>>("dialog");
  constructor() {
    afterRenderEffect(() => {
      const dialog = this.dialog().nativeElement;
      if (this.props().open && !dialog.open) {
        if (typeof dialog.showModal === "function") dialog.showModal();
        else dialog.open = true;
      } else if (!this.props().open && dialog.open) {
        if (typeof dialog.close === "function") dialog.close();
        else dialog.open = false;
      }
    });
  }
  protected cancel(event: Event): void {
    event.preventDefault();
    this.props().onClose();
  }
}

/** A nonmodal native dialog leaves the table behind it operable. @public */
@Component({
  selector: "adapt-assistant-window",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<dialog
    open
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [style]="props().style"
    style="margin:0;padding:0;border:0"
  >
    <ng-container [ngTemplateOutlet]="props().children" />
  </dialog>`,
})
export class AdaptAssistantWindow {
  readonly props = input.required<TableAssistantWindowProps>();
}

/** Native dictation language selection. @public */
@Component({
  selector: "adapt-assistant-language-chip",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<select
    [attr.aria-label]="props().label"
    [attr.data-adapttable-part]="props().part"
    [class]="props().className"
    [value]="props().value"
    [disabled]="props().disabled === true"
    (change)="changed($event)"
  >
    @for (option of props().options; track option.value) {
      <option [value]="option.value">{{ option.label }}</option>
    }
  </select>`,
})
export class AdaptAssistantLanguageChip {
  readonly props = input.required<TableAssistantLanguageChipProps>();
  protected changed(event: Event): void {
    this.props().onChange((event.target as HTMLSelectElement).value);
  }
}

/** The platform's disclosure keeps examples local and handles nested Escape. @public */
@Component({
  selector: "adapt-assistant-menu",
  imports: [AdaptAssistantContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<details
    #details
    data-adapttable-part="assistant-examples"
    (keydown)="onKeyDown($event)"
  >
    <summary
      style="display: flex; align-items: center; justify-content: center; list-style: none"
      #trigger
      [attr.aria-label]="props().label"
      [title]="props().label"
      [attr.data-adapttable-part]="props().part"
      [class]="props().className"
      [attr.aria-disabled]="props().disabled ? 'true' : null"
      (click)="onTrigger($event)"
    >
      <adapt-assistant-content [content]="props().icon" />
    </summary>
    <menu
      data-adapttable-part="assistant-examples-list"
      [style.max-height]="props().maxHeight"
      style="overflow-y:auto"
    >
      @for (item of props().items; track item.id) {
        <li>
          <button
            type="button"
            [attr.data-adapttable-part]="item.part"
            [disabled]="props().disabled === true"
            (click)="select(item.id)"
          >
            <adapt-assistant-content [content]="item.icon" /><span>{{
              item.title
            }}</span>
            @if (item.description) {
              <small>{{ item.description }}</small>
            }
          </button>
        </li>
      }
    </menu>
  </details>`,
})
export class AdaptAssistantMenu {
  readonly props = input.required<TableAssistantMenuProps>();
  private readonly details =
    viewChild.required<ElementRef<HTMLDetailsElement>>("details");
  private readonly trigger =
    viewChild.required<ElementRef<HTMLElement>>("trigger");
  protected onTrigger(event: Event): void {
    if (this.props().disabled) event.preventDefault();
  }
  protected select(id: string): void {
    if (this.props().disabled) return;
    this.details().nativeElement.open = false;
    this.trigger().nativeElement.focus();
    this.props().onSelect(id);
  }
  protected onKeyDown(event: KeyboardEvent): void {
    const details = this.details().nativeElement;
    if (event.key === "Escape" && details.open) {
      event.preventDefault();
      event.stopPropagation();
      details.open = false;
      this.trigger().nativeElement.focus();
    }
  }
}

/** Every control in the native assistant, including its optional voice and examples. @public */
export const TABLE_ASSISTANT_SLOTS: TableAssistantSlots = {
  Panel: AdaptAssistantPanel,
  Sheet: AdaptAssistantSheet,
  Window: AdaptAssistantWindow,
  Button: AdaptAssistantButton,
  Composer: AdaptAssistantInput,
  Badge: AdaptAssistantBadge,
  Menu: AdaptAssistantMenu,
  LanguageChip: AdaptAssistantLanguageChip,
};

/** A complete native assistant, directly mountable beside a table. @public */
@Component({
  selector: "adapt-table-assistant",
  imports: [AdaptTableAssistantChrome],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "adapt-aria", style: "display: contents" },
  template: `<adapt-table-assistant-chrome
    [props]="accented()"
    [slots]="slots"
  />`,
})
export class AdaptTableAssistant {
  readonly props = input.required<TableAssistantProps>();
  protected readonly accented = computed((): TableAssistantProps => ({
    accent: "AccentColor",
    ...this.props(),
  }));
  protected readonly slots = TABLE_ASSISTANT_SLOTS;
}

/** Compose the native assistant into TABLE_ASSISTANT. @public */
export function tableAssistant() {
  return createAdapterTableAssistantFeature(AdaptTableAssistant);
}
