// packages/core/src/focus/GridFocusAnnouncer.tsx
/**
 * The live region that says where keyboard focus went.
 *
 * A cell gaining DOM focus is announced by the screen reader on its own, but
 * only as the cell's contents — not which column it belongs to, and not where
 * it sits in a dataset the user cannot see the end of. "1,240" is useless;
 * "Budget, 1,240, row 40,002 of 100,000" is navigation.
 *
 * It lives in core rather than in eight adapters because the region's own
 * details are easy to get wrong — see {@link LiveRegion}, which owns them.
 */
import type { ReactElement } from "react";

import { LiveRegion } from "../a11y/LiveRegion";
import type { GridFocusState } from "./useGridFocus";

/**
 * Props for {@link GridFocusAnnouncer}.
 *
 * @public
 */
export interface GridFocusAnnouncerProps {
  /** The grid focus state, straight from `table.gridFocus`. */
  focus: GridFocusState;
}

/**
 * Renders the grid's focus announcements, or nothing at all when cell
 * navigation is off — so an adapter spreads it unconditionally and the opt-in
 * promise still holds. When on, the region is present from the first render and
 * empty until focus moves, which is the order screen readers need.
 *
 * @public
 */
export function GridFocusAnnouncer({
  focus,
}: Readonly<GridFocusAnnouncerProps>): ReactElement | null {
  if (!focus.enabled) return null;
  return <LiveRegion part="grid-announcer">{focus.announcement}</LiveRegion>;
}

// packages/angular/angular/src/focus/gridFocusAnnouncer.ts
/**
 * The live region that says where keyboard focus went.
 *
 * A focused cell is announced as its contents alone. This adds the column
 * and the place in the dataset. It renders nothing when cell navigation is
 * off, and an empty region from the first paint when it is on.
 */
import {
  ChangeDetectionStrategy,
  Component,
  input,
  type Signal,
} from "@angular/core";

import { AdaptLiveRegion } from "../a11y/liveRegion";

/**
 * The grid-focus fields the announcer reads.
 *
 * @public
 */
export interface GridFocusAnnouncement {
  /** Whether cell navigation is on. */
  readonly enabled: Signal<boolean>;
  /** What to say as focus moves. Empty until it does. */
  readonly announcement: Signal<string>;
}

/**
 * Speaks the focused cell, or nothing when cell navigation is off.
 *
 * @public
 */
@Component({
  selector: "adapt-grid-focus-announcer",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AdaptLiveRegion],
  template: `
    @if (focus().enabled()) {
      <output
        [adaptLiveRegion]="focus().announcement()"
        part="grid-announcer"
      ></output>
    }
  `,
})
export class AdaptGridFocusAnnouncer {
  /** The grid focus, straight from the table. */
  readonly focus = input.required<GridFocusAnnouncement>();
}
