// packages/angular/adapter-angular-unstyled/src/components/savedViewsMenu.ts
/**
 * The saved-views menu: a button and a panel listing the saved views —
 * click one to apply it, or delete it — above a row that saves the table's
 * current state under a name.
 */
import {
  injectSavedViews,
  type SavedViewsControllerOptions,
  type SavedViewsSlotProps,
  type SavedViewsState,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  inject,
  Injector,
  input,
  type OnInit,
  signal,
  viewChild,
} from "@angular/core";

import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";

/**
 * The saved-views toolbar control.
 *
 * @internal
 */
@Component({
  selector: "adapt-saved-views-menu",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let l = props().labels;
    <div #root data-adapttable-part="views-menu" style="position: relative">
      <button
        #trigger
        type="button"
        aria-haspopup="true"
        data-adapttable-part="views-button"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        {{ l.savedViews }}
      </button>
      @if (popover.open()) {
        <div #panel data-adapttable-part="views-panel" [style]="panelStyle">
          @for (view of views()?.views() ?? []; track view.name) {
            <div data-adapttable-part="views-row" [style]="rowStyle">
              <button
                type="button"
                data-adapttable-part="views-item"
                (click)="apply(view.name)"
              >
                {{ view.name }}
              </button>
              <button
                type="button"
                data-adapttable-part="views-delete"
                [attr.aria-label]="l.deleteView + ': ' + view.name"
                (click)="views()?.remove(view.name)"
              >
                ×
              </button>
            </div>
          }
          <hr data-adapttable-part="views-divider" />
          <div data-adapttable-part="views-save-row" [style]="rowStyle">
            <input
              data-adapttable-part="views-input"
              [attr.aria-label]="l.viewName"
              [attr.placeholder]="l.viewName"
              [value]="name()"
              (input)="name.set($any($event.target).value)"
            />
            <button
              type="button"
              data-adapttable-part="views-save"
              [disabled]="trimmed() === ''"
              (click)="save()"
            >
              {{ l.saveView }}
            </button>
          </div>
        </div>
      }
    </div>
  `,
})
export class AdaptSavedViewsMenu implements OnInit {
  /** The slot's props. */
  readonly props =
    input.required<SavedViewsSlotProps<SavedViewsControllerOptions>>();

  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly rowStyle = {
    display: "flex",
    "align-items": "center",
    gap: "6px",
  };
  protected readonly name = signal("");
  protected readonly trimmed = computed(() => this.name().trim());
  /** The views, once the props say where they are kept. */
  protected readonly views = signal<SavedViewsState | undefined>(undefined);

  private readonly injector = inject(Injector);
  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  private readonly trigger = viewChild<ElementRef<HTMLElement>>("trigger");
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.trigger()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    this.injector
  );

  /** Open the views where the props say they are kept. */
  ngOnInit(): void {
    this.views.set(
      injectSavedViews(
        computed(() => ({ ...this.props().options, injector: this.injector }))
      )
    );
  }

  protected apply(name: string): void {
    this.views()?.apply(name);
    this.popover.close();
  }

  protected save(): void {
    this.views()?.save(this.trimmed());
    this.name.set("");
  }
}

// packages/adapter-mui/src/components/SavedViewsMenu.tsx
import {
  type TableLabels,
  useSavedViews,
  type UseSavedViewsOptions,
} from "@adapttable/core";
import {
  Box,
  Button,
  Divider,
  IconButton,
  Popover,
  Stack,
  TextField,
} from "@mui/material";
import { useState } from "react";

/** The label strings the saved-views menu renders. */
export type SavedViewsLabels = Pick<
  Required<TableLabels>,
  "savedViews" | "saveView" | "viewName" | "deleteView"
>;

/** Props for the saved-views menu. */
export interface SavedViewsMenuProps {
  /** Storage + URL backend wiring, forwarded to core's `useSavedViews`. */
  options: UseSavedViewsOptions;
  /** Resolved table labels (trigger, save row, delete action). */
  labels: SavedViewsLabels;
}

/**
 * MUI saved-views menu: a toolbar button opening a popover that lists the
 * saved views — click applies one to the table, the trailing × deletes it —
 * above a save row that captures the table's CURRENT URL state (search,
 * sort, page, filters, column layout) under a typed name.
 */
export function SavedViewsMenu({
  options,
  labels,
}: Readonly<SavedViewsMenuProps>) {
  const { views, save, apply, remove } = useSavedViews(options);
  const [anchor, setAnchor] = useState<null | HTMLElement>(null);
  const [name, setName] = useState("");
  const trimmed = name.trim();
  return (
    <>
      <Button
        size="small"
        variant="outlined"
        aria-expanded={anchor !== null}
        aria-haspopup="true"
        onClick={(e) => setAnchor(e.currentTarget)}
      >
        {labels.savedViews}
      </Button>
      <Popover
        anchorEl={anchor}
        open={anchor !== null}
        onClose={() => setAnchor(null)}
        anchorOrigin={{ vertical: "bottom", horizontal: "left" }}
      >
        <Box sx={{ p: 0.75, minWidth: 250 }}>
          {views.map((view) => (
            <Stack
              key={view.name}
              direction="row"
              spacing={0.5}
              sx={{ alignItems: "center" }}
            >
              <Button
                size="small"
                fullWidth
                sx={{ justifyContent: "flex-start" }}
                onClick={() => {
                  apply(view.name);
                  setAnchor(null);
                }}
              >
                {view.name}
              </Button>
              <IconButton
                size="small"
                aria-label={`${labels.deleteView}: ${view.name}`}
                onClick={() => remove(view.name)}
              >
                ×
              </IconButton>
            </Stack>
          ))}
          <Divider sx={{ my: 0.5 }} />
          <Stack direction="row" spacing={0.5} sx={{ alignItems: "center" }}>
            <TextField
              size="small"
              value={name}
              placeholder={labels.viewName}
              slotProps={{ htmlInput: { "aria-label": labels.viewName } }}
              onChange={(e) => setName(e.target.value)}
            />
            <Button
              size="small"
              variant="contained"
              disabled={trimmed === ""}
              onClick={() => {
                save(trimmed);
                setName("");
              }}
            >
              {labels.saveView}
            </Button>
          </Stack>
        </Box>
      </Popover>
    </>
  );
}
